### ISSUE TITLE
Openlayers - Error for WMS getGetFeatureInfoUrl

### ISSUE THREAD

**Issue by andreaordonselli** [tomchadwin/qgis2web#1014]
Hello,
I have created a project with 2 WMS layers concerning the Italian land registry by this link https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php

I get an error when I click the map to get the feature info.
I have configured the getfeatureinfo only in 1 level but both can provide the data.
**How can I solve?**

I enclose:
- the qgis project
- folder produced by qgis2web

[wms_land registry_italy.zip](https://github.com/tomchadwin/qgis2web/files/9775314/wms_land.registry_italy.zip)

Screenshot:
![2022-10-13 11_05_53-wms italy cadastral — QGIS](https://user-images.githubusercontent.com/89784373/195565174-1efa3a79-1c7c-4d29-93a6-6f1b90c8e281.png)

![2022-10-13 11_08_39-Proprietà Layer — Particelle — Informazioni](https://user-images.githubusercontent.com/89784373/195565335-6f66637d-9501-43a1-85b3-bc6d369cab06.png)

![2022-10-13 11_06_51-Export to web map](https://user-images.githubusercontent.com/89784373/195565246-82e05d23-d077-4926-a1b1-4333c052e8ff.png)

![2022-10-13 11_07_55-index html](https://user-images.githubusercontent.com/89784373/195565272-d3d4896a-4d23-4ed9-9a58-cf866d803ebe.png)

**Comment by andreaordonselli** [comment]
I believe there is a small bug in the qgis2web.js file

![image](https://user-images.githubusercontent.com/89784373/196148548-99165420-8942-4f56-b0ce-ca979887c4c0.png)

Just writing `getFeatureInfoUrl` the call works again, but I get this other error

![image](https://user-images.githubusercontent.com/89784373/196152818-e806db58-91dd-4758-b323-8131d0ce0bc0.png)

Do you know how to overcome it?

**Comment by andreaordonselli** [comment]
Good morning,
I've worked on it for a while and I feel like I've fixed everything.

1. by writing in this way, only the wms / wfs layers visible in the legend can be queried

`if (wms_layers[i][1] && wms_layers[i][0].getVisible()) {`

2. writing in this way you do not receive errors in the return of information from servers that block iframe or cors policy
```
if (url) {
  content.innerHTML = "";
  fetch("https://api.allorigins.win/raw?url=" + encodeURIComponent(url))
    .then((response) => response.text())
    .then((html) => {
      overlayPopup.setPosition(coord);
      content.innerHTML += html;
      container.style.display = "block";
    });
}
```

il codice intero finale è questo
```
var viewProjection = map.getView().getProjection();
var viewResolution = map.getView().getResolution();
for (i = 0; i < wms_layers.length; i++) {
  if (wms_layers[i][1] && wms_layers[i][0].getVisible()) {
    var url = wms_layers[i][0]
      .getSource()
      .getFeatureInfoUrl(evt.coordinate, viewResolution, viewProjection, {
        INFO_FORMAT: "text/html"
      });
    if (url) {
      content.innerHTML = "";
      fetch("https://api.allorigins.win/raw?url=" + encodeURIComponent(url))
        .then((response) => response.text())
        .then((html) => {
          overlayPopup.setPosition(coord);
          content.innerHTML += html;
          container.style.display = "block";
        });
    }
  }
}
```

@tomchadwin can you test too? if you want I make a pull request

**Comment by andreaordonselli** [comment]
@tomchadwin It's been over 1 month since I mentioned you in the previous post. Do you still support this plugin?
I think I fixed the problems affecting the wms query, what do you think?

**Comment by KoalaGeo** [comment]
I believe I've got the same error with the GetFeatureInfo. 

- It's enabled on https://koalageo.rocks/charnwood-forest-geology/map/index.html 
  - Host files: https://github.com/KoalaGeo/charnwood-forest-geology/tree/main/docs/map 
- WMS Connecting to https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities&_ga=2.122629579.1928349753.1671634180-1967471003.1671634180

**Comment by andreaordonselli** [comment]
Edit the qgis2web.js file by deleting from line 347 to 360 and insert this code in its place:
```
var viewProjection = map.getView().getProjection();
	var viewResolution = map.getView().getResolution();
		for (i = 0; i < wms_layers.length; i++) {		
			if (wms_layers[i][1] && wms_layers[i][0].getVisible()) {
				var url = wms_layers[i][0].getSource().getFeatureInfoUrl(
					evt.coordinate, viewResolution, viewProjection,
					{
						'INFO_FORMAT': 'text/html',
					});
				if (url) {
					const layer = wms_layers[i][0];
					content.innerHTML = '';
					fetch('https://api.allorigins.win/raw?url=' + encodeURIComponent(url))
					.then((response) => response.text())
					.then((html) => {
						overlayPopup.setPosition(coord);
						content.innerHTML += html + '<p>' + '</p>';
						container.style.display = 'block';
				  });	
				}	
			}
		}
```

Then try again to click on the map.

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/1f438d900ed071bba8e2fd6d25b9f533c8460aa4) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.1)
