### ISSUE TITLE
Plugin non funziona su windows11

### ISSUE THREAD

**Issue by antonellosummo** [tomchadwin/qgis2web#1025]
Quando lancio qgis2web (ultima versione) su Windows 11 il programma Qgis 3.28.3, ma anche con la versione precedente stabile, si chiude e non è possibile utilizzare il plugin

**Comment by andreaordonselli** [comment]
Edit the post and write it in English please.
Does QGIS give errors when opening? For example, does it tell you that it can't load the plugin?
Or QGIS starts fine but when you click the qgis2web icon it closes? What is closing, QGIS or qgis2web?
Are you getting any errors that you can copy and paste?
Thank you

**Comment by andreaordonselli** [comment]
I'm closing due to lack of response
