### ISSUE TITLE
qgis2web update plan

### ISSUE THREAD

**Issue by wutianS** [tomchadwin/qgis2web#1027]
I would like to ask if this Plugin has a next step update plan? If so, when will it be the fastest?I hope to join the global attribute retrieval function.Looking forward to answering.

**Comment by tomchadwin** [comment]
I'm afraid there is no update plan. I've not been able to commit time to the plugin over the past couple of years, and I don't think I see that changing. I'd naturally be delighted if other people wanted to take the project on, and help where I can, but I'm not sure how likely that is.

**Comment by andreaordonselli** [comment]
The development of qgis2web has restarted, a list of expected updates will soon be available on the main page of the github repo
