### ISSUE TITLE
QGIS2web popup scrolling - help needed

### ISSUE THREAD

**Issue by outbackducky** [tomchadwin/qgis2web#103]
Hi,

I think this plugin is brilliant but I am struggling to get my popups to have a maxheight element and therefore scroll. The popups contain a lot of data which doesn't fit on a lot of a lot of screens. I am able to edit what is displayed in the popup but can't seem to set the max height, any ideas?

Here is the code from my index.html

<!DOCTYPE html>
<html>
    <head>
        <title>Working With Natural Processes</title>
    
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
        <link rel="stylesheet" href="css/MarkerCluster.css" />
        <link rel="stylesheet" href="css/MarkerCluster.Default.css" />
        <link rel="stylesheet" type="text/css" href="css/qgis2web.css">
        <link rel="stylesheet" href="css/label.css" />
        <link rel="stylesheet" href="https://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.css" />    
        <link rel="stylesheet" href="css/leaflet.draw.css" />
        <link rel="stylesheet" href="css/leaflet.measurecontrol.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
        <script src="js/leaflet-hash.js"></script>
        <script src="js/label.js"></script>
        <script src="js/Autolinker.min.js"></script>
        <script src="https://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.js"></script>
        <script src="js/leaflet.markercluster.js"></script>
        <script src="js/leaflet.draw.js"></script>
        <script src="js/leaflet.measurecontrol.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    </head>
    <body>
        <div id="map"></div>
        <script src="data/json_casestudydatabasev3.js"></script>
        <script>
        var map = L.map('map', {
            measureControl:true,
            zoomControl:true, maxZoom:26, minZoom:1
        })
        var hash = new L.Hash(map);
        var additional_attrib = '<a href="https://github.com/tomchadwin/qgis2web" target ="_blank">qgis2web</a>';
        var feature_group = new L.featureGroup([]);
        var raster_group = new L.LayerGroup([]);
        var basemap = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: additional_attrib + ' &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
        });
        basemap.addTo(map);
        var layerOrder = new Array();
        function restackLayers() {
            for (index = 0; index < layerOrder.length; index++) {
                layerOrder[index].bringToFront();
            }
        }
        map.on('overlayadd', restackLayers);
        layerControl = L.control.layers({},{},{collapsed:false});
        function pop_casestudydatabasev3(feature, layer) {
            var popupContent = '<table><tr><th scope="row">Name</th><td>' + Autolinker.link(String(feature.properties['Name'])) + '</td></tr><tr><th scope="row">Aims - flood risk</th><td>' + Autolinker.link(String(feature.properties['Aims - flood risk'])) + '</td></tr><tr><th scope="row">Aims - diffuse pollution</th><td>' + Autolinker.link(String(feature.properties['Aims - diffuse pollution'])) + '</td></tr><tr><th scope="row">Region</th><td>' + Autolinker.link(String(feature.properties['Region'])) + '</td></tr><tr><th scope="row">Rainfall (mm)</th><td>' + Autolinker.link(String(feature.properties['Rainfall (mm)'])) + '</td></tr><tr><th scope="row">Altitude (m)</th><td>' + Autolinker.link(String(feature.properties['Altitude (m)'])) + '</td></tr><tr><th scope="row">Type</th><td>' + Autolinker.link(String(feature.properties['Type'])) + '</td></tr><tr><th scope="row">Measures</th><td>' + Autolinker.link(String(feature.properties['Measures'])) + '</td></tr><tr><th scope="row">Construction</th><td>' + Autolinker.link(String(feature.properties['Construction'])) + '</td></tr><tr><th scope="row">Size (km2)</th><td>' + Autolinker.link(String(feature.properties['Size (km2)'])) + '</td></tr><tr><th scope="row">Date implemented</th><td>' + Autolinker.link(String(feature.properties['Date implemented'])) + '</td></tr><tr><th scope="row">Maintainence checks</th><td>' + Autolinker.link(String(feature.properties['Maintainence checks'])) + '</td></tr><tr><th scope="row">Who implemented</th><td>' + Autolinker.link(String(feature.properties['Who implemented'])) + '</td></tr><tr><th scope="row">Investment</th><td>' + Autolinker.link(String(feature.properties['Investment'])) + '</td></tr><tr><th scope="row">Additional storage (m3)</th><td>' + Autolinker.link(String(feature.properties['Additional storage (m3)'])) + '</td></tr><tr><th scope="row">Elevation of defences (m)</th><td>' + Autolinker.link(String(feature.properties['Elevation of defences (m)'])) + '</td></tr><tr><th scope="row">Risk reduction</th><td>' + Autolinker.link(String(feature.properties['Risk reduction'])) + '</td></tr><tr><th scope="row">Performane/Ecosystem benefits</th><td>' + Autolinker.link(String(feature.properties['Performane/Ecosystem benefits'])) + '</td></tr><tr><th scope="row">Photo</th><td>' + '<img src=\"pictures/' + feature.properties.photo + '\" />' + '</td></tr></table>';
            layer.bindPopup(popupContent);
        }

        var json_casestudydatabasev3JSON = new L.geoJson(json_casestudydatabasev3, {
            onEachFeature: pop_casestudydatabasev3, 
        pointToLayer: function (feature, latlng) {
            return L.circleMarker(latlng, {
                radius: 5.0,
                fillColor: '#af640d',
                color: '#000000',
                weight: 0.0,
                opacity: 1.0,
                dashArray: '',
                fillOpacity: 1.0
            })
            }
        });
    layerOrder[layerOrder.length] = json_casestudydatabasev3JSON;
        //add comment sign to hide this layer on the map in the initial view.
        feature_group.addLayer(json_casestudydatabasev3JSON);
        raster_group.addTo(map);
        feature_group.addTo(map);
        var osmGeocoder = new L.Control.OSMGeocoder({
            collapsed: false,
            position: 'topright',
            text: 'Search',
        });
        osmGeocoder.addTo(map);
		map.locate({setView: true, maxZoom: 16});
        function onLocationFound(e) {
            var radius = e.accuracy / 2;
            L.marker(e.latlng).addTo(map)
            .bindPopup("You are within " + radius + " meters from this point").openPopup();
            L.circle(e.latlng, radius).addTo(map);
        }
        map.on('locationfound', onLocationFound);
        map.fitBounds(feature_group.getBounds());
        L.control.scale({options: {position: 'bottomleft',maxWidth: 100,metric: true,imperial: false,updateWhenIdle: false}}).addTo(map);
    </script>
</body>
</html>

**Comment by boesiii** [comment]
ducky,

Edit index.html, near line 46.  It should looks as follows:

layer.bindPopup(popupContent, {maxHeight: 80, autoPan: true });

**Comment by outbackducky** [comment]
Boesiii,

Thank you very  much, that worked a charm! Been trying that sort of thing but must have been getting the phrasing wrong. Will that also work if I use a % so that it autoscales to fit any screen size?

**Comment by boesiii** [comment]
Looks like you can only specify a size not a percent.

http://leafletjs.com/reference.html#popup

**Comment by outbackducky** [comment]
Okay thanks, still a huge help!

**Comment by tomchadwin** [comment]
Thanks again, @boesiii for answering.
