### ISSUE TITLE
File Name Too Long error when exporting to Leaflet

### ISSUE THREAD

**Issue by bnapoletano** [tomchadwin/qgis2web#1036]
I am advising a student who is trying to develop a Web Mapping application, and we have encountered an error that I am unable to make sense of. The error repeats on different machines and operating systems, and only occurs when trying to publish an otherwise functional map with qgis2web. Admittedly, it has been about a decade since I have really done anything in GIS myself, and I usually used GRASS when I did, so I am already rather ignorant of QGIS and its plugins. In short, the error occurs when trying to export a project as a web map using qgis2web with the Leaflet option (I checked, and the other options also throw up the error).

I am including a screenshot of the map we are struggling with, and a copy of all the text that accompanied the error message. The error indicates a file name is too long, but I have no idea why the plugin is trying to generate a file (I assume a temporary one) with such a long file name. This is what leads me to believe it is a bug.

![Screenshot from 2023-08-04 00-57-58](https://github.com/tomchadwin/qgis2web/assets/31174070/1e71c4e1-2523-4a41-87ff-4125b23a255d)

The shapefile we are having trouble with can be found here: [https://maps.princeton.edu/catalog/tufts-westbankcheckpt08](https://maps.princeton.edu/catalog/tufts-westbankcheckpt08)

I have checked that I am using the latest version of qgis2web, and even reinstalled the plugin.

Here is a screenshot of the appearance settings. I am unable to make any sense of the attribute filter. I have asked my student to restrict the attributes to those relevant to what he is trying to display, but I am not sure if he has done so.
![Screenshot from 2023-08-04 01-31-07](https://github.com/tomchadwin/qgis2web/assets/31174070/ffdb729d-d254-4759-9cd3-aa4c02ec1fa4)

Here is the text of the progress reported up to the point where the error appears:
```
Creating Leaflet map...
Exporting libraries... done
Writing CSS... done
Exporting Israeli Territorial Boundaries (Green Line) to JSON... done
Exporting Palestinian Territorial Boundaries (Green Line) to JSON... done
Exporting Palestinian Localities to JSON... done
Exporting Total Road Network to JSON... done
Exporting Earth Mounds to JSON... done
Exporting Checkpoints to JSON... done
Exporting Earth Walls to JSON... done
Exporting Israeli-only Roads to JSON... done
Writing Israeli Territorial Boundaries (Green Line) as JSON... done
Writing Palestinian Territorial Boundaries (Green Line) as JSON... done
Writing Palestinian Localities as JSON... done
Writing Total Road Network as JSON... done
Writing Earth Mounds as JSON... done
Writing Checkpoints as JSON...
```

Here is the error that appears (it includes the version number of QGIS and the plugin):

```
An error has occurred while executing Python code: 

OSError: [Errno 36] File name too long: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0icG9saWNlLUpQIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNSIgaGVpZ2h0PSIxNSIgdmlld0JveD0iMCAwIDE1IDE1Ij4KICA8cGF0aCBmaWxsPSJwYXJhbShmaWxsKSAjMDAwIiBmaWxsLW9wYWNpdHk9InBhcmFtKGZpbGwtb3BhY2l0eSkiIHN0cm9rZT0icGFyYW0ob3V0bGluZSkgI2ZmZiIgc3Ryb2tlLXdpZHRoPSJwYXJhbShvdXRsaW5lLXdpZHRoKSAwIiBzdHJva2Utb3BhY2l0eT0icGFyYW0ob3V0bGluZS1vcGFjaXR5KSIgZD0iTTcuNSwxQTYuNSw2LjUsMCwxLDAsMTQsNy41LDYuNSw2LjUsMCwwLDAsNy41LDFabTIuNiwyLjg0TDcuNSw2LjQ0LDQuOSwzLjg0QTQuNDQyOCw0LjQ0MjgsMCwwLDEsMTAuMSwzLjg0Wk0zLjg0LDQuOTAwNyw2LjQzOTQsNy41bC0yLjYsMi41OTkzQTQuNDQyOSw0LjQ0MjksMCwwLDEsMy44NCw0LjkwMDdaTTQuOSwxMS4xNmwyLjYtMi42LDIuNiwyLjZBNC40NDI4LDQuNDQyOCwwLDAsMSw0LjksMTEuMTZabTYuMjYtMS4wNjA2TDguNTYwNiw3LjVsMi42LTIuNTk5M2E0LjQ0MjksNC40NDI5LDAsMCwxLS4wMDA2LDUuMTk4NloiLz4KPC9zdmc+' 
Traceback (most recent call last):
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 348, in saveMap
    results = writer.write(self.iface,
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 90, in write
    self.preview_file = self.writeLeaflet(
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 261, in writeLeaflet
    useOSMB) = writeVectorLayer(layer, safeLayerName,
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 125, in writeVectorLayer
    useShapes) = getLayerStyle(layer, safeLayerName, interactive,
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 41, in getLayerStyle
    pattern) = getSymbolAsStyle(symbol, markerFolder,
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 225, in getSymbolAsStyle
    shutil.copy(sl.path(), path)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 36] File name too long: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0icG9saWNlLUpQIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNSIgaGVpZ2h0PSIxNSIgdmlld0JveD0iMCAwIDE1IDE1Ij4KICA8cGF0aCBmaWxsPSJwYXJhbShmaWxsKSAjMDAwIiBmaWxsLW9wYWNpdHk9InBhcmFtKGZpbGwtb3BhY2l0eSkiIHN0cm9rZT0icGFyYW0ob3V0bGluZSkgI2ZmZiIgc3Ryb2tlLXdpZHRoPSJwYXJhbShvdXRsaW5lLXdpZHRoKSAwIiBzdHJva2Utb3BhY2l0eT0icGFyYW0ob3V0bGluZS1vcGFjaXR5KSIgZD0iTTcuNSwxQTYuNSw2LjUsMCwxLDAsMTQsNy41LDYuNSw2LjUsMCwwLDAsNy41LDFabTIuNiwyLjg0TDcuNSw2LjQ0LDQuOSwzLjg0QTQuNDQyOCw0LjQ0MjgsMCwwLDEsMTAuMSwzLjg0Wk0zLjg0LDQuOTAwNyw2LjQzOTQsNy41bC0yLjYsMi41OTkzQTQuNDQyOSw0LjQ0MjksMCwwLDEsMy44NCw0LjkwMDdaTTQuOSwxMS4xNmwyLjYtMi42LDIuNiwyLjZBNC40NDI4LDQuNDQyOCwwLDAsMSw0LjksMTEuMTZabTYuMjYtMS4wNjA2TDguNTYwNiw3LjVsMi42LTIuNTk5M2E0LjQ0MjksNC40NDI5LDAsMCwxLS4wMDA2LDUuMTk4NloiLz4KPC9zdmc+'


Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
QGIS version: 3.22.4-Białowieża Białowieża, exported 

Python Path:
/usr/share/qgis/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/home/napoletano/Dropbox/datos/brandon-tesis/gisproject/mde palestina
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins
```

**Comment by tomchadwin** [comment]
I've not seen this issue before. As well as the layer data, are you able to share a copy of the QGIS project file, with all layers removed apart from that Checkpoints one? The issue seems to be in the marker style export code, but why it is trying to use base64 encoding, I have no idea. We would need to recreate the issue to be able to debug it, and for that, we need the simplified project file.

**Comment by andreaordonselli** [comment]
As Tom wrote to you, try to provide the complete project if possible.
The shape file has no problem, here is the openlayers and leafleat export
![2023-08-04 10_48_18-Calcolatrice](https://github.com/tomchadwin/qgis2web/assets/89784373/9bc7c634-7821-48ad-80ad-db4a3b707b71)
![2023-08-04 10_48_58-Calcolatrice](https://github.com/tomchadwin/qgis2web/assets/89784373/b3a62e94-fb2f-47b6-ba68-bfdbe1c052ec)

**Comment by bnapoletano** [comment]
Thank you for looking into this. I am including two versions of the project file. Both are derived from the project file that my student sent to me. As an additional check I tried exporting a map after removing all the other layers, and the error still occurred. Here is just the project file (I placed it in a zip archive because the server would not accept a qgz file):
[movement.zip](https://github.com/tomchadwin/qgis2web/files/12260402/movement.zip)

I also saved a copy of the project with the checkpoints file using the Save All plugin:
[movementsaveall.zip](https://github.com/tomchadwin/qgis2web/files/12260411/movementsaveall.zip)

I tried exporting the map with all the layers other than the checkpoints, and encountered an additional problem. I am not sure if this is the same issue or something different. When I export the map to a local folder, I am able to export the map without the checkpoints successfully. When I try to export the same map directly to the web server using FTP, however, I receive the following error:

```
An error has occurred while executing Python code: 

TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 354, in saveMap
    result = self.exporter.postProcess(results, feedback=self.feedback)
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/exporter.py", line 367, in postProcess
    if not uploadPath(os.path.join('.', source_folder)):
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/exporter.py", line 361, in uploadPath
    if not uploadPath(current_path):
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/exporter.py", line 352, in uploadPath
    feedback.setProgress(
  File "/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/feedbackDialog.py", line 160, in setProgress
    self.progressBar.setValue(progress)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'


Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
QGIS version: 3.22.4-Białowieża Białowieża, exported 

Python Path:
/usr/share/qgis/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/home/napoletano/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/home/napoletano/Dropbox/datos/brandon-tesis/gisproject/gettinghelp
```

This is a different error, but equally baffling to me. The layer in question contains two fields with floating point data, X and Y GPS coordinates.

We also had some initial trouble with another map, but managed to export it successfully after I gave him a 30m SRTM model to replace the 10m ASTER model he was using to display elevation and hillshade (that map also uses some data from the same source, and an incomplete version is online here: [http://palestina.napoletano.net/gismaps/asentamientos/](http://palestina.napoletano.net/gismaps/asentamientos/). In this case he was able to publish the map directly to the web using FTP, despite the initial troubles.

**Comment by andreaordonselli** [comment]
I think the problems derive from the svg icon used for the Checkpoints.shp layer stored in movementsaveall.zip
Try using a standard symbology or changing the svg icon.

If the first problem (base64) resolves, try to see if you still get the error saving to FTP. But here there are many hypotheses, what do you use? FTP or SFTP? Have you set a password? ...

**Comment by bnapoletano** [comment]
Thank you Andrea. I had my student follow your suggestion, and he was able to export the map directly to the server using a standard symbology. Thus, it seems to that the same issue was responsible for the errors on both fronts. The export was done vía FTP, using the options included in the qgis2web plugin and a password. He reports receiving no errors with the standard symbology.
