### ISSUE TITLE
Build suite of test data

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#105]
Travis now has tests to load test data and export it in both Leaflet and OL3. We now need a suite of tests. In the first instance, these should cover every combination of:

- point
- line
- poly

and:

- simple
- categorized
- graduated

making nine test projects. This can then be expanded with another dimension: SHP/WFS. Rasters can also be tested.

There is a huge amount of work to do to add in these tests, so this will be a long-standing issue to add them in as I can.

**Comment by tomchadwin** [comment]
Hrm. I've added the tests. Problem is, they are not failing when I put a deliberate error in the code. In current master, Leaflet export gives a Python error, but Travis does not fail. I've also put in a more specific error (for Leaflet export of categorized line layers), but that is also passing Travis.

What has gone wrong?

**Comment by tomchadwin** [comment]
I think the problem I have is that my test isn't referencing the plugin UI. I've asked for help on this here:

http://gis.stackexchange.com/questions/162579/pyqgis-reference-to-qgis-plugin-ui-in-travis-unittest

No takers yet - can anyone here help?

**Comment by tomchadwin** [comment]
@akbargumbira, @timlinux - sorry to bother you, but can either of you point to where I am going wrong?

**Comment by akbargumbira** [comment]
hi @tomchadwin. Can you explain what you want to achieve? and what is the problem? Thanks

**Comment by tomchadwin** [comment]
@akbargumbira

In Travis unittest of this plugin:

1. Load a layer from plugin /test_data folder into QGIS
2. Click plugin UI "Export" button

The problem seems to be that when the plugin is called by the unittest, the plugin code which retrieves the list of layers from the plugin UI fails to retrieve the layers. I don't know why:

- the reference to the plugin UI fails under unittest conditions?
- the QGIS layers fail to populate the plugin UI layer list?
- something else?

The actions of this test work when carried out manually - it is just when running as a unittest under Travis that it fails.

**Comment by tomchadwin** [comment]
@akbargumbira @timlinux Did you ever implement `legendInterface()` in your dummy IFACE? My code uses `self.iface.legendInterface().isLayerVisible(layer)`, so that's obviously failing and preventing the test from completing.

**Comment by akbargumbira** [comment]
Hi @tomchadwin, sorry for not responding you fast, I just moved to Poland. And I haven't worked on QGIS for a long time and need some time to look back to this issue. I'll see what I can do about this

**Comment by tomchadwin** [comment]
@akbargumbira Don't worry. I had only one instance of legendInterface, and I've removed it, so there's no need for you to look into anything. Good luck in Poland!

**Comment by tomchadwin** [comment]
The initial test suite is now complete at last, after more than five months of occasional work. There is a test for each combination of:

Leaflet + JSON/WFS + point/line/polygon + single/categorized/graduated

OL3 + point/line/polygon + single/categorized/graduated

Total: **27 data tests**

The HTML and JS output is tested against known good reference files.

Next steps are to do single tests against other options selectable from the GUI.
