### ISSUE TITLE
.../js/images/marker-icon.png file cannot be found

### ISSUE THREAD

**Issue by hoge6b01** [tomchadwin/qgis2web#106]
When I activate the geolocator the map zooms to my location correctly but the image seems to be broken. This is because the path to the file does not exist. Could it be fixed? Thanks

**Comment by tomchadwin** [comment]
I can't recreate this - I have a marker. Just to double-check: this is Leaflet export format, yes?

**Comment by tomchadwin** [comment]
Ah, got it. Only happens on Leaflet export with local copy of library. Will look into it now.

**Comment by hoge6b01** [comment]
Yes, that's correct. I export a local copy of the library on Leaflet.

2015-09-08 11:00 GMT+02:00 Tom Chadwin <notifications@github.com>:

**Comment by tomchadwin** [comment]
Fixed in master, released as 0.23.0, pushed to QGIS plugins repo - please test and report back
