### ISSUE TITLE
One attribute popup on hover, all on click - can it be done?

### ISSUE THREAD

**Issue by outbackducky** [tomchadwin/qgis2web#107]
Does anyone know of a way of making a single attribute (eg name) popup when the mouse hovers over a point but then if the point is clicked the entire popup is shown as it currently is? I have fair few points on my map now and would be good to have a way of identifying them by name before clicking on them, other methods to achieve this also welcome.

Thank you in advance.

**Comment by tomchadwin** [comment]
How about labelling with the single field instead? No way to do what you are asking without coding.
