### ISSUE TITLE
PDF as hyperlink won't open in QGIS2Web output [SOLVED]

### ISSUE THREAD

**Issue by StoneBeater** [tomchadwin/qgis2web#1086]
I have attached some pdfs in a point layer with QGIS 3.34.6. 
I used a code like this: `<a href="images/123" target="_blank">123`, so that I can open the pdf via the popup.

![Unbenannt](https://github.com/user-attachments/assets/d9a068b6-c9a1-470e-a010-723c0378b2ca)

When I export the interactive map I have a hyperlink i can click on, but the pdf won't open saying "Error: File not found"

![Unbenannts](https://github.com/user-attachments/assets/840d5bfc-2292-45ee-829e-00f79d71c421)

The pdf is in the same folder as the QGIS2Web output, so this should be no issuse. How can I fix this?

**Comment by StoneBeater** [comment]
@andreaordonselli thanks, that works

**Comment by andreaordonselli** [comment]
I am happy that it works, consider donating a coffee, through the button in the home, to support the project. Thanks
