### ISSUE TITLE
Fit to layers extent together with clustering

### ISSUE THREAD

**Issue by csandor** [tomchadwin/qgis2web#109]
'Fit to layers extent' together with 'Cluster' on gives a JS error:
Uncaught TypeError: Cannot read property 'lat' of undefined
v0.23
QGIS 2.10

**Comment by tomchadwin** [comment]
I can't recreate this - cluster plus layers extent works for me. Perhaps you could screenshot your settings?

**Comment by csandor** [comment]
thanks for looking into it! Attached are the screenshots. If I turn off cluster or set to canvas extent the preview and export will work.
Thanks, great plugin!
![cluster_layerextent1](https://cloud.githubusercontent.com/assets/1776830/9957114/df82853a-5dfd-11e5-8e87-ef5ddc95152e.png)
![cluster_layerextent2](https://cloud.githubusercontent.com/assets/1776830/9957115/dfe00a8e-5dfd-11e5-93fd-b968ee92bbb7.png)

**Comment by tomchadwin** [comment]
OK, got it. I'll look into it.

**Comment by tomchadwin** [comment]
I've tried a fix for this in master. Are you able to test it @csandor?

**Comment by csandor** [comment]
Works now. Thanks!

**Comment by tomchadwin** [comment]
Splendid. I'll release it, but can you keep an eye out for any unintended side-effects (such as layers not appearing on the map)?

**Comment by tomchadwin** [comment]
Released as 0.23.1 and pushed to QGIS plugins repo.

**Comment by csandor** [comment]
Thanks, I'll try. 
It seems that 'Match project CRS' with basemap kills it but as I see it's already in another thread.

**Comment by tomchadwin** [comment]
The basemaps are generally only available in EPSG:3857. If you match to a different CRS, it will request tiles, but the tileservers won't give you anything back. If you mean the basemaps don't show up, that's as expected. If you get errors, I'd like to hear about them (probably not on this thread, as you say).

Thanks for the reporting and testing - much appreciated.

**Comment by csandor** [comment]
Got it. So I narrowed it down, I'll open a new issue.
