### ISSUE TITLE
Fit to Layers extent + Add layers list + Any base layer + Match project CRS 

### ISSUE THREAD

**Issue by csandor** [tomchadwin/qgis2web#110]
Project is in epsg:3083.
I know there's not much use to add a baselayer in this projection but I get
'Uncaught ReferenceError: baseMaps is not defined' 
and nothing shows up. If I turn off any of these 4 it comes back again.
QGIS 2.10
qgis2web v0.23.1

**Comment by tomchadwin** [comment]
You get the prize for the most specific bug. I'll see if I can trap it.

**Comment by tomchadwin** [comment]
I confirm I get that error under those conditions. I'll try to sort it out.

**Comment by tomchadwin** [comment]
I've added a possible fix to master - can you test?

**Comment by csandor** [comment]
Working now, thanks!
