### ISSUE TITLE
Labels appear over popups

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#111]
plugin rel. 0.23.1 on leaflet preview and also in generate code

![screenshot from 2015-09-21 09 57 20](https://cloud.githubusercontent.com/assets/1607387/9987276/c398e738-6046-11e5-89b2-64fdc8020807.png)

**Comment by tomchadwin** [comment]
Goodness, what is that? Do the labels overlap the popup, is that the problem?

**Comment by marcobra** [comment]
yes

**Comment by tomchadwin** [comment]
Confirmed. This is an issue with the label plugin, I believe. It was raised, and allegedly fixed, here:

https://github.com/Leaflet/Leaflet.label/issues/14

@marcobra, could you try exporting a map, and then overwriting the label JS and CSS files, to see if it fixes it? I've tried, and I don't think it does fix it.

**Comment by marcobra** [comment]
In some try in i put in css/label.css
        z-index: 0;
The popup is clean and over the label layer
![screenshot from 2015-09-22 11 32 13](https://cloud.githubusercontent.com/assets/1607387/10014975/7b90bb46-611d-11e5-888c-6110fe34cd73.png)

**Comment by tomchadwin** [comment]
Yes, that solution was suggested here:

https://groups.google.com/forum/#!topic/leaflet-js/8S-DH84XzRI

However, I thought that the patch I linked to above should have sorted the issue, and this hack should not be needed.

**Comment by marcobra** [comment]
Do you mean to fetch master and test ? i do it and i have still the issue...

**Comment by marcobra** [comment]
the previous requested test, i done it,  do not solve the issue

**Comment by tomchadwin** [comment]
I'll reopen the Leaflet.label ticket, and see if we can avoid adding the CSS hack. If not, I'll add it.

**Comment by marcobra** [comment]
Tom please set the CSS layer hack in the stable plugin release.

**Comment by tomchadwin** [comment]
Committed to master - will release ASAP. I'll reopen and look at this again if Leaflet.label confirms an issue and fixes it.

**Comment by tomchadwin** [comment]
Released as 0.24.0 and pushed to QGIS plugins repo
