### ISSUE TITLE
"Highlight features" doesn't highlight points

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#112]
For me, the OL3 option "Highlight features" does not work. From my understanding of the code, it should change feature style on hover to red, but for me it doesn't. Does it work for anyone else, or am I right that this is broken?

**Comment by boesiii** [comment]
I am using version 0.23.2 and I am seeing the same issue.  I reviewed index.html and the old highlight code is still the same before this issue was brought up, https://github.com/tomchadwin/qgis2web/issues/100.

**Comment by boesiii** [comment]
Sorry I made a mistake.  Issue #100 was fixed in 0.23.3 which I just downloaded and it is working as expected.  Sorry for the confusion.

**Comment by tomchadwin** [comment]
Sorry to labour the point: do highlights show up for you or not?

**Comment by boesiii** [comment]
Yes, highlights show up for me.

**Comment by tomchadwin** [comment]
Ah, OK. It works for lines and polygons. Does it work for points for anyone?

**Comment by arjan22** [comment]
Hi, it works for lines and polygons. Not for points (0.23.3)

**Comment by tomchadwin** [comment]
I've committed a change to master to highlight points. I'm not 100% happy with it for a couple of reasons. Can you test and let me know if it works for you? Things I think might go wrong:

- JS errors, so please check your console
- highlights not disappearing

That said, I've not had either error myself. Let me know how it goes.

**Comment by boesiii** [comment]
It works for me

**Comment by tomchadwin** [comment]
Thanks, @boesiii. I'll try to release ASAP.

**Comment by tomchadwin** [comment]
Released as 0.24.0 and pushed to QGIS plugins repo

**Comment by tomchadwin** [comment]
I've redone this a different way, as I really wasn't happy with how I'd done it before.

Old method: duplicate the highlight overlay as a dedicated point highlight overlay - only add highlights for lines and polys to the existing one, and for points to the new one. Concerned that highlights were not cleanly being removed from the right overlay, though it seemed to work.

New method: get rid of the duplicate overlay - add highlight feature to overlay regardless of geometry type (as before this issue was raised), and instead change the overlay's style according to whether it's a point or not.

**Comment by tomchadwin** [comment]
Please let me know if you see any problems with highlights.

**Comment by tomchadwin** [comment]
Released as 0.25.0 and pushed to QGIS plugins repo

**Comment by tomchadwin** [comment]
I'm now getting a JS "nvalidStateError when I mouseover OL3 points with "Highlight layers". Is everyone else getting that? Not sure when that went wrong.

**Comment by tomchadwin** [comment]
Possibly causes #140

**Comment by tomchadwin** [comment]
No, not related to #140. Error seems to be caused by trying to create an ol.style.Circle without specifying a radius. However, I can't find a way to retrieve the radius of a feature, so I'm a bit stuck at the moment.

**Comment by tomchadwin** [comment]
Might have to consider reverting to the previuos method.

**Comment by tomchadwin** [comment]
No, previous method still has to construct the style, so it's no better.

**Comment by tomchadwin** [comment]
Have asked for help on the OL3 list:

http://osgeo-org.1560.x6.nabble.com/Change-fill-colour-of-existing-ol-style-Circle-td5228716.html

**Comment by lucacasagrande** [comment]
I can take a look at this issue.

**Comment by tomchadwin** [comment]
I'd really appreciate it - thanks, Luca.

**Comment by tomchadwin** [comment]
Fixed in master by @lucacasagrande. Thanks, Luca!

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
