### ISSUE TITLE
Plugin settings not loading/saving

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#113]
The settings you choose in the lower pane should persist, but I think mine are not, and this is leading to problems. There might also be issues with default settings, leading to blank drop-downs which I'm sure were not there before.

Is anyone else having the same issue?

**Comment by boesiii** [comment]
I have had blank drop downs many times.

**Comment by arjan22** [comment]
Me too, also with newest version.

**Comment by tomchadwin** [comment]
I'm sure this used to work, until quire recently. I'll have to look at what has changed.

**Comment by tomchadwin** [comment]
I'm getting the error @philipjohnbarlow reported in #124 every so often now:

IOError: [Errno 9] Bad file descriptor

I still don't understand what has gone wrong with the QSettings code. Have to make this one a priority.

**Comment by tomchadwin** [comment]
Sorry - mistakenly closed.

**Comment by tomchadwin** [comment]
A search suggested that printing to STDOUT could give the bad file descriptor error. I've therefore got rid of the debug print statements relating to QSettings and committed to master. I'm also not currently experiencing the blank dropdowns and forgotten settings at the moment. Will keep looking.

Please tell me if you get the bad file descriptor error after this commit.

**Comment by tomchadwin** [comment]
I'm not seeing this problem any more. Closing for the moment - let me know if it reoccurs for you.

**Comment by tomchadwin** [comment]
Others are still experiencing this issue (http://gis.stackexchange.com/questions/166330/preserving-style-when-producing-web-maps-with-the-qgis-qgis2web-plugin/166370#166370). I think I shall try to push on with #145. This will involve rewriting the settings save code completely, so we'll see if that improves things.
