### ISSUE TITLE
Point feature - font marker symbol or vector field marker crashes the plugin

### ISSUE THREAD

**Issue by csandor** [tomchadwin/qgis2web#114]
If I set a font marker symbol or vector field marker symbol on a point layer I get this:

Traceback (most recent call last):
File "C:/Users/sando_000/.qgis2/python/plugins\qgis2web\maindialog.py", line 101, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/sando_000/.qgis2/python/plugins\qgis2web\maindialog.py", line 239, in previewLeaflet
previewFile = writeLeaflet(self.iface, utils.tempFolder(), 500, 700, 1, layers, visible, "", cluster, "", "", "", labels, 0, 0, json, params, popup)
File "C:/Users/sando_000/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 241, in writeLeaflet
borderWidth = symbol.symbolLayer(0).outlineWidth()
AttributeError: 'QgsFontMarkerSymbolLayerV2' object has no attribute 'outlineWidth'

In contrast SVG symbol is nicely falling back to simple symbology.

**Comment by tomchadwin** [comment]
Ah, I'm sure you're right. I think qgis2leaf had a fallback if the renderer was not simple, categorized, or graduated. I need to implement that.

I'm not much of a GIS person - what do font marker and field marker do, and do you think it likely that we could implement them properly in the plugin?

**Comment by csandor** [comment]
Font marker lets you chose a character from a font to use as a symbol, vector field marker - I never used - seems to draw the vector symbol based on attributes. I'll ask my colleague @brncsk to have a look at it to see feasibility. I suspect it could be done through converting to SVG or raster icon. He recently rewrote the RT Mapserver Exporter plugin's style export parts to let users export more advanced symbols to mapserver mapfile.

**Comment by tomchadwin** [comment]
OK. In the meantime, you are right, and we just need to default to a plain marker. If people want those renderers to be implemented, they can ask, but I think there are currently other priorities.

Question: does font marker only apply to point geometries?

**Comment by tomchadwin** [comment]
Ah, I was getting that wrong - font marker is a symbol layer type, not a renderer type, so the qgis2leaf method doesn't work. It catches the other renderer types such as rule-based, point displacement, etc. which the plugin does not support. I'll have to figure out how to handle unsupported symbol layer types.

**Comment by csandor** [comment]
Font markers can be used directly in point features and wherever a point style is part of a complex style like in "Marker Line" styles and polygon styles with "Outline: Marker line".

You're absolutely right if someone needs support for these features they should ask.
As I'm thinking about this it turns out to have a lot in common deciding how deep the mapserver exporter should support QGIS styling features. In that case we needed to have a fully automated solution to fit into an existing workflow to avoid mocking around in the resulting mapfile code completely. So if someone will need such "enterprise" capabilities for qgis2web he/she will have a project to fund it. ;)

**Comment by tomchadwin** [comment]
OK, I think I've caught both font and vector field markers - committed to master. Please test and report back.

**Comment by csandor** [comment]
Works on the reported 2 cases, thanks!
Since then I found that it crashes when a 'marker line' is part of a complex line style and of course when a polygon boundary has 'Outline: Marker Line' style.

**Comment by tomchadwin** [comment]
Can you post the errors?

**Comment by csandor** [comment]
Sorry,  here they are:

* Marker line style:
AttributeError: 'QgsMarkerLineSymbolLayerV2' object has no attribute 'penStyle'

* Polygon with marker line outline: 
AttributeError: 'QgsMarkerLineSymbolLayerV2' object has no attribute 'borderWidth'
(basically the same happens for any polygon fill that does not directly have a 'borderWidth')

**Comment by tomchadwin** [comment]
Sorry, I need the full errors, to get the filenames and line numbers.

**Comment by tomchadwin** [comment]
Not to worry - I think I've recreated both errors. I've caught them and output a plain style. Can you test?

**Comment by csandor** [comment]
Works fine, thanks!

**Comment by tomchadwin** [comment]
Splendid. Thanks for testing.

**Comment by tomchadwin** [comment]
Released as 0.24.0 and pushed to QGIS plugins repo

**Comment by khiyer** [comment]
Vector field markers do not work for point geometries. Have they been tested or have only font marker symbols been previously tested? 
The markers are not displayed at all in OL3 while they are redrawn as simple markers in Leaflet. There are no crashes in either case. I've attached snapshots of them below 1) shown in qgis 2) OL3 preview in qgis2web and 3) Leaflet preview  in qgis2web
![capture_vector_qgis](https://cloud.githubusercontent.com/assets/22297597/18635832/b6aba682-7e86-11e6-94eb-669940bf6bff.PNG)
![capture_vector_ol3](https://cloud.githubusercontent.com/assets/22297597/18635835/bb336ab4-7e86-11e6-94ad-ffd36e975c6e.PNG)
![capture_vector_leaflet](https://cloud.githubusercontent.com/assets/22297597/18635842/c306501c-7e86-11e6-9b5e-9e0c69e3cc26.PNG)

**Comment by tomchadwin** [comment]
@khiyer No, I'm afraid neither font markers nor vector field markers are supported.
