### ISSUE TITLE
Please set leaflet option to zoom to level 19

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#115]
Hi Tom 
Now leaflet can zoom only to level 18 in openstreetmap the zoom level can be 19 
please set it
https://groups.google.com/forum/#!topic/shareabouts-dev/RDT402691oI

thank

**Comment by tomchadwin** [comment]
Is this for all included OSM basemaps, or only some?

**Comment by tomchadwin** [comment]
OSM base layers in the plugin are:

- OSM standard
- OSM DE
- OSM HOT

Do all of these support zoom level 19?

**Comment by marcobra** [comment]
osm 19
de 18
hot 20

**Comment by tomchadwin** [comment]
I'm just committed a change to master which passes the plugin UI maxZoom property through to the Leaflet basemap layer. That seems to let you zoom in further than before on OSM standard. Can you confirm that this works, and is a solution for your request?

**Comment by marcobra** [comment]
tom, yes works 
thank

**Comment by tomchadwin** [comment]
Released as 0.25.0 and pushed to QGIS plugins repo
