### ISSUE TITLE
Leaflet default label offset

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#117]
Hi Tom 
the default value of offset for leaflet made label text too far from points 
You tell me to try to find best value of offset 

So, best value for me is :
in index.html 
{noHide: true, offset: [-0, -16] })

and even better by dectivating bold in label.css
        font: 10px/18px "Helvetica Neue", Arial, Helvetica, sans-serif;
/*      font-weight: bold; */

![sss](https://cloud.githubusercontent.com/assets/1607387/10020965/e3a4bcd2-6145-11e5-9c84-af92262ea1b6.png)

Thank

**Comment by tomchadwin** [comment]
Committed to master - does that work as requested? If anyone disagrees with @marcobra's suggestions, do comment.

**Comment by tomchadwin** [comment]
Released as 0.24.0 and pushed to QGIS plugins repo
