### ISSUE TITLE
Ol3 popup fields name are not in bold style 

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#119]
hi Tom, in Ol3 popup dialog the fields name are not in bold type.
![ol3dialog](https://cloud.githubusercontent.com/assets/1607387/10021346/e24080fe-6147-11e5-9dad-1fb362e21699.png)

To get better visualization can you dress it ?
Thank

**Comment by tomchadwin** [comment]
I think they also don't use field aliases where they are set, not are they in tabular layout. Yes, they can definitely be improved.

**Comment by tomchadwin** [comment]
Bold and tabular now committed to master. Please test. Not sure I can do field aliases, but shall have a look.

**Comment by marcobra** [comment]
works ...

**Comment by tomchadwin** [comment]
Released as 0.24.0 and pushed to QGIS plugins repo

**Comment by tomchadwin** [comment]
OL3 now uses field aliases in master. Please test.
