### ISSUE TITLE
OSM basemap missing in v0.24.0

### ISSUE THREAD

**Issue by arjan22** [tomchadwin/qgis2web#120]
Hi Tom, I think that after the update to 0.24.0 the OSM basemap is missing. (win7 - Qgis 2.10.1)

See picture below
![0 24 0](https://cloud.githubusercontent.com/assets/14556566/10043894/ae8ae42a-61f6-11e5-98b7-00436bbb2b67.jpg)

am i right or am i doing something wrong?

thanks.

**Comment by tomchadwin** [comment]
Is OSM standard selected in the base layer dropdown?

**Comment by arjan22** [comment]
I thought is was selected in the dropdown. But maybe it wasn't. After trying again the OSM standard layer is visible in the preview and export. 

We can close the issue.
Thanks.

**Comment by tomchadwin** [comment]
Great - your settings should remain, but that is currently not working - see #113

**Comment by arjan22** [comment]
Hi Tom, I reproduced the error of the missing OSM basemap.

After opening QGIS i did an update of qgis2web to v0.27.0. When i tried to use the plugin for my project, the OSM basemap was not visible (all settings and drop-down menus were right).

After restarting QGIS, the OSM basemap is back again and visible.

**Comment by tomchadwin** [comment]
So you didn't change any settings - just restarted QGIS? This is very difficult to debug, if the problem only briefly appears, but then disappears again.

If you can work out how to get the problem to occur 100% of the time, then we can look into it. Without that, it's going to be hard to fix.
