### ISSUE TITLE
WMS GetFeatureInfo 

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#121]
Possible future inclusion?
http://openlayers.org/en/v3.0.0/examples/getfeatureinfo-tile.html

**Comment by tomchadwin** [comment]
Could be useful, yes.

**Comment by philipjohnbarlow** [comment]
It should be possible to request legend graphics from geoserver for WMS, QGIS does (2.6 onwards?)

**Comment by tomchadwin** [comment]
Probably no need, if we use the code which gets vector legend graphics from the QGIS API. We should try using that for raster layers, and see what it comes out with.

**Comment by tomchadwin** [comment]
In other words, we query QGIS, which has already requested and got the info from the WMS. That's the theory, anyway.

**Comment by tomchadwin** [comment]
Would the Leaflet equivalent be provided by https://github.com/heigeo/leaflet.wms?

**Comment by philipjohnbarlow** [comment]
Sorry Tom, only just come back to this after going over some notes from the conference.  Yes, that looks like the equivalent (comparing it with the OL one).

**Comment by tomchadwin** [comment]
@mtravis - you still able to look at this?

**Comment by mtravis** [comment]
I'll try and have a look over the next couple of days.

**Comment by tomchadwin** [comment]
Looked at this again, and the Leaflet plugin I linked to above is definitely what we need.

Next step: use the plugin to export a WMS layer, then edit the Leaflet output to use the WMS plugin instead. If that works, we can then replace the current Leaflet WMS code.

**Comment by philipjohnbarlow** [comment]
Thanks for the update Tom.  The demo looks good, returning results for multiple layers in one pop-up.  Be interesting to see if it returns multiple results from the same layer.

**Comment by tomchadwin** [comment]
Leaflet getFeatureInfo now implemented in master, though transparent pixels in the WMS seems to be a regression with this approach:

https://github.com/heigeo/leaflet.wms/issues/51

Can people test and let me know how it works for them?

**Comment by tomchadwin** [comment]
OK, Leaflet transparency issue fixed, plus now using `info_format=text/html` to get meaningful info back. Seems to work on my test layer, but obviously relies on that `info_format` being available on the server.

OL also now implemented, so please test and report back.

**Comment by philipjohnbarlow** [comment]
Hi Tom, I had a quick test yesterday with leaflet so it wasn't particularly
thorough. What I did notice was that wms layers obscure the basemap (osm or
whichever) or any other wms layer you put in I.e. you can only see one at a
time and with no basemap. Pop-ups were working well though. I'll have
another go on Monday and test it properly.

**Comment by tomchadwin** [comment]
You'll only be able to see underlying layers/basemaps if there are gaps in the WMS, or if you make the WMS partially transparent.

**Comment by mtravis** [comment]
I'm not getting any popups using our tpo_points layer. Maybe there is a
setting I'm missing within the plugin.

I'm using v2.30.0

**Comment by tomchadwin** [comment]
Can you give me the layer address?

**Comment by mtravis** [comment]
https://maps.dartmoor.gov.uk/geoserver/wms?service=wms&request=getcapabilities

layer=general:tpo_points

**Comment by tomchadwin** [comment]
```
2017-11-06T12:21:31	1	Network request https://maps.dartmoor.gov.uk/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-21.19739999999999824,0,700000,1300000&CRS=CRS:84&WIDTH=156&HEIGHT=290&LAYERS=general:tpo_points&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE timed out
```

**Comment by philipjohnbarlow** [comment]
Hi Tom,

Thank you for adding this feature.

I've grabbed the latest master and WMS is overlaying just fine for me now
so the transparency change you made must have sorted that. I can see
pop-ups in OL but the pop-ups in leaflet have no content so probably the
same issue that Matt is having.

Phil

**Comment by philipjohnbarlow** [comment]
Actually scratch the above, I've worked out what the issue is... I was using emapsite WMS as a base map and that was returning an error. I guess the work around would be to have the option to only request pop-up attributes for specific layers?

**Comment by tomchadwin** [comment]
@mtravis That's a QGIS error - the layer didn't load for me in QGIS.

@philipjohnbarlow Yes, we really need to be able to disable per-layer, since many WMSes are basemaps, so lots of popups won't help things.

**Comment by tomchadwin** [comment]
If I put a checkbox per WMS layer as to whether it should enable getFeatureInfo, what text label should that checkbox have:

- enable getFeatureInfo
- clickable
- queryable
- popups

?

**Comment by mtravis** [comment]
popups or queryable I would say.

**Comment by geoglis** [comment]
queryable

**Comment by tomchadwin** [comment]
GUI option now implemented in master - text label TBC.

**Comment by philipjohnbarlow** [comment]
Hi Tom, just tested the new master using two WMS layers; one as the base map (emapsite) and the other is an LDP allocations layer. I get a pop-up if both layers are enabled with GetFeatureInfo but no pop-up if just the LDP allocations layer is enabled. Of course enabling GetFeatureInfo for the basemap results in an empty pop-up in leaflet or an error in the pop for OL as previously.

**Comment by philipjohnbarlow** [comment]
In both.

**Comment by tomchadwin** [comment]
Wow, had I got that OL code wrong - I completely miscoded a JS two-dimensional array. I think it's sorted now. Can you test?

Bear in mind that if a layer with gaps is queryable, you get a popup even if you don't click on a query. That probably explains some of the other behaviour which didn't seem right to you. I don't know whether I can disable that.

**Comment by tomchadwin** [comment]
Hopefully this is now working, so I'll close. Let me know if not.

**Comment by philipjohnbarlow** [comment]
I'll give it a test tomorrow and let you know Tom.

**Comment by philipjohnbarlow** [comment]
Hi Tom,

OL3 looks to be working well with multiple layers. I threw a planning
constraints map at it (20 wms layers)and it handled it very well. Just two
things of note there which are: blank pop-ups if you click on area where
there are no layers; and not an issue as such, more something to keep in
mind for later, when using layer groups there isn't the option to enable
getfeatureinfo as yet.

**Comment by mtravis** [comment]
Leaflet not working properly. I've got two wms layers; one with getfeatureinfo, one without. Both our showing popups which is odd as the identify option is set to false.

**Comment by tomchadwin** [comment]
> blank pop-ups if you click on area where there are no layers

Yes. As I say, that's because it's a WMS, so every pixel has "data", unlike a vector layer. Currently the webmaps just ask for the URL of the response to the query, and put an iframe in the popup with that address. In other words, the webmap never gets the actual data. That means it has no way of knowing whether there is *actual* data in the response or not.

Two possible solutions:

- retrieve the *content* of the URL and parse it to determine whether it contains data, and only show the popup if it does - probably not possible as the response template is built by the user, so there is probably no reliable way of interpreting a response as no data

- change the request to try to retrieve the raw feature data (via GML - the default - or JSON/JSONP). I wasn't having a lot of joy getting that to work, so I don't know whether it's an option.

> when using layer groups there isn't the option to enable getfeatureinfo as yet

As you're probably aware, layer groups functionality is very poor - see #175 

@mtravis Which layers, so I can recreate?

**Comment by mtravis** [comment]
@tomchadwin tpo points and tpo areas

retrieve the *content* of the URL and parse it to determine whether it
contains data, and only show the popup if it does - probably not possible
as the response template is built by the user, so there is probably no
reliable way of interpreting a response as no data

Agreed that this is extremely difficult to ensure it always works. I've set
our maps up not to show popups and can share that but I think you already
know how that works by the sounds of it.

**Comment by tomchadwin** [comment]
> I've set our maps up not to show popups and can share that

I would like to see it. The usual issue is that a solution has to be general enough to work with a significant majority of users' setups. I'm not convinced the current solution conforms to that, but we also need to apply that test to any alternative.

**Comment by tomchadwin** [comment]
> tpo points and tpo areas

Working for me. Upload some output, and I can take a look.

**Comment by kflaw** [comment]
testing this out with a wms but not getting a popup, looks like this line does not evaluate:
if (wms_layers[i][1])
what is that item? console logs as undefined
