### ISSUE TITLE
0.25.0 - Zoom level and template

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#124]
Just at a glance I've spotted a couple of issues in the OL3 preview:

- template has some inverted commas top left
- Zoom levels are behaving strangely, seems to be stuck at 5000m 

I'll test a bit more later today, and do an export to see what's happening in the template with the zoom levels.

I also just had this error when loading the plugin but it only happened on the second time I loaded it in the same project.

Traceback (most recent call last):
  File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\qgis2web.py", line 51, in run
    dlg = MainDialog(self.iface)
  File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 53, in __init__
    self.populateConfigParams(self)
  File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 187, in populateConfigParams
    print "R " + param + ": " + unicode(QSettings().value("qgis2web/" + param))
IOError: [Errno 9] Bad file descriptor

**Comment by tomchadwin** [comment]
I've committed a fix for the quotes. Will look into the other two issues.

**Comment by tomchadwin** [comment]
Gut feeling is that both the other issues relate to the problem with plugin settings not saving properly #113

**Comment by tomchadwin** [comment]
I've also had the "Bad file descriptor" error. Convinced it is because the QSettings() functionality is fundamentally failing somewhere.

**Comment by tomchadwin** [comment]
See #113 - after the last commit, can you tell me if you get the bad file descriptor message again?

**Comment by tomchadwin** [comment]
I'll close this one for the moment - let me know if you see either of these issues again.
