### ISSUE TITLE
Leaflet "Show popups on hover"

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#125]
To match the OL3 feature

**Comment by tomchadwin** [comment]
This is proving a brute to achieve. I therefore ask myself, is it worth it? Should we ditch "Show popups on hover" completely, even though it currently works in OL3.

What do you all think?

**Comment by boesiii** [comment]
If it works then leave it for OL3

**Comment by tomchadwin** [comment]
I've started thinking about when we could call this version 1.0.0. For me, that would be when all features in the UI work for both OL3 and Leaflet. At the moment, "Show popups on hover" is one of those which doesn't work in one format. Add to that the fact that I am sceptical as to how useful it is in real life as a feature, and I therefore ask whether we should just get rid of it completely.

**Comment by boesiii** [comment]
I probably wouldn't use it either so I would not be against abandoning it.

**Comment by philipjohnbarlow** [comment]
I think it's perfectly acceptable to have features greyed out Tom, OL3 and Leaflet have differing capabilities and that's why its good to have both in on plugin i.e. if one isn't giving you the features you need you just swap to the other.

**Comment by tomchadwin** [comment]
@philipjohnbarlow From a usability perspective, I'm not sure you're right. We've even had an issue raised here by someone who did not understand the greyed out options:

https://github.com/tomchadwin/qgis2web/issues/99

I'll ponder a bit more, but given my scepticism that popups on hover are actually useful, I am still tempted to ditch it. Just because software _can_ do something doesn't mean it _should_.

**Comment by philipjohnbarlow** [comment]
I see... Ok then, how about a tabbed menu so it is more obvious which one you are working with.  I can sort of understand how confusion can arise with the current ui as you switch between the two with the little dots at the bottom and they are quite small.

**Comment by tomchadwin** [comment]
Tabs could have the advantage of reducing the number of options on the main screen so that you can see more of them without scrolling. I don't know. I don't want to make the UI too confusing.

**Comment by tomchadwin** [comment]
Well, I've just about managed to get this working anyway. Please test. I'm aware that popups often immediately disappear. Will file that as a different issue.
