### ISSUE TITLE
"Match project CRS" in OL3

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#126]
At the moment, all OL3 exports are in EPSG:3857.

**Comment by tomchadwin** [comment]
I'm struggling to get this right. Can someone use the plugin to create an OL3 map, and then amend it so that it is in a different projection? I can then use that as the template to get this to work.

**Comment by tomchadwin** [comment]
Now committed to master - please test

**Comment by philipjohnbarlow** [comment]
Working just fine in preview and export.

**Comment by tomchadwin** [comment]
Thanks, Phil. Released as 0.38.0 and pushed to QGIS plugins repo.
