### ISSUE TITLE
Leaflet line style no longer working

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#139]
Dotted/dashed lines were working in Leaflet, but seem no longer to be. I don't know why.

**Comment by tomchadwin** [comment]
Hopefully fixed in master. Line widths < 1 were translated into sub-1-pixel dashes.

**Comment by mappingmilwaukee** [comment]
Is this still an ongoing issue? I'm using qgis2web v.3.12.1 from the master branch, with Q 3.10 A Coruña. I have one layer of dashed/dotted lines that render solid, even at 1.1 and .99 widths in both Leaflet preview and exported result. Happy to provide any other details. Did not resolve when I upgraded from Q3.6 to 3.10, and whatever former version I was using of qgis2web to the current master branch.

**Comment by tomchadwin** [comment]
Any chance you could upload your layer and project file?

**Comment by mappingmilwaukee** [comment]
Let me know if you need more/other data.
[dashed-line-issue.zip](https://github.com/tomchadwin/qgis2web/files/4321869/dashed-line-issue.zip)

**Comment by tomchadwin** [comment]
This is a units issue. qgis2web struggles to handle millimetres well, since they have no real meaning in a web context. Your style uses mm for the dash definitions. The output actually is dashed, as you can see if you zoom right in on a line. However, at initial zoom the dashes are pushed together.

I'd try experimenting with different settings for the dashes, including switching to pixels as your units. I will see if I can get it working better with this style as it is now, as it's plainly not much of a recreation of the QGIS style. However, it's not guaranteed to work, so I would experiment with the style in QGIS yourself.

**Comment by mappingmilwaukee** [comment]
Thanks much. I will experiment with pixels instead, but I should note that the layer in question is of street segments between blocks, so if you are zoomed in at a city or neighborhood level, you will that the lines along entire streets appear dashed but are solid between blocks. I hope that's clear. If you zoom in to max (23) you will see solid lines between blocks, each a different object. For reference, https://mappingmilwaukee.com/

**Comment by mappingmilwaukee** [comment]
Ran some more tests: when the units points or pixels are used, any line width >2.5 in both units collapse dashes into solid lines at even the lowest altitude zooms; furthermore, those units are not static at all zoom levels as millimeters currently is. I need a unit and width combo that does _not_ dynamically adapt at any given zoom level - what do you recommend?
