### ISSUE TITLE
Missing popup in OL3 on click

### ISSUE THREAD

**Issue by anitagraser** [tomchadwin/qgis2web#140]
To reproduce this: get the airports data from the QGIS sample files and reproject it to WGS84 (couldn't get it work otherwise in OL3). Then try to show a popup with all attributes on click. For me, it does not appear you can see in the following screencast: http://youtu.be/0oz_Jif2CLE?hd=1

Strangely enough, the popup shows when "show popups on hover" is enabled. The popup also shows without "on hover" if I only select the NAME column for example.

**Comment by tomchadwin** [comment]
This is odd - I still cannot recreate this issue. Can you export and check the browser dev tools JS console?

**Comment by anitagraser** [comment]
Sorry, can't get OL3 preview to work at all now ... will have to figure this out later.

**Comment by tomchadwin** [comment]
Hrm. OK, if you do get the chance,  export and send over the output. Browser JS console the next thing to check.

**Comment by tomchadwin** [comment]
I think I've recreated this and narrowed it down. OL3 popups on click do not work with "Highlight features". I presume this is because the highlight receives the click, not the original feature. Not sure how to fix that yet.

**Comment by tomchadwin** [comment]
@anitagraser, can you confirm that this issue disappears if "Highlight features" is unchecked?

**Comment by tomchadwin** [comment]
Possibly caused by #112

**Comment by boesiii** [comment]
I downloaded master and OL3 export is broken.  I get an error

Uncaught TypeError: Cannot read property 'wd' of undefined  ol.js:308

**Comment by boesiii** [comment]
OL3 preview also does not work

**Comment by tomchadwin** [comment]
Can you check all your popup settings - any blank dropdowns/odd values?

**Comment by boesiii** [comment]
Nothing is blank and no odd values.  It looks like it was "broken" for version 0.24, it works for me when I use version 0.23.3.

**Comment by tomchadwin** [comment]
Is this dependent on options chosen? Does the error occur with Highlight features checked and unchecked?

**Comment by boesiii** [comment]
No.  I have tried both and it is still broken

**Comment by tomchadwin** [comment]
Can you send me your output?

**Comment by boesiii** [comment]
I compared many files between versions and have found that the style javascript(styles/shapefile_style.js) is not correct.

**Comment by anitagraser** [comment]
I use plugin version 0.26 and the OL3 preview is broken. 

Only used default settings and points from 
http://data.wien.gv.at/daten/geo?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=ogdwien:CITYBIKEOGD&SRSNAME=EPSG:31256

Previews fine in Leaflet mode.

**Comment by anitagraser** [comment]
When I export, the JS error is

Uncaught TypeError: Cannot read property 'wd' of undefined

**Comment by tomchadwin** [comment]
OK, consistent with @boesiii. Only thing which can confuse matters is that the plugin saves its settings, so you are unlikely both to have had defaults set. Still, I'll see if I can sort this one out tomorrow.

**Comment by tomchadwin** [comment]
@boesiii's output has an empty style file for the layer. Can you send me your project and layer?

**Comment by boesiii** [comment]
![climate](https://cloud.githubusercontent.com/assets/2079638/10347950/72dd3be4-6d04-11e5-9f15-3342c3bfc08c.jpg)

**Comment by boesiii** [comment]
download the image file as a zip

**Comment by boesiii** [comment]
At first I was using a simple symbol in QGIS but I changed to a categorized and the OL3 preview and export are working.  Obviously something is wrong with the plugin function that converts a "simple" style.

**Comment by tomchadwin** [comment]
OK, thanks for your patience, both. I've now recreated the issue. I'll look at it now.

**Comment by tomchadwin** [comment]
I think I've found the issue. Will commit in a sec.

**Comment by tomchadwin** [comment]
@anitagraser, @boesiii, can you test now?

**Comment by boesiii** [comment]
Works for me.  Thanks.

**Comment by tomchadwin** [comment]
Released as 0.28.0 and pushed to QGIS plugins repo
