### ISSUE TITLE
Upgrade OL3 to 3.10.0

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#143]
Needs testing before we migrate to it.

**Comment by tomchadwin** [comment]
Committed to master - please test before I release

**Comment by philipjohnbarlow** [comment]
Hi Tom, I've installed master and had a bit of a play about with OL3.  Small issue I've noticed from a few tests is with polygons.  If you choose "show all attributes" you get no pop-up on click, you can select individual attributes and it will work.  If you select show pop-ups on hover then "show all attributes" does work.  All the pop-up settings seem to be working with points though (I haven't tried lines yet).

**Comment by tomchadwin** [comment]
Master is OL3.9.0. Does it behave like this with the previous OL3.8.2? In other words, is the OL3 version the cause of the issue?

**Comment by philipjohnbarlow** [comment]
Good question, I've haven't tried it for a while and you updated it a couple of days ago? I'll roll it back to the version on the plugin rep and try it again.

**Comment by tomchadwin** [comment]
Yes, there have been other changes as well. Not a huge number, though. Let me know what happens.

**Comment by philipjohnbarlow** [comment]
Getting the same issue with the current version on the rep, I've tried 5 different polygon layers and 4/5 seem to have the issue I described above.  The one that does not is coming from the ANPA portal WFS, the other layers have been local (3 in spatialite and one MapInfo tab).

**Comment by tomchadwin** [comment]
Upgraded master to 3.10.0. Let me know how it goes.

**Comment by philipjohnbarlow** [comment]
Working again, thanks Tom.

**Comment by tomchadwin** [comment]
With 3.10.0?

**Comment by philipjohnbarlow** [comment]
Yeah seems to be.

**Comment by tomchadwin** [comment]
Master upgraded to 3.10.1

**Comment by tomchadwin** [comment]
Reopen if issues occur
