### ISSUE TITLE
Remote WFS layers broken in Leaflet

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#146]
The style function at least is not reaching the output.

**Comment by tomchadwin** [comment]
Point geometries only, I think.

**Comment by tomchadwin** [comment]
Regression introduced with https://github.com/tomchadwin/qgis2web/commit/1bfb0172241453ea41162cf2ba215fb415da08ab

**Comment by philipjohnbarlow** [comment]
I can confirm that style function is not reaching the output for points.

![wfs points](https://cloud.githubusercontent.com/assets/14541141/10634006/a539fe50-77e6-11e5-8ee6-64611cc820fa.PNG)

I get the following error for polygons as WFS.

![wfspolygon](https://cloud.githubusercontent.com/assets/14541141/10634018/b83b20a6-77e6-11e5-91c1-a6ea68ace5b2.PNG)

**Comment by tomchadwin** [comment]
Confirmed. Dear me, but it looks as though non-JSON-encoded WFS layers might be significantly broken. Initial quick attempts to fix have proved fruitless. I'll try and solve this polygon error first.

**Comment by tomchadwin** [comment]
"Fixing" the polygon error above leads to the same result as the points - no output, owing to missing style function. Investigating further.

**Comment by philipjohnbarlow** [comment]
Good news is that poly-lines appear to be quite happy with no JSON encoding.

**Comment by tomchadwin** [comment]
Confirmed. I'll see if there us common code I can use. Thanks.

**Comment by tomchadwin** [comment]
Ah - you're a gent! Looks like the line which writes out the style function was missing in the polygon code, for some reason. Thanks so much! Have to check categorized and graduated now, and then back to look at the points.

**Comment by tomchadwin** [comment]
No problem with categorized or graduated polygons, and no issue with lines. Good news. Back to look at points again now. See whether the fix for polygons applies here as well.

**Comment by tomchadwin** [comment]
Leaflet WFS polygon fix committed to master

**Comment by philipjohnbarlow** [comment]
You're Welcome Tom, once you get the points working I'll look at using the plugin to create a web map I'm working on for our website (Planning constraints, its something in the new LDP regs in Wales).

**Comment by tomchadwin** [comment]
OK, I've committed a possible fix to master. Try it if you can, and let me know. If it works, I need to check that popups work, and that categorized and graduated work.

**Comment by philipjohnbarlow** [comment]
Gave it a go... Polygons work fine when not encoded but the option for no pop-up is currently not working.  Points are now loading in and taking the style but pop-ups are not available when not encoded to JSON.  Also clustering is not currently working but seems to be enabled by default. 

I also had this error come up a couple of times but it seems to be intermittent, and I've haven't been able to replicate which combination of settings were causing it so far. Initially I thought it was having a point layer and polygon layer on together with the layers list enabled but when I tried it a second time there was no issue.

![capture](https://cloud.githubusercontent.com/assets/14541141/10636073/ef4a023e-77f4-11e5-9ea8-e79195c601d8.PNG)

**Comment by tomchadwin** [comment]
This came up before, and seemed to be caused intermittently by debug print statements. I've removed the one which triggered that error and committed to master, so hopefully they will go away.

I'll come back to the popups issue - trying to fix broken categorized points at the mo.

**Comment by tomchadwin** [comment]
Categorized and graduated points fixed and committed to master - please test.

Now to look at popups.

**Comment by tomchadwin** [comment]
Popups now working for Leaflet WFS points (remembering that Leaflet doesn't acknowledge the per-layer popup setting).

**Comment by tomchadwin** [comment]
Popups weren't broken for lines or polygons, I think.

So, I think all of this is now sorted. @philipjohnbarlow, can you see if you agree? Thanks for all the help.

**Comment by philipjohnbarlow** [comment]
Sorry Tom, I didn't get a chance to look at this again today. I'll test it first thing tomorrow.

**Comment by philipjohnbarlow** [comment]
Confirmed, pop-ups working for points from WFS now.

**Comment by tomchadwin** [comment]
Great - do you agree that this issue is now sorted? Thanks for the help.

**Comment by tomchadwin** [comment]
Oh, you mentioned clustering was broken - is that still the case? If so, under what circumstances?

**Comment by tomchadwin** [comment]
Released as 0.31.0 and pushed to QGIS plugins repo.
