### ISSUE TITLE
Plugin crash on start up - saved settings (current master)

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#147]
Hi Tom, 

The following happens with the project I created just now to test the popups with points for wfs when I reload the project and attempt to run the plugin again.  So my guess is that it is to do with the plugin settings that are saved with the project?

![capture](https://cloud.githubusercontent.com/assets/14541141/10660256/9807d704-789d-11e5-9e6e-b10af85cae6e.PNG)

I've got training today 9:30-13:30 but I will do a few more tests later to see if I can replicate with different types of data and data from other sources.

**Comment by tomchadwin** [comment]
Can you open your project file in a text editor, and search for qgis2web? You should find that saved setting applied to your layer. What value does the setting have?

**Comment by philipjohnbarlow** [comment]
<property key="qgis2web/Info popup content" value="1"/>

I had a mess about and changed a couple of these settings to see if it would make any difference, none thus far though.

**Comment by tomchadwin** [comment]
As in, you're still getting the error on startup? Any joy with my previous comment?

**Comment by philipjohnbarlow** [comment]
The error is just on starting the plugin, the project loads up fine.

**Comment by philipjohnbarlow** [comment]
![capture](https://cloud.githubusercontent.com/assets/14541141/10664777/dc206c60-78bd-11e5-8d92-bff8a90298fa.PNG)

Sorry, I put the settings in the comment but they don't display...

**Comment by tomchadwin** [comment]
OK, can you open maindialog.py in a text editor, and change l.366 to `self.combo.setCurrentIndex(int(layer.customProperty("qgis2web/Info popup content"))`? See if that fixes it.

**Comment by philipjohnbarlow** [comment]
![capture](https://cloud.githubusercontent.com/assets/14541141/10665052/29727f9c-78c0-11e5-81aa-952948d7bf0c.PNG)

**Comment by philipjohnbarlow** [comment]
Ah! looks like it needed one more ")"

**Comment by tomchadwin** [comment]
Sorry! Missed a closing parenthesis. Try `self.combo.setCurrentIndex(int(layer.customProperty("qgis2web/Info popup content")))``

**Comment by tomchadwin** [comment]
Exactly. Is it working now?

**Comment by philipjohnbarlow** [comment]
yup.

**Comment by tomchadwin** [comment]
Splendid. Fix committed to master. Thanks for the help.
