### ISSUE TITLE
WFS points layers json encoding

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#150]
Hi Tom,

Just had a quick go with a couple of different sized point layers from the NP portal geoserver as WFS in 0.33.0.  The points as WFS works fine but if you select encode to json it breaks, that is to say you get no map canvas or controllers in the preview or export.  

Phil

**Comment by tomchadwin** [comment]
Hmm. Can you export and use browser dev tools (F12) to look for console errors?

**Comment by philipjohnbarlow** [comment]
Sorry Tom, I'm on leave this week. I'll see if I can get in front of a PC later in the week.

**Comment by tomchadwin** [comment]
I'm getting a different problem - I get the unclustered points. Will look into it.

**Comment by tomchadwin** [comment]
Is this issue still present?

**Comment by philipjohnbarlow** [comment]
Hi Tom, the issue is no longer present in 1.0.0.  I notice that clustering is currently not working though.

**Comment by tomchadwin** [comment]
OK, closing this. Will look at clustering and raise new issue if I find the problem. Any steps to recreate v useful.
