### ISSUE TITLE
Version 0.33.0 Plugin Broken QGIS 2.8 

### ISSUE THREAD

**Issue by nothing-butanol** [tomchadwin/qgis2web#151]
This very well may be isolated to my computer alone due to my weird python install, but after the latest update I now receive:

"The plugin is broken. Python said: cannot import name show_message_log"

I could reinstall python to see if it would fix the issue, but it's currently in a delicate functional state I rather not mess with. I'm just curious if anyone else has this problem after the update.

**Comment by tomchadwin** [comment]
I'm going to pass on this one, as I've no idea what show_message_log is. Perhaps have a look here to see if it helps:

http://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x
