### ISSUE TITLE
empty labels are shown as 'null' in OL3

### ISSUE THREAD

**Issue by batje** [tomchadwin/qgis2web#154]
I have a map where only very few buildings have a name, thus label. In OL3 for all empty labels, I see 'null'. More pretty would be to see nothing.

**Comment by tomchadwin** [comment]
I've seen this for popup values, as have others. You have seen it for labels?

**Comment by tomchadwin** [comment]
Confirmed - labels show "null" as well. Will look into it.

**Comment by tomchadwin** [comment]
Fix committed to master - please test. By the way, can anyone recreate the issue of seeing "null" in popups? I can't at the moment.

**Comment by batje** [comment]
Works for me, in master. Thanks.

**Comment by tomchadwin** [comment]
Released as 1.0.0-beta2 and published in QGIS plugins repo.
