### ISSUE TITLE
grouped layer script issue

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#155]
Installed version: 0.39.0 (in /home/ubuntu/.qgis2/python/plugins/qgis2web)
Available version: 0.39.0 (in Repository plugin ufficiale QGIS)

Tom, i have grouped layers trees at preview time i get... this error, i mean the error is coming out only if i check the group name (it was recognized as layer, but is not)... 
Best regards 
Marco

Traceback (most recent call last):
File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 115, in previewMap
MainDialog.previewLeaflet(self)
File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 291, in previewLeaflet
json, params, popup)
File "/home/ubuntu/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 102, in writeLeaflet
cleanedLayer = writeTmpLayer(i, eachPopup)
File "/home/ubuntu/.qgis2/python/plugins/qgis2web/utils.py", line 62, in writeTmpLayer
uri = TYPE_MAP[layer.wkbType()]
KeyError: -2147483647

Here the tree of the qgis group...

![screenshot from 2015-12-14 15 08 58](https://cloud.githubusercontent.com/assets/1607387/11782926/6e06c5e0-a274-11e5-88b1-27e25d545315.png)

**Comment by tomchadwin** [comment]
Can you tell me two things:

- the geometry type of the layer which causes the error
- confirm that no drop-downs in the plugin GUI have blank values

This error came up before, and those were two possible causes:

http://gis.stackexchange.com/questions/163283/qgis-export-to-openlayers-python-error

**Comment by marcobra** [comment]
The grouped layers are lines layer: ESRI Shapefile, Geometry: Line

![screenshot from 2015-12-15 09 35 36](https://cloud.githubusercontent.com/assets/1607387/11805782/f8a4c342-a30e-11e5-8de9-50bd41dec8b5.png)

**Comment by tomchadwin** [comment]
Closing as cannot recreate. Reopen if error reoccurs.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
