### ISSUE TITLE
Allow remote WFS layers in OL3

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#17]
This is a big enhancement, but one we really need, to mirror the functionality in the Leaflet export.

**Comment by tomchadwin** [comment]
Related to #16

**Comment by ThomasG77** [comment]
The only way to do this is to set CORS headers. I already explained [a way to bypass](https://gis.stackexchange.com/questions/121555/wms-server-with-cors-enabled/147403) this issue using a third party proxy. As you can't ask end users to set their own proxy for WFS,  the solution is to begin your JS code with

```
(function() {
    var cors_api_host = 'cors-anywhere.herokuapp.com';
    var cors_api_url = 'https://' + cors_api_host + '/';
    var slice = [].slice;
    var origin = window.location.protocol + '//' + window.location.host;
    var open = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function() {
        var args = slice.call(arguments);
        var targetOrigin = /^https?:\/\/([^\/]+)/i.exec(args[1]);
        if (targetOrigin && targetOrigin[0].toLowerCase() !== origin &&
            targetOrigin[1] !== cors_api_host) {
            args[1] = cors_api_url + args[1];
        }
        return open.apply(this, args);
    };
})();
```

**Comment by tomchadwin** [comment]
If the remote server supports JSONP, do I presume that the above is not necessary?

**Comment by ThomasG77** [comment]
You are right but what you should know is :
* JSON output is not standard (only Geoserver, TinyOWS, recent QGIS Server and recent tweaked Mapserver)
* for JSONP, there are not convention for callback name and it's not supported by default by all servers.

So, relying on JSONP is a not a bad idea but not enough generic. On the other hand, for intranet purpose, a third party server is a drawback if no Internet.
A tickbox per layer for choosing if we use JSONP and a global tickbox to switch to external CORS proxy could be an answer.

**Comment by tomchadwin** [comment]
Committed to master - please test
