### ISSUE TITLE
Fix and unify save settings

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#170]
At the moment, individual GUI widgets fire events which save those widgets' settings. I did it that way because I didn't know about (despite asking on the dev list) closeEvent(). I've now used closeEvent() to save the dialog size and position.

I want to remove all the signal-slot connections from individual widgets where possible, and instead save the settings in closeEvent().

**Comment by tomchadwin** [comment]
When a setting is saved for the second time, the original saved setting is not deleted, leading to two entries. I'll try manually deleting when saving.

**Comment by tomchadwin** [comment]
I've committed a fix for saving the bottom-left panel settings. @magerlin, can you test? If you get errors, or settings not saving properly, can you open your project file in a text editor, and remove the <qgis2web> tag and its contents? I've not fixed saving basemaps yet (well, technically, they save, but don't restore yet).

**Comment by tomchadwin** [comment]
Basemaps are now saved. @magerlin, I think everything is now saved correctly. I'll close this issue, but if you find problems, I'll reopen.

**Comment by magerlin** [comment]
After downloading latest master I can confirm that base map saving and reading works as expected.

BUT NOT the bottom-left panel. I can see the settings are store in the .qgs file but they are apparently not read again (at least not in Win 7, 64 bit).

And by the way: The default export folder (at my PC: C:\Users\xxx\AppData\Local\Temp\qgis2web) is normally a hidden system folder in win 7. Inexperienced users might have a hard time finding their exported maps....
