### ISSUE TITLE
Tidy different test files into subfolders

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#172]
/test_data is a mess of different things - data, styles, and reference files. This should be sorted and combined with the /test folder in a clear way.

**Comment by akbargumbira** [comment]
Hi @tomchadwin, can you assign this to me?

**Comment by tomchadwin** [comment]
Yup - I'd be delighted. Please go ahead. And thanks!

**Comment by akbargumbira** [comment]
Closing this (done here https://github.com/tomchadwin/qgis2web/pull/177)

**Comment by akbargumbira** [comment]
Hmm, actually I can't close the issue :)

**Comment by tomchadwin** [comment]
No, because I opened it. Thanks for the work!
