### ISSUE TITLE
Leaflet "Add layers list" misses out layers from map

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#179]
I have a map with three SHP layers. If I select "Add layers list" and Leaflet format, two of my layers are not loaded onto the map, even though they appear in the layers list control. Can anyone recreate? If so, what is causing the problem?

**Comment by philipjohnbarlow** [comment]
Hi Tom, did you have any other options selected or a base map?  What type of geometry were your three shape files?  

I've just had a go with three shape files of polygons, all are appearing in the layer list and in the canvas.

**Comment by tomchadwin** [comment]
Very odd. No basemap, single styles, one point, line, and poly layer.

**Comment by tomchadwin** [comment]
This is in master, by the way, not rc1.

**Comment by philipjohnbarlow** [comment]
Yup I'm on master.  I just tried it with the test data and it is still all working fine for me.

**Comment by tomchadwin** [comment]
Sane layers I used. V odd.

**Comment by tomchadwin** [comment]
Is this the same issue that @michellemoine has reported #181? Is it the layer list and graduated/categorized styles which triggers this? Can you have a quick test when you are able, @philipjohnbarlow?

**Comment by tomchadwin** [comment]
Assuming this is the same issue as #190, I'll close this now.
