### ISSUE TITLE
Many more unit tests needed

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#180]
The tests currently include:
- single layer
- Leaflet or OL3
- point, line, or polygon
- single, categorized, or graduated
- JSON or WMS (WMS only in Leaflet)

Other than that, all options, both per-layer and general, are left with their default values. This means that many things are not tested.

### Per-layer
- popups
- clustering

### General
Every option, including:
- address search
- layers list
- scale bar
- etc

We really could do with testing more of the codebase.

**Comment by akbargumbira** [comment]
I would also suggest to add some unittesting for each functions as I can see that the tests right now are only validation tests

**Comment by tomchadwin** [comment]
Most features now have tests, so I'll close this for now.
