### ISSUE TITLE
Wrong raster / vector order in Leaflet layer list.

### ISSUE THREAD

**Issue by dvictori** [tomchadwin/qgis2web#182]
Created a Leaflet map with one vector, one raster layer, OSM and a layer list. In QGis, vector is on top of raster. However, when I export the map, raster appears on top of the vector in the layer list BUT, on the map, vector appears on top. Once I turn off /on the raster layer, raster is displayed on top of vector.

Data and webmap created can be downloaded from https://dl.dropboxusercontent.com/u/19035357/teste_qgis2web.7z

**Comment by tomchadwin** [comment]
I'm having a pretty hard time disentangling what Leaflet can do, both in stable 0.7.7 and 1.0.0 beta, as far as z-index of *both vector and raster layers* goes. I might have to ask a question on StackExchange to get a proper answer to it. Sorry not to be able to do something straight away.

**Comment by dvictori** [comment]
No need to apologize. What you've done is great and I wish I could help out more. Thanks for the hard work

**Comment by tomchadwin** [comment]
I've asked here:

http://gis.stackexchange.com/questions/178622/z-index-of-geojsons-and-imageoverlays-in-leaflet

No answers yet.

**Comment by tomchadwin** [comment]
Looks as though there will be ways of sorting this with Leaflet 1.0.0 (see StackExchange question above, now answered). I don't want to use 1.0.0 until its full release, though. Hope that makes sense.

**Comment by dvictori** [comment]
Good to know this will be addressed. And completely understand the wait for the full release.

**Comment by tomchadwin** [comment]
Closing as a wontfix until Leaflet 1.0.0 is released, when the whole z-order thing will need revisiting.
