### ISSUE TITLE
"Highlight features" doesn't work with lines

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#188]
Can anyone confirm? Polygons and points work. I thought lines used to, but they are not for me at the moment.

**Comment by tomchadwin** [comment]
Is it that, with lines, we need to change the stroke colour to the highlight colour, unlike points and polygons, where we change the fill?

**Comment by lucacasagrande** [comment]
Yes, and we also need _width_ from style definition.

**Comment by lucacasagrande** [comment]
There is a problem also when using Leaflet.

**Comment by tomchadwin** [comment]
Fixed in master by @lucacasagrande. Thanks again, Luca!

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
