### ISSUE TITLE
Using 'Fit to layers extent' with a WMS screws Leaftlet up

### ISSUE THREAD

**Issue by ukmapper** [tomchadwin/qgis2web#193]
One WMS layer in QGIS, exports fine in all situations except when using the 'Fit to layers extent' option with Leaflet. 

The result is nothing is displayed, not even a basemap.

**Comment by tomchadwin** [comment]
Is it true that this is only the case *if no other raster or vector layers are present*?

**Comment by tomchadwin** [comment]
Yes, I believe that is the issue - can you confirm? In other words, if you add a second non-WMS layer, does the issue disappear? If so, I've just committed a fix to master, so do please test if you can. I'll close this issue for now - reopen if the fix does not work, or if I've not narrowed down the problem correctly.

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
