### ISSUE TITLE
Legend graphic from WMS

### ISSUE THREAD

**Issue by ukmapper** [tomchadwin/qgis2web#194]
Is it possible to pull through the legend graphic from a WMS? It appears in QGIS, but not in the layers list.

**Comment by tomchadwin** [comment]
I don't have much experience of this. I've just loaded up a WMS in QGIS, and the legend graphic seems to be a very large one with ugly graphical representation of text. Is that the kind of thing you are seeing? If so, I'm not very keen for that to go in the maps automatically.

Are you able to share your WMS address?

**Comment by tomchadwin** [comment]
Closing after no response from original requester. Reopen if required.
