### ISSUE TITLE
Highlight Features issues in Chrome and Firefox

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#195]
Highlighting a polygon will have a bad effect on another layer. In this case the red dots will be hidden behind the highlighted polygon
Please check this with Chrome or Firefox:
http://bassinefe-liege.be/qgis2web_canvasextent
Internet Explorer 11 seems to be doing a better job.

**Comment by tomchadwin** [comment]
Can you try removing line 51 of `index.html`:

`highlightLayer.bringToFront();`

I've always wondered whether that should be there.

**Comment by michellemoine** [comment]
Thanks Tom. It's fine now

**Comment by tomchadwin** [comment]
OK, let me fix that in the plugin.

**Comment by tomchadwin** [comment]
Fixed in master - that line should no longer be present, so it should work straight from export. If anyone sees any unwanted side effects of this, do report them.

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
