### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#196]
Tom,
Could you please check this link:
http://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.css%22

**Comment by tomchadwin** [comment]
That final %22 shouldn't be there. Manually delete it and let us know if that fixes it. If so, I'll find out how it got there, and fix the issue.

**Comment by tomchadwin** [comment]
I think I've fixed this in master. Can you let us know?

**Comment by michellemoine** [comment]
Thanks Tom.

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
