### ISSUE TITLE
Clustering layer points: checking out and in any layer in the list layer will affect the visiility of the layer points.

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#198]
http://bassinefe-liege.be/qgis2web_hiddenlayer
There is no issue if the cluster option is off:
http://bassinefe-liege.be/qgis2web

**Comment by tomchadwin** [comment]
Do you mean if you uncheck and then check layers in the layers list, the stacking order of clustered layers is changed?

**Comment by michellemoine** [comment]
Yes. Checking out and in any layer will affect only the red point layer. Clustered points are not affected.

**Comment by michellemoine** [comment]
Tom, we haven't talked about this issue since then, but I just tested this again and the problem has gone.
Having said that, there is a new issue. Unchecking the point layer will not hide the layer completely.  
http://bassinefe-liege.be/qgis2web_cluster

**Comment by tomchadwin** [comment]
Ah, this is a reversion - the map is displaying points both clustered and unclustered at once. I'll have to investigate next week.

**Comment by tomchadwin** [comment]
Closing this one and will open another for the new issue

**Comment by tomchadwin** [comment]
See #204
