### ISSUE TITLE
wms doesn't work

### ISSUE THREAD

**Issue by Axgro12** [tomchadwin/qgis2web#200]
Hi!
If I add a wms service in Qgis and then I go in Qgis2web nothing is showed in OpenLayers or Leaflet. I tried adding just one layer (the wms) and adding some other layer, but nothing changed. 

Thanks for your work!

**Comment by tomchadwin** [comment]
You probably need to check the following:

- in what projection is the WMS supplying its data?
- set your QGIS project to that projection
- in qgis2web, check "Match project CRS"

If that does not work (and it might well not), we probably need the address of the WMS in order to help - is it public?

**Comment by Axgro12** [comment]
The projecton is WGS84, I set correctly and made all, but it doesn't work.
I think the wms is pubblic: http://www.cartografia.servizirl.it/arcgis/services/wms/ctr_wms/MapServer/WMSServer?request=GetCapabilities&amp

It's a wms from Regione Lombardia (taly)

**Comment by tomchadwin** [comment]
OK, I've connected to that WMS fine. Which layer have you used?

**Comment by tomchadwin** [comment]
CTR-DBT works for me, in both Leaflet and OpenLayers3.

**Comment by Axgro12** [comment]
It's CTR_DBT Layer,
thank tou for the help

**Comment by Axgro12** [comment]
OK, thank you.
I try reinstall plugin or/and Qgis.

If useful, I have Qgis Lyon 2.12.3 and Windows 10

**Comment by Axgro12** [comment]
I did reinstall plugin and qgis. Still don't work, but other wms service work. Don't know what to say

**Comment by tomchadwin** [comment]
I added that WMS server as a new connection, connected to it, and added that layer. I right-clicked that layer, and set the project CRS from the layer. I then exported. I had other layers open in my map. Did your process differ from that in any way?

**Comment by Axgro12** [comment]
nope!
I did the same things exactly and still doesn't work. Maybe it's something about my Qgis.
Thanks for the help, I hope I will figure out it someway

**Comment by tomchadwin** [comment]
Are you using current master from here on Github, or 1.0.0-RC2?

**Comment by Axgro12** [comment]
I used to use 1.0.0-RC2. Now I downloaded the master from here, substituted all files in the plugin folder but no results.

This wms, for example, works: http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/ortofoto_colore_provincia_como.map

layer 1.

I'm searching if it is something different from the two wms layers. CRS is the same and others setting are the same. It's just smaller than the first wms, but I tried with larger layer wms and they work.

**Comment by tomchadwin** [comment]
OK, I was describing what I did from memory. I'm at my machine now, so will describe it fully:

1. Click `Add WMS/WMTS Layer`
2. Click `New`
3. Give a friendly name, and the URL `http://www.cartografia.servizirl.it/arcgis/services/wms/ctr_wms/MapServer/WMSServer` - no other settings changed
4. Click `OK`, and then `Connect`
5. Select layer id 1, name and title CTR_DBT
6. Leave all other settings untouched (JPEG, WGS 84)
7. Click `Add` and then `Close`
8. Right-click the layer, and click `Set Project CRS from Layer`
9. Zoom and pan in QGIS so the layer is visible
10. Start qgis2web and set `Extent` to "Canvas extent", and select Leaflet format
11. Click `Update preview`

I see the layer:

![wms](https://cloud.githubusercontent.com/assets/7840213/12843123/2a6687ea-cbef-11e5-9245-d19d2bd86fba.png)

**Comment by Axgro12** [comment]
Now it really works, I think the url of wms I use was someway wrong.
Thanks for you're help, you're plugin is great.

**Comment by tomchadwin** [comment]
Glad it's working for you now. And thanks for the kind words.
