### ISSUE TITLE
Leaflet categorized layer - value legend missing

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#203]
Layer "Opérateurs"  : symbol markers with different colors.
http://bassinefe-liege.be/qgis2web_categorized

**Comment by tomchadwin** [comment]
Opérateurs is categorized in QGIS?

**Comment by michellemoine** [comment]
Yes it is.

**Comment by tomchadwin** [comment]
Any javascript errors?

**Comment by michellemoine** [comment]
No errors Tom.

**Comment by tomchadwin** [comment]
Can you share the layer?

**Comment by michellemoine** [comment]
If you mean the link. It's on the on my first post

**Comment by tomchadwin** [comment]
No, I mean the source layer, so I can try to recreate the problem. Can't think what it is.

**Comment by tomchadwin** [comment]
Does it fail if it's the only layer in the map?

**Comment by michellemoine** [comment]
It fails also when it's the only layer on the map.
How can I share the layer Tom ?

**Comment by tomchadwin** [comment]
Sorry, as well as the layer file, I'd need a style file.

**Comment by tomchadwin** [comment]
Upload the layer file and saved style file somewhere, or email it to me.

**Comment by michellemoine** [comment]
Ok. Will do

**Comment by michellemoine** [comment]
Sent by email.

**Comment by tomchadwin** [comment]
Thanks for the files. Since the layer name has an é in it, have you tried current master, given the i18n changes which have been made?

**Comment by tomchadwin** [comment]
I meant to say, it works for me:

![screenshot 2016-02-05 12 58 25](https://cloud.githubusercontent.com/assets/7840213/12847028/593f405c-cc08-11e5-914b-ba29968d7cc1.png)

**Comment by michellemoine** [comment]
I have tried both yesterday. I 'll download the new version and will try again. As you can see in the screen capture, the different color categories are missing from the legend.

**Comment by tomchadwin** [comment]
My apologies - of course you are right. The categories are not present in the layers list. I'll investigate.

**Comment by tomchadwin** [comment]
Recreated - thanks. Fix coming.

**Comment by tomchadwin** [comment]
Fix committed to master - please test.

**Comment by michellemoine** [comment]
Thanks Tom. It's working

**Comment by tomchadwin** [comment]
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
