### ISSUE TITLE
Leaflet cluster shows unclustered points as well

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#204]
From #198

**Comment by michellemoine** [comment]
I suppose it's a normal behaviour to show clustered points only when it's necessary. If you turn that layer off, some points will stay visible and not others regardless if they are clustered or not.

**Comment by tomchadwin** [comment]
This happened before:

https://github.com/tomchadwin/qgis2web/issues/162

**Comment by tomchadwin** [comment]
Does it also happen with remote WFS layers?

**Comment by tomchadwin** [comment]
No, it doesn't happen with WFS layers. It also doesn't happen with JSON single-style layers, only JSON categorized/graduated.

**Comment by tomchadwin** [comment]
I've committed a fix to master. Please test and let me know if it is now sorted.

**Comment by michellemoine** [comment]
Hello Tom,
Actually, only part of the issue is fixed and that's excellent. Checking out the points layer works for clustered and non clustered points. Checking in the layer again, non clustered points layer order is changed.

**Comment by tomchadwin** [comment]
Reopening to investigate.

**Comment by tomchadwin** [comment]
To clarify, is the following description of this issue as it now stands correct:

- layers cluster correctly - there is no longer duplication of clustered and unclustered points
- clustered points are visible above other layers, but unclustered points within a clustered layer are moved lower down the z-order when the clustered layer is hidden and then displayed via the layers control

Is that it?

**Comment by michellemoine** [comment]
That's correct.

**Comment by tomchadwin** [comment]
I don't know if I can do anything about this. My suspicion is that this behaviour emerges from the markercluster plugin. Does anyone else think differently?
