### ISSUE TITLE
Option to add text on map

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#207]
It would be nice if one could add a few lines of text on the map. 
I often manually add something like this just before the <\body> tag in the generated index.htm file:

`<div style="position: absolute; left: 70px; top: 10px;  background-color: white; opacity:0.6; padding:5px">
     <h2>Map title</h2>
      Map subtitle
</div>`

I suppose it will be quite easy to add this feature as a part of the plugin?

**Comment by tomchadwin** [comment]
Edit the template, or create a new one. You should see a lot of @VARIABLES@, including one which is the QGIS project title. You can add your DIV to a template, and put that variable into it, then set your text add the QGIS project title.
