### ISSUE TITLE
Option to save map setup

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#208]
It would be nice if one could save the setup for Qgis2web. 

Either as a part of the .qgs project file (don't know if that is possible?).

Or in a separate file - perhaps with the same feature as for .qml files and .shp files: If you use the same name for the saved qgis2web settings file as the .qgs project file, then it will be used as the defaults for Qgis2web in that project - also the next time you open the project?

**Comment by tomchadwin** [comment]
This is already implemented,  but I thought it might not be working. I guess you do too?

**Comment by magerlin** [comment]
First off all: It is a VERY cool plugin!

As I see it:
•	Settings from the topleft pane are stored as you say
•	From the bottom left pane it appears to me, that none or perhaps a few settings are stored (or they are perhaps just kept at their default settings?)
•	From the bottom right pane (background maps) nothing is stored

Regarding my other post on adding text to the map I am embarrassed not to have seen that in the help pane :-(

It is cool that the plugin can use the field alias’ (I have not seen much use of that elsewhere).
But there is a problem on using national characters in alias names (perhaps a general Qgis problem?) – it gives this error:
Error
qgis2web produced an error:
Traceback (most recent call last):
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\maindialog.py", line 125, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\maindialog.py", line 308, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 157, in writeLeaflet
visible, json, legends, new_src)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 85, in writeVectorLayer
popupsOnHover, popup, count)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 179, in labelsAndPopups
popFuncs = popFuncsScript(table)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletScriptStrings.py", line 167, in popFuncsScript
layer.bindPopup(popupContent);""".format(table=table)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 171: ordinal not in range(128)

Another small problem: The order of layers in legend in the final map is not always the same as in the Qgis Project and qgis2Web Preview (the two latter have I only seen being in identical order)

Regards

**Comment by tomchadwin** [comment]
See this issue for the layer list order and z-order of layers in Leaflet: https://github.com/tomchadwin/qgis2web/issues/182

**Comment by tomchadwin** [comment]
For the save settings issue, see https://github.com/tomchadwin/qgis2web/issues/170
