### ISSUE TITLE
icon_exp being ignored when exporting to leaflet

### ISSUE THREAD

**Issue by azstumbler** [tomchadwin/qgis2web#209]
When exporting from QGIS the Layer markers are showing up correctly based upon what is in the legend_exp field of the attribute table. However the marker on the map is not what is in the icon_exp field and appears to be an arbitrary blob of color. The symbols are png and I have used them in qgis2leaf but now in qgis2web they are not working

**Comment by tomchadwin** [comment]
icon_exp is no longer supported. For custom markers, the recommendation is to use SVG markers in QGIS, which are exported.
