### ISSUE TITLE
Unicode characters in field aliases give unicode error in Leaflet

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#210]
Reported here: https://github.com/tomchadwin/qgis2web/issues/208

**Comment by tomchadwin** [comment]
Fixed in master: please test, @magerlin

**Comment by magerlin** [comment]
Confirmed - no more errors.

Using alias in OpenLayers has no effect - is that known/intended?

**Comment by tomchadwin** [comment]
Thanks. No, that needs to be added to OL3. Will create a new issue.

**Comment by tomchadwin** [comment]
Aliases now used in OL3 in master. Please test.

**Comment by magerlin** [comment]
I can confirm that aliases now work in OL3 as well. 

A minor issue: The width of the pop up in OL3 is rather small compared to the width in Leaflet maps giving longer aliases a bad layout:

OL3:
![image](https://cloud.githubusercontent.com/assets/1887531/16322153/8c6702b0-39a1-11e6-9e92-68b3bab5a650.png)

Leaflet:
![image](https://cloud.githubusercontent.com/assets/1887531/16322172/9cd0a50c-39a1-11e6-920b-de7471aaf333.png)

But perhaps this is an OL3 issue not Qgis2web.....
