### ISSUE TITLE
Integrating Qtiles plugin too?

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#211]
Vector files with many features (~100.000) will normally "kill" any browser in both Leaflet and OpenLayers maps.

One solution is to convert to raster tiles and use these instead. The [Qtiles plugin](https://github.com/nextgis/QTiles) can do this and even produce a leaflet viewer of the tiles so I guess it would not be that much work to incorporate it in Qgis2web?

**Comment by tomchadwin** [comment]
I'm reluctant to build in such a dependency/integration. People can prepare the layers they want to in QGIS itself, rather than qgis2web taking on that job.

**Comment by magerlin** [comment]
OK fair enough - I saw it a bit like when gis2web can transfer wfs layers to geojson

**Comment by tomchadwin** [comment]
I don't think the similarity holds - WFS to JSON keeps vectors as vectors, stores attribute data, and so on. It really is just a storage format change. But burning a vector dataset to raster, thereby losing attribute data, and then tiling it is a much bigger change. My opinion, anyway.
