### ISSUE TITLE
Export to webmap crashes

### ISSUE THREAD

**Issue by ametz112** [tomchadwin/qgis2web#213]
Hello,

Upon opening the qgis2web plugin, I receive the following error message:

minidump written to C:\Users\AMETZ_~1\AppData\Local\Temp\qgis-20160212-114317-6984-6708-99ac688.dmp

When I click 'OK', the entire qgis program closes.

Thank you for taking the time to review this and comment!

**Comment by tomchadwin** [comment]
Has anyone else experienced this? I've never debugged a minidump. Can anyone help with this?

**Comment by tomchadwin** [comment]
Are you still getting this crash?

**Comment by ametz112** [comment]
Hey Tom yes I am.

**Comment by tomchadwin** [comment]
Can you upload your project and layers so I can try to recreate the issue?

**Comment by tomchadwin** [comment]
Closing for now without further feedback.

**Comment by ernapiantari** [comment]
@tomchadwin I have same problem with @ametz112. When I used QGIS2WEB for a little layer, I got it. But when I tried to add some other layer, I got error message same with @ametz112. Can you help me?

**Comment by boesiii** [comment]
Are you able to upload the "some other layer" so we can look at the layer?

**Comment by tomchadwin** [comment]
@ametz112 @ernapiantari Yes, can you upload the data which causes the crash? @boesiii is right - we need that to solve this problem.

**Comment by tomchadwin** [comment]
Closing with no feedback.
