### ISSUE TITLE
Problem producing lots of features

### ISSUE THREAD

**Issue by ardit700** [tomchadwin/qgis2web#215]
I was using qgis2web successfully in November, 2015. 

Now, I tried it again with the current version and realized that when I had lots of polygon features (2000 rows) the navigation on the produced web map (i.e. zooming, panning) becomes very slow. 

I then deleted most of the features and kept only 200 of them and noticed the navigation was working smoothly. 

Do you know why this might be?

**Comment by philipjohnbarlow** [comment]
2000 polygons? The lag I not surprising. There are a couple of things you could try. I'd start by simplifying your layer, you can on this in the plugin just reduce the accuracy. You could also try applying a scale dependency so less objects render at once.

This is a known short coming of leaflet, another option is to render your layer as a raster.

**Comment by ardit700** [comment]
Yeah, I was able to find a solution by simplifying the geometry. Those polygons had too many vertexes. 
The scale dependency feature also sounds like a good option.

**Comment by tomchadwin** [comment]
Glad you found a solution. Closing this issue - reopen if necessary.
