### ISSUE TITLE
Update OL3 LayerSwitcher

### ISSUE THREAD

**Issue by walkermatt** [tomchadwin/qgis2web#217]
Hi Tom,

I thought you might like to know that [ol3-layerswitcher] (https://github.com/walkermatt/ol3-layerswitcher/) has seen some updates recently including [fixing scrolling on touch devices](https://github.com/walkermatt/ol3-layerswitcher/issues/18).

Cheers,

Matt.

**Comment by tomchadwin** [comment]
Ah, great. No breaking changes, to your knowledge? I'll try dropping in the new version. Thanks.

**Comment by tomchadwin** [comment]
Updated in master. If you were ale to test, I'd be very grateful.

**Comment by philipjohnbarlow** [comment]
Looks to be working fine with the test data and a few WFS layers.  The only thing I have noticed is that if you enable the measuring tool and highlight on hover highlighting stops working and you get "click to start drawing" message as if you had just selected the measuring tool. This happens in both preview and export e.g

![capture](https://cloud.githubusercontent.com/assets/14541141/13285635/a07b272a-daf3-11e5-842b-a240e8934112.PNG)

**Comment by tomchadwin** [comment]
Confirmed - I'll open a new issue for that.

**Comment by walkermatt** [comment]
Thanks Tom, I've also just tested and the updated layer switcher is displaying as expected.

I initially create a map without a base map, I think I might update the layer switcher to only display the base maps group when there are base maps.

**Comment by tomchadwin** [comment]
OK, great. Have you also seen this: http://gis.stackexchange.com/questions/181111/tweaking-some-aspects-of-open-layer-3-output-using-qgis2web. Don't know if any of that is possible via the switcher.
