### ISSUE TITLE
Conflict between measure and highlight in OL3

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#218]
From #217

**Comment by tomchadwin** [comment]
Can't figure this one out. Can anyone else?

**Comment by philipjohnbarlow** [comment]
Had a look at the plugin output where I first noticed this issue.  I'm getting a single message in the debugger in IE that refers to the helptooltip element.  "Unable to get property 'removeClass' of undefined or null reference".  Line 145.

**Comment by walkermatt** [comment]
I'd be happy to take a look providing you don't mind if it takes me a few days to get to it.

**Comment by tomchadwin** [comment]
That would be brilliant. You can take two months if you want. Really grateful.

**Comment by walkermatt** [comment]
I've been looking at this over the last few days and almost have something workable. I think medium term we probably want to create a measure control but I'll focus on fixing up the current implementation first.

**Comment by tomchadwin** [comment]
Brilliant - thanks, Matt. What was the conflict?

By the way, are you going to FOSS4GUK? Can you stay for the sprint?

**Comment by walkermatt** [comment]
The main issue is that the hover / highlight and measure logic is in the same handler for the `pointermove` event.

Are you aware that some leaflet related tests are currently failing on master? I should probably wait until they are fixed before issuing a PR?

I'm helping organise FOSS4GUK so will definitely be there, I'm hoping to make the code sprint.

**Comment by tomchadwin** [comment]
I've not got Leaflet failures on Tavus: https://travis-ci.org/tomchadwin/qgis2web. Have you got up-to-date current master?

**Comment by walkermatt** [comment]
I'll take a look at this today at the #foss4guk code-sprint.

**Comment by tomchadwin** [comment]
Released as 1.10.0-FOSS4GUK2016 experimental and pushed to QGIS plugins repo.
