### ISSUE TITLE
Add `type: 'base'` property to ol3 base layers

### ISSUE THREAD

**Issue by walkermatt** [tomchadwin/qgis2web#219]
Currently ol3 base layers are added to a "Base maps" layer group but they do not have have a `type` property with a value of `'base'` which is required by [walkermatt/ol3-layerswitcher](https://github.com/walkermatt/ol3-layerswitcher) in order for radio buttons to be displayed. Unless there is a valid reason for this I'd be happy to make the required changes.

**Comment by tomchadwin** [comment]
Please do - that would be splendid. Many thanks!

**Comment by tomchadwin** [comment]
ANy joy with this, @walkermatt?

**Comment by walkermatt** [comment]
Hi, I've a WIP version that needs a little more testing. BTW I couldn't get the unit tests to run due to a missing processing module, any tips (I'm on Linux and have tried running the env script)?

**Comment by tomchadwin** [comment]
You mean running them manually? I've only ever run them via Travis, so I'm not sure. If you post the error here, @akbargumbira might be kind and take a look. But don't worry too much. Travis will test your PR.

**Comment by akbargumbira** [comment]
@walkermatt perhaps try to source this script? https://github.com/tomchadwin/qgis2web/blob/master/scripts/run-env-linux.sh (and don't forget to change the QGIS_PREFIX_PATH to your qgis installation path)

**Comment by tomchadwin** [comment]
Thanks, Akbar.

**Comment by walkermatt** [comment]
I've made some progress with running the tests on Ubuntu 15.10 with QGIS 2.8.3-Wien. To get the tests to run I had to run:

    cd ~/.qgis2/python/plugins/qgis2web
    source scripts/run-env-linux.sh /usr
    make test

Where `/usr` is the `QGIS_PREFIX_PATH`.

I'll now look create some tests for my changes :smile_cat:

**Comment by tomchadwin** [comment]
Thanks very much! Yes, the existing tests don't enable the layer switcher, so it is untested.

**Comment by tomchadwin** [comment]
Just built an Ubuntu VM, but cannot get tests to run locally:

```
/bin/sh: 4: nosetests: not found
```

How do I solve this?

**Comment by tomchadwin** [comment]
Duh. I haven't installed nose. Sorry. Linux n00b.

**Comment by tomchadwin** [comment]
OK, got nose running the tests fine, but it doesn't like my SHPs:

```
Exception: Layer "/home/tchadwin/.qgis2/python/plugins/qgis2web/test/data/layer/
airports.shp" is not valid
```

Two other tests fail:

```
======================================================================
FAIL: QGIS properly parses a wkt string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tchadwin/.qgis2/python/plugins/qgis2web/test/test_qgis_environment
.py", line 50, in test_projection
    self.assertEqual(auth_id, expected_auth_id)
AssertionError: u'' != 'EPSG:4326'

======================================================================
FAIL: QGIS environment has the expected providers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tchadwin/.qgis2/python/plugins/qgis2web/test/test_qgis_environment
.py", line 35, in test_qgis_environment
    self.assertIn('gdal', r.providerList())
AssertionError: 'gdal' not found in []
```

All of these pass in Travis, and for @walkermatt and @akbargumbira. What is wrong in my fresh install?

**Comment by walkermatt** [comment]
Which directory are you running the tests from? Can you post the commands you run? For example I ran:

    cd ~/.qgis2/python/plugins/qgis2web
    source scripts/run-env-linux.sh /usr
    make test

**Comment by tomchadwin** [comment]
Another n00b error: I presumed that my environment meant I had to set QGIS_PREFIX_PATH to `/usr/bin`. Leaving it as `/usr` has the tests all running. Thanks very much for the help, and apologies for the noise.

**Comment by tomchadwin** [comment]
Added these local testing instructions to README.
