### ISSUE TITLE
2.5d writes OSMBuildings columns back to original layer

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#221]
If so, this is serious. Can anyone confirm, and if so, find out what is going wrong?

**Comment by tomchadwin** [comment]
Confirmed: every time a 2.5d layer is rendered by the plugin (preview or export), it adds another three variables to the *original* layer (`height`, `wallColor`, and `roofColor`). I don't know why these are being written to the original layer file, and not simply to the temp scratch memory layer created by `writeTmpLayer()`.

**Comment by anitagraser** [comment]
Confirmed here: I'm already at column no. 29 ;-)

**Comment by tomchadwin** [comment]
Yeah. Mid-80s is my record, before I realized it was happening. Eek. Happily, @nyalldawson has spotted my error, so I hope to have a fix soon. Thanks, Nyall!

**Comment by tomchadwin** [comment]
I've committed a possible fix to master, but it needs more testing before being released. Let me know if it works for you.
