### ISSUE TITLE
Features disappearing in Chrome (Firefox OK), and in Export window

### ISSUE THREAD

**Issue by dpsspatial** [tomchadwin/qgis2web#223]
I've built a simple map with 2 layers, a point (overlay) and polygon(background)

When viewing the map in Chrome, after some panning/zooming, some of the point features disappear:

![chrome](https://cloud.githubusercontent.com/assets/12851723/13795778/6c85d534-eac8-11e5-8114-8261115756a5.PNG)

After some time trying to re-produce this in Firefox, I can't get the points to disappear:

![ff](https://cloud.githubusercontent.com/assets/12851723/13795777/6c84caf4-eac8-11e5-9dab-c05bce558749.PNG)

I'm also seeing features disappearing in the Export to web map window:

![export](https://cloud.githubusercontent.com/assets/12851723/13795918/5bb2662c-eac9-11e5-9143-69c527daeb83.PNG)

Any thoughts on this one?

**Comment by tomchadwin** [comment]
I've not seen this myself. Is it in Leaflet or OL3 maps, or in both? Are you able to recreate the problem reliably? It might also be worth searching for the issue online relating to Leaflet/OL3 - ie this might be an underlying issue with the mapping library, and not specific to qgis2web.

**Comment by dpsspatial** [comment]
Seems to be only in Leaflet, and can repro this every time both in the preview window and the exported project.

Also: has the symbol size setting changed? Preview/export maps are not showing the same size as in the QGIS map (but yesterday, as with images above, symbol sizes were the same...)

Image from today's test:

![leaflet_disppearingfeatures](https://cloud.githubusercontent.com/assets/12851723/13890134/885aa6ec-ed0f-11e5-8b0a-63858b4bad17.PNG)

**Comment by magerlin** [comment]
Same problem occurred in one of my maps. Googling I found it to be a Leaflet issue as suggested: [https://github.com/Leaflet/Leaflet/issues/2824](url)

The link suggests a simple fix (at the bottom) assuring that setRadius is a number, not a string.

Could that be the problem (and fix) with maps generated by Qgis2web?

**Comment by tomchadwin** [comment]
Can you confirm that radii are being set as strings, perhaps not always, but in the maps which show this problem?

**Comment by magerlin** [comment]
I am not sure how to do that?

In Qgis I have just selected a fixed radius of 6 mm in the layer styling (graduated). Whether "6" then is a string or a number when transferred to javascript by the plugin I do not know how to find out - I only know at little about javascript, sorry. 

Setting a fixed radius in pixels still have the same problem. 

But it seems like changing the Qgis styling to "Single Symbol" instead of graduated removes the problem! 

I have attached the generated map code (with graduated styling) here:

[qgis2web_1463991291.07.zip](https://github.com/tomchadwin/qgis2web/files/277211/qgis2web_1463991291.07.zip)

**Comment by tomchadwin** [comment]
I think you've found it:

```
radius: '6.0',
```
I'll try and do a fix now.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by magerlin** [comment]
Issue Solved - nice and quick. Thank you

**Comment by tomchadwin** [comment]
Great. @dpsspatial, can you test and report back?

**Comment by tomchadwin** [comment]
Thanks for finding the explanation, @magerlin!

**Comment by tomchadwin** [comment]
I'll close this for now. Please reopen if you are still having this issue.

**Comment by dpsspatial** [comment]
This looks great on my end - thank you all for tracking this down!!!

**Comment by tomchadwin** [comment]
Splendid - thanks for letting us know.
