### ISSUE TITLE
Suggestion: remove popup field chooser for layers

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#224]
You can manage which fields appear in your popups by setting fields in QGIS to hidden. Does that mean we should get rid of the qgis2web combobox for selecting popup fields? It's not perfect anyway, as the only options are no popup, all fields, and any one single field - you can't have multiple selected fields (#205).

**Comment by freewheelCarto** [comment]
This makes sense to me.  you could just have a 'no popups' checkbox for if you don't want them. Otherwise, people probably already have their data organized for what they want to show.

**Comment by tomchadwin** [comment]
OK, I think this is the way to go. Thanks for the feedback. Will do this when I can. Will be a good bit of work to unpick the existing code.

**Comment by boesiii** [comment]
What if a shapefile you are using has many fields?  It is not easy to make them all hidden, so i would say leave it as is?

**Comment by tomchadwin** [comment]
Done in master. Sorry,  @boesiii.
