### ISSUE TITLE
Leaflet layers order 

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#225]
Hi Tom,

I am having the following issues :

- The layers are in reversed order when exported

- In the following example : http://cartographie-bassinefeliege.be/qgis2web If I ckeck off the points layers and check on only the last layer (green), it will show under the polygon layer. Checking on all the other point layers will restore the green layer on top of the polygon layer.

Any help is very much appreciated

**Comment by tomchadwin** [comment]
Confirmed. Very strange behaviour. There have been various issues raised about layer order already, and there is no easy solution until Leaflet 1.0.0 is fully released. I'll try to find the links tomorrow.

**Comment by tomchadwin** [comment]
See #98 and #182. Are either of those the same issue(s)?

**Comment by michellemoine** [comment]
In my example, the first point layer (blue) is working fine. The last two points layers if checked off and on again while the blue layer is still checked on, will be displayed normally as they should.
 
The blue layer seems to trigger something when it's checked on for the last two layers to work properly. Without the blue layer checked on, the last two layers will be displayed under the polygon layer.

**Comment by tomchadwin** [comment]
Can you try the leaflet1.0.0 branch and report back? The layer sort code is cimpletely different in Leaflet 1.0.0.
