### ISSUE TITLE
My own templates get deleted when Qgis2web is updated

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#227]
Should there be a separate folder for user templates as the templates in C:\Users\XXX\.qgis2\python\plugins\qgis2web\templates gets deleted when the plugin is updated using Plugin Manager?

**Comment by tomchadwin** [comment]
A very valid and important point - I am so sorry that you have lost files. I'l have to think about how to handle this.

**Comment by tomchadwin** [comment]
OK, I've committed a change to master to fix this, and updated the README/Help tab to describe the new location of the templates folder. Let me know how it works for you. Once again, many apologies that you lost your templates.

**Comment by tomchadwin** [comment]
Released as 1.5.0 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
Sorry for late answer, been away on easter holliday...

Using latest release 1.5.0 gives this error

Error

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\maindialog.py", line 123, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\maindialog.py", line 304, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 191, in writeLeaflet
matchCRS, canvas, mapLibLocation, new_src, template)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\leafletFileScripts.py", line 155, in writeHTMLstart
base = replaceInTemplate(template + ".html", values)
File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\utils.py", line 295, in replaceInTemplate
with open(path) as f:
IOError: [Errno 2] No such file or directory: u'C:/Users/MAP/.qgis2/python/plugins\\qgis2web\\templates\\Ramboll.html'

As I see it "/python/plugins" should be removed from the above path to my template?

Files should been in right location as I understand the Help tab:
![screenshot 2016-04-04 10 17 38](https://cloud.githubusercontent.com/assets/1887531/14241892/7ff78ff0-fa4e-11e5-9f0e-8bbd0851d9bd.png)

**Comment by magerlin** [comment]
Just adding: The built in templates gives no error...

**Comment by tomchadwin** [comment]
Thanks for the feedback - I've been away for a week too - and sorry it's still not sorted for you. Will have to investigate, as my tests had this sorted.

**Comment by tomchadwin** [comment]
Ah, I've found the error - fix coming.

**Comment by tomchadwin** [comment]
Fix committed to master - please test.

**Comment by tomchadwin** [comment]
Released as 1.5.1 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
Works well now

**Comment by tomchadwin** [comment]
Great. Thanks for testing and reporting back.

**Comment by magerlin** [comment]
Just realized that I will have to manually put the "canvas-size.html" and "full-screen.html" templates in the new "C:\Users\XXX\.qgis2\qgis2web\templates" folder since they are not read from the old folder "C:\Users\XXX\.qgis2\python\plugins\qgis2web\templates" anymore. Is this by intention?

**Comment by tomchadwin** [comment]
No, they should be copied over when first run. If it's not too much to ask, can you uninstall qgis2web and delete `.qgis2/qgis2web`, then reinstall qgis2web and look at the contents of the `.qgis2/qgis2web` folder to see if the templates are there?

**Comment by magerlin** [comment]
Totally removing Qgis2web **AND** the "C:\Users\XXX\.qgis2\qgis2web\templates" folder makes "canvas-size.html" and "full-screen.html" being copied to a new created "C:\Users\XXX\.qgis2\qgis2web\templates" folder.

But if "C:\Users\XXX\.qgis2\qgis2web\templates" already exists the templates are NOT copied. 

This means that when updating the plugin the "canvas-size.html" and "full-screen.html" are not being updated (in case changes should have been made to these). The user will "be stuck" on the ones from the first installation.

**Comment by tomchadwin** [comment]
I understand now. However, since there is nothing to prevent users making their own modifications to those two templates, I'd argue that they should not be overwritten, as that would be the equivalent of the issue you first reported, with an upgrade destroying user data.

**Comment by magerlin** [comment]
I see your point - but could there not be a situation where you add some new features which requires some new code in the templates? At least user will then have to be made aware the the update requires some manual copying.

**Comment by tomchadwin** [comment]
There could, yes. Two ways round it:

1. If that happens, I version the filenames, or give them different names
2. Write a whole bunch of code which diffs the install templates to the ones already installed on the user's PC and overwrites if they are uncustomized.

**Comment by magerlin** [comment]
Option one sounds like a fine solution :-)

**Comment by tomchadwin** [comment]
And a loss less code, so I'm happy.
