### ISSUE TITLE
OSM Black & White as background map

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#228]
The Qgis2leaf plugin which Qgis2web is based on has an option to choose OSM Black & White as background map. I would like to have that in Qgis2web too, as the more colourful background maps often interfere to much with colours of layers put on top.

**Comment by tomchadwin** [comment]
From memory, the tileserver which served the B&W OSM tiles from qgis2leaf disappeared, so I had to remove it from qgis2web. If you can find an open tileserver with those tiles (or any others you think should be basemaps in qgis2web), post the address(es) here, and I can look at adding them. **Note**: they must be tileservers (xyz), and not WMS.

**Comment by magerlin** [comment]
They work fine in Qgis2leaf - viewing generated source code reveals this:

`var basemap_0 = L.tileLayer('http://{s}.www.toolserver.org/tiles/bw-mapnik/{z}/{x}/{y}.png', { 
			attribution: additional_attrib + '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
		});	`

**Comment by tomchadwin** [comment]
OK, great. Try editing the plugin file basemaps.py, and you should be able to add that one in. Please do submit a pull request, and I can then incorporate your addition back into the main plugin.

**Comment by magerlin** [comment]
I would love to do this and I have tried to put it in completely parallel to the ordinary OSM map but I can not get it to show up when running the plugin. I am not a programmer :-(

**Comment by tomchadwin** [comment]
Added to master - please test.

**Comment by tomchadwin** [comment]
Released as 1.5.0 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
I can confirm it is working
