### ISSUE TITLE
Choosing "Show all attributes" in popup show only "Undefined" as attribute values

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#229]
I have problems using "Show all attributes" in popup. The popup table is filled with "Undefined" as values:

![screenshot 2016-03-22 15 29 06](https://cloud.githubusercontent.com/assets/1887531/13955428/de443f9a-f044-11e5-941e-b2316ed74a84.png)

Choosing only one attribute to popup works fine.

Choosing all attributes in Qgis2leaf works fine too.

Test shape file:
[test.zip](https://github.com/tomchadwin/qgis2web/files/184312/test.zip)

**Comment by tomchadwin** [comment]
Yes, we've been looking at that issue in #127 - not solved yet. Will close this - watch that other issue.

**Comment by tomchadwin** [comment]
No, wait, that was labels, but this is popups. Let me reopen.

**Comment by tomchadwin** [comment]
OK, @lucacasagrande and @walkermatt have committed some fixes on this. I think it's working now. Can you test?

**Comment by tomchadwin** [comment]
Released as 1.5.0 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
I can confirm it is working now :-)
