### ISSUE TITLE
Hard/impossible to get popup from all clustered point

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#230]
With several points at exactly same position the cluster function can "spread them out"

But it can be hard to get pick up from all of the points. Usually one point seems to be closer to the green dot (the left one) and perhaps sort of covered by the green dot and it is very hard/impossible to get it to popup:
![screenshot 2016-03-22 16 30 41](https://cloud.githubusercontent.com/assets/1887531/13957212/fa7f6bd8-f04b-11e5-97f7-c64c173e468f.png)

**Comment by tomchadwin** [comment]
Leaflet clustering is done by the Leaflet MarkerCluster plugin (https://github.com/Leaflet/Leaflet.markercluster). Does it have options to improve this situation? If not, yoyu'd have to raise it as an issue with them.

**Comment by tomchadwin** [comment]
Looks like there is an option (`spiderfyDistanceMultiplier`) which will do this:

https://github.com/Leaflet/Leaflet.markercluster#other-options

I don't think qgis2web can get involved in setting this away from its default value. However, you can edit your output code to make the change.

**Comment by magerlin** [comment]
Manually changing "spiderfyDistanceMultiplier:1" to "spiderfyDistanceMultiplier:2" in the created js\leaflet.markercluster.js file solved the problem

**Comment by tomchadwin** [comment]
Glad you found a solution.
