### ISSUE TITLE
OL3 pop-ups no longer working in 1.4.0

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#231]
Pop-ups appear to have stopped working in OL3 previews and exports.  Points and polygons from PostGIS and WFS tested so far.

**Comment by philipjohnbarlow** [comment]
Small update to this, pop-ups do appear to be working for flat files such as mapinfo tabs.

**Comment by philipjohnbarlow** [comment]
Possibly related?  I also get undefined field values from PostGIS layers in leaflet.
![capture](https://cloud.githubusercontent.com/assets/14541141/13984310/35a839e6-f0ed-11e5-9e30-631df9283bf4.PNG)

**Comment by tomchadwin** [comment]
That's #229, yes. Think I've introduced a bunch or problems by trying to fix the display of numeric values in #127. Will have to take a look.

**Comment by MapNavTom** [comment]
I got this error but the fix is simple, basically the the json file gives the fields numerical IDs rather than the original field names in the data. The code in the index.html file calls the fields by the name rather than the numerical ID.  I just edited the field names to be the numerical IDs in the html file and the popup text appeared. I guess you need to make the plugin use the numerical IDs when it generates the index.html file.

**Comment by tomchadwin** [comment]
Ah, OK. Thanks for investigating. Can you post a sample of your edited output JS? What I don't understand is what has changed to stop this working when it was OK before.

**Comment by MapNavTom** [comment]
Here is the Json file created in the data folder:

`var json_firstfour1={
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                                                                  
"features": [
{ "type": "Feature", "properties": { "0": "En-suite rooms", "1": "1 bed", "2": "22nd July to 29th Aug", "3": "From £350 per week" }, "geometry": { "type": "Point", "coordinates": [ -3.200056, 55.945388 ] } },
{ "type": "Feature", "properties": { "0": "Studio Apartments", "1": "1 bed", "2": "1st Aug to 29th Aug", "3": "From £600 \/ week (£1700\/mth)"  }, "geometry": { "type": "Point", "coordinates": [ -3.200721, 55.945832 ] } },
{ "type": "Feature", "properties": { "0": "Studio Apartments", "1": "1 bed", "2": "22nd July to 29th Aug", "3": "From £600 \/ week (?2000 \/ mth)" }, "geometry": { "type": "Point", "coordinates": [ -3.178784, 55.950508 ] } },
{ "type": "Feature", "properties": { "0": "Studio Apartments", "1": "1 bed", "2": "22nd July to 29th August", "3": "From £770 \/week (£2200 \/mth)" }, "geometry": { "type": "Point", "coordinates": [ -3.186544, 55.945331 ] } }
]
}`

The numbers 0-3 have replaced the field names. Below is the original section of code for the popup and my amended version:

Original

`        function pop_firstfour1(feature, layer) {
            var popupContent = '<table><tr><th scope="row">Type</th><td>' + (feature.properties['Type'] !== null ? Autolinker.link(String(feature.properties['Type'])) : '') + '</td></tr><tr><th scope="row">Bedrooms</th><td>' + (feature.properties['Bedrooms'] !== null ? Autolinker.link(String(feature.properties['Bedrooms'])) : '') + '</td></tr><tr><th scope="row">Dates</th><td>' + (feature.properties['Dates'] !== null ? Autolinker.link(String(feature.properties['Dates'])) : '') + '</td></tr><tr><th scope="row">Price</th><td>' + (feature.properties['Price'] !== null ? Autolinker.link(String(feature.properties['Price'])) : '') + '</td></tr></table>';
            layer.bindPopup(popupContent);
        }
`

Amended:

`        function pop_firstfour1(feature, layer) {
            var popupContent = '<table><tr><th scope="row">Type:</th><td>' + (feature.properties['0'] !== null ? Autolinker.link(String(feature.properties['0'])) : '') + '</td></tr><tr><th scope="row">Bedrooms:</th><td>' + (feature.properties['1'] !== null ? Autolinker.link(String(feature.properties['1'])) : '') + '</td></tr><tr><th scope="row">Dates:</th><td>' + (feature.properties['2'] !== null ? Autolinker.link(String(feature.properties['2'])) : '') + '</td></tr><tr><th scope="row">Price:</th><td>' + (feature.properties['3'] !== null ? Autolinker.link(String(feature.properties['3'])) : '') + '</td></tr></table>';
            layer.bindPopup(popupContent);
        }
`
As you can see I just changed the names to numbers except where the names are used for display.

The other Json file I was using had only one field in the popup and needed no alteration as it used a text name in both the Json and code for the popup.

Really do like the plugin, please keep up the good work! Lt me know if you need anything else.

**Comment by tomchadwin** [comment]
OK, that's interesting. Why has the JSON export dumped the field names? Anyone else see this? I'm unlikely to be able to check until Tuesday.

**Comment by tomchadwin** [comment]
OK, @lucacasagrande has fixed the issue of the fieldnames disappearing from the JSON. However, OL3 popups now seem not to appear at all if there is no basemap. @walkermatt, can you think of why this might have happened, and could it be related to the change you made to the layerswitcher code relating to maps without basemaps?

**Comment by Naturtecnica** [comment]
Hi @tomchadwin!!! 
Your plugin solved lots problems of mine. Great!!!
When are you going to fixe this issue and update the plugin?

**Comment by tomchadwin** [comment]
@Naturtecnica We'll fix it when we work out what is causing the problem. At the moment, I don't know, so I don't know when it will be fixed. Hopefully this week, though.

**Comment by Naturtecnica** [comment]
@tomchadwin Grate, Thanx!!!

**Comment by walkermatt** [comment]
@tomchadwin I'll try and take a look over the next few days. It could be that the pop-up code makes an assumption that there is always a base maps group. One of the changes in #226 was to only add a base maps group if one or more base maps are selected.

**Comment by tomchadwin** [comment]
Released as 1.5.0 and pushed to QGIS plugins repo.

**Comment by Naturtecnica** [comment]
Love it, thanx!
