### ISSUE TITLE
Allow a selection of attributes for popup display instead of [one attribute] or [all attributes]

### ISSUE THREAD

**Issue by jumpinjackie** [tomchadwin/qgis2web#232]
Currently the attribute display options for a layer is restricted to only one attribute, or all attributes. It would be nice if I could pick a selection of attributes to show in a popup

**Comment by philipjohnbarlow** [comment]
You can do this through the layer properties>fields. Just change the field widgets to hidden for those you don't want to appear in the pop-up. You then just choose "show all attributes" in the plugin.  

Tip: You can also add aliases in the fields menu and these will appear as the attribute headings in your pop up.

**Comment by jumpinjackie** [comment]
Ah, so that's how you control attribute display at the QGIS level! Good to know.

**Comment by tomchadwin** [comment]
Thanks for explaining, @philipjohnbarlow. This information was not in the README/Help tab, so I've just added it.
