### ISSUE TITLE
Problem with shapefile with Z and M values

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#233]
I was trying to use a polyline shapefile and I was having problems.  After some hair pulling and banging my computer monitor, it turned out that the shapefile had Z and M values.  It would be nice if q2w thru an error or message about the shapefile having these values.

**Comment by tomchadwin** [comment]
Or even better, if it handled the layers. Can you post some z/m layers? I don't know enough about them to create one.

**Comment by boesiii** [comment]
Attached is a shapefile with both Z and M values.

[polyline_z_and_m_values.zip](https://github.com/tomchadwin/qgis2web/files/192322/polyline_z_and_m_values.zip)

**Comment by tomchadwin** [comment]
Confirmed. Looks as though the approach currently used to identify the geometry type doesn't work with new geometry types. Looking for solutions, but not found them yet.

**Comment by tomchadwin** [comment]
Asked for help here:

http://osgeo-org.1560.x6.nabble.com/Python-drop-z-m-values-td5258674.html

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Released as 1.5.0 as pushed to QGIS plugins repo.
