### ISSUE TITLE
Multipart labelled even though not selected

### ISSUE THREAD

**Issue by polashbora** [tomchadwin/qgis2web#237]
The web page is showing all labels of a multi-part features even though this selection is disabled in QGIS Desktop. This leads to a messy map.
QGIS 2.14.1 Essen.
Also tried in Lyon with same problem.

See image.
![multipart-labelled](https://cloud.githubusercontent.com/assets/4884865/14199128/540a9e7e-f7ff-11e5-81d2-72f7ee5cde44.png)
Thanks & Rgds

**Comment by tomchadwin** [comment]
I don't fully understand (because my QGIS knowledge is not brilliant). Labels are enabled if they are enabled for the layer in QGIS. What are multi-part features?

**Comment by polashbora** [comment]
I am attaching 2 snapshots for clarity.
Suppose I have some islands in QGIS.
1. We can label all of them as one (default behavior)
![single-label](https://cloud.githubusercontent.com/assets/4884865/14205827/eeb291c6-f82b-11e5-98d9-894cea0194c8.PNG)

2. We can repeatedly label them i.e. same label repeated for each closed polygon. Kind of messy in certain cases.
![multpart-feature-label](https://cloud.githubusercontent.com/assets/4884865/14205830/f57cc10c-f82b-11e5-9c57-82cf12b56a67.PNG)

The problem is qgis2web is defaulting to the 2nd option and labeling each closed polygon of the same feature.

**Comment by tomchadwin** [comment]
I've asked for help here:

http://stackoverflow.com/questions/33484283/restrict-labeling-to-one-label-for-multipolygon-features

See my comment on the answer.

**Comment by tomchadwin** [comment]
Can you try the leaflet1.0.0 branch, and see if things have improved (Leaflet export, obviously)? I've migrated from a Leaflet labelling plugin to core tooltips in v1.0.0. No idea how they label multiparts.

**Comment by tomchadwin** [comment]
While this is not yet solved, output should have been improved because of work on #398. I hope it makes things a little better.
