### ISSUE TITLE
Vector data displayed in OL3, not in Leaflet

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#239]
I'm using a sample project (geomorpho) and data from:
https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/training_manual/exercise_data/processing/more_backends
all default options.

**Comment by tomchadwin** [comment]
Just tested, and works here:

https://www.dropbox.com/s/niql2zxpz1m078k/Screenshot%202016-04-14%2013.06.16.png?dl=0

**Comment by tomchadwin** [comment]
Closing with no feedback. Reopen as required, @pcav.

**Comment by pcav** [comment]
Not the same project. Just testet, I confirm the issue. See attached.
![qgis2web_geomorpho](https://cloud.githubusercontent.com/assets/691842/14785044/fe8cad04-0af8-11e6-9152-3118e22ce8d2.png)

**Comment by tomchadwin** [comment]
Let me reopen and check - I can see which layers you are using now.

**Comment by tomchadwin** [comment]
Works for me:

![screenshot 2016-04-25 15 57 17](https://cloud.githubusercontent.com/assets/7840213/14788131/7e485070-0afe-11e6-9469-759d8f414a87.png)

The raster is unstyled, but that's an existing issue #148. Are you sure it's not just that the vector layers are there, but stacked under the raster?

**Comment by pcav** [comment]
If I deactivate the dtm, the vectors show off correctly. However, in OL3 they are in the correct order. For some reason, in leaflet the dtm is brought over the others.
Let me chack if this is due to other plugins.

**Comment by tomchadwin** [comment]
No, I think it is likely to be the hacks involved in trying to approximate layer order in Leaflet. Should be better with Leaflet 1.0

**Comment by pcav** [comment]
Confirmed, with a clean --configpath, same issue.

**Comment by tomchadwin** [comment]
Closing, as existing Leaflet layer order issue.
