### ISSUE TITLE
Not obvious how to deselect background maps once selected

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#240]
Once you have clicked in the lower right pane and selected a background map it seems at first view like you can only change the selection to another background map. Trying random clicks I found that CTRL+Left Click deselects a selected map.

Since this is not very obvious I suggest a "No background map" as the top option in the lower right panel?

Or at least to mention the CTRL+Left Click in the Help tab?

**Comment by tomchadwin** [comment]
I thought it was mentioned in the help tab - must check. There used to be a "None" option, but that didn't make any UI sense with a multi-select widget.

**Comment by tomchadwin** [comment]
You're right - Help only mentions CTRL/CMD-click for multiple selections, not deselecting. Will update. Thanks for pointing it out.

**Comment by tomchadwin** [comment]
Help text updated in master

**Comment by tomchadwin** [comment]
Released as 1.5.1 and pushed to QGIS plugins repo.
