### ISSUE TITLE
OL3 measure output incorrect

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#242]
I have added the measure tool to an ol3 map and the output seams to be incorrect.  You can easily test this by adding a scale bar to your web map and measure the scale bar.  I was measuring a scale bar that said 10 km but the measurement was coming up 13 km.  The leaflet map looks to be giving correct measurements.

**Comment by boesiii** [comment]
The issue has to do with geodesic measurements.  We will need to add some code.  I am working on a fix.

**Comment by tomchadwin** [comment]
I'm pretty surprised that gives a 30% error, but I'm not a geographer. Thanks for looking into it.

**Comment by tomchadwin** [comment]
Just seen what I presume is the answer to this where the code came from:

- http://openlayers.org/en/v3.11.0/examples/measure.html

I guess when I used that code, I just left geodesic unimplemented, as that was the default in the example.

Non-geographer question: I presume some projections are geodesic, some planar? If so, is there a way to determine from the QGIS CRS which a given projection is?

**Comment by tomchadwin** [comment]
I think the answer to my non-geographer question is yes. Can you use `QgsCoordinateReferenceSystem.geographicFlag()` to drive whether measurement should be planar or geodetic?

**Comment by boesiii** [comment]
Yes to your question above.  The measurements in OL3 seam to be correct.

**Comment by tomchadwin** [comment]
OK. Need to fix this. Just to double-check: you're sure you're treat indicated that the measure tool was wrong, and not that the scale bar was wrong?

**Comment by boesiii** [comment]
Correction.  The measurement output in OL3 is still incorrect.  The bar scale is correct.

**Comment by Sortronic** [comment]
A length of 4 miles OL3 reads it as 3.1

**Comment by Sortronic** [comment]
Please, don't pass this issue. It makes no sense to have at all as it works now. Thank you.

**Comment by tomchadwin** [comment]
It looks as though the metric and imperial measure scripts are different. Can you confirm that both are wrong in this way?

**Comment by tomchadwin** [comment]
From my limited, non-geographer understanding, the imperial measure script was using geodetic measurement, while the metric measure script was using projected (planar) measurement. I've changed the metric script to geodetic. Can you let me know if that has fixed the problem?

**Comment by Sortronic** [comment]
Both wrong. In metric a length of 24.405 km measured with QGIS shows in OL3 28.35 km. I'll check right now if geodesic works

**Comment by tomchadwin** [comment]
> Both wrong

Sorry, was this before or after the commit above on this issue?

**Comment by Sortronic** [comment]
Previous comment was before. Unfortunately after using the new master(?) it doesn't make nay difference. A length of 94.093 mi it shows 87.8 mi in both new and old versions.

**Comment by Sortronic** [comment]
Well, it's more complicated then that.
QGIS 17.888 km - OL3 19.24 km.
QGIS 11.115 mi - OL3 11.94 mi.
So till around 20 mi OL3 has a longer length, but measuring bigger length, 80 miles for example, OL3 become shorter.
QGIS 90.093 OL3 87.8.
Forgot to take measures on km, sorry.
I don't get it.

**Comment by tomchadwin** [comment]
Are you confident iv the QGIS measurement results? Is QGIS giving geodesic or projected measurements?

**Comment by Sortronic** [comment]
Sorry I am away from my desk. No I am not confident about my measurements. As soon as I am back I will do more investigation. Thanks

**Comment by Sortronic** [comment]
It works well for me. I made more measurements, double checked with Google Earth, and mile distances are in par for what I am expecting to get. Thanks for your patience.

**Comment by tomchadwin** [comment]
Ah, great! Many thanks for all the work checking. Really appreciate it. Great to close off such an old bug.
