### ISSUE TITLE
Test WFS point layer broken by Matt

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#244]
See https://travis-ci.org/tomchadwin/qgis2web/builds/122509839

You villain, @mtravis. What have you done to http://maps.nationalparks.gov.uk/geoserver/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=dartmoor:dnpa-tpo-point&SRSNAME=EPSG:27700?

@mtravis has broken @travis-ci. Pffft.

**Comment by tomchadwin** [comment]
Adding a BBOX to the WFS URL disables feature caching.

**Comment by tomchadwin** [comment]
Released as 1.5.1 and pushed to QGIS plugins repo.

**Comment by mtravis** [comment]
Good to know. The layer is a view of a mixed geometry table so that may explain it.
