### ISSUE TITLE
Printing map from browser causes map to be streched

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#245]
The printed result from a web browser causes map to be stretched and skewed.  Is there anything that can be done to prevent it from happening?  To recreate simply export any map then use the browser print preview to see the output.

**Comment by tomchadwin** [comment]
I think that falls outside the scope of the plugin. qgis2web takes maps from a print-based application (QGIS) to make webmaps out of them. Really not sure how worth it is trying to improve the printed output of the webmaps, when users of the plugin by definition have the means to create print-friendly versions directly from QGIS (static images, PDFs, etc).

If a good solution can be devised, happy to look at it. For the moment, though, I don't think it's part of core functionality.

**Comment by boesiii** [comment]
I use qgis2web so that my end-users can easily access GIS information without having to install\learn\use a desktop application, so most of my users don't have QGIS.

**Comment by tomchadwin** [comment]
No, I mean that *you* do, so you can create a PDF/whatever, to link to alongside the Leaflet/OL3 map.

**Comment by boesiii** [comment]
The issue does not occur with Leaflet

**Comment by tomchadwin** [comment]
Interesting. Anything Googlable about the issue with OL3 more generally? You come across this,  @walkermatt?

**Comment by boesiii** [comment]
i think it is an issue with OL3 because the issue occurs with an OL3 example.
