### ISSUE TITLE
Layer Transparency Scale is reversed in exported Openlayers3 Maps

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#247]
When I in Qgis in "Style", "Layer Rendering", "Layer Transparency" sets a small transparency value like say 10% the exported Openlayers3 maps looks like having a 90% transparency. 

Setting individual symbol transparencies works as it should and Leaflet map works too.

**Comment by tomchadwin** [comment]
Confirmed. Nice spot! Will investigate.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by magerlin** [comment]
Works as expected now :-)

**Comment by tomchadwin** [comment]
Great - thanks for confirming.

**Comment by tomchadwin** [comment]
Released as 1.7.0 and pushed to QGIS plugins repo.
