### ISSUE TITLE
Using CDN for .js option doesn't load tiles properly

### ISSUE THREAD

**Issue by Zeitsperre** [tomchadwin/qgis2web#248]
I've noticed that the CDN option for leaflet scripts is broken. For me, choosing it and trying to preview/export maps makes the tiles appear out of order/misaligned and no data is shown. Not sure if this is a known bug or a configuration issue. Local option works fine since last update. Running QGIS 2.14.1 on Debian 8.
![screenshot from 2016-04-15 14 22 50](https://cloud.githubusercontent.com/assets/10819524/14571171/c3f14186-0315-11e6-9db1-83cbf34ff0f0.png)

**Comment by tomchadwin** [comment]
Confirmed. Wow, what a mess! Anyone have any ideas what's causing this?

**Comment by tomchadwin** [comment]
It's not finding the Leaflet CSS on the CDN. Must have changed the naming in some way. Looking into it now.

**Comment by tomchadwin** [comment]
Ah, no, some kind of code typo, leading to `http://http` in the address.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Released as 1.7.0 and pushed to QGIS plugins repo.
