### ISSUE TITLE
OL3 to observe per-layer "Label" setting

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#25]
Needs #23

**Comment by tomchadwin** [comment]
Labels are present in OL3, but not controllable.

**Comment by tomchadwin** [comment]
There is a difference in behaviour between Leaflet and OL3 exports here. OL3 simply always uses the labels from QGIS, if QGIS specifies labels. Leaflet uses them **only if** the qgis2web "Label" option is checked for a layer. I'm not sure we need this control in qgis2web. So: how do people feel if I remove the per-layer "label" checkbox from the plugin, and simply label layers whenever they are labelled in QGIS?

**Comment by batje** [comment]
That makes a lot of sense, imho.

**Comment by tomchadwin** [comment]
I agree. The basic principal of qgis2web has always been **not** to replicate any functionality already present in QGIS. I'll have a go at removing it. It will have the major benefit of simplifying the GUI as well.

**Comment by tomchadwin** [comment]
OK, "Label" checkbox removed from GUI in master. Label settings are now transparently taken from QGIS.
