### ISSUE TITLE
"Visible" toggle has no effect in Leaflet

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#250]
All layers are always visible in the generated Leaflet map on map load. 

Thought I could change it manually but it seems to be deep buried in some of the js files?

Works OK in OpenLayers

**Comment by tomchadwin** [comment]
Confirmed. Will look into it.

**Comment by tomchadwin** [comment]
It's the layer stacking order hack which causes this. Will see if I can work around it.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by magerlin** [comment]
Works OK now!

**Comment by tomchadwin** [comment]
Splendid. Thanks for testing and confirming.

**Comment by tomchadwin** [comment]
Released as 1.7.0 and pushed to QGIS plugins repo.
