### ISSUE TITLE
Toggle all layers off

### ISSUE THREAD

**Issue by LAdrain** [tomchadwin/qgis2web#252]
It would be very useful to have a toggle option to turn all layers visibility on or off from the web page.  

Only just started to use qgis2web, so apologies if this has been addressed elsewhere.

**Comment by tomchadwin** [comment]
No. it's not been requested before.

**Comment by magerlin** [comment]
I suggest it will also make it possible to completely turn off **base maps**. Sometimes the Qgis layers blend too well into the background so turning to background off can make things clearer.

**Comment by tomchadwin** [comment]
CTRL-click a basemap to deselect it.

**Comment by magerlin** [comment]
CTRL-click is when I create the web map - right?. 

My comment was to give the user of **the final web map** the possibility to turn of base maps.

**Comment by tomchadwin** [comment]
Ah, apologies - misunderstood. OK, but this will be harder than normal layers, since both Leaflet and OL3 expect basemaps to be selected with a radio button, meaning you can't deselect them all. Can someone come up with a good GUI element for this?

**Comment by magerlin** [comment]
Is a "No Base Map" radio button a possibility? 
A quick and dirty solution could be to make it point at a non existing map? Choosing any of the OpenMapSurfer base map gives (unintentionally) this functionality.

**Comment by tomchadwin** [comment]
We don't do quick and dirty here...

I'm not very keen on a "No basemap" radio button. However, if we could implement an opacity control for layers, including basemaps, that would probably solve the problem you describe. Do you agree?

**Comment by magerlin** [comment]
Yes, that could be a solution

**Comment by tomchadwin** [comment]
I've not come up with a solution for this I'm happy with, so I'm going to close this issue. Happy to discuss solutions further. Reopen if required.

**Comment by LAdrain** [comment]
Thanks Tom.
