### ISSUE TITLE
Fields with image edit widgets should display as images in popups

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#254]
Is this possible? I've had quite a lot of requests for pics in popups...

**Comment by philipjohnbarlow** [comment]
I just do it with html and it isn't much of a faff to be honest.  Say you have a layer with a column for your image path you just use the field calculator to update or add a new row and concatenate e.g.

CONCAT('<img src=","name of column with filepaths",'" width="400"><img>

Then you'd just run the plugin and there is your photo in your pop-up

**Comment by tomchadwin** [comment]
That's too hard for a big portion of the target audience of the plugin, in my opinion. And for all of us, automating it saves time.

**Comment by philipjohnbarlow** [comment]
Fair enough (any way to stop git hub rendering my post as html?)

**Comment by tomchadwin** [comment]
Enclose code with backticks (`), or treble-backticks for paragraphs. You can also specify the language of the code you are writing, and it will syntax highlight and so on:

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by GeoSpark** [comment]
I'm taking this on for the FOSS4GUK code sprint.

**Comment by tomchadwin** [comment]
OK, working in Leaflet if you select just that single field in the popup drop-down in the plugin dialogue. I'll try to look at getting it to work if all fields are selected for the popup. If I can't make sense of it, I'll report back.

Was about to fix the issue of the image overflowing the popup, but then that behaviour disappeared for me. Can people let me know if they see that behaviour again?

And huge thanks to @geospark for this great new feature!

**Comment by tomchadwin** [comment]
@GeoSpark I'm happy to look at getting this working when "Show all attributes" is selected for popups, but I'm having difficulty getting started:

https://github.com/tomchadwin/qgis2web/blob/master/leafletLayerScripts.py#L86

Do I take it that `eachPopup == 1` indicates that "Show all attributes" is selected?

**Comment by tomchadwin** [comment]
@GeoSpark No, it's OK. I've had a go at implementing this in master. Can you test? Image edit widget fields should now work in Leaflet with "Show all attributes" selected for the popup, not just for single fields.

**Comment by tomchadwin** [comment]
Akzo now implemented in OL3. Please test.

**Comment by tomchadwin** [comment]
Released as 1.10.0-FOSS4GUK2016 experimental and pushed to QGIS plugins repo.

**Comment by tomchadwin** [comment]
Images overflow popups in some browsers.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test, @philipjohnbarlow.

**Comment by philipjohnbarlow** [comment]
Tested and confirmed working in Edge, IE 11 and Firefox 47.0, no image overflow.

**Comment by tomchadwin** [comment]
Great - will release as soon as I can. Thanks.
