### ISSUE TITLE
Suggestion: Add Google Aerial as background map

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#261]
Perhaps not striclty Open Source ????

It can be done manually like this:

Download these leaflet plugins: [https://github.com/shramov/leaflet-plugins](https://github.com/shramov/leaflet-plugins).

Create a map with no background in Qgis2web.

Extract downloaded zip file and copy google.js from "leaflet-plugins-master\layer\tile" to the js folder created by Qgis2web.

Add this to the index.html file:

In `<head>` section:

```
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<script src="js/Google.js"></script>
<script src="http://maps.google.com/maps/api/js?v=3"></script>
```

Add this just before the last ` </script>` in index.html:
```
var ggl = new L.Google();
map.addLayer(ggl);
```

**Comment by tomchadwin** [comment]
I'm not sure - as you say, not open. Same goes for #260

**Comment by tomchadwin** [comment]
Plus we'd need a solution for OL3 export as well.

**Comment by tomchadwin** [comment]
I think I'll close for now - if people really need it, they can code it. Let's try to stay open.
