### ISSUE TITLE
SVG markers not supported for categorised based rendering

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#262]
Produces the following error:

Traceback (most recent call last):
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 125, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 304, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 159, in writeLeaflet
canvas)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 186, in writeVectorLayer
json, wfsLayers)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 448, in categorizedLayer
catLegend)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 483, in categorizedPoint
border_transp = float(symbolLayer.borderColor().alpha()) / 255
AttributeError: 'QgsSvgMarkerSymbolLayerV2' object has no attribute 'borderColor'

I've tried half a dozen symbols and combinations of symbols, can anyone replicate?

**Comment by philipjohnbarlow** [comment]
Sorry I meant categorised, I am aware that rule is not supported.

**Comment by tomchadwin** [comment]
You just saved me typing that reply. OK, will investigate - sounds as though you are probably right, though. I'm fairly sure that categorized and graduated assumes that it is a simple marker.

This one could be a swine to fix, actually. Might be OK in OL3 because Victor and Luca's code is properly modularized. Not so much the Leaflet stuff, though. Thanks a bunch, Phil...

**Comment by philipjohnbarlow** [comment]
I'm surprised someone hasn't noticed before, I didn't even think to try until just now.  I'm working on some maps for an HLF bid that have invasive non-native species categorised by species for which I am using SVG markers.  It doesn't have to be a web map but I ran the plugin just to see if it would export it.

**Comment by tomchadwin** [comment]
Workaround is of course to split the layer out into separate layers. Still worth investigating a fix.

**Comment by tomchadwin** [comment]
Python error occurs with Leaflet. OL3 produces no error, but also produces no output. Agreed?

**Comment by philipjohnbarlow** [comment]
Agreed.

**Comment by tomchadwin** [comment]
Crash trapped (issue was raised again as #328). Issue not solved, so not closing, but at least the crash is gone.

**Comment by tomchadwin** [comment]
Leaflet now implemented in master. Please test.
