### ISSUE TITLE
Add area measurement

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#264]
Should I work on adding an area measurement option?

**Comment by tomchadwin** [comment]
By all means - do check what functionality comes out of the box with the Leaflet measure plugin. The OL3 code came from the OL3 code examples page, and that might have an area option.

- https://github.com/makinacorpus/Leaflet.MeasureControl/commits/gh-pages (I think it's this one)
- http://openlayers.org/en/v3.11.0/examples/measure.html

**Comment by tomchadwin** [comment]
Oh, and if it's done, can it just be enabled automatically with linear measure, both at the same time? I don't want the qgis2web UI to overbalance with measurement options.

**Comment by tomchadwin** [comment]
Area measure now enabled with switch to leaflet-measure for #457. OL still to add.

**Comment by andreaordonselli** [comment]
For openlayers the solution is here #971

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/80defd3c5753ca2bee0ebb72a0e0c4e65a7c207d) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.0)
