### ISSUE TITLE
SVG markers in Leaflet not working when published on the net

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#265]
When I use SVG markers in a Leaflet map the markers are shown both in Plugin Preview and when I open the created web page from my hard drive.

But when uploaded to the web the markers are gone: http://byogtrafik.ramboll.dk/akv/test/#5/-7.863/56.426

The pages created by the plugin are here: 
[qgis2web_1462273668.79.zip](https://github.com/tomchadwin/qgis2web/files/246760/qgis2web_1462273668.79.zip)

**Comment by tomchadwin** [comment]
The requests for the following files are getting a 404 from the server:

```markers/Airport_Red.svg
markers/Port_red.svg```

Are they definitely up there? Permissions?

**Comment by magerlin** [comment]
Sorry - this seems to be a problem with my server. 
It has once been solved but apparently now reappears: svg files are not per default supported in Microsoft IIS

**Comment by tomchadwin** [comment]
Great - did you have to add the MIME type?

**Comment by magerlin** [comment]
Yes - last time it was fixed by our tech guy by adding MIME type image/svg+xml. 

He is unavailable right now, so I have not had the chance to get it done again but I hope it will solve the problem. I can see that with just a simple uploaded SVG file I also get the 404 error

**Comment by tomchadwin** [comment]
Did you intentionally reopen this issue?

**Comment by magerlin** [comment]
No it was a mistake. By the way I found out how to ad the mime type myself by just adding a web.config file in the root folder.

**Comment by tomchadwin** [comment]
Perfect - glad you got sorted.
