### ISSUE TITLE
Mismatch between Legend and map styles

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#269]
In the produced Leaflet maps the styling shown in the legend does (often?) not match the style shown on the map: 
- Polygon borders are in the legend are too wide 
- The radius on point markers (dots) is too big. Furthermore the dots have a border in the legend (as it had in QGis) but there is no border around the dots on the map.

![image](https://cloud.githubusercontent.com/assets/1887531/15111843/271586aa-15ea-11e6-873f-80c0e5ae16dd.png)

The legend styles matches the original QGIS map the best - better than the map it self. (see also issue #268).

**Comment by tomchadwin** [comment]
I think I may have fixed this in master. Can you test and report back?
