### ISSUE TITLE
Wrong attribute data in popup window (Leaflet & OpenLayers)

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#272]
In generated maps data values for attribute "tourism" are displayed also for the "name" attribute (in all points. "Show all" is chosen for popups):

![image](https://cloud.githubusercontent.com/assets/1887531/15144218/53232b34-16ae-11e6-8b55-1d204e18b878.png)

Data: 
[Tourism.zip](https://github.com/tomchadwin/qgis2web/files/256996/Tourism.zip)

**Comment by tomchadwin** [comment]
No CRS in that SHP? What are you using?

**Comment by magerlin** [comment]
Sorry - it is a user generated CRS. Here it is in WGS84: [Tourism_WGS84.zip](https://github.com/tomchadwin/qgis2web/files/257026/Tourism_WGS84.zip)


But strange thing is that when I open the original shapefile in a new blank project file the problem is gone. 

I have earlier experienced, that project files keep old dirt (even for layers no longer in the project). Maybe that is the case here? Earlier I had more attributes in the shape file which might confuse the plugin?

A qgs file **with** the problem using the data from my first comment is here: [Test.zip](https://github.com/tomchadwin/qgis2web/files/257036/Test.zip)

**Comment by magerlin** [comment]
After a little more testing: Reopening the shape file in the same project removes the problem. 
But the problem is back when I assign a Categorized styling to the layer (based on "Tourism" attribute)

**Comment by tomchadwin** [comment]
OK, so can you create the problem from scratch: no project, just open SHP, and apply categorized renderer?

If there are issues with stale values in projects, that might be a separate bug.

**Comment by magerlin** [comment]
Yes I can confirm to above. And there are no invalid or NULL values.

**Comment by tomchadwin** [comment]
Apologies - having no joy recreating this. Can you upload malfunctioning project and layer together, with a working CRS?

**Comment by magerlin** [comment]
Shure. Started out with new project. Same shape file (in WGS84) loaded twice. One of the layer instances is styled with categorization and shows the problems mentioned in the original post while the instance without categorization shows the right values.

Also a created leaflet map is included in this file:
[Tourism_WGS84.zip](https://github.com/tomchadwin/qgis2web/files/261106/Tourism_WGS84.zip)

**Comment by tomchadwin** [comment]
Thanks for your patience - confirmed. It's the underlying JSON that's wrong. NO idea why yet. Will look into it.

**Comment by tomchadwin** [comment]
Baffled by this - the JSON export happens before the renderer is even looked at, so I don't see how the resulting file can differ. Unless there's some old code in there which does alter the file once it's been exported. The 2.5d functionality alters the file, but that should not kick in in this instance. Very odd.

**Comment by tomchadwin** [comment]
Possible fix committed to master - please test, and let me know.

**Comment by magerlin** [comment]
It seems to work now :-)

**Comment by tomchadwin** [comment]
Great. I bet I can make it break, though. Instead of choosing all attributes for the popup, just choose the one your renderer categorizes on. I think that might fail. Then choose a different popup attribute (not the one on which your renderer is categorized). That will probably work. Let me know.

**Comment by magerlin** [comment]
As far as I can test all the mentioned cases work fine. 

One small issue even though: Choosing to pop-up the one I renderer categorizes on shows two identical rows in the pop-up: 
![image](https://cloud.githubusercontent.com/assets/1887531/15214506/baa388bc-184d-11e6-898b-10c18ea14fc7.png)

But this has been a (minor important) issue for a long time and has nothing to do with resent update.

**Comment by tomchadwin** [comment]
It is related, though I don't quite know why the problem led to the values being confused. Are you happy for me to close this issue as things stand now?

**Comment by magerlin** [comment]
Yes sure

**Comment by tomchadwin** [comment]
Great. Thanks.
