### ISSUE TITLE
Qgis2web crash windows 7

### ISSUE THREAD

**Issue by mayureshbhole** [tomchadwin/qgis2web#273]
version Qgis 2.14.2 essen 
When run qgis2web plugin in complex project then its crash entire system and reboot windows 7

**Comment by tomchadwin** [comment]
I'm afraid I need more information. Can you try steadily reducing the number of layers to see whether there is one specific layer which is causing the crash? If you find one, see if that layer then causes the crash when loaded on its own. Let us know what you find so we can help get to the bottom of the problem.

**Comment by mayureshbhole** [comment]
There are 67 layers projection utm wgs84 43n
All r display very fine in qgis
How i know which layer have problem

I tried almost 50 times but always cresh and reboot system



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by tomchadwin** [comment]
Remove half of the layers, and see if the problem remains, or disappears. If it remains, remove half of the remaining layers. If it disappears, remove the remaining layers, and load in the half you initially removed. Keep halving like that, and see if there is one (or a few) layers which have the issue.

Regardless, I think a 67-layer map is going to be too much for qgis2web to handle. even if it works, I'm not sure it would be a very usable webmap.

**Comment by mayureshbhole** [comment]
Ok will try and let u know
I have many projects in hand of govt. If u interested work with me will gr8 for me


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by tomchadwin** [comment]
Closing with no feedback
