### ISSUE TITLE
Address search on OL3 not working?

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#276]
Nothing seems to appear. Does anyone else confirm?

**Comment by boesiii** [comment]
It is working for me

**Comment by tomchadwin** [comment]
With current master?

**Comment by boesiii** [comment]
Oh.  Let me download master and try it.

**Comment by boesiii** [comment]
Yes it is working with current master.  I typed in a city and it came up with a list of places.  Clicking on a place it zooms the map to that position.

**Comment by tomchadwin** [comment]
OK, I'll close this for now. It's not working for me - no control appears, but no errors that I can see. Very strange.

**Comment by tomchadwin** [comment]
Thanks for checking.

**Comment by riadhamoudi** [comment]
Do you know how I make search on specific field ? where I can change the parameter.
