### ISSUE TITLE
Leaflet Layer are not in proper order.

### ISSUE THREAD

**Issue by sudhirsp** [tomchadwin/qgis2web#278]
Hi,
I am trying to export point, line, polygon, raster and base map. After exporting from OL3 layers are arranged as per qgis. But when same data is exported by leaflet basemap becomes 1st in legend and raster is coming after that. In legend layers are sequenced in Basemap, Raster, line/polyline, point and polygon.

Beacuse of this vector data is not visible as raster is overlayed on vector data.
I have uninstall the plugin and install a fresh version. But problem is same. Please extend your help.

Thanks & Regards
Sudhir Patil

**Comment by tomchadwin** [comment]
Leaflet 0.7 is problematic with layer stacking order, which is why this issue has been raised a few times before. Until Leaflet 1.0 is fully released (and all the Leaflet plugins which qgis2web uses are updated to be compatible), there's not much we can do.
