### ISSUE TITLE
Leaflet maps appears to only accept integer point labels

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#279]
As for now point layers can be labeled in Leaflet maps. But if label is not an integer in Qgis it is not shown on the Leaflet map. It is shown OK in OpenLayers3.

**Comment by tomchadwin** [comment]
Not for me. I've just tried it with a String field, and it works. What can the difference between your layer and mine be?

**Comment by magerlin** [comment]
Oh sorry - it is a real value like 5.2 (five point 2) that does not work.

**Comment by tomchadwin** [comment]
Got it - can't display decimal/real labels. Will look into it.

**Comment by tomchadwin** [comment]
Fix committed to master - please test

**Comment by magerlin** [comment]
Confirmed OK

**Comment by tomchadwin** [comment]
Thanks for confirming. Released as 1.9.2 and pushed to QGIS plugins repo.
