### ISSUE TITLE
Some raster colour models are rendered transparent

### ISSUE THREAD

**Issue by volcan01010** [tomchadwin/qgis2web#287]
The attached file is rendered fully transparent in the web maps.  Projection is epsg:27700.

![os_background_castle_biz](https://cloud.githubusercontent.com/assets/12040043/16121634/e7e9b946-33db-11e6-9a20-5c4bc14f8323.png)

It has a strange colour model:

```
tw-johns@qgishack:~/dev/foss4guk$ gdalinfo os_background_castle_biz.png
Driver: PNG/Portable Network Graphics
Files: os_background_castle_biz.png
       os_background_castle_biz.pngw
Size is 1565, 833
Coordinate System is `'
Origin = (277733.776355042005889,694985.743249999941327)
Pixel Size = (0.512432773109237,-0.512432773109237)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  277733.776,  694985.743) 
Lower Left  (  277733.776,  694558.887) 
Upper Right (  278535.734,  694985.743) 
Lower Right (  278535.734,  694558.887) 
Center      (  278134.755,  694772.315) 
Band 1 Block=1565x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=1565x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=1565x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=1565x1 Type=Byte, ColorInterp=Alpha
```

**Comment by volcan01010** [comment]
The .pngw should contain:

```
0.51243277310923696
0 
0 
-0.51243277310923696
277734.03257142857182771
694985.48703361337538809
```

**Comment by tomchadwin** [comment]
I think this could well be related to #148. @lucacasagrande, many colour models will not display in a browser - I don't know which ones precisely will. We therefore need to make sure we always convert rasters to a web friendly model.

**Comment by lucacasagrande** [comment]
Yes, in my code for #148  it is working fine.

**Comment by tomchadwin** [comment]
I'll close this for now, as we've not looked into it for a long time. @volcan01010, reopen if you think this is still an issue. I'm hoping that @lucacasagrande's work on #148 has sorted this.
