### ISSUE TITLE
Rewrite OL3 popup code

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#290]
Currently the attribute names and values come straight from the GeoJSON. This means they can't be preprocessed. Two features are therefore currently blocked by this, which work in Leaflet:

- use field aliases
- images in popups

There could already be other such blocked issues, and certainly could be again.

I don't have a solution for this, but I'm sure it will be possible. Suggestions welcome.

**Comment by GeoSpark** [comment]
I suspect the best approach would be to unify the code generation - OL3 and Leaflet are essentially the same. As we talked about at FOSS4GUK2016 moving to a Python templating library would be a start, [Jinja2](http://jinja.pocoo.org/) would be my recommendation. There will, I think, need to be JS templating too and so [handlebars](http://handlebarsjs.com/) seems to be the most popular engine. Once the code templates have been separated out, merging the two code generation systems should be a lot easier by passing in the same data to two different templates and doing the heavy lifting in Jinja2.

This is a big task and will touch almost every file, but it can be done in stages.

**Comment by tomchadwin** [comment]
Python templating I agree with. JS templating only of it does not add too much to the download to have additional libraries.

**Comment by tomchadwin** [comment]
OK, let's look at the field aliases first. How about we write out a JS object called fields_LAYERNAME:

```javascript
var fields_layerName {
    fieldName1: 'alias1',
    fieldName1: ''alias2
}
```
We then change the popup code from:

```javascript
popupField = '<th>' + currentFeatureKeys[i] + ':</th>'
```

to:

```javascript
popupField = '<th>' + fields_layerName[currentFeatureKeys[i]] + ':</th>'
```

Anyone else think I am on the right lines with this?

**Comment by tomchadwin** [comment]
No, I'm getting my Python and JS confused. Have to work on it a tad more...

**Comment by tomchadwin** [comment]
Reached another dead end. I don't know how to retrieve any layer name in JS which matches back to the layer name in QGIS, so I can therefore get to the right list of fields. Very confusing.

I start with Python retrieving the list of layers, fields in each layer, and aliases for each field. I can write them out in any JS structure we need, but how do I then retrieve the right entry in JS when a feature is clicked? The function I need to do it in is here:

https://github.com/tomchadwin/qgis2web/blob/master/resources/qgis2web.js#L75

However, that `layer` var is the OL3 JS layer object. Any way I can retrieve the layer "name" from that object? I can't see one. Can I assign an extra (ie non-OL3) property to the object?

**Comment by ThomasG77** [comment]
You can set any arbitrary property to `layer` with `layer.set('my_arbitrary_name_for_layer_name', 'my_layer_name')`
See [this example](http://openlayersbook.github.io/ch04-interacting-with-raster-data-source/example-06.html) for a concrete use case.

**Comment by tomchadwin** [comment]
Ah, thanks @ThomasG77! Hopefully that will do it.

**Comment by tomchadwin** [comment]
Yes, that's done it, @ThomasG77. I do:

```javascript
layer.set('fieldAliases', {'ID': 'id', 'fk_region': 'Region', 'ELEV': 'Elevation', 'NAME': 'Name', 'USE': 'Use'});
```

**Comment by tomchadwin** [comment]
Aliases and images both done without rewriting. Closing for now.

**Comment by chrismayer** [comment]
Hi, I just stumbled upon this. Just for a quick reference to comprehend what has been done, what are the commits belonging to this issue? So far I reconstructed that the following should be somehow related:

  - 123a9967b94e8ef6319a6982855e4484ac883774
  - 9b7eca73a70d1bcc2a468f05d7a62207ea744a37
  - ab9a4be97ca6b1dd368c3443246addb21197a4b4
  - 4fee078c01fc0c0b1ddc196d48d497f27e227934
  - 0d584badae86d8ca3956de317a7a1a9e7241cd54
  - a9275afa28c509c39cf85e253571b2e39a3afda0
  - 97d3875d5248b5e965cff05748cde8bff0403518

@tomchadwin can you confirm this? TIA!

**Comment by tomchadwin** [comment]
@chrismayer Now you're asking. Not sure without checking, as I ended up not having to rewrite the code. Instead, I was able to use the existing code for field aliases and images in popups.

I'm hoping to release a new version with all the recent changes, including these. Is that enough for you, or is there another reason you want to know which commits were against this issue?

**Comment by chrismayer** [comment]
No, there is no other reason. As said I was just curious how you finally solved this in the code and was wondering that there was no reference to a PR or commits or something. With the above listed commits I was able to comprehend, so everything is fine for me. Thanks you for your reply and your great work so far!

**Comment by tomchadwin** [comment]
No problem, and thanks for the kind words. As I say, I don't know if the list is comprehensive. Try downloading current master, and exporting OL3 maps with field aliases set, and with an image edit widget used. You'll see the two changes then.
