### ISSUE TITLE
Rewrite code to use a templating engine

### ISSUE THREAD

**Issue by GeoSpark** [tomchadwin/qgis2web#291]
There are a great deal of JS strings in the Python code that could be simplified by using something like Jinja2 to do the heavy lifting and separate out the JS and HTML from the Python.

**Comment by tomchadwin** [comment]
Python templating I agree with. JS templating only if it does not add too much to the download to have additional libraries.

**Comment by tomchadwin** [comment]
Closing for now, as I've never been able to investigate properly. Separation of strings from code would still be a great enhancement, though, so I'll reopen if anyone can tackle this.
