### ISSUE TITLE
How to use SVG markers from Qgis?

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#293]
Is there someway I can get Q2W to use the symbols from Qgis?
![capture](https://cloud.githubusercontent.com/assets/2079638/16238662/45f32640-37af-11e6-9ae2-b1abbe642562.PNG)

**Comment by boesiii** [comment]
If I use leaflet the legend shows correctly but the symbols are not consistent with Qgis.
![capture2](https://cloud.githubusercontent.com/assets/2079638/16239082/5a026cde-37b1-11e6-9668-3e802c4e4f12.PNG)

**Comment by boesiii** [comment]
![capture3](https://cloud.githubusercontent.com/assets/2079638/16239109/80a38058-37b1-11e6-9da8-e677f6967b0a.PNG)

**Comment by tomchadwin** [comment]
I find that the QGIS SVGs don't tend to work, but external ones do. I think it might be to do with the presence of SVG variables within the QGIS ones. I don't have a solution for this yet.

**Comment by tomchadwin** [comment]
By the way, have you checked them in export, not just in preview?

**Comment by boesiii** [comment]
Yes

**Comment by tomchadwin** [comment]
By the way, @boesiii, this will work only with `SVG marker` symbol layers, not `Simple marker` symbol layers. And are you having problems with SVGs in both OL3 and Leaflet?

**Comment by boesiii** [comment]
I am using leaflet. When you use Leaflet and you have a layer list, it creates the PNG symbol for the legend, so all you have to do is point the leaflet style to the PNG file.  Late yesterday I finished a working version (by editing the HTML and JS) but I haven't coded it to Q2W.

```
var hydrantIcon = L.icon({
            iconUrl: 'legend/Hydrant3.png',
            iconAnchor: [8, 8],            
        }); 
```

```
function doPointToLayerHydrant3(feature, latlng) {
            return L.marker(latlng, {icon: hydrantIcon}, doStyleHydrant3()).bindLabel((feature.properties.HYD_ID !== null?String(feature.properties.HYD_ID):''), {noHide: true, offset: [-0, -16]})
        }
```

**Comment by tomchadwin** [comment]
Odd. The SVG issues I've had are with OL3 (think I've just fixed them - commit coming). Leaflet works, **but not in the preview window**. It works in the export, as far as I can see:

https://www.dropbox.com/s/4nmqe8no91z4erv/Screenshot%202016-06-23%2015.54.20.png?dl=0

**Comment by boesiii** [comment]
Oh wait.  I am using simple markers.  Sorry.  

So the issue is Q2W does not export simple markers correctly.

**Comment by boesiii** [comment]
You are right SVG symbols work correctly in leaflet.

**Comment by tomchadwin** [comment]
Great. Yes, the way it detects SVGs is by detecting SVG marker symbol layers. I'll look into how simple marker symbol layers work, and see if it's possible with those - no idea if the simple markers are SVGs themselves.

**Comment by tomchadwin** [comment]
Yeah, it's not going to be easy to recreate the non-circle simple markers. The QGIS API just gives you a shape string (eg "circle", "square", etc), rather than an SVG. Similarly, both OL3 and Leaflet have built-in circle markers, but not other shapes.

With your permission, therefore, I might close down this issue - it's forced me to get the OL3 SVG code working, which is A Good Thing.

**Comment by boesiii** [comment]
Instead of working with simple shapes and SVG just export the symbol to PNG and use that for the marker in OL3.  Leaflet export has a function that exports the symbol to PNG so all that is needed is connect the PNG symbol to OL3 and Leaflet.

**Comment by tomchadwin** [comment]
I'm slightly reluctant to do that because it means rasterizing what is vector symbology in QGIS. I have concerns at how it will look on high-dpi displays, and when users zoom their browsers.

The better approach would be to save out SVGs of all of the shapes, somehow, and then use the SVG methods already used.

**Comment by tomchadwin** [comment]
Released as 1.10.0-FOSS4GUK2016 experimental and pushed to QGIS plugins repo.

**Comment by boesiii** [comment]
@tomchadwin 
Was this ever brought in to master, because i am still seeing incorrect symbols for my points?

**Comment by tomchadwin** [comment]
Not SVG simple marker layers, no. SVG layers should work, though.

**Comment by mpbotti** [comment]
Tom, I´m using your plugin with leaflets + SVG icons. What I've noticed is that you can't mix SVG external icons with SVG simple markers. Both works OK, but independently...

You have to choose to use one or the other, but not both at the same time (icons I mean... or layer, although I didn´t checked this out yet...)

Regards,
M.

**Comment by tomchadwin** [comment]
@mpbotti That sounds odd. I don't quite understand. Do you mean one simple layer and one SVG layer?

**Comment by mpbotti** [comment]
Nope, same layer with different icons, some external SVG's (like myicon.svg) and some SVG's simple markers (like circle, triangle or square). For some reason I don't understand, leaflets can´t manage both Icon representations at the same time... please see next screen captures...

In captura0.jpg the red dot is a simple marker while the other three are external SVG's, while in captura1.jpg all icons are external SVG's. 
![captura0](https://user-images.githubusercontent.com/29799871/30292351-2f98cb30-970c-11e7-8b34-ad06f4f63996.JPG)
![captura1](https://user-images.githubusercontent.com/29799871/30292360-36ac219c-970c-11e7-91c1-c9ecc0704b1b.JPG)

The misunderstanding arise when you doesn's have all the external SVG's you need for your map and decide to make a draft map that will finish later (when you have all your SVG's, like I did!!! jajaja...).

Regards,
M.

**Comment by tomchadwin** [comment]
I don't think this is possible. The way the simple shapes are implemented in Leaflet requires a dedicated layer type, while SVG markers require a different layer type. That means it's not possible to have both in a single layer. Sorry.
