### ISSUE TITLE
Cant find layer until after browser refresh

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#295]
If I change the export folder to something on the network then the first time it opens in the browser after export, it is not able to find the JSON layers but if I refresh the page then it works fine.

**Comment by boesiii** [comment]
It looks like it might be more of a timing issue

**Comment by tomchadwin** [comment]
Really? Race condition of some kind?

**Comment by tomchadwin** [comment]
Does the problem disappear with much smaller datasets?

**Comment by boesiii** [comment]
Yes the problem disappears with a smaller dataset.  

Dataset = 1246 polylines = Problem

Dateset = 257 polylines = No Problem

**Comment by tomchadwin** [comment]
Obvious question: have you just waited?

**Comment by boesiii** [comment]
If I wait a few seconds and hit F5 to refresh the browser then everything is fine.

**Comment by tomchadwin** [comment]
If you wait without F5, does it eventually appear?

**Comment by tomchadwin** [comment]
Closing without feedback - reopen if required.

**Comment by boesiii** [comment]
Sorry.

No it does not appear.

**Comment by tomchadwin** [comment]
OK. Still got no explanation, but reopening.

**Comment by tomchadwin** [comment]
Can you try your F12 browser dev tools - network tab? See what happens with the request for that layer.

**Comment by boesiii** [comment]
After I export, a web page will display but with an error message "json_layer2 is not defined index.html".  If I refresh the page the maps displays fine.  
For my windows network I am having a DNS issue which might be causing a lag.

**Comment by tomchadwin** [comment]
Is this issue still occurring?

**Comment by tomchadwin** [comment]
OK, I'll close for now. Reopen if it reoccurs.

**Comment by boesiii** [comment]
Before the major code re-write by Nyall, yes but after no, so I would so yes keep this closed.
