### ISSUE TITLE
Data export settings not observed in Leaflet

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#3]

**Comment by mixedbredie** [comment]
Is this to do with exporting the QGIS project as a Leaflet map?  When I export as Leaflet it writes to C:\OSGeo4W\bin\index.html\export_2015_04_23_02_13_13 and not the folder I specified in the export dialogue.

**Comment by tomchadwin** [comment]
No, that's a different issue I need to open - that each export routine has its own export path. This issue relates to the settings in the UI under the section entitled "Data export" - Delete unused fields, minify, etc

**Comment by tomchadwin** [comment]
Precision now used, but blocked by #14 and #15

**Comment by tomchadwin** [comment]
Splitting remaining issues in #18 and #19.
