### ISSUE TITLE
OL3 basemap attribution

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#30]
Basemap attribution seems not to be present in OL3 export

**Comment by lucacasagrande** [comment]
Just fixed the code to show the attribution text. For some Layers we need to update the ol3 writer to use baselayers.py to populate it.

**Comment by lucacasagrande** [comment]
Hi Tom, can we close this issue?

**Comment by tomchadwin** [comment]
Ah yes, of course. Added to master by @lucacasagrande. Thanks, Luca!

**Comment by tomchadwin** [comment]
Released as 1.0.0-beta2 and published in QGIS plugins repo. Thanks again, @lucacasagrande.
