### ISSUE TITLE
qgis2web hangs QGIS in case of very large layers

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#300]
The plugin trying to convert the full layer, instead of just the extent. This is OK for small or moderate layers, but for very large layers the only practical solution is to kill QGIS. The user is not warned about this. I suggest to add the option (enabled by default) to only use visible items in the canvas.

**Comment by pcav** [comment]
This is also true for WFS layers.

**Comment by boesiii** [comment]
I believe it hangs because of the preview.  I wonder if there is some way to disable preview for certain layers over a certain limit of features.

**Comment by tomchadwin** [comment]
I'll dig out how to disable preview on load - just comment or one line at the beginning of maindialog.py.

The best way to handle this would be to stop the preview blocking the interface. I don't know how to do that. Is it multithreading?

**Comment by tomchadwin** [comment]
To disable initial preview when the plugin loads, comments out https://github.com/tomchadwin/qgis2web/blob/master/maindialog.py#L65:

```
        # self.previewMap()
```

**Comment by tomchadwin** [comment]
Two new features should now help with this issue:

1. There is a new `Settings` tab, which has the option `Preview on startup` (checked by default). Try unchecking if the plugin hangs when you first start it up.

2. I've changed the behaviour of `Scale/Zoom` > `Restrict to extent`. If you check it, and your `Extent` is set to 'Canvas extent', only the features currently displayed on the QGIS canvas will be exported.

Please let me know how these work for you. I'll close this issue for now - reopen if required.

**Comment by pcav** [comment]
I'm testing, but I'm still unable to get a map, cursor running forever.
