### ISSUE TITLE
Error When Exporting to Leaflet with Custom Labels

### ISSUE THREAD

**Issue by JonnoFTW** [tomchadwin/qgis2web#302]
In the display for my layer, I have set a user defined function for my label. When I export I get the following error:

```
KeyError: "PPName +'\\n'+to_string(bybooth_pct)+'%'" 
Traceback (most recent call last):
  File "C:/Users/Jonathan/.qgis2/python/plugins\qgis2web\maindialog.py", line 150, in saveMap
    MainDialog.saveLeaf(self)
  File "C:/Users/Jonathan/.qgis2/python/plugins\qgis2web\maindialog.py", line 329, in saveLeaf
    cluster, json, params, popup)
  File "C:/Users/Jonathan/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 95, in writeLeaflet
    layerFileName, safeLayerName, minify, canvas)
  File "C:/Users/Jonathan/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 15, in exportJSONLayer
    cleanedLayer = writeTmpLayer(i, eachPopup)
  File "C:/Users/Jonathan/.qgis2/python/plugins\qgis2web\utils.py", line 80, in writeTmpLayer
    fieldType = layer.pendingFields().field(field).type()
KeyError: "PPName +'\\n'+to_string(bybooth_pct)+'%'"
```

That key is actually the function that defines the point label.

**Comment by tomchadwin** [comment]
Yeah, I'm afraid expressions in labels are not supported:

https://github.com/tomchadwin/qgis2web/issues/51

I need to trap the error, though, and just export without labels.

**Comment by tomchadwin** [comment]
Or perhaps the best thing to do is to create a new field `qgis2web_label`, and populate it with the evaluated expression for each feature. I've been considering the same approach for popups for some time, but have never got round to implementing it.

**Comment by JonnoFTW** [comment]
Is there no way to evaluate the user defined label through python?

**Comment by tomchadwin** [comment]
That's what my suggestion is. However, since Python is not available in the browser, our only option is to preprocess each feature's label. Hope that makes sense.

**Comment by tomchadwin** [comment]
Expressions in labels are now supported in master, so please test to see whether concatenation is working for you. Only basic expressions are supported at the moment, so report failures, and we'll see what can be developed. In this specific case, I think `to_string()` is *not* yet supported, so this example will fail, but it would still be good for people to test expressions in labels if they can.

**Comment by tomchadwin** [comment]
Closing for now, although expression functions need to be developed.
