### ISSUE TITLE
Clicking convert to web hangs qgis

### ISSUE THREAD

**Issue by Caesar305** [tomchadwin/qgis2web#303]
Hello, I have a qgis map with about 10 layers based on spatiallite. As soon I click the button to convert to web, it freezes the entire application. I can see in my task manager qgis using about 15% cpu. I left it running for about 30 minutes to see if it would eventually finish to no avail. I'm on Windows 10, running Qgis 2.14 64 bit.

I would attach some logs but I'm not sure where to look for them, if there are even any.

I have tried hiding all the layers except for one small one with the same results.

**Comment by Caesar305** [comment]
I tried just importing the shapefile rather than using spatiallite db with same results. Seems like these layers are so large (shapefile is about 200MB) that causes the plugin to hang.  Maybe if I leave it running long enough it will open the dialog box.

**Comment by Caesar305** [comment]
Actually, it happens even with a smaller layer. Here is a shapefile with the issue in case you want to try and replicate.

https://drive.google.com/file/d/0B4sfSKoQ2q8UaU9zcmFqaHZjZEU/view?usp=sharing

**Comment by boesiii** [comment]
I tried with your dataset above and Q2W didn't even come alive.  Qgis sat waiting for a few minutes and I eventually killed the application.  I then grabbed 5048 features from the original dataset and it worked so it looks like there is a "limitation" in Q2W.

Even if Q2W was able to export your project, I doubt the resulting webapp would be very usable because of the number vector features.

**Comment by Caesar305** [comment]
Thanks for taking the time to look into it. Do you know of any other methods to export this to a web map? I tried looking into using qgis server but I could not manage to get it to work properly. I would prefer a simple solution like this plugin. I have everything inside a spatiallite database.

**Comment by boesiii** [comment]
I don't think q2w will suite your needs because your layers have too many features.  You will more likely need a web server which can server your data in a WMS type format.  There are other map servers out there you can try, mapserver.org or geoserver.org

**Comment by Caesar305** [comment]
Thanks

**Comment by boesiii** [comment]
This might help if you can get it too work with your data.

https://github.com/mapbox/geojson-vt
