### ISSUE TITLE
Exporting custom raster layers causes error in QGIS

### ISSUE THREAD

**Issue by sudheesh001** [tomchadwin/qgis2web#304]
qgis2web produced an error:
```
Traceback (most recent call last):
File "C:/Users/susingan/.qgis2/python/plugins\qgis2web\maindialog.py", line 134, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/susingan/.qgis2/python/plugins\qgis2web\maindialog.py", line 307, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/susingan/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 100, in writeLeaflet
exportRasterLayer(i, safeLayerName, dataPath)
File "C:/Users/susingan/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 114, in exportRasterLayer
extentRep = xform.transform(i.extent())
QgsCsException: forward transform of
(0.000000, -50.265482)
PROJ.4: +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 +to +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs
Error: latitude or longitude exceeded limits
```

**Comment by tomchadwin** [comment]
Can you define "custom raster"? I've not seen this issue before. Any ideas, @lucacasagrande?

**Comment by sudheesh001** [comment]
I think my mistake was that I was exporting a base map layer CairoPNG image along with the `Features` traced on a new layer, but the problem is that none of the attributes of the features are being exported.

**Comment by tomchadwin** [comment]
What is your project projection and the projection of your layers?

**Comment by sudheesh001** [comment]
I do not understand what you mean, where do I find that information ? I am new to the tool, so what i've done is, imported a cairoPNG image and created a new layer, made a few feature objects on the image by using the `Add Feature` after toggling edit. I then added attributes to the feature objects. Then I am trying to save and export.

**Comment by tomchadwin** [comment]
I'm afraid I'll have to ask you to find some QGIS instructions. You need to make sure that your project and layers have appropriate coordinate reference systems (CRS). This dictates whether the coordinates of your features are measured in, for example, meters, or degrees of latitude/longitude. Once that is set up correctly, the plugin should work. The error above has occurred because you have a conflict between meters and lat/long.
