### ISSUE TITLE
Leaflet error

### ISSUE THREAD

**Issue by fitoprincipe** [tomchadwin/qgis2web#308]
Hello, I have seen a similar issue posted 5 days ago. It was closed, but I have a similar one. I am just trying to create a simple webmap with qgis2web. I have just one layer (EPSG22181). Choosing OL3 works fine, but when I choose Leaflet it says:

> Error
> 
> qgis2web produced an error:
> 
> Traceback (most recent call last):
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/maindialog.py", line 134, in previewMap
> MainDialog.previewLeaflet(self)
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/maindialog.py", line 308, in previewLeaflet
> visible, cluster, json, params, popup)
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 156, in writeLeaflet
> canvas)
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 274, in writeVectorLayer
> json, usedFields, legends, count, popFuncs)
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 441, in singleLayer
> usedFields, wfsLayers, count)
> File "/home/fitoprincipe/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 554, in singlePolygon
> colorName, borderStyle, capString,
> UnboundLocalError: local variable 'capString' referenced before assignment

Any ideas?

**Comment by tomchadwin** [comment]
Hmm, no, not seen that before. Are you using the most up-to-date release? If so, are you able to upload your layer, project, and style files so I can take a look - it's a definite bug.

**Comment by fitoprincipe** [comment]
I thought of that and updated qgis2web before posting.. 





[error_shape.zip](https://github.com/tomchadwin/qgis2web/files/359429/error_shape.zip)

**Comment by tomchadwin** [comment]
KO, that layer works for me, so I need you to export your layer style as QML and upload that as well - `Layer Properties > Style > Style &#9660; > Save Style > QGIS Layer Style File`. That should allow me to recreate the bug.

**Comment by fitoprincipe** [comment]
Just in case (I don't think it matters) I am using ubuntu 14.04 and QGIS 2.14.3..
[style_error.zip](https://github.com/tomchadwin/qgis2web/files/359473/style_error.zip)

**Comment by tomchadwin** [comment]
OK, I've got the error now - thanks! Now to try to figure out what is causing it...

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by fitoprincipe** [comment]
It works perfect! I could have used another style (similar), but I'm happy the issue helped and pushed a change for optimization. Thanks a lot!

**Comment by tomchadwin** [comment]
You're welcome - thanks for testing and confirming! I'll be doing a release in the next couple of days, which will include this fix.
