### ISSUE TITLE
Small side effect of photo overflow fix

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#310]
Also causes pop-up to wrap to text.

![capture](https://cloud.githubusercontent.com/assets/14541141/16842712/56d172ee-49d6-11e6-9338-399f5dbc4920.JPG)

**Comment by philipjohnbarlow** [comment]
Attempting to adjust .leaflet-popup-content with height and width parameters seems to alter the anchor point of the pop-up.  

![image](https://cloud.githubusercontent.com/assets/14541141/16867492/0b959ac8-4a6a-11e6-8f4b-76efa9dd7e5b.png)

If you attempt to correct the position with "position: relative/absolute" you end up with this:

![image](https://cloud.githubusercontent.com/assets/14541141/16867567/6ebf7e7a-4a6a-11e6-804c-a153d61a9b3b.png)

**Comment by tomchadwin** [comment]
Do you mean it stretches the popup to full screen, pushed there by text? Try removing `height` from your fix. If that fails, replace `width` with `max-width`. Can you report back?

**Comment by philipjohnbarlow** [comment]
Hi Tom,

Yes, just the width.  Setting width or specifying a max-width fixes that problem but still results in the problem in the first screen shot above, you pop-up anchors at the top of the screen rather than to the point.

**Comment by tomchadwin** [comment]
OK. Ditch the CSS approach. I need to look at the Leaflet API to see how to specify dimensions in the JS. Don't know if `max-` is supported.

**Comment by philipjohnbarlow** [comment]
I wonder if what I have inside my pop-ups could be causing them to be created at a distance from their associated points?  I had a quick go with some more simple content at home and wasn't able to recreate the issue.  I'm on leave now for a week so I can't get my hands on the data to have another play around unfortunately.  In my data set I am using some webkit as well as html for the pop-up content, you can probably see from the screen shot that I've created a scrollable gallery within some of them?

When I am back in the office next week I'll have another go and see if I can get to the bottom of the issue.

**Comment by tomchadwin** [comment]
Yeah, I don't want to draw conclusions based on complex data that is less likely to be used very often. I'll leave it as is for the mo. Thanks for testing.

**Comment by tomchadwin** [comment]
Yeah, scratch the CSS, and tweak the option in the `bindPopup` statement:

http://leafletjs.com/reference.html#popup-options

Some `min-` and `max-` options are available.

**Comment by tomchadwin** [comment]
I'm going to close this one on the assumption that all bets are off if custom HTML is used. Reopen if necessary.
