### ISSUE TITLE
Inquiry of basemap of the satellite image

### ISSUE THREAD

**Issue by mkmdivy** [tomchadwin/qgis2web#315]
Hi, I am using qgis2web very usefully, thank you very much. I have one question. Will it be possible to have a satellite map as a basemap for the further version? Is it difficult to have it because of copyright? I think it can be very useful to have satellite basemap.

Thanks

**Comment by tomchadwin** [comment]
There was a satellite/aerial basemap from MapQuest, but they recently withdrew it. If you can find a free tile server with imagery you would like, you can add it yourself by editing basemaps.py.
