### ISSUE TITLE
turn Leaflet (and OL?) scrollWheelZoom off by default

### ISSUE THREAD

**Issue by jnicho02** [tomchadwin/qgis2web#317]
One pain with embedded webmaps is that when scrolling down the screen the map zoom catches your scroll action. I've started turning it off by default.

map.scrollWheelZoom.disable();   in Leaflet, probably similar in OpenLayers

e.g. Steven Feldman's http://knowwhereconsulting.co.uk/blog/child-poverty-in-london/

**Comment by tomchadwin** [comment]
I don't think I want to change the default behaviour of the libraries, to be honest. If people start to scream about it, we can add an option, I guess.
