### ISSUE TITLE
Leaflet labels don't like attributes starting with numbers

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#319]
I have a shapefile which has a attribute that starts with a number "4test" and I was using it as a label in Qgis.  When I tried to export it to Leaflet using q2w the resulting webpage gave me an error "Uncaught Error: Invalid or unexpected token index.html line 86".  When using OL3 I have no problems.

Line 86
`return L.circleMarker(latlng, doStyleairportstest20()).bindLabel((feature.properties.4test !== null?String('<div style="color: #000000; font-size: 8pt; font-family: \'MS Shell Dlg 2\', sans-serif;">' + feature.properties.4test) + '</div>':''), {noHide: true, offset: [-0, -16]})`

After I revised the attribute to include a letter before the number I was able to export to Leaflet with no problems.

To reproduce the error, add the data below and label using field '4test' then try and export to Leaflet.

[airports_test2.zip](https://github.com/tomchadwin/qgis2web/files/418669/airports_test2.zip)

**Comment by tomchadwin** [comment]
Good catch. I need to move from dot notation to brackets. Let me try to sort a fix.

**Comment by tomchadwin** [comment]
Possible fix committed to master - please test and let me know.

**Comment by tomchadwin** [comment]
Tested locally, and works for me, so closing - let me know of any problems.

**Comment by boesiii** [comment]
It worked!  Thanks.

**Comment by tomchadwin** [comment]
Released as 1.14.0 and pushed to QGIS plugins repo.
