### ISSUE TITLE
Remove popup fields if they are hidden in Qgis

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#321]
If a field is hidden in Qgis then the popup label option should also be hidden.

**Comment by tomchadwin** [comment]
Yes.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by boesiii** [comment]
Works!  Thanks!

**Comment by tomchadwin** [comment]
Released as 1.14.0 and pushed to QGIS plugins repo.
