### ISSUE TITLE
Storing selected popup fields in project file

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#323]
The selection of popup fields (no label/inline label/header label) is not stored in project file.

So every time I open qgis2web I must reselect it - quite tedious with 4 layers with each 15 fields...

**Comment by tomchadwin** [comment]
Correct - the old popups settings were stored, but since I redid it all, that functionality is lost. It needs to be recreated. This was mentioned somewhere else by another user, but I can't find that comment, so let this issue stand.

**Comment by tomchadwin** [comment]
Update: this is harder than I thought. Before, there was just a single popup drop-down per layer, but now there is one per field, so it's a fundamental change. QGIS has layer vrs, but not field vars (I presume). Wrangling an unknown number of drop-downs per layer into layer variables is proving confusing. No prototype to test yet.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Please can you let me know whether this works for you?

**Comment by boesiii** [comment]
The layers are saving the popup fields but my settings (layer list, measure, etc) are not being stored.  Will Q2W remember my settings if I close Qgis and reopen a project?

**Comment by tomchadwin** [comment]
@boesiii Looking into it now.

**Comment by boesiii** [comment]
It is also not saving the which library is used, OL3 or LF.

**Comment by tomchadwin** [comment]
Can't remembered if that was ever implemented - not too worried, as it's simple for people to switch. The other settings are a concern, though. As far as I can see, they are being saved in the project file. I guess that means they are failing to load. Still investigating.

**Comment by boesiii** [comment]
I can see the settings in the qgis file but yes they are not being loaded.

**Comment by tomchadwin** [comment]
Will open a new issue for this.

**Comment by tomchadwin** [comment]
New issue opened #327

**Comment by tomchadwin** [comment]
Released as 1.14.0 and pushed to QGIS plugins repo.
