### ISSUE TITLE
Question about CSS

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#324]
I cannot figure out where in the CSS for leaflet map these attributes are defined:
* Font size and colour for map labels (used to be labels.css but that is apparently changed)
* Width of popup  - they used to be wider, I think they are to narrow now, especially if you add some meaningful aliases:

![screenshot 2016-08-19 13 21 44](https://cloud.githubusercontent.com/assets/1887531/17808374/3a2320e2-6610-11e6-815a-c7c177a5c92b.png)

**Comment by tomchadwin** [comment]
For labels, it is css/label.css - does that not work for you?

For popups, edit index.html, according to this:

http://leafletjs.com/reference.html#popup

Use the settings in the `Options` section, such as `minWidth`.

**Comment by magerlin** [comment]
Earlier I have edited the font size in this part of label.css but it has no effect now?: 

`.leaflet-label {
	font: 10px/18px "Helvetica Neue", Arial, Helvetica, sans-serif;
}`

Regarding the widt of popup windows I have succeeded in setting a fixed width by editing qgis2web.css from this:
`.leaflet-popup-content {
    width:auto !important;
}`
to this:
`.leaflet-popup-content {
    width:200px;
}`

**Comment by tomchadwin** [comment]
Use your browser dev tools (F12, also availabl in qgis2web preview) to investigate which CSS declarations are overriding which others.

**Comment by magerlin** [comment]
Popup window width can also be set in qgis2web.css adding a minimum width like this:
`.leaflet-popup-content {
    width:auto !important;
/*Set minimum width of popup window: */
    min-width: 300px;
}`

**Comment by magerlin** [comment]
Regarding the font CSS I just realized there is no longer any need for this!

The produced map from Qgis2web now matches my font selection in Qgis - bravo!

**Comment by tomchadwin** [comment]
Ha! Why on earth didn't I think of mentioning that? Thank you!

**Comment by tomchadwin** [comment]
*Note*: the font file is not exported (for many reasons), so if your map is viewed online, or on someone else's machine, they will only get the font you specified in QGIS if they have that font installed.
