### ISSUE TITLE
Leaflet maps: Popups cannot be avoided?

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#325]
If "No label" is selected for **all** popup fields for a layer the result is that **all fields** are shown but with no field headers:

![screenshot 2016-08-19 15 49 58](https://cloud.githubusercontent.com/assets/1887531/17811842/d11c80ec-6624-11e6-9aec-fe318cf06696.png)

**Comment by tomchadwin** [comment]
Correct. Presume OL3 as well. Not sure how to sort this in the GUI.

**Comment by magerlin** [comment]
It is not possible to completely toggle popups off for a layer?

**Comment by tomchadwin** [comment]
In a word, no. And there needs to be.

**Comment by tomchadwin** [comment]
Although what happens if all fields are set to Hidden in QGIS?

**Comment by tomchadwin** [comment]
I think that works in OL3, but throws an error in Leaflet. Do you confirm?

**Comment by magerlin** [comment]
I can hide all fields in my layer and get no popup with no errors in Leaflet too. 

But in my actual example I am using a field for classification of roads and if I hide this it seems like Qgis2web understands this as I am having only missing values and create a map with "spooky looking" semi transparent roads instead:

![screenshot 2016-08-19 16 19 15](https://cloud.githubusercontent.com/assets/1887531/17812786/e6d2c83e-6628-11e6-9363-ffe2b03f86ab.png)

**Comment by tomchadwin** [comment]
Ugh. You're right. Labels and categorized/graduated renders rely on fields, but hiding them in QGIS stops them being exported to JSON.

Time for a rethink. *Sigh*.

**Comment by tomchadwin** [comment]
I think this issue existed before my recent commits. Can you confirm that you get your "spooky looking" effect in qgis2web 1.13.1, not just in master?

**Comment by magerlin** [comment]
Yes, I am working in version 1.13.1. The "spooky looking" effect has "always" been there for features with missing values for classification or labels.

**Comment by tomchadwin** [comment]
OK, so I can go ahead and release recent changes without causing a reversion. Still have to work out a fix for this, though.

**Comment by tomchadwin** [comment]
This issue logged as #326

**Comment by tomchadwin** [comment]
Can you confirm that the initial issue (ability to get rid of popups for a layer) is solved, though?

**Comment by magerlin** [comment]
Well sort of.... 

In my example I have 72 fields I have to mark as hidden one by one.

If possible I would much prefer a simple toggle......

**Comment by tomchadwin** [comment]
I'm reluctant to do that - the philosphy behind the plugin has always been not to duplicate QGIS functionality, and be as lightweight as possible.

**Comment by magerlin** [comment]
Well I see your point. 
On the other hand when I am working with my data in Qgis I like to be able to see all the data during the map production - also those being irrelevant to the final viewer (the final maps are not going to be too complicated).

**Comment by tomchadwin** [comment]
Accepted. It's a difficult line to tread. But qgis2web is meant to reproduce your QGIS project. If the data is not hidden there, it shouldn't be hidden in the webmap.

**Comment by magerlin** [comment]
I can follow your principle - in many situations a complete replica of the Qgis map is what is wanted.

So let conclude this issue is solved.

**Comment by tomchadwin** [comment]
Many thanks. On to #326...

**Comment by boesiii** [comment]
@magerlin 
You may want to look at the link below.  It talks about using python to turn multiple fields to hidden.  I have been meaning to try it becasue I have run into the same issue as you with many fields needing marked as "hidden".
http://gis.stackexchange.com/questions/190843/how-to-hide-more-than-one-qgis-attribute-field-at-a-time

**Comment by magerlin** [comment]
I just realized one more negative implication of the "always popup feature". Layers where you have avoided popups by hiding the fields in Qgis still in Leaflet seems to be regarded as having popups and they are showing wrong cursor type and they are blocking popups from underlying layers. 

In the actual map I am working with ([http://byogtrafik.ramboll.dk/Dubrovnik/model_input/road_network/traffic_counts/index.html](http://byogtrafik.ramboll.dk/Dubrovnik/model_input/road_network/traffic_counts/index.html)) I am illustrating a county using a non filled polygon. I put this as the bottom layer (and it i shown at the top in the legend). My top layer (shown at the bottom of the legend) is "Car Counts Low season". 

All works fine when map is loaded and I have the wanted popups from "Car Counts Low season" dots. But try to toggle "Car Counts Low season" off and on again. Now the "Car Counts Low season" is no longer the top layer in the map  (this is a separate issue?) and popups are no longer functioning. This is because the county polygon is now on top and leaflet expects a popup from this layer instead. Try to toggle the county layer off and now popups for "Car Counts Low season" works again.

Also note how the cursor changes (or rather not changes) when moving the cursor across the county border from the outside - the whole county is regarded as "clickable and popup-able" which it not should be. This was not the case in similar maps I have made 8th of june with the newest Qgis2web version at that time: [http://byogtrafik.ramboll.dk/Dubrovnik/model_input/road_network/link_data/index.html](http://byogtrafik.ramboll.dk/Dubrovnik/model_input/road_network/link_data/index.html). Here the cursor only changes just when passing the county border.

By some reason my actual map does not at all show up in OL3 so I cannot tell anything about the situation in OL3.

Sorry for this long post - but it is a rather complex problem....

**Comment by tomchadwin** [comment]
Don't apologize. I had also noticed the cursor issue, and didn't like it from a UX point of view, but hadn't thought of the issue of blocking other stacked layer popups. Needs further investigation. It's as though a null popup is bound when there are only hidden fields, instead of no popup at all.

Yes, layer stacking order is a longstanding Leaflet issue. Should be fixed once Leaflet 1.0 is out, and qgis2web is migrated to it (another big job).

**Comment by magerlin** [comment]
Thanks to boesiii for the Python link. 

Hopefully the QGis gui at sometime will be extended to more easily handle changes to several fields at a time....

Or perhaps someone with Python knowledge could make a plugin of the Python code?
