### ISSUE TITLE
Boolean project settings being overwritten

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#327]
Behaviour not fully diagnosed yet. Please try the following, and confirm what happens for you:

1. Open some simple data in QGIS
2. Start qgis2web
3. Check the `Minify GeoJSON files` option
4. Close qgis2web
5. Open qgis2web
6. **Confirm that `Minify GeoJSON files` is still checked**
7. Close qgis2web
8. Save your project
9. Open another unrelated project
10. Reopen the first project
11. Start qgis2web
12. **For me, `Minify GeoJSON files` is now incorrectly unchecked**

So it seems to me that the QGIS save project process is doing something to these values.

Can anyone confirm? Can anyone explain?

**Comment by boesiii** [comment]
I notice the same behavior even if I ignore #9 BUT it does remember my basemap setting of OSM.

**Comment by tomchadwin** [comment]
Something's definitely afoot...

**Comment by tomchadwin** [comment]
How about dropdowns? Are they behaving correctly? In other words, does this bug only affect checkboxes?

**Comment by boesiii** [comment]
The precision setting was able to be restored when the project is opened again.

I wonder if it has something to do when the preview gets initialized

**Comment by tomchadwin** [comment]
No, I think it's to do with how booleans are stored and compared. I've asked a question on the dev list, as I still don't understand what's going wrong. I thought this worked before.

**Comment by boesiii** [comment]
In the qgis file there is
`<Addlayerslist type="int">1</Addlayerslist>`

Why does it say "int"?  Shouldnt it say something like "bool"?

**Comment by tomchadwin** [comment]
Another question: do the per-layer checkbox settings save correctly - visible, cluster, etc?

**Comment by tomchadwin** [comment]
THIS IS DRIVING ME CRAZY. I CAN'T FIGURE OUT WHAT ON EARTH IS GOING WRONG AAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by tomchadwin** [comment]
No, wait, the boolean thing looks like it's a red herring. I don't think *any* settings are saving. They save within a session, but if you open a different project, and then reopen the one where you have made the qgis2web changes, nothing is remembered - layer settings, config settings, checkboxes, dropdowns.

Can anyone confirm? This is on my local copy where I have been hacking around wildly to try to fix this, so perhaps all is well in master. Think I'll discard all my local changes and start again.

**Comment by tomchadwin** [comment]
Might have cracked it. Here's the theory:

1. You can write project settings with spaces in the setting name
2. Until you close the project, you can read them by calling the setting name with the spaces in it
3. Once you've closed and reopened the project, all spaces are stripped from the setting name
4. Therefore, then reading by setting name with spaces fails

Need to confirm, but it's looking good so far.

**Comment by boesiii** [comment]
I think the settings were being saved.  Atleast I can see them in the qgis file.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test and report back. **Note**: this might well not work with existing projects (it might), so you might have to reset your options again (apologies) - let me know.

**Comment by boesiii** [comment]
Works for me.  Thanks.

**Comment by tomchadwin** [comment]
Thanks for testing.
