### ISSUE TITLE
Newly arrived problem with user defined projections

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#330]
Until now I have had had no problem creating Leaflet maps from shape files in a user defined projection (they are output from another application).

Since last update of Qgis2web (I think...) these layers are completely missing from produced OL3 and Leaflet maps.

Just after clicking the Qgis2web menu point I get an error "Crs was undefined":
![screenshot 2016-08-31 15 07 04](https://cloud.githubusercontent.com/assets/1887531/18129999/8e7dc1ca-6f8d-11e6-94d2-1547b7dbd083.png)

Test shape file: 
[Links_link.zip](https://github.com/tomchadwin/qgis2web/files/447260/Links_link.zip)

Can anyone make a leaflet map of this with the projection defined in the included .prj file:

PROJCS["Sphere_Mercator",GEOGCS["GCS_Sphere",DATUM["D_Sphere",SPHEROID["Sphere",6371000,0]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Mercator"],PARAMETER["False_Easting",0],PARAMETER["False_Northing",0],PARAMETER["Central_Meridian",0],PARAMETER["Standard_Parallel_1",0],UNIT["Meter",1]]

**Comment by tomchadwin** [comment]
All I can say immediately is that that is a  QGIS error, not a qgis2web one.

**Comment by tomchadwin** [comment]
I'm going to leave this to GIS people, as I just don't know enough about projections to figure this out. When I run it in 2.16.2, I get the QGIS CRS dialog popping up, and if I accept what it suggests, qgis2web works. I've not had any joy in getting any further, since I can't get either your proj text in the post above, or that in the .PRJ file to convert to something which QGIS recognizes.

Sorry.

**Comment by boesiii** [comment]
What projection is your data? What EPSG code?

**Comment by boesiii** [comment]
Have you teid creating a QPJ file so that Qgis can read your projection?

**Comment by magerlin** [comment]
I recieve the shp file from another application also delivering the .prj file. When I open it in Qgis it says USER:105000 in the bottom right corner where the EPSG code usually is.

QGIS describes this projection as: 
+proj=merc +lon_0=0 +lat_ts=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs. 

It works fine in Qgis and it has worked without problems in also in Qgis2web until recently.

How do I make a QPJ file? - I am currently in China with very bad internet acces, so I have not had a change to Google it...

**Comment by tomchadwin** [comment]
@magerlin Do you have Arc? If so, what projection does it say when you open it? I'm really no help here. The fact that QGIS calls it user-defined could be because it is genuinely user-defined, or because it contains an error of some kind. But that's the limit of my knowledge, I'm afraid.

**Comment by tomchadwin** [comment]
Closing with no feedback
