### ISSUE TITLE
Marker Symbol Orientation

### ISSUE THREAD

**Issue by khiyer** [tomchadwin/qgis2web#336]
The orientation of a marker in qgis can be defined by assigning an attribute value to the angle field in the layer properties. This is not preserved in OL3 while Leaflet produces an error.
Screenshots of the layer in 1) qgis, 2) OL3 and 3) Leaflet are shown below.
Thanks!

![capture_marker_orient_qgis](https://cloud.githubusercontent.com/assets/22297597/18636421/09b9543a-7e89-11e6-97ee-316124dfdd9c.PNG)
![capture_marker_orient_ol3](https://cloud.githubusercontent.com/assets/22297597/18636426/0d5f62e6-7e89-11e6-9863-41980c704638.PNG)
![capture_marker_orient_leaflet](https://cloud.githubusercontent.com/assets/22297597/18636429/0f586c78-7e89-11e6-8431-6bf1b63dc5c0.PNG)

**Comment by tomchadwin** [comment]
What's interesting is that OL3 **does** work. I guess it could be possible to pass in rotation. As for Leaflet, this is covered by #332, which is a large job, and hasn't been tackled yet.

**Comment by tomchadwin** [comment]
OL3 *does* support rotation. So this feature can be achieved, I guess.

**Comment by khiyer** [comment]
thanks for the quick replies.
OL3 only passes the svg markers (circles with lines) but not the vector ones (black lines only in the qgis snapshot). However, it would be great if rotation could be implemented for other markers in OL3.
I've tested the update and confirm that the crash does not occur. Leaflet displays all markers as simple symbols now. Keep up the good work!
![capture_vector_leaflet_update](https://cloud.githubusercontent.com/assets/22297597/18658469/a66e60f2-7f03-11e6-959c-a5a5790f57a1.PNG)

**Comment by khiyer** [comment]
confirmed that rotation works when a constant angle is specified but not by a field value.

**Comment by tomchadwin** [comment]
I've tried to implement rotation by data-defined override:

```javascript
    var style = [ new ol.style.Style({
        image: new ol.style.Icon({
                  imgSize: [32, 32],
                  scale: 0.59375,
                  anchor: [9, 9],
                  anchorXUnits: "pixels",
                  anchorYUnits: "pixels",
                  rotation: function(feature){return feature.get("ELEV") * 0.0174533;},
                  src: "styles/a18_sluis.svg"
            })
    })];
```

But it doesn't rotate. No errors. Anyone know why?

**Comment by tomchadwin** [comment]
Have asked GIS.SE:

http://gis.stackexchange.com/questions/211475/openlayers-3-feature-driven-rotation

Can you help, @ThomasG77?

**Comment by tomchadwin** [comment]
I was over-complicating. OL3 rotation committed to master. Please test.

**Comment by tomchadwin** [comment]
I've committed a Leaflet version, but it's not working. No error, but no rotation, and SVGs disappear. Anyone any ideas what I'm doing wrong?

**Comment by tomchadwin** [comment]
Have asked for help elsewhere:

https://github.com/bbecquet/Leaflet.RotatedMarker/issues/5
http://gis.stackexchange.com/questions/211515/leaflet-geojson-marker-rotation

**Comment by khiyer** [comment]
OL3 does not display svg correctly now.
![capture_marker_orient_ol3_2](https://cloud.githubusercontent.com/assets/22297597/18739550/b011651c-80a4-11e6-884e-5f939206ed2a.PNG)

**Comment by tomchadwin** [comment]
Hrm. It's working for me. To double-check, are you explicitly setting the marker as an SVG marker? Or are you setting it at the top symbology level somehow?

**Comment by khiyer** [comment]
The markers are set as svg in qgis. Used to work before in qgis2web (see first few snapshots in thread)

**Comment by tomchadwin** [comment]
[rotation.zip](https://github.com/tomchadwin/qgis2web/files/486792/rotation.zip)

Here's an example of rotated SVGs in OL3. Can you open your browser console to see if there are any JS errors? Can you paste the contents of `/styles/[layername]_style.js`?

**Comment by khiyer** [comment]
It seems that it cannot find the associated feature for some reason.
Here's the error
ReferenceError: feature is not defined
<anonymous>WorldStressMap2008_style.js:9
1WorldStressMap2008_style.js:9:19

[rotation_stress.zip](https://github.com/tomchadwin/qgis2web/files/486817/rotation_stress.zip)

**Comment by tomchadwin** [comment]
Can you try stripping the number of features right down and trying again? I wonder if a 28MB JSON file is too much to handle.

**Comment by tomchadwin** [comment]
Re: Leaflet. Bizarrely, though I thought it wasn't working yesterday, it now seems to be. Please test.

**Comment by khiyer** [comment]
stripping it down doesn't work either. Also, leaflet just shows simple symbols.
[rotation_leaflet.zip](https://github.com/tomchadwin/qgis2web/files/486856/rotation_leaflet.zip)
[rotation_ol3.zip](https://github.com/tomchadwin/qgis2web/files/486857/rotation_ol3.zip)

**Comment by tomchadwin** [comment]
Ah, wait. Can yuo try a single symbol renderer, instead of categorized?

**Comment by khiyer** [comment]
That did the trick. It works in both ol3 and leaflet. Will it be updated so that it accepts categorized symbols as well?

**Comment by tomchadwin** [comment]
I'm looking at OL3 categorized now, but I've not figured out how to apply it yet. Graduated will also need fixing, I guess, as well as Leaflet for both.

**Comment by tomchadwin** [comment]
Ah, I might have managed to get the OL3 output to work. I'll try to code it back into the plugin and let you know when it's ready to test.

**Comment by tomchadwin** [comment]
OK, I've committed a change to try to get OL3 working with categorized renderers. Can you test and feed back?

**Comment by khiyer** [comment]
confirmed working in OL3.

**Comment by tomchadwin** [comment]
Great - many thanks. Will look at Leaflet next.

**Comment by tomchadwin** [comment]
Ah, no, of course Leaflet categorized SVGs don't work - that's #332. Given that, are we happy to sign off this issue yet, pending getting categorized SVGs to work in Leaflet? Or does anything else fail?

**Comment by khiyer** [comment]
Nope. All good. Thanks a lot.

**Comment by tomchadwin** [comment]
Closing for now - #332 will enable other changes.
