### ISSUE TITLE
Leaflet WFS Layers always visible

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#337]
Toggling 'visible' has no effect on WFS layers in leaflet, both in preview and output, but does work if layers are encoded to GEOJSON.

**Comment by tomchadwin** [comment]
Hrm. Can't recreate that. a single symbol styled polygon layer works. What geometry type and renderer are you using?

**Comment by tomchadwin** [comment]
Wait. Scratch that. Was looking at OL3. OK. Looking into it.

**Comment by philipjohnbarlow** [comment]
Points.

**Comment by philipjohnbarlow** [comment]
Same effect with all geometry types, can you confirm

**Comment by tomchadwin** [comment]
Yup, confirmed. No idea on the cause yet.

**Comment by tomchadwin** [comment]
OK, I've tried a fix in the leaflet1.0.0 branch - can you test? It's not perfect yet, as I'm getting a JS error when unchecking the layer in the layers list, but it's probably better than what we had before.

**Comment by tomchadwin** [comment]
JS error sorted - please test (leaflet1.0.0 branch)
