### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#340]
```
Uncaught TypeError: Cannot read property 'call' of undefined
```

**Comment by tomchadwin** [comment]
Now working, though irritatingly Leaflet 1.0.0 defaults to giving labels a frame. Will have to try to get rid of it via CSS.

**Comment by boesiii** [comment]
When I have a label for a point the preview is not working and I am getting an error in the browser.

"Cannot read property 'popupPane' of undefined"

**Comment by tomchadwin** [comment]
I can't recreate. Can you upload your layer and project?
