### ISSUE TITLE
Rewrite layer stacking order to use panes

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#341]

**Comment by tomchadwin** [comment]
I've committed this to the leaflet1.0.0 branch. It "works" in that the code generated looks correct to me. However, layers are stacked in the wrong order. I'd be very grateful if someone else could take a look and see what is wrong. This is the first time I've worked with Leaflet map panes, and I might just be fundamentally misunderstanding something.

**Comment by tomchadwin** [comment]
I think I've got it. The fact that points in a layer are all individual layers from a Leaflet persepctive is what I was missing. This might now be working. Please test.

**Comment by boesiii** [comment]
The layer stacking order is not correct for me.  In the layer list it is correct but in the map it is wrong.

**Comment by tomchadwin** [comment]
Can you give any more details? Is it reversed? Random? Does it always come out with the same incorrect order?

**Comment by tomchadwin** [comment]
@boesiii Are you using the leaflet1.0.0 branch? Master does not yet have these changes.

**Comment by boesiii** [comment]
Yes I am using the LF branch.  In my map I have 2 point layers (PT1 and PT2) and a polyline layer.  The polyline layer should be below all layers but it appears on top of all layers.  The point layers appear to be random.  Sometime areas PT1 overlaps PT2 but other areas it looks reversed, PT2 overlaps PT1.  My points are all simple SVG styles.

**Comment by tomchadwin** [comment]
Ah, SVGs. Let me check I've done them. Probably not.

**Comment by tomchadwin** [comment]
Thanks - SVGs were not updated. Can you try now?

**Comment by boesiii** [comment]
Tom, still not working.  Attached is some sample qgis project and exported q2w


[sample_data.zip](https://github.com/tomchadwin/qgis2web/files/511087/sample_data.zip)
[qgis2web_1475669652.83.zip](https://github.com/tomchadwin/qgis2web/files/511088/qgis2web_1475669652.83.zip)

**Comment by tomchadwin** [comment]
Whoops - error in the SVG code - apologies. Can you test again?

**Comment by boesiii** [comment]
Works!

**Comment by tomchadwin** [comment]
Splendid!
