### ISSUE TITLE
WMS

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#342]
Not sure if this is limited to Leaflet 1.0.0. I just tried a single WMS and it failed, but it also failed in OL3, so it might not be indicative. Anyone have a good, stable, public WMS we could use for testing which contains a layer which should remain in place (with the same name) for some time?

**Comment by boesiii** [comment]
I am sure NASA has something.  I will look tomorrow.

**Comment by tomchadwin** [comment]
@boesiii Did you find one? I should also have said that it needs to give out EPSG:3857.

**Comment by tomchadwin** [comment]
Ah, it's OK. Just tried it  with this:

contextualWMSLegend=0&crs=EPSG:3857&dpiMode=all&featureCount=10&format=image/png&layers=GBR_BGS_625k_BLT&styles=&url=http://ogc.bgs.ac.uk/cgi-bin/BGS_Bedrock_and_Superficial_Geology/wms?

Looks like it works. OL3 doesn't, but that's another matter...
