### ISSUE TITLE
OL3 WMS

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#343]
I don't think it's working at the moment. Can anyone confirm?

**Comment by philipjohnbarlow** [comment]
Working for me with the current Master Tom.

**Comment by tomchadwin** [comment]
Can you try the leaflet1.0.0 branch?

**Comment by philipjohnbarlow** [comment]
I can, also working.

**Comment by tomchadwin** [comment]
Thanks. How odd. If you can be bothered, can you try with the layer I mention from the BGS in #342?

**Comment by philipjohnbarlow** [comment]
I already have that particular WMS service in my list so no problem.  Working fine in OL3.

**Comment by tomchadwin** [comment]
No idea how it was working for you, but I think I've now fixed the issue.

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/1f438d900ed071bba8e2fd6d25b9f533c8460aa4) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.1)
