### ISSUE TITLE
Remove Leaflet feature_group/raster_group

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#344]
The Leaflet export creates two groups:

`feature_group`
`raster_group`

It adds layers to those groups, and then adds those groups to the map. I'm not sure this is worth doing - the layers can be added directly to the map.

Anyone know of a reason why I shouldn't remove them? @riccardoklinger, any memories from qgis2leaf?

**Comment by boesiii** [comment]
I think the search option needs "feature_group"

**Comment by tomchadwin** [comment]
I think that was just laziness on my part - I should pass in the specific layer name instead.

**Comment by tomchadwin** [comment]
The specific layer name is now being passed in to the Leaflet layer search, so this can probably now be done.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.
