### ISSUE TITLE
Polygons disappears 

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#349]
Qgis2web 1.19. makes anoying bug. Polygons on exported map sometimes disappears. Example: http://bug.kelv.cz/#8/49.852/15.688 . Try to move focus out from polygons (from EU) and back on them, click on them... sometimes they will hide. Older version of qgis2web was ok.

Bug detected in Chrome browser.

**Comment by boesiii** [comment]
I am not noticing anything, maybe the problem is with your browser or computer.  How large is the geojson file containing your features?  Try it on a smaller set of data.

**Comment by kelv-cz** [comment]
I use much bigger geojson generated with older qgis2web (some summer version) and it is ok. 
mapy.kelv.cz/pisemna-zminka

**Comment by kelv-cz** [comment]
https://www.youtube.com/watch?v=-JmQOsd4GGw  time 00:14. Polygons disapppeared.

**Comment by tomchadwin** [comment]
I managed to recreate this big once, bit only once. I don't know how to proceed. Could it be the highlight on hover option? Can you try recreating the map without that, and see whether the problem persists?

**Comment by kelv-cz** [comment]
Probably it is not hover. Polygons disappeared after moving from their area (sometimes), try to move on  Engand and back. Qgis2web 1.15 works ok.

**Comment by tomchadwin** [comment]
You mean drag the map so the polys are no longer in the viewport, and then drag it back? Tried that - all works. When the bug occurred for me before, I was mousing over lots of polys, and clicking on them to ge the popups.

**Comment by kelv-cz** [comment]
Yes i mean that. Sometimes happened. I have not this version of qgis2web now, i can try export it without highlight after six hours from now. But io think that is not a problem in higlight :(.

**Comment by tomchadwin** [comment]
For what it's worth, I've now made polygons and basemap disappear. However, I did this by clicking and dragging like a madman, so I don't feel the need to debug such behaviour too much. If we can find a reliable way to trigger the polys' disappearance, that would be great.

**Comment by tomchadwin** [comment]
Forget the basemap thing - I'd dragged south of the map. Apologies.

**Comment by kelv-cz** [comment]
Maybe this happens only with only one layer on map.

**Comment by kelv-cz** [comment]
No. More layer and bug too :(

**Comment by kelv-cz** [comment]
Downgrade. 1.18.0 seems ok.

**Comment by tomchadwin** [comment]
So it looks like Leaflet 1.0.0 could be the issue. Could you try an export from the working 1.18.0, and replace`js/leaflet.js` and `css/leaflet.css' with the Leaflet 1.0.0 versions in the output? See if the problem reoccurs.

**Comment by kelv-cz** [comment]
Export in 1.18. Replaced js/leaflet.js and  /css/leaflet.css from 1.19. No change (only legend (control) disappeared too).

**Comment by kelv-cz** [comment]
I tried that. Export in 1.18 and replace leaflet.js and leaflet.css. And bug is here. Yes, this files make it.

**Comment by tomchadwin** [comment]
OK. Can you post the contents of `index.html` here? I can then simplify it further. I need to make sure we have as simple an example as possible. If my simplification makes the bug disappear, it's a qgis2web problem, or a problem with one of the Leaflet plugins it uses (probably). If the problem remains, it's possibly a Leaflet 1.0.0 issue, which I'll have to report. But the example has to be as simple as it can be.

One other test you could do - can you try a single symbol renderer instead? Does that fix it, or does the error still occur? The code output for single symbol renderers is simpler than the renderer used in your example.

**Comment by kelv-cz** [comment]
Sorry, I forgot about this issue. 
http://qgis2web-1-19.kelv.cz/ - one layer. But maybe without this bug.

**Comment by tomchadwin** [comment]
Ah, is the issue that the highlight on hover and popup only work if you click on the *border* of the polygon, not on its interior?

**Comment by kelv-cz** [comment]
This is not polygon, this is line only. Popup works ok.

**Comment by kelv-cz** [comment]
Fixed in QGIS  2.18.2 + qgis2web 2 (maybe fixed in previous versions, i do not know).

**Comment by tomchadwin** [comment]
Is this issue resolved? I'll close, but reopen if required.
