### ISSUE TITLE
Multiple basemaps

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#35]
Port over from qgis2leaf. Does OL3 support multiple basemaps?

**Comment by tomchadwin** [comment]
How much of a demand is there for this feature?

**Comment by boesiii** [comment]
I believe this would be a useful feature because it is always handy to have a map type background and an aerial image type background.

**Comment by tomchadwin** [comment]
To achieve this, we need to change the baselayer dropdown from a QComboBox to a QListWidget, I think, as it is in qgis2leaf, if that can be made songle-line and scrollable. I think moving it to below the preview frame would also improve the GUI (getting rid of some of the unwanted horizontal scrolling which currently happens.

**Comment by tomchadwin** [comment]
Added to rendered-raster branch, PR created to merge into master, awaiting Travis results.

**Comment by tomchadwin** [comment]
Released as 1.0.0-beta2 and published in QGIS plugins repo.
