### ISSUE TITLE
Adding new basemaps

### ISSUE THREAD

**Issue by mattpitts74** [tomchadwin/qgis2web#350]
Hi There, 

I'm using the qgis2web plugin and it works very well, but I'm wondering if it's possible to add some addtional basemaps and how I would go about this? 

I'm really after some aerial images as a basemap and I know that there is an ESRI Leaflet plugin here: http://leafletjs.com/plugins.html#basemap-providers  I'm not a coder and wondering if its simple to add addintional basemaps to choose in the qgis2web interface?  Thanks again for a great plugin

**Comment by tomchadwin** [comment]
Yes, you can add your own additional basemaps. To do so, you'll need the URL of the tileserver you want to use. It will look like a normal web address, but with `{z}`, `{x}`, and `{y}` in it (and often some other codes). You'll also need the required attribution text.

Next, from the qgis2web folder on your machine, open `basemaps.py` in a text editor. It contains two functions and a variable:

```python
def basemapLeaflet():
[...]

def basemapOL():
[...]

basemapAttributions = {
[...]
}
```

Hopefully you'll be able to see that each contains configuration for each basemap in the plugin. What you therefore need to do is to add to each of these functions, using the existing basemaps as your guide, and slot in the details of your basemap provider. The name you use in each must be identical.

You then need to edit `configParams.py` in a text editor, and add the name of your new base layer to the `baselayers` variable. The name you add here must match the name you use in `basemaps.py`.

Once the changes are saved, restart QGIS. Let us know whether it works or not. If it doesn't, upload or copy and paste the content of those two files, and we can see what hasn't worked.

**Comment by mattpitts74** [comment]
Hi Tom,  This is great, I've just tried adding the following tile server for ersi world imagery  'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'

As I said I'm not a coder so when I tried I may well of got the code changes wrong as the plugin gave me some syntax errors, even after several attempts, so I was wondering if you're able to add this to the plugin, as I'm sure that other would also find it really useful.  Thanks  Matt

**Comment by tomchadwin** [comment]
I'm afraid I am a little hesitant to add this to the plugin, in case it breaches any licence restrictions. If you can paste the contents of your `basemaps.py` and `configParams.py` here, I'm sure we can figure it out.

**Comment by mattpitts74** [comment]
Hi Tom Fair enough, 

Here's the code from the baemap.py 

`# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis2leaf @ Social Planing Council of the City of Ottawa
                                 A QGIS plugin
 QGIS to Leaflet creation programm
                             -------------------
        begin                : 2014-04-29
        copyright            : (C) 2013 by Riccardo Klinger
        email                : riccardo.klinger@geolicious.com
 ***************************************************************************/
/***************************************************************************
INSTRUCTION ON FILE USAGE:
***************************************************************************/
"""
# To add a line to the layer list you might use this dictionary python
# variable. Its first element is the basemap service name which will be
# displayed in the GUI. The second entry marked with "META" is the metadata for
# the leaflet. Please respect copyrights and licenses
# After you've added a basemap service, the plugin needs to be reinstalled.
#
"""
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


def basemapLeaflet():
    dictionary = {
        'OSM': 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        'OSM B&W': ('http://{s}.www.toolserver.org/tiles/bw-mapnik/' +
                    '{z}/{x}/{y}.png'),
        'Stamen Toner': 'http://a.tile.stamen.com/toner/{z}/{x}/{y}.png',
        'OSM DE': ('http://{s}.tile.openstreetmap.de/tiles/' +
                   'osmde/{z}/{x}/{y}.png'),
        'OSM HOT': 'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
        'Thunderforest Cycle': ('http://{s}.tile.thunderforest.com/cycle/' +
                                '{z}/{x}/{y}.png'),
        'Thunderforest Transport': ('http://{s}.tile.thunderforest.com/' +
                                    'transport/{z}/{x}/{y}.png'),
        'Thunderforest Landscape': ('http://{s}.tile.thunderforest.com/' +
                                    'landscape/{z}/{x}/{y}.png'),
        'Thunderforest Outdoors': ('http://{s}.tile.thunderforest.com/' +
                                   'outdoors/{z}/{x}/{y}.png'),
        'OpenMapSurfer Roads': ('http://openmapsurfer.uni-hd.de/tiles/' +
                                'roads/x={x}&y={y}&z={z}'),
        'OpenMapSurfer adminb': ('http://openmapsurfer.uni-hd.de/tiles/' +
                                 'adminb/x={x}&y={y}&z={z}'),
        'OpenMapSurfer roadsg': ('http://openmapsurfer.uni-hd.de/tiles/' +
                                 'roadsg/x={x}&y={y}&z={z}'),
        'Stamen Terrain': 'http://a.tile.stamen.com/terrain/{z}/{x}/{y}.png',
        'Stamen Watercolor': ('http://a.tile.stamen.com/watercolor/' +
                              '{z}/{x}/{y}.png'),
        'OpenWeatherMap Clouds': ('http://{s}.tile.openweathermap.org/map/' +
                                  'clouds/{z}/{x}/{y}.png'),
        'OpenWeatherMap Precipitation': ('http://{s}.tile.openweathermap.org' +
                                         '/map/precipitation/{z}/{x}/{y}.png'),
        'OpenWeatherMap Rain': ('http://{s}.tile.openweathermap.org/map/' +
                                'rain/{z}/{x}/{y}.png'),
        'OpenWeatherMap Pressure': ('http://{s}.tile.openweathermap.org/' +
                                    'map/pressure/{z}/{x}/{y}.png'),
        'OpenWeatherMap Wind': ('http://{s}.tile.openweathermap.org/map/' +
                                'wind/{z}/{x}/{y}.png'),
        'OpenWeatherMap Temp': ('http://{s}.tile.openweathermap.org/map/' +
                                'temp/{z}/{x}/{y}.png'),
        'OpenWeatherMap Snow': ('http://{s}.tile.openweathermap.org/map/' +
                                'snow/{z}/{x}/{y}.png'),
        'OpenSeaMap': 'http://tiles.openseamap.org/seamark/{z}/{x}/{y}.png'
		
		'EsriWorld Imagery': ('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}')
    }
    return dictionary


def basemapOL():
    basemaps = {
        "Stamen Watercolor": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.Stamen({{
        layer: 'watercolor'
    }})
}})""",
        "Stamen Toner": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
        source: new ol.source.Stamen({{
        layer: 'toner'
        }})
}})""",
        "Stamen Terrain": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.Stamen({{
        layer: 'terrain'
    }})
}})""",
        "OSM": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.OSM()
}})""",
        "OSM B&W": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: \
'http://{{a-c}}.www.toolserver.org/tiles/bw-mapnik/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "Thunderforest Transport": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.thunderforest.com/transport/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "Thunderforest Landscape": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.thunderforest.com/landscape/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "Thunderforest Outdoors": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.thunderforest.com/outdoors/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenMapSurfer Roads": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: \
'http://openmapsurfer.uni-hd.de/tiles/roads/x={{x}}&y={{y}}&z={{z}}',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenMapSurfer adminb": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: \
'http://openmapsurfer.uni-hd.de/tiles/adminb/x={{x}}&y={{y}}&z={{z}}',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenMapSurfer roadsg": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: \
'http://openmapsurfer.uni-hd.de/tiles/roadsg/x={{x}}&y={{y}}&z={{z}}',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OSM HOT": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://{{a-c}}.tile.openstreetmap.fr/hot/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenSeaMap": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://t1.openseamap.org/seamark/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "Thunderforest Cycle": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.thunderforest.com/cycle/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OSM DE": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openstreetmap.de/tiles/osmde/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Clouds": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openweathermap.org/map/clouds/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Precipitation": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url:'http://tile.openweathermap.org/map/precipitation/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Rain": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openweathermap.org/map/rain/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Pressure": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: \
'http://tile.openweathermap.org/map/pressure/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Wind": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openweathermap.org/map/wind/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Temp": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openweathermap.org/map/temp/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})""",
        "OpenWeatherMap Snow": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://tile.openweathermap.org/map/snow/{{z}}/{{x}}/{{y}}.png',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})"""
       "EsriWorld Imagery": """
new ol.layer.Tile({{
    'title': '{title}',
    'type': 'base',
    source: new ol.source.XYZ({{
        url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attributions: [new ol.Attribution({{html: '{attr}'}})]
    }})
}})"""
    }
    basemaps = {k: v.format(**{'title': k, 'attr': basemapAttributions[k]})
                for k, v in basemaps.iteritems()}
    return basemaps

basemapAttributions = {
    'OSM': """\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OSM B&W': """\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, \
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'Stamen Toner': """\
Map tiles by <a href="http://stamen.com">Stamen Design</a>,\
<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map\
data: &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>\
contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OSM DE': """\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OSM HOT': """\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>,\
Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">\
Humanitarian OpenStreetMap Team</a>""",
    'OpenSeaMap': """\
Map data: &copy; <a href="http://www.openseamap.org">OpenSeaMap</a>\
contributors""",
    'Thunderforest Cycle': """\
&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>,\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'Thunderforest Transport': """\
&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>,\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'Thunderforest Landscape': """\
&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>,\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'Thunderforest Outdoors': """\
&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>,\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OpenMapSurfer Roads': """\
Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @\
University of Heidelberg</a> &mdash; Map data:\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OpenMapSurfer adminb': """\
Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @\
University of Heidelberg</a> &mdash; Map data:\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'OpenMapSurfer roadsg': """\
Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @\
University of Heidelberg</a> &mdash; Map data:\
&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,\
<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>""",
    'Stamen Terrain': """\
Map tiles by <a href="http://stamen.com">Stamen Design</a>,\
<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash;\
Map data: &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>\
contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">\
CC-BY-SA</a>""",
    'Stamen Watercolor': """\
Map tiles by <a href="http://stamen.com">Stamen Design</a>,\
<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash;\
Map data: &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>\
contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">\
CC-BY-SA</a>""",
    'OpenWeatherMap Clouds': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Precipitation': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Rain': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Pressure': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Wind': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Temp': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>""",
    'OpenWeatherMap Snow': """\
Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>"""
 'EsriWorld Imagery': """\
Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community"""
}
`

Here's the code from the configparas

```
# qgis-ol3 Creates OpenLayers map from QGIS layers
# Copyright (C) 2014 Victor Olaya (volayaf@gmail.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from qgis.core import QgsApplication
import os
import shutil
from utils import tempFolder


def getTemplates():
    fl = os.path.join(QgsApplication.qgisSettingsDirPath(),
                      "qgis2web",
                      "templates")
    if not os.path.exists(fl):
        shutil.copytree(os.path.join(os.path.dirname(__file__),
                                     "templates"),
                        fl)
    return tuple(f[:f.find(".")] for f in reversed(os.listdir(fl))
                 if f.endswith("html"))

paramsOL = {
    "Appearance": {
        "Add layers list": False,
        "Match project CRS": False,
        "Add address search": False,
        "Layer search": ("None", "placeholder"),
        "Measure tool": ("None", "Metric", "Imperial"),
        "Show popups on hover": False,
        "Highlight on hover": False,
        "Geolocate user": False,
        "Template": getTemplates()
    },
    "Data export": {
        "Export folder": tempFolder(),
        "Precision": ("maintain", "1", "2", "3", "4", "5", "6", "7", "8",
                      "9", "10", "11", "12", "13", "14", "15"),
        "Minify GeoJSON files": True,
        "Mapping library location": ("Local", "CDN")
    },
    "Scale/Zoom": {
        "Extent": ("Canvas extent", "Fit to layers extent"),
        "Restrict to extent": False,
        "Max zoom level": ("1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11", "12", "13", "14",
                           "15", "16", "17", "18", "19", "20", "21",
                           "22", "23", "24", "25", "26", "27", "28"),
        "Min zoom level": ("1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11", "12", "13", "14",
                           "15", "16", "17", "18", "19", "20", "21",
                           "22", "23", "24", "25", "26", "27", "28"),
    }
}

baselayers = (
            "OSM",
            "OSM B&W",
            "Stamen Toner",
            "OSM DE",
            "OSM HOT",
            "Thunderforest Cycle",
            "Thunderforest Transport",
            "Thunderforest Landscape",
            "Thunderforest Outdoors",
            "OpenMapSurfer Roads",
            "OpenMapSurfer adminb",
            "OpenMapSurfer roadsg",
            "Stamen Terrain",
            "Stamen Watercolor",
            "OpenWeatherMap Clouds",
            "OpenWeatherMap Precipitation",
            "OpenWeatherMap Rain",
            "OpenWeatherMap Pressure",
            "OpenWeatherMap Wind",
            "OpenWeatherMap Temp",
			"EsriWorld Imagery",
            "OpenWeatherMap Snow"),


specificParams = {
}

specificOptions = {
}
```

**Comment by tomchadwin** [comment]
Sorry I missed your latest replies. If it's any use to you, I can see an issue. In both places where you have added your basemap, you have not added a comma after the preceding item - see all the others in the list have commas after them, but the last one does not. Now that you have added another entry at the end, what was the last item is now second-last, so it needs a comma after it to separate it from your new one.

Hopefully you can understand what is required from my garbled and confusing explanation. Can you try, and let us know how you get on? I'll close this issue for now - reopen if it still doesn't work.

**Comment by Maks2615** [comment]
excuse me, but I couldn't find the file basemap.py in my comp. (after installing plugin and searching in the python plugins folder). Any suggestions why is that? Thanks.

**Comment by riccardoklinger** [comment]
basemaps are not stored inside the plugin anymore. with the current releases it will use a xyz basemap from your project. add it by hand or via the quickmapservice plugin.
