### ISSUE TITLE
Unable to export any vector layer

### ISSUE THREAD

**Issue by liamflood-magseis** [tomchadwin/qgis2web#351]
Hi,

I am trying to overlay one simple polygon vector shapefile (literally a box) using QGIS2web and cannot export anything except the basemaps with no layers. 

When I try no html file is generated and I get the following error:

`An error has occurred while executing Python code: 

TypeError: 'int' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/liam.flood/.qgis2/python/plugins\qgis2web\maindialog.py", line 447, in closeEvent
    for attr in pop:
TypeError: 'int' object is not iterable

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.16.3 Nødebo, 7d00cae 

Python Path:
C:/PROGRA~1/QGIS2~1.16/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.16/apps/qgis/./python
C:/Users/liam.flood/.qgis2/python
C:/Users/liam.flood/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\bin\python27.zip
C:\PROGRA~1\QGIS2~1.16\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.16\bin
C:\PROGRA~1\QGIS2~1.16\apps\Python27
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.16\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/liam.flood/.qgis2//python
C:\Users\liam.flood\.qgis2\python\plugins
`

**Comment by tomchadwin** [comment]
That error looks like it should only happen when you close qgis2web. When precisely does it occur?

**Comment by liamflood-magseis** [comment]
Yes...that's correct. It is a pop up when the plugin closes.

**Comment by liamflood-magseis** [comment]
OK....it seems the problem was that the layers are grouped. when the layers are removed from their groups they can be displayed ok.

**Comment by tomchadwin** [comment]
Yeah, it's a known issue, I'm afraid: https://github.com/tomchadwin/qgis2web/issues/175. Hopefully it's something we can work on soon. I'll close this, since the other issue covers it.

**Comment by liamflood-magseis** [comment]
Ok thanks. Just getting to know the software so wasn't aware of this. Took a bit of playing around to figure out that the groups was causing the problem.

**Comment by tomchadwin** [comment]
Yeah - it really needs improvement. Glad you got to the bottom of it, and apologies for the confusion.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
