### ISSUE TITLE
No module named QtWebKit when installing qgis2web

### ISSUE THREAD

**Issue by sindile** [tomchadwin/qgis2web#358]
I am getting the following error when installing qgis2web on Ubuntu 16.10 - No module named QtWebKit 

I am running:
QGIS version - 2.18.0
QGIS code revision - b7fe4bb2
Compiled against Qt - 4.8.7
Running against Qt - 4.8.7
Compiled against GDAL/OGR - 2.1.1
Running against GDAL/OGR - 2.1.1
Compiled against GEOS - 3.5.0-CAPI-1.9.0
Running against GEOS - 3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version - 9.5.4
SpatiaLite Version - 4.3.0a
QWT Version - 5.2.3
PROJ.4 Version - 492
QScintilla2 Version - 2.9.3

On Ubuntu 16.10

Running sudo locate qtwebkit

/usr/include/x86_64-linux-gnu/qt5/QtWebKit/qtwebkitversion.h
/usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets/qtwebkitwidgetsversion.h
/usr/lib/python3/dist-packages/PyQt5/uic/widget-plugins/qtwebkit.py
/usr/lib/python3/dist-packages/PyQt5/uic/widget-plugins/__pycache__/qtwebkit.cpython-35.pyc
/usr/share/doc/libqtwebkit-dev
/usr/share/doc/libqtwebkit-qmlwebkitplugin
/usr/share/doc/libqtwebkit4
/usr/share/doc/python3-pyqt5.qtwebkit
/usr/share/doc/libqtwebkit-dev/changelog.Debian.gz
/usr/share/doc/libqtwebkit-dev/copyright
/usr/share/doc/libqtwebkit-qmlwebkitplugin/changelog.Debian.gz
/usr/share/doc/libqtwebkit-qmlwebkitplugin/copyright
/usr/share/doc/libqtwebkit4/changelog.Debian.gz
/usr/share/doc/libqtwebkit4/copyright
/usr/share/doc/python3-pyqt5.qtwebkit/changelog.Debian.gz
/usr/share/doc/python3-pyqt5.qtwebkit/copyright
/usr/share/qt4/doc/html/qtwebkit-bridge.html
/usr/share/qt4/doc/html/qtwebkit-goes-mobile.html
/usr/share/qt4/doc/html/qtwebkit-guide-cache.html
/usr/share/qt4/doc/html/qtwebkit-guide-canvas.html
/usr/share/qt4/doc/html/qtwebkit-guide-css.html
/usr/share/qt4/doc/html/qtwebkit-guide.html
/usr/share/qt4/doc/html/qtwebkit.html
/var/cache/apt/archives/python3-pyqt5.qtwebkit_5.7+dfsg-2_amd64.deb
/var/lib/dpkg/info/libqtwebkit-dev.list
/var/lib/dpkg/info/libqtwebkit-dev.md5sums
/var/lib/dpkg/info/libqtwebkit-qmlwebkitplugin:amd64.list
/var/lib/dpkg/info/libqtwebkit-qmlwebkitplugin:amd64.md5sums
/var/lib/dpkg/info/libqtwebkit4:amd64.list
/var/lib/dpkg/info/libqtwebkit4:amd64.md5sums
/var/lib/dpkg/info/libqtwebkit4:amd64.shlibs
/var/lib/dpkg/info/libqtwebkit4:amd64.triggers
/var/lib/dpkg/info/python3-pyqt5.qtwebkit.list
/var/lib/dpkg/info/python3-pyqt5.qtwebkit.md5sums

Any pointers on what could the issue be?

**Comment by tomchadwin** [comment]
Yes. QtWebkit has indeed been removed. See #309. I'll close this issue as a duplicate, but I'm afraid I have no solution at this stage. Many apologies - it's a serious issue for this and other QGIS plugins. 

cc @jef-n, @m-kuhn, @lucacasagrande, @akbargumbira.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
