### ISSUE TITLE
Pane ordering ignored when using Marker Cluster in Leaflet

### ISSUE THREAD

**Issue by joshdickerson92** [tomchadwin/qgis2web#367]
Tom, 

Not sure if this is a mistake on my part but when exporting Clustered points to Leaflet it appears to apply the pane z-index to the points and not to the cluster so it therefore appears below other layers. Are you aware if it is possible for me to edit the code on this for it to be applied to the cluster rather than the point or does this not work?

Thanks!

**Comment by tomchadwin** [comment]
That could be an extremely good catch. Let me look into it and get back to you. Should be fixable if you're right.

**Comment by joshdickerson92** [comment]
Yeah i gave it a go at fixing it this morning but didn't have a lot of time. I'm pretty certain i've put a MarkerCluster layer into a pane before but couldn't seem to dig out any past examples. Cheers

**Comment by tomchadwin** [comment]
Just tried to recreate, and my clusters were below another layer. I'm afraid I'm going to need some data to reproduce this (layers and project). Reopen if you get the time and opportunity to look into it further.
