### ISSUE TITLE
Points not showing in Leaflet

### ISSUE THREAD

**Issue by butte37** [tomchadwin/qgis2web#368]
Hi 

Im a stupid newbie, trying to figure things out, so please have patience with me.

A couple of month ago i installed Qgis and Qgis2web for the first time.
It went pretty well, here is the result:
www.nordek.net/skyggekort1

Now a couple of month later, i wanted to make some changes. Qgis and Q2W was updated to latest.
Now my troubles started.

I am not only a stupid newbie, but also not good at English, so i made a movie showing what is wrong.
Ill also explain.

Movie : https://youtu.be/2JdcXJ7JaxE

When preview in OL, no layers work, except the layer with points (dots).
When preview in Leaflet, all layers work, except layer with points (dots).

Can someone please point me in the right direction. How do i solve this, what did i do wrong ?
Can i give additional information, helping me in solving this ?

Thanks for reading.

**Comment by tomchadwin** [comment]
To help us solve the problem, can you follow these instuctions: https://github.com/tomchadwin/qgis2web#reporting-bugs?

**Comment by tomchadwin** [comment]
Closing after no response
