### ISSUE TITLE
Function based graduated ramp fails silenty

### ISSUE THREAD

**Issue by easherma** [tomchadwin/qgis2web#371]
![score](https://cloud.githubusercontent.com/assets/10539855/21200884/81d4c800-c20e-11e6-996d-179046bb1b19.PNG)
![markers](https://cloud.githubusercontent.com/assets/10539855/21200889/88a31c72-c20e-11e6-963a-84f62df8dc40.PNG)

Makes code like
```
  function doStylecpsleadOGRGeoJSONPointcopy1(feature) {
        if (feature.properties['score * 100'] >= 0.0 &&
                feature.properties['score * 100'] <= 5.0) {

            return {
                radius: 6.0,
                fillColor: '#fef0d9',
                color: '#000000',
                weight: 0.0,
                fillOpacity: '1.0',
                opacity: '1.0',
                dashArray: ''
            }
        }
```

vs

![correct](https://cloud.githubusercontent.com/assets/10539855/21200897/8f063b3a-c20e-11e6-9aca-0b3043408893.PNG)
If I load that column in as-is.

**Comment by tomchadwin** [comment]
No, in afraid expressions in the categorised value are not supported. Remove the `* 100` and change your category values to 0-0.2, 0.2-0.4, etc

**Comment by easherma** [comment]
@tomchadwin thanks! I did figure that out, but I'm thinking it would be nice (if possible), to have qgis2web throw an error/heads up that this is the case. As is, the code exports just fine but just doesn't work as expected. It was obvious once I finally deduced the issue.

**Comment by tomchadwin** [comment]
Absolutely. The same is the case for labels and popups. At minimum I need to tap the error and alert. However, there is a better workaround which would allow expressions, but I've not had time to code it. Soon, I hope.

**Comment by tomchadwin** [comment]
Also, I don't think the QGIS `Legend` values are used, and they need to be.
