### ISSUE TITLE
Point Labels using Leaflet

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#373]
I am using q2w 2.0 beta1

When I try and label a point and preview it using leaflet, I get a script error message, "The script on this page appears to have a problem...  Yes or No".  I click yes and the preview does not update.  If I click export the resulting webpage has point labels but is very slow to react to mouse.  No javascript error in developer tools.

**Comment by tomchadwin** [comment]
Can I have your layer and project files? Not seen this, and it sounds nasty.

**Comment by tomchadwin** [comment]
Cannot recreate with /test/data/layer/airports.shp. Will close for the moment. @boesiii, reopen if you can upload your files.

**Comment by boesiii** [comment]
[test_points.zip](https://github.com/tomchadwin/qgis2web/files/682421/test_points.zip)

Sorry, I have been away.

Here is a sample file.  It looks like the error happens when there are a few thousand points.

**Comment by tomchadwin** [comment]
OK, I get the error in the preview window. You should click "No". I think this isn't really an error in the plugin - just a Leaflet performance limit.

Interestingly, there is a possible solution in development: https://twitter.com/JamesLMilner/status/813363623074656256
