### ISSUE TITLE
Create legend option: why there's not ?

### ISSUE THREAD

**Issue by nformica** [tomchadwin/qgis2web#379]
Old plugin "qgis2leaf" had a useful option to create a legend (for vector layers).
Why there's no more in qgis2web ?

Regards
Nino

**Comment by tomchadwin** [comment]
Does "Add layers list" not do what you want?

**Comment by nformica** [comment]
You're right !
I did'nt  think it was the same thing, sorry !

**Comment by tomchadwin** [comment]
No problem. You're welcome!
