### ISSUE TITLE
Preview pane far too short

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#381]
Since I made the GUI change to add the settings tab, the preview pane only seems to take up half the vertical space it should, leaving a big gap between it and the basemaps list. Can anyone confirm?

**Comment by boesiii** [comment]
Yes, it is too short here also.

**Comment by tomchadwin** [comment]
Thanks for confirming. No idea what has changed - Qt is not my strong suit. Might just have to copy the previous code back over.

**Comment by pcav** [comment]
Possibly related (if not I can open a new ticket): Leaflet preview in my case is moving up and down of a few pixels. Nothing serious, I just wonder whether this is due to an underlying issue.

**Comment by tomchadwin** [comment]
You man it is in motion? And is it just the features,  or is it the zoom controls and attribution text as well?

**Comment by pcav** [comment]
It seems to be dependent on the geometry of the popup. I'm unable to replicate it right now. You can disregard it, not a big issue anyway.

**Comment by tomchadwin** [comment]
Preview back to the right size in master. Please test. I'll close this for now. @pcav, if you still get the movement bug, can you open a new ticket?

**Comment by pcav** [comment]
Sure, I will.
Thanks.
