### ISSUE TITLE
Display of areas is different from the canvas

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#383]
See attached images.
![q2w_canvas](https://cloud.githubusercontent.com/assets/691842/21953422/b0584b44-da36-11e6-97d8-91277816be53.png)
![q2w_preview](https://cloud.githubusercontent.com/assets/691842/21953421/b0577688-da36-11e6-85be-aba3173734d2.png)
Rule-based styling not honoured.

**Comment by tomchadwin** [comment]
No, rule-based rendering is not supported, and there is no way to achieve it, though @NathanW2 hinted that a change to QGIS might make this possible. I don't know what that change was, and I don't think it ever happened.

**Comment by tomchadwin** [comment]
See http://osgeo-org.1560.x6.nabble.com/Python-granular-access-to-rules-in-rule-based-renderer-td5201632.html

**Comment by NathanW2** [comment]
The way I was going to do it was using the visit() method.  We can do it by
walking the expression tree.  I will see if I can put something together
for you.
