### ISSUE TITLE
Issue a warning when N of features too high

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#385]
Rendering of a preview can take ages for layers with tens of thousands of features, and it cannot be interrupted, forcing people to kill QGIS. I suggest checking this first and issue a warning "Rendering can take a very long time. Consider switching off some layers, and restrict rendering to canvas extent" before doing the preview.

**Comment by tomchadwin** [comment]
If the preview could be rendered in another thread, that would also help, but I've never used threads before.

**Comment by pcav** [comment]
Right; however, a warning would be useful in any case.

**Comment by tomchadwin** [comment]
Yes, but it would probably have to be a timed warning. Number of features would not be a good indicator, I presume, as non-points with lots of nodes would take much longer than points. 

Of course, the best solution would be a progress bar. I think that might only be possible with threads, but I'm not sure.

**Comment by pcav** [comment]
Sure, a progress bar with an Abort button would be fine, especially if the bar is realistic.

**Comment by tomchadwin** [comment]
Progress bar opened as new ticket: #431

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by pcav** [comment]
When I have many layers with a few hundreds of features, the warning does not seem to be triggered.

**Comment by tomchadwin** [comment]
Correct. It currently triggers if any single layers has more than 1000 features.

**Comment by pcav** [comment]
Tried with a 10k points layer, no warning.
Perhaps the warning should be triggered when total number of features across all layers is too bog?

**Comment by tomchadwin** [comment]
@pcav Can I have access to the layer? @nyalldawson what do you think about a limit for total features of all layers (as well as the per-layer limit).

**Comment by pcav** [comment]
I just created with Processing, random points. Perhaps point are cheap and therefore not taken into account?

**Comment by tomchadwin** [comment]
No, I tested with points, and got the warning. Let me try to recreate.

**Comment by tomchadwin** [comment]
Hrm. I can't find random points in Processing.

**Comment by pcav** [comment]
It is called `Random points in extent`

**Comment by tomchadwin** [comment]
I can't find it, I'm afraid.

**Comment by boesiii** [comment]
Vector Menu -> Research Tools -> Random Points

![reg_points](https://cloud.githubusercontent.com/assets/2079638/23997538/0fa16b28-0a28-11e7-8a9f-ee47e357e2da.PNG)

**Comment by tomchadwin** [comment]
None of that in my Vector menu - only item is OpenStreetMap.

**Comment by boesiii** [comment]
Or if you are using the processing panel

![pro](https://cloud.githubusercontent.com/assets/2079638/23997627/70fa5470-0a28-11e7-90d9-fb4e6a3d9d8a.PNG)

**Comment by tomchadwin** [comment]
I don't have QGIS geoalgorithms in my Processing toolbox either.

**Comment by pcav** [comment]
Just activate them in Processing options.
Otherwise I can send you a test dataset, just let me know.

**Comment by tomchadwin** [comment]
QGIS algorithms already activated:

![2017-03-21 13_40_59-processing options](https://cloud.githubusercontent.com/assets/7840213/24149954/3583634c-0e3c-11e7-873c-629963d6ac1a.png)

I don't understand why:

![2017-03-21 13_45_22-qgis 2 18 4](https://cloud.githubusercontent.com/assets/7840213/24150103/bd3f345a-0e3c-11e7-86cb-ef13e1b8f31f.png)

**Comment by pcav** [comment]
Maybe you have an older version of Processing masking the new one?
![schermata del 2017-03-21 15-03-20](https://cloud.githubusercontent.com/assets/691842/24150970/b4d4e412-0e47-11e7-9998-0fbc8f0bd339.png)

**Comment by tomchadwin** [comment]
I seem to have versions in both /qgis2 and in my application dir. Which is the preferred location?

**Comment by pcav** [comment]
Please remove the one in .qgis2, so QGIS will use the default (newer in your case) version.

**Comment by boesiii** [comment]
Similar issue
http://gis.stackexchange.com/questions/231831/vector-menu-tools-missing-processing-plugin-broken

**Comment by tomchadwin** [comment]
Thanks, @boesiii, but @pcav was right. The versionin `.qgis2` must have been out of date, and as taking priority. It's working now.

Back to the original issue: I've created a 5000 points, and I get the correct warning instead of an initial automatic preview (using current master). Can you recheck, @pcav?

**Comment by pcav** [comment]
I confirm, now the warning appears correctly.
