### ISSUE TITLE
Add a method to upload the webGIS created to a webserver

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#386]
Parameters and protocols should be configurable and stored in configs. As a first step, I think FTP and SCP should be supported. Ultimately, it would be great to have a public site people could upload their work on.

**Comment by tomchadwin** [comment]
I don't really want to sanction some central QGIS official webmap store. That sounds a bit too much like ArcGIS Online, and possibly competes with client-server solutions like QGIS Cloud. It also depends on the reliability of the external location. If we can just get publishing built for people's own sites, that would be great.

**Comment by pcav** [comment]
Well', that's a matter for general, probably PSC, discussion. Perhaps some general service could be used, e.g. this same GH, etc.
Matter for thoughts later.

**Comment by tomchadwin** [comment]
Agreed. The subsystem is still required in the plugin, with or without a central publishing repo. 

Didn't Github recently impose traffic limits? Or am I confusing them with another service? If they have, we couldn't use them as an official webmap repo.

**Comment by tomchadwin** [comment]
Publishing subsystem released. Will close this issue. Open individual issues for other publishing protocols (SSH, SFTP, etc).
