### ISSUE TITLE
layer search

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#389]
I have been able to make it work this function only with points, but if I add a layer lines (trails) underneath it stops working. 
Ideal for me would be to be able to center the layer with lines directly.
May I know what are the limitations and eventual workaround to use this function?
Thank you

**Comment by tomchadwin** [comment]
Which map format are you using? Leaflet or OpenLayers 3?

**Comment by Sortronic** [comment]
I use leaflet, OpenLayers 3 doesn't even show layer search on the map.
For what I experimented, layer search works only with points, right?I need to show a map of trails with an easy way to find individual routes. Pointing layer search to this map never worked. The workaround is to stack on top a layer of points a the starting of each trail. But when I stack together the two layers it won't work. Points layer alone works well. :(




Sent from Yahoo Mail on Android 
 
  On Wed, Jan 18, 2017 at 6:07 PM, Tom Chadwin<notifications@github.com> wrote:   
Which map format are you using? Leaflet or OpenLayers 3?

**Comment by tomchadwin** [comment]
OpenLayers works for me. Leaflet seems to throw an error in the browser: `a.getLatLng` is not a function. Can you confirm? This could be that the Leaflet search plugin only supports points. I have to investigate further.

**Comment by Sortronic** [comment]
Tom, OpenLayers3 does work very well indeed. I was focused on Leaflet because I thought OL3 couldn't show the search bar. Well the problem is another one. If you turn on Geolocate user and Layer Search at the same time LS hovers on the Gu layer. It still visible in transparency but not clickable. I didn't notice before, a little bug there I guess.  But for now a big step forward for my project. This is a wonderful piece of software, looking forward to see polished those little problems I thank you very much.

**Comment by Sortronic** [comment]
On Open Layers 3 all the icons stack on top of each other, Geolocate users, Measure tool, Layer Search

**Comment by tomchadwin** [comment]
OK, great. That OL3 'multiple controls on top of each other' issue has been in the back of my mind. Now you've encouraged me to fix it. Not sure about the Leaflet issue yet.

**Comment by Sortronic** [comment]
I am sorry I cannot help as illiterate as I am, but...

**Comment by tomchadwin** [comment]
Separate issues #391 and #392 opened, so closing this.
