### ISSUE TITLE
Export fails with no-ASCII chars in categories name

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#395]
http://qgis-colors.obci.cz/qgis2web-diacritic-bug.png   
Export in leaflet fails when non-ascii chars is in categories name. Here are czech chars like "ě", "Í".  
This bug is only in leaflet export. Openlayers export is ok. 

This bug was not in Qgis2web 1.15 (probably).

**Comment by jie4922** [comment]
I have the same error message in leaflet export. My chars is Traditional Chinese as the attached snapshot.
![default](https://cloud.githubusercontent.com/assets/25398198/22418613/af67c4cc-e714-11e6-8e04-3a975290bc99.jpg)

**Comment by tomchadwin** [comment]
Looking into this now. Could you both upload a layer for me?

**Comment by tomchadwin** [comment]
@jie4922 - I'll try to fix this before releasing the WMS fixes (#396), so you might have  to wait a little longer. Hope that's OK.

**Comment by tomchadwin** [comment]
Just tested with field named `Å`, and it worked. Hrm.

**Comment by tomchadwin** [comment]
Ah, got it. Categorized. Confirmed bug. Looking into it now.

**Comment by tomchadwin** [comment]
Fix committed to master - please test. I also need to check graduated renders for the same issue.

**Comment by jie4922** [comment]
Hi Tom
I'm totally ok wait for this issue get fixed, thanks for your instant response! 
Try the sample shp file. 
https://drive.google.com/file/d/0B01wuahjDBFGbmExdTRoZk9YNHM/view?usp=sharing

**Comment by tomchadwin** [comment]
Perfect. On which field did you categorize?

**Comment by tomchadwin** [comment]
Confirmed working with your layer.

**Comment by jie4922** [comment]
I use the third column to categorize.
Actually, in my real work scenario, I joint a .csv file and use one of the jointed columns to categorize.
But I got the same error just simple use the the original column~

**Comment by tomchadwin** [comment]
Graduated seems *not* to be affected by this bug.

**Comment by tomchadwin** [comment]
Confirmed that categorization now works on the third field of your layer. I'll do a release now with those fixes.

**Comment by tomchadwin** [comment]
Released as 2.3.1 and pushed to QGIS plugins repo.
