### ISSUE TITLE
Version 2.3.1 breaks OL3 layer search

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#399]
Updated to last version and not able anymore to add Layer Search function on  OL3. The preview map goes blank and once exported shows a blank window. Downgraded to to 2.2.0 version and it works fine, fortunately.

**Comment by tomchadwin** [comment]
What errors can you see in the browser console when you export?

**Comment by Sortronic** [comment]
Not sure what you are asking for but I have found this:

Console:
SyntaxError: missing } after property list[Learn More]                 Qgis2Web.js:32:22     

Hope it helps.

**Comment by tomchadwin** [comment]
Yes, that looks like exactly what I am looking for. Will investigate.

**Comment by tomchadwin** [comment]
I can't recreate this. Can you upload your layer, and say which field to search on?

**Comment by Sortronic** [comment]
Now it works. I have opened a new file in qgis with the same layer and tried again qgis2web 2.3.1. As I said it works well. Using a new file all the previous settings are in default, the only difference is that the file isn't working has Precision set to 10. The reason is that in version 2.2.0 I have noticed the lines were zaggy and I had to to pull up Precision to 10 to have round lines again. In this new version Precision set to 1 makes smooth lines. I don't know if that was the glitch, I will check. Thanks for now and sorry for wasting your time, but this morning my life was very miserable unable as I was to delivery that map.

**Comment by tomchadwin** [comment]
Firstly, you are certainly not wasting my time, or anyone else's. I really appreciate the reports of problems you experience. Without them, qgis2web would not have developed as far as it has.

Let me know if the browser console error occurs again. If it does, upload your layer, and post a screenshot of your qgis2web settings. 

Does setting `Precision` to "maintain" not work for you? That should give the same number of decimal places in your export as in your original layer.
