### ISSUE TITLE
OL3 layer search only for numbers?

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#400]
I see that OL3 layer search function works only for numbers.

  <dt>Layer search</dt>
<dd>Add option to search for values in layer field values</dd>

this does it mean it's only for integers? I have a map indexed with letters: AA, AB, AC....
that keeps braking qgis2web.

**Comment by tomchadwin** [comment]
No, you should be able to search strings. I need more details of what happens. Error messages? Screenshots?

**Comment by Sortronic** [comment]
Well, I am learning.
The layer I was using had PROVA_PedHorse name and Console showed this:
ReferenceError: lyr_PROVA is not defined[Learn More]
So something triggered in my mind and I changed the name in a "human" readable form, as it is well explained in HELP, and now it works.
Sorry, and again Thank you very much.

**Comment by tomchadwin** [comment]
Thanks for the details. In fact, the problem could well have been the code - I've made some changes over the last day or two to the search code. I'm glad it's working for you. Reopen this ticket if this problem reoccurs, or open a new one for any other issues you experience.
