### ISSUE TITLE
Opacity of basemaps

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#401]
Sometimes the basemaps are be too colourfull making it hard to understand colour styled layers put on top.

Inside the generated index.html one can add an opacity value to the basemaps to make them less visible:
![screenshot 2017-02-02 11 14 07](https://cloud.githubusercontent.com/assets/1887531/22545446/1272eac6-e939-11e6-8595-5662f01ea619.png)

It would be nice if one could control this opacity from within Qgis2web.

**Comment by magerlin** [comment]
Also in OL3 is it quite simple. Just add the same Opacity:0.2 (or 0.4 if you better like) at the top of Layers.js created by Qgis2web:

![screenshot 2017-02-02 15 18 27](https://cloud.githubusercontent.com/assets/1887531/22557833/0421f10a-e96c-11e6-8318-7c10fa984fdd.png)

**Comment by tomchadwin** [comment]
We could certainly do this, but there are different ways to achieve it, depending what is required:

1. Just have a "Basemaps opacity" field, which applies to all basemaps

2. Give each basemap its own opacity field, so different basemaps can have different opacity

3. Get rid of the basemaps completely, and instead handle tilemaps from QGIS (that is #378)

I think 2 is probably more work than is merited, so perhaps 1 is the best way to go until 3 is done.

What do you think?

**Comment by magerlin** [comment]
Sounds like a fine solution to me

**Comment by tomchadwin** [comment]
QGIS native XYZ layers are now supported, with transparency. Can you try that approach to see if it works for you?

**Comment by magerlin** [comment]
Should it be available in the latest version 2.5.0? I cannot find it anywhere?

**Comment by tomchadwin** [comment]
I'm saying that QGIS native XYZ tiled layers are working, with transparency, not that I have added transparency to the basemaps in the qgis2web basemap list. Can you add your required basemap as an XYZ layer in QGIS itself, set it transparency, and then start qgis2web?

**Comment by magerlin** [comment]
Ah sorry, I didn't get that. 

Do you by NATIVE xyz tiles mean it has to be tiles created/stored on your own PC/server?
I don't use this feature that much. 

I normally use the QuickMapServices plugin to get background maps but they are not transferred using Qgis2web :-(

External tiles I only know to ad by hand coding an XML file like below and drag it to the canvas - are there any easier way for this (a plugin)

`<GDAL_WMS>
<Service name="TMS">
<Version>1.1.1</Version>
<ServerUrl>http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}.png</ServerUrl> 
</Service>
<DataWindow>
<UpperLeftX>-180</UpperLeftX> 
<UpperLeftY>180</UpperLeftY> 
<LowerRightX>180</LowerRightX> 
<LowerRightY>-180</LowerRightY>
<TileLevel>19</TileLevel> 
<TileCountX>1</TileCountX> 
<TileCountY>1</TileCountY> 
<YOrigin>top</YOrigin> 
</DataWindow>
<Projection>EPSG:4326</Projection> 
<BlockSizeX>256</BlockSizeX> 
<BlockSizeY>256</BlockSizeY> 
<BandsCount>3</BandsCount> 
<Cache /> 
</GDAL_WMS>`

**Comment by tomchadwin** [comment]
No no. QGIS now supports the kind of layers which Quick Map Services/OpenLayers provide. In QGIS:

1. Open the Browser panel - `View` > `Panels` > `Browser Panel`
2. In the Browser Panel, right-click on `Tile Server (XYZ)`, and click `New Connection...`
3. Paste the tileserver URL (eg http://stamen-tiles-a.a.ssl.fastly.net/terrain-background/{z}/{x}/{y}.png) and hit return

You can then drag the newly created layer from the Browser Panel into your canvas.

**Comment by magerlin** [comment]
NICE - I learned something new today :-) 
I do not normally use the browser - a little strange the XYZ Tile functionality is hidden there?

I can confirm that opacity on XYZ tiles work in Qgis2web.

Adding an Image layer like http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png
together with for instance a semitransparent OSM layer gives interesting possibilities
