### ISSUE TITLE
Popup width 

### ISSUE THREAD

**Issue by Naturtecnica** [tomchadwin/qgis2web#402]
Hi Tom,
I got some problems width popup width.
Where can I set the width I want? 
I'd like all words inline...
Thanx
Best regards

Lorenzo

**Comment by tomchadwin** [comment]
Are you using Leaflet or OL3 export format?

**Comment by Naturtecnica** [comment]
Solved right now!
I modified in .css:

.leaflet-popup-content {
    max-width: 600px;
    height: 200px;
    overflow-y: scroll;
	margin: 13px 19px;
	line-height: 1.4;
	}

Thanx TOM!!!

**Comment by tomchadwin** [comment]
Glad you got it sorted.

**Comment by riccardoklinger** [comment]
Is there a reason, why the param maxWidth was not implemented in the popupbuilder workflow with Leaflet? Reference here:
https://leafletjs.com/reference-1.5.0.html#popup
