### ISSUE TITLE
Geolocate does not work when using Chrome

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#403]
I had a map with the Geolocate tool and when I uploaded it to my web server and opened my webpage the Geolocate tool would not work in Chrome.  The console showed the message:

getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

It works with Firefox 51 and IE 11

**Comment by tomchadwin** [comment]
Yup. Security feature introduced in Chrome. You have to use HTTPS to allow geolocation in Chrome, I'm afraid. Not a qgis2web issue. Sorry!
