### ISSUE TITLE
Visible setting is not being restored when re-opening project

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#404]
If I set a layer to not be visible, the setting is not restored when re-opening the file in Qgis.  It is recognized when opening and closing q2w when qgis is left open.

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by boesiii** [comment]
It partially works.  it does not work with layers that have all fields hidden.  I have a layer with all fields hidden in Qgis and I am using the layer for labels only.

**Comment by tomchadwin** [comment]
It also doesn't work for layers you've only just added.

**Comment by tomchadwin** [comment]
OK, I've had another go. Can you try again?

**Comment by boesiii** [comment]
Works for me

**Comment by tomchadwin** [comment]
Splendid. Reopen if any other similar issues become apparent.
