### ISSUE TITLE
Remove basemaps from GUI?

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#406]
Now that we support QGIS native XYZ tileservers, shall we remove the basemaps from qgis2web? My inclination is yes: the philosophy of the plugin has always been not to duplicate anything which QGIS can do itself.

**Comment by tomchadwin** [comment]
It also has the benefit of not getting us mixed up in any licensing issues.

**Comment by tomchadwin** [comment]
And now layer attributions are pulled through. Time for the basemap last to go, I think.

**Comment by tomchadwin** [comment]
Does anyone have any thoughts on this? I really think the basemaps should go. Another good reason to get rid of them is that using them really doesn't create the best maps. I/we call them basemaps, but the majority of them are far too busy to work with layers over the top of them. The fact that you cannot change the transparency of basemaps means there really isn't a solution for this.

I think the basemaps need to go from qgis2web. Final thoughts, anyone?

**Comment by boesiii** [comment]
I would agree about duplicating stuff from Qgis but does Qgis 2.14 LTR support XYZ layers?  I think XYZ layers suppoer was added in 2.18.

**Comment by tomchadwin** [comment]
An extremely good point - it was either 2.16 or 2.18. Now that the roadmap has 2.18 becoming an LTR, I guess we wait until then and remove at that point. Thanks for the advice.

**Comment by HerbFargus** [comment]
I just started using qgis2web so I don't know how valid my opinion is,  but I can see your point with not wanting to duplicate functionality.

From using it for the first time I was a little confused why I couldnt hide fields from the exporter but eventually realised it was by design after reading through the issue tracker.  So I can see some first time users wondering where their basemap options are, and likely people who update the plugin and see their basemap choices disappear.

As long as there is sufficient documentation though and an explanation about the philosophy behind the decision I don't see why it would be a problem.

**Comment by tomchadwin** [comment]
I think the other issue is that at the moment, QGIS doesn't ship with any prepopulated XYZ layers, though possibilities in this area are being investigated. That means people have to figure out how to add them themselves. However, even given all of these points, I think we'll go ahead and remove the basemap list from the GUI when 2.18 becomes LTR.

**Comment by tomchadwin** [comment]
@HerbFargus You raise a very valid point. The wiki is out of date, and needs to be revised. This kind of big change can work, but only if users can easily find the explanation for the change, and the workaround.

**Comment by HerbFargus** [comment]
I do a significant amount of documentation on other projects ([eg see related](retropie.org.uk/docs)) so I wouldn't mind helping out on the wiki here. I find its always easiest to write documentation the first time I try to use something so i wouldn't mind looking into it when I can find some free time

**Comment by tomchadwin** [comment]
@HerbFargus That's an extremely kind offer, and would be very welcome indeed. I believe the wiki is fully open, so I don't think I even get notified when edits take place. I mention that to make sure you get in touch directly if you want to ask anything. Thanks again!

**Comment by OlaKov** [comment]
Is it possible to use Google Maps as the base map for my qgis2web openlayers map? Right now I'm using Bing Maps (I got an account with them), but google seems to have better resolution and more details.. Thanks.

**Comment by tomchadwin** [comment]
It's probably possible, technically. However, I seem to remember that it's against the Google terms of use. Add to that the fact that qgis2web is all about open, and creating alternatives to Google Maps, it's not something I've looked into. I certainly wouldn't want qgis2web to support it out of the box. Hope you understand.

**Comment by OlaKov** [comment]
Oh yes, I just though maybe there was an easy way of doing it.
