### ISSUE TITLE
Add an image in a template

### ISSUE THREAD

**Issue by giannibianconi** [tomchadwin/qgis2web#415]
I must add a logo in my own template. Can you help me?
Thanks

**Comment by boesiii** [comment]
Where do you want the logo to appear?

**Comment by giannibianconi** [comment]
In the lower left corner of the map.

**Comment by boesiii** [comment]
just add the following code to index.html

```
<div id="logo">
            <img src="http://demo.qgis.org/demos/alaska/alaska.png" alt="some_text" style="position:fixed;bottom:0;left:0;">
        </div>
```

**Comment by giannibianconi** [comment]
Ok, I added them.
This is my own file
[technovo.txt](https://github.com/tomchadwin/qgis2web/files/794889/technovo.txt)

But it works fine with OpenLayers 
![sample1_ol](https://cloud.githubusercontent.com/assets/25864698/23234011/02b0ea7a-f951-11e6-8ced-251f8b3bc306.png)

Not with LeafLet
![sample2_leaflet](https://cloud.githubusercontent.com/assets/25864698/23234060/252030b6-f951-11e6-80d8-4f760c0abc2c.png)



`

**Comment by boesiii** [comment]
Mine works with leaflet.  Check if you get any errors in the console.  Make sure you make a copy of the HTML template because it could be overwritten during a plugin update.

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        @CSSADDRESS@
        @EXTRACSS@
        @LEAFLET_CLUSTERCSS@
        @LEAFLET_LAYERSEARCHCSS@
        @LEAFLET_ADDRESSCSS@
        @LEAFLET_MEASURECSS@
        @OL3_BACKGROUNDCOLOR@
        @OL3_GEOCODINGLINKS@
        @OL3_MEASURESTYLE@
        <style>
        html, body, #map {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
        }
        </style>
        <title>@PAGETITLE@</title>
    </head>
    <body>
        <div id="map">
            @OL3_POPUP@
        </div>
        @EXP_JS@
        @OL3_PROJ4@
        @OL3_PROJDEF@
        @JSADDRESS@
        @LEAFLET_EXTRAJS@
        @LEAFLET_ADDRESSJS@
        @LEAFLET_MEASUREJS@
        @LEAFLET_CRSJS@
        @OL3_LAYERSWITCHER@
        @OL3_GEOCODINGJS@
        @LEAFLET_CLUSTERJS@
        @LEAFLET_LAYERSEARCHJS@
        @OL3_GEOJSONVARS@
        @OL3_STYLEVARS@
        @OL3_LAYERS@ 
        @QGIS2WEBJS@
        @OL3_WFSVARS@
         <div id="logo">
            <img src="http://demo.qgis.org/demos/alaska/alaska.png" alt="some_text" style="position:fixed;bottom:0;left:0;">
        </div>
    </body>
</html>

```

**Comment by boesiii** [comment]
make sure to rename your template file and save it to the following folder so it will not be overwritten during a plugin upgrade

`C:\Users\username\.qgis2\qgis2web\templates`

**Comment by philipjohnbarlow** [comment]
Just had crack at this myself because I have found recently that I can't overlay text with div either in leaflet.  Issue persists, your example above works ok in open layers but once you add a base map in leaflet the logo is obscured by it.

**Comment by boesiii** [comment]
You need to change the z-index of the map and the logo, see below

<div id="map" style="z-index:1;">
<img src="http://demo.qgis.org/demos/alaska/alaska.png" alt="some_text" style="position:fixed;bottom:0;left:0;z-index:2;">

entire template code below

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        @CSSADDRESS@
        @EXTRACSS@
        @LEAFLET_CLUSTERCSS@
        @LEAFLET_LAYERSEARCHCSS@
        @LEAFLET_ADDRESSCSS@
        @LEAFLET_MEASURECSS@
        @OL3_BACKGROUNDCOLOR@
        @OL3_GEOCODINGLINKS@
        @OL3_MEASURESTYLE@
        <style>
        html, body, #map {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
        }
        </style>
        <title>@PAGETITLE@</title>
    </head>
    <body>
        <div id="map" style="z-index:1;">
            @OL3_POPUP@
        </div>
        @EXP_JS@
        @OL3_PROJ4@
        @OL3_PROJDEF@
        @JSADDRESS@
        @LEAFLET_EXTRAJS@
        @LEAFLET_ADDRESSJS@
        @LEAFLET_MEASUREJS@
        @LEAFLET_CRSJS@
        @OL3_LAYERSWITCHER@
        @OL3_GEOCODINGJS@
        @LEAFLET_CLUSTERJS@
        @LEAFLET_LAYERSEARCHJS@
        @OL3_GEOJSONVARS@
        @OL3_STYLEVARS@
        @OL3_LAYERS@ 
        @QGIS2WEBJS@
        @OL3_WFSVARS@
         <div id="logo">
            <img src="http://demo.qgis.org/demos/alaska/alaska.png" alt="some_text" style="position:fixed;bottom:0;left:0;z-index:2;">
        </div>
    </body>
</html>

```

**Comment by boesiii** [comment]
@tomchadwin 
Would it be worth while to add an option to let a user specifiy a logo and position it in the lower left corner?  Or just let the user handle it with a templete?

**Comment by philipjohnbarlow** [comment]
That did the trick.

**Comment by giannibianconi** [comment]
Great, with z-index it's ok also with Leaflet.
Thanks

**Comment by giannibianconi** [comment]
Solved, thanks

**Comment by ordisabeba** [comment]
adding the <div id="logo"> is shown above the legend when it is opened. Is there a solution to create a logo that stays behind the legend when opened?

![image](https://user-images.githubusercontent.com/89784373/135851154-681d9766-cac1-4596-bc95-3f9d2c7ab8de.png)

**Comment by boesiii** [comment]
@ordisabeba Have you tried changing the z-index value for either the  the legend or logo?

**Comment by ordisabeba** [comment]
Yes, I tried `z-index` both on the logo and on the layerswitcher but I think the problem is that they fall into two different `div id` so the `div id = "logo"` cannot go under the layerswitcher contained in the `div id ="map"` rather it is the elements contained in the same `div id` that can overlap with the `z-index`. Tell me if my interpretation is correct, I'm almost a beginner with everything. I also tried `ol-panel[](https://stackoverflow.com/questions/52117406/how-to-place-a-html-element-on-a-map-in-openlayers) ` but same thing (different div id). I tried to use the `customcontrol[](https://stackoverflow.com/questions/45615423/how-do-i-create-a-custom-control-in-open-layers-with-an-image-inside) ` but I could not apply it due to my lack of experience and in any case it seems to me that it is used to create clickable buttons not form images and writings.

**Comment by tomchadwin** [comment]
@ordisabeba You are right that the z-index only works for elements with the same parent. You could do something like this in script, not HTML (warning, this is just pseudocode, so you need to work out how to do it properly):

```javascript
var logo = document. createElement('img');
logo.src = '/path/to/your/log/file.png';
logo.alt = 'Logo alt text';
logo.id = 'logo';

var switcherIdentifier = '[#id or .class of the layer-switcher]';
var switcher = document.querySelector(switcherClass);

switcher.appendChild(logo);
```

Then in your CSS file (again, pseudocode, so do check):

```CSS
#logo {
    position: absolute;
    left: 0px;
    right: 0px;
    z-index: -1;
}
```

**Comment by ordisabeba** [comment]
all clear but can you tell me how to find this? [#id or .class of the layer-switcher].
without the two lines "var switcherIdentifier" and
"var switcher" the logo appeared, but the z-index had no effect between logo and switcher
