### ISSUE TITLE
Scale based label visibility working for OpenLayers but not Leaflet 

### ISSUE THREAD

**Issue by isaacbain** [tomchadwin/qgis2web#416]
Using qgis2web 2.6.0, qgis 2.14.3-Essen, macOS 10.12.4

Two layers total in map, one point layer (labels) and one line layer (labels not needed).

Scale based label visibility IS working when the map is exported via OpenLayers 3, but NOT when exported via Leaflet. The labels show all the time instead of switching off (as opposed to never showing). 

![screen shot 2017-02-20 at 2 16 05 pm](https://cloud.githubusercontent.com/assets/22882041/23108775/102f4402-f777-11e6-969e-ed0be25e16af.jpg)
![screen shot 2017-02-20 at 2 21 46 pm](https://cloud.githubusercontent.com/assets/22882041/23108828/d5c8c4fe-f777-11e6-86c7-298904d020fb.jpg)

**Comment by tomchadwin** [comment]
Yes, you are right. Scale-based label visibility has not been implemented for Leaflet exports. Not sure how easy it will be, as the Leaflet label code was recently completely rewritten to use Leaflet 1.x `L.Tooltip`. I'll have to see whether a simple option is available, or whether we have to hook into the `onzoom` events as per overall layer scale-based visibility.

**Comment by tomchadwin** [comment]
No, `L.Tooltip` doesn't have an option for scale-based visibility. Have to look into it manually, as with the layer visibility itself.

**Comment by tomchadwin** [comment]
OK, I was talking nonsense. I *had* implemented this, but then the upgrade to Leaflet 1.x broke it. I think it's fixed now. Can you report back?

**Comment by reginaldc** [comment]
Hi Tom,
I have a layer of a couple of thousand graves.
When I want to show the ID as label (in QGIS I set it scale dependant (only showing < 1/200)) all the labels show up in the preview and I get a notification that the script is blocked or something like that.
On the webpage the labels are not showing, no matter how I zoom in or out.
Regards,

**Comment by vajlex** [comment]
Hi Tom,   
I found that if I am using Markercluster and bindToolTip to geojson points, the map doesn't refresh properly.   Also, about scale dependency, I tried an if statement with zoomend and it sort of worked, but the map refresh got worse (the point objects appeared in the wrong places.   Similarly, what I really wanted to implement was https://github.com/yakitoritabetai/Leaflet.LabelTextCollision, but could never get it to work with geojson layer and bindToolTip.    Is there any way to either remove the labels at a certain zoom level, remove the layer at the zoom level, or ideally, just prevent the labels from colliding at any level?   Thanks!

**Comment by ntrip6** [comment]
I am having this issue with scale-dependent labels in Leaflet exports as well. It works as expected in QGIS 3.14 (labels at 1:5000 and closer) but nothing in the QGIS2web preview or the browser after export. The plugin is amazing otherwise -- thank you!
![image](https://user-images.githubusercontent.com/480545/91722727-871d2780-eb4f-11ea-91e9-8b7a0d5dea4c.png)
 
![image](https://user-images.githubusercontent.com/480545/91722837-b16ee500-eb4f-11ea-80b7-f0d2b1730e6f.png)
