### ISSUE TITLE
Full hard disk after executing QGIS2Web

### ISSUE THREAD

**Issue by CvTooren** [tomchadwin/qgis2web#419]
QGIS2Web version 2.6.0.
QGISversion 2.18.3.
Windows 10

When I start QGIS2Web by clicking on the button, the plug-in starts right away, without giving any dialog box in which I can enter my settings. It start immediately executing algorithm, not coming further then 0%. After e.g. 10 minutes my hard disk has no space anymore. Before start it has at least 5Gb.

Where are the the produced files, so that that I can free space on my conputer :)

Regards
Coen van Tooren

**Comment by boesiii** [comment]
What type of data are you trying to display/export?  Q2W makes a copy of all the data in the gqis project file.  The vector data is exported to geojson and the raster images are still raster images.

**Comment by boesiii** [comment]
I would suggest you try Q2W with one layer and then start adding layers back into the project.  @tomchadwin Should there be some type of check about hard disk space?

**Comment by CvTooren** [comment]
Dear Tom,

 

It’s u huge project consisting of mainly vector data. I have encloed the projectfile. I think the total amount of input project data is 250 Mb. 

The problem is that I can’t even define which data I want to export, because no dialog box is opened. I don’t have a clue what is being exported.

 

Met vriendelijke groeten,                                                                                          

 

Coen van Tooren
------------------------------------------------

vt liggend
E:            coen@vuurtooren.nl

LI:           nl.linkedin.com/in/coenvantooren/  <http://nl.linkedin.com/in/coenvantooren/> 

A:            Prof. Hugo de Vrieslaan 49

PC:          3571 GG  Utrecht

T.             030-2710581

M.           06 - 168 20 375

KvK:        30199151

------------------------------------------------

 Luchtverontreiniging en verkeer <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=92&Itemid=58>    Verkeerstellingen <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=90&Itemid=58>    Milieu-ICT <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=37&Itemid=40>    Geostatistiek <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=10&id=31&Itemid=43>     Zonnepanelen <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=17&id=49&Itemid=54>  

 

Van: boesiii [mailto:notifications@github.com] 
Verzonden: dinsdag 21 februari 2017 15:21
Aan: tomchadwin/qgis2web
CC: Coen; Author
Onderwerp: Re: [tomchadwin/qgis2web] Full hard disk after executing QGIS2Web (#419)

 

What type of data are you trying to display/export? Q2W makes a copy of all the data in the gqis project file. The vector data is exported to geojson and the raster images are still raster images.

**Comment by CvTooren** [comment]
How do I do this I no dialog box is opened in which I can define what to export. Or should I make a blank project with only one layer in it?

The problem remains that I can’t influence the settings…..

 

Met vriendelijke groeten,                                                                                          

 

Coen van Tooren
------------------------------------------------

vt liggend
E:            coen@vuurtooren.nl

LI:           nl.linkedin.com/in/coenvantooren/  <http://nl.linkedin.com/in/coenvantooren/> 

A:            Prof. Hugo de Vrieslaan 49

PC:          3571 GG  Utrecht

T.             030-2710581

M.           06 - 168 20 375

KvK:        30199151

------------------------------------------------

 Luchtverontreiniging en verkeer <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=92&Itemid=58>    Verkeerstellingen <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=90&Itemid=58>    Milieu-ICT <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=37&Itemid=40>    Geostatistiek <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=10&id=31&Itemid=43>     Zonnepanelen <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=17&id=49&Itemid=54>  

 

Van: boesiii [mailto:notifications@github.com] 
Verzonden: dinsdag 21 februari 2017 15:32
Aan: tomchadwin/qgis2web
CC: Coen; Author
Onderwerp: Re: [tomchadwin/qgis2web] Full hard disk after executing QGIS2Web (#419)

 

I would suggest you try Q2W with one layer and then start adding layers back into the project. @tomchadwin <https://github.com/tomchadwin>  Should there be some type of check about hard disk space?

**Comment by boesiii** [comment]
Yes.  Make a blank project with one layer and test.

**Comment by boesiii** [comment]
All visible layers are exported to a temp file as soon as you open the plugin.

**Comment by CvTooren** [comment]
Hello,

 

This works so far with only one layer in the whole project. I get a dialog box. I will now further explore QGIS2Web.

Thanks for your help!

 

Met vriendelijke groeten,                                                                                          

 

Coen van Tooren
------------------------------------------------

vt liggend
E:            coen@vuurtooren.nl

LI:           nl.linkedin.com/in/coenvantooren/  <http://nl.linkedin.com/in/coenvantooren/> 

A:            Prof. Hugo de Vrieslaan 49

PC:          3571 GG  Utrecht

T.             030-2710581

M.           06 - 168 20 375

KvK:        30199151

------------------------------------------------

 Luchtverontreiniging en verkeer <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=92&Itemid=58>    Verkeerstellingen <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=90&Itemid=58>    Milieu-ICT <http://www.vuurtooren.nl/index.php?option=com_content&task=view&id=37&Itemid=40>    Geostatistiek <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=10&id=31&Itemid=43>     Zonnepanelen <http://www.vuurtooren.nl/index.php?option=com_content&task=category&sectionid=17&id=49&Itemid=54>  

 

Van: boesiii [mailto:notifications@github.com] 
Verzonden: dinsdag 21 februari 2017 15:37
Aan: tomchadwin/qgis2web
CC: Coen; Author
Onderwerp: Re: [tomchadwin/qgis2web] Full hard disk after executing QGIS2Web (#419)

 

Yes. Make a blank project with one layer and test.

**Comment by boesiii** [comment]
If you don't want the temp files you can turn off the preview under the settings tab.

**Comment by tomchadwin** [comment]
Thanks, @boesiii for helping out - I was away last week. Everything he says is correct. By default, the preview is generated, which means your data is exported. Vector data is converted to GeoJSON, which is generally large in file size. As you've discussed, start the plugin with only one layer, or no layers at all, and then you can turn off the automatic preview in the Settings tab.

To clear out the files which have been generated, we need to know what platform you are on - Win/Linux/Mac etc. If you can let us know that, we can point you towards the location of the temp files.

**Comment by tomchadwin** [comment]
I'll close this for the moment - please reopen if required.
