### ISSUE TITLE
Linked Control.OSMGeocoder.js does not exist anymore?

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#421]
http://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.js does not exist and earlier produced map goes blank:

![image](https://cloud.githubusercontent.com/assets/1887531/23395328/40cdcd64-fd8e-11e6-96fb-105a17d05ac5.png)

**Comment by tomchadwin** [comment]
Confirmed - the remote address has changed. I'll update, but really need to pull down a local copy.

**Comment by magerlin** [comment]
Yes it will be nice if a produced map is not dependent on any external stuff which can be changed without your knowledge.

Are you by the way aware that the layer list acts differently if you choose "Mapping library location" as either local or CDN? Choosing CDN give a more dynamic list which contains scroll bars and collapses to a layer symbol on mouse out.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by magerlin** [comment]
I can confirm it works in master
