### ISSUE TITLE
Leaflet does not show the address search and a list of layers.

### ISSUE THREAD

**Issue by DarekLesniewski** [tomchadwin/qgis2web#422]
Hi Tom

 Leaflet does not show the address search and a list of layers for 6 days.

What happened?

**Comment by tomchadwin** [comment]
Address search should now be fixed: see #421. Let me check the layers list.

**Comment by tomchadwin** [comment]
The layers list works for me, assuming we are both talking about the same thing: `Add layers list`.

**Comment by tomchadwin** [comment]
I'll close for now - if you can give steps to recreate the problem, reopen this issue, and give some details.
