### ISSUE TITLE
Leaflet Autopanning popup content

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#423]
When I make a leaflet map with a feature who has many attributes, the web map will autopan to fit the popup content.  I would prefer the map to not autopan to fit popup contents.  Where would I set the autopan option for the popup content?

**Comment by boesiii** [comment]
The line below fixes my issue by not panning the map but also adds a vertical scroll bar.

`layer.bindPopup(L.popup({autoPan: false, maxHeight: 200}).setContent(popupContent));`

@tomchadwin Should this be added to project?

**Comment by tomchadwin** [comment]
You mean set those options by default? Possibly not. I'd rather stick to Leaflet defaults, and let people customize their output as you have if they need. I don't want to second-guess that most users would want the behaviour you do, rather than autopanning.
