### ISSUE TITLE
qgis2web/test/data/control/leaflet_25d.htm

### ISSUE THREAD

**Issue by GlenRiver** [tomchadwin/qgis2web#424]
In the leaflet_25d.html, it does not find the file. "<script src="data/lakes0.js"></script>"

**Comment by tomchadwin** [comment]
Can you give more details? I don't understand the issue.

**Comment by GlenRiver** [comment]
<img width="1277" alt="qq20170303-084308 2x" src="https://cloud.githubusercontent.com/assets/18395304/23533618/dfdb4bc8-ffed-11e6-83b4-f352e93aa835.png">
<img width="1260" alt="qq20170303-084559 2x" src="https://cloud.githubusercontent.com/assets/18395304/23533620/e14b8626-ffed-11e6-8137-3832557088c6.png">

**Comment by GlenRiver** [comment]
I don't find the file of lakes0.js.

**Comment by tomchadwin** [comment]
Ah, I see. The HTML files in /test/data/control are not meant to be opened by the user in a browser. They are there as test result comparison files for the test suite. Don't try to open them yourself.
