### ISSUE TITLE
Control.OSMGeocoder

### ISSUE THREAD

**Issue by azstumbler** [tomchadwin/qgis2web#426]
http://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.js is no longer valid for the OSMgeocoder. The valid location is now  https://rawgit.com/k4r573n/leaflet-control-osm-geocoder/master/Control.OSMGeocoder.js yet the most current version of QGIS2Web keeps directing to the invalid location.

**Comment by tomchadwin** [comment]
Duplicate of #421. 2.7.0 released this evening which should include the fix.
