### ISSUE TITLE
Max zoom level not being saved

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#427]
The max zoom level setting is not being saved.  Sometimes it is blank causing an error and the web map not displaying.

**Comment by tomchadwin** [comment]
You on the latest release from last night?

**Comment by boesiii** [comment]
No but I installed the latest and I am still seeing a blank box when using an existing project.  It appears to be working if I start from a new blank project.

**Comment by tomchadwin** [comment]
With an existing project, if you set the drop down to a proper value, does it behave after that?

**Comment by boesiii** [comment]
Yes it is working now.

**Comment by tomchadwin** [comment]
So I wonder how you got the fail. Did you download master after @nyalldawson's recent work, but before the latest version was released? If so, did you them open that project?

**Comment by boesiii** [comment]
Yes and yes.

**Comment by tomchadwin** [comment]
OK, so I'll close this as fixed, but reopen if I've misunderstood, or if it reoccurs.
