### ISSUE TITLE
Get map dimensions from QGIS window

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#43]
Merge in code from qgis2leaf

**Comment by tomchadwin** [comment]
Is this worth doing, or should we just leave the output full-screen?

**Comment by boesiii** [comment]
I would prefer full screen

**Comment by tomchadwin** [comment]
qgis2leaf gets dimensions from QGIS canvas, but has an override optional setting for full-screen. Having the option to get the dimensions from the QGIS canvas is of use, because users can frame their maps more accurately.

**Comment by tomchadwin** [comment]
This could probably be implemented via two different templates, one full-screen, one not. I'll try that to see if it works

**Comment by tomchadwin** [comment]
Added to master by means of an additional template.
