### ISSUE TITLE
Send some text to preview

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#430]
I am trying to write some code that sends some text to the preview window because I have a project with some large layers and would like to see some progress information but I am having trouble following the code.  I am using the following code in leafletwriter.py

`preview.setHtml('Processing Layer: ' + layer)`

but I always get an error about preview not being defined.  How and where would I pass the preview variable to leafletwriter.py?  I am a python novice.

**Comment by tomchadwin** [comment]
Hrm. Not sure. Can you try `self.dlg.preview.setHtml`?

**Comment by boesiii** [comment]
global name 'self' not defined

**Comment by tomchadwin** [comment]
Hmm. You couldn't have timed this better. Or worse. The whole architecture of the code is being refactored by @nyalldawson. Before that, I would have said add `dlg` as an argument to `writeLeaflet()`. Now, though, I need to understand the new structure before I can give an intelligent answer.

Out of interest, ate you trying to address the issue raised in #385?

@nyalldawson, what is the best way to reference the dialog from the writer?

**Comment by boesiii** [comment]
#385 Not necessarily but might be able to deal with it if I can figure out the architecture of the code.

**Comment by nyalldawson** [comment]
> @tomchadwin what is the best way to reference the dialog from the writer?

I don't think this should be allowed - we should strive to keep the writers non gui, so that we can reuse them in cases where the writing is not being done through the dialog (processing!)

Instead I'd set it at https://github.com/tomchadwin/qgis2web/blob/master/maindialog.py#L228 - just before the preview is created by the writer.

**Comment by tomchadwin** [comment]
@nyalldawson OK, but that will only allow access before and after the export, not at different stages during it. 

@boesiii, if that is enough for your needs, place it where Nyall says, and use `self.preview.setHtml()`.

**Comment by nyalldawson** [comment]
Ah - if you need progress reports, then it gets a bit trickier

You'd then need to make a "feedback" class (probably based on QObject). This class would get passed to the writers, and writers could call "setProgress" or "setFeedbackText" on the feedback object as required. The dialog would listen out to "progressChanged" or "feedbackChanged" from the feedback object and update the displayed progress when this occurs.

More work, but it's more future proof (ie something like this would also be needed for 3.0 if you want to port to task manager and have exports occur in the background)

**Comment by nyalldawson** [comment]
Good news is that https://github.com/tomchadwin/qgis2web/pull/435 implements this!
