### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#431]
Should some type of progress/status bar be included?  I was thinking some type of status and progress bar which would indicate which layer is being worked on and the current progress. Should it somehow be included in the preview window or a separate element somewhere else in the GUI?

**Comment by boesiii** [comment]
![new dialog with progress and text](https://cloud.githubusercontent.com/assets/2079638/23770723/3a5ba00e-04e2-11e7-8b3d-a9676c3ca73e.png)

**Comment by tomchadwin** [comment]
@nyalldawson discussed this. The reality is that it will be quite difficult to implement at the moment, but will become much easier with QGIS3. I suggest we therefore wait until we have updated the plugin for QGIS3, and then try to implement this then.

**Comment by nyalldawson** [comment]
https://github.com/tomchadwin/qgis2web/pull/435 will help here

**Comment by tomchadwin** [comment]
This is now merged into master. Many thanks once again to @nyalldawson, @pcav, and ENEL for the major contribution.
