### ISSUE TITLE
layer control icon gone for leaflet version

### ISSUE THREAD

**Issue by echoesinthestairwell** [tomchadwin/qgis2web#432]
hello,

the icon for layer control for the leaflet version of an export has disappeared. it was there earlier and i was able to produce webmaps with a functioning layer control. but now it is static and layers/legend is fully displayed. it does not revert to the icon upon mouseout. the icon is present on the openlayers export version of same map (but has no legend, which i desire).

i am using qgis 2.18.2 on mac and the latest version of the plugin (2.8.0) - although the problem appeared before i updated the plugin. when this problem appeared the plugin exhibited additional buggy behaviour, like producing an exported map with incomplete data (but with a functioning layer control icon!). i tried a workaround of coping a complete data file (from an exported map without a functioning layer control icon) but the search bars failed to recognize the new data (although it did display on the layers!).

the plugin worked flawlessly before. the buggy behaviour seems to have stopped, but no layer control icon for the leaflet version of the export.

thank you for all of the work on the plug in and thank you in advance for any help.

![screen shot 2017-03-11 at 1 35 41 pm](https://cloud.githubusercontent.com/assets/13191448/23827302/6a7d3412-0665-11e7-9aa6-ee8a56cdf6ca.png)
![screen shot 2017-03-11 at 1 35 30 pm](https://cloud.githubusercontent.com/assets/13191448/23827301/6a7bf156-0665-11e7-9836-4ff5702e95cb.png)

**Comment by tomchadwin** [comment]
I didn't think the layers list in Leaflet ever did collapse to an icon  on mouseout, did it? Is that what you mean?

**Comment by tomchadwin** [comment]
You've reminded me of how I should resolve this. I'll change the Add layers list checkbox to a drop down, with options None, collapsed, and expanded. That's if the OL plugin supports remaining open, @walkermatt?

**Comment by echoesinthestairwell** [comment]
thanks so much. and yes, on leaflet the layers list did collapse to an icon on mouseout.

**Comment by walkermatt** [comment]
@tomchadwin there was a PR along these lines a while back to ol3-layerswitcher. What behaviour would you ideally like for the "expanded" option, display the layer list by default and collapse to an icon on mouseout?

**Comment by tomchadwin** [comment]
No: initial full display, never collapse. Compare the qgis2web layer list output for OL to Leaflet. What do you think?

**Comment by walkermatt** [comment]
I think it's possible at the moment, all be it a little bit of a hack:

    // Create a LayerSwitcher instance and add it to the map
    var layerSwitcher = new ol.control.LayerSwitcher();
    map.addControl(layerSwitcher);

    // Override the hidePanel function so calls to hide
    // the panel will be ignored
    layerSwitcher.hidePanel = function() {};

    // Manually show the panel
    layerSwitcher.showPanel();

**Comment by tomchadwin** [comment]
Lovely - that does the trick perfectly. Thanks very much! I'll try to implement that now.

**Comment by tomchadwin** [comment]
OK, this all works, apart from one thing. @nyalldawson, I've changed the existing parameter `Appearance: Add layers list` from a boolean to a tuple. It's all working, apart from the initial value: it's coming up blank, instead of defaulting to the first option (None). I can't figure out how to fix this since the refactor.

**Comment by tomchadwin** [comment]
Regardless, the issue is cosmetic only, so can you test current master, @echoesinthestairwell, and let us know if everything is now working (apart from the initial blank dropdown)?

**Comment by tomchadwin** [comment]
OK, it's more specific than that, I think. The dropdown ends up (wrongly) blank if you open a project which already has the **boolean** Add layers list value saved to it.

**Comment by tomchadwin** [comment]
OK, I've stopped a drop-down from restoring a setting if the index of the saved value is -1 (ie the value does not exist in the dropdown list). I hope this works OK.

**Comment by echoesinthestairwell** [comment]
thanks for looking into this. has the updated plugin been put in the
official repository? i uninstall and reinstall the plugin but still no
restored layer icon for the leaflet version. (i downloaded the master but,
new to this, so couldn't discover where to put new/overwrite old. tried (on
mac osx) applications > qgis.app, ctrl+click 'show package contents',
contents > resources > plugins = nothing, contents > plugins = nothing.)

thank you again.

mahmood

**Comment by tomchadwin** [comment]
@echoesinthestairwell No, I've not released a new version with these fixes yet. However, I shall as soon as I can.

**Comment by tomchadwin** [comment]
@echoesinthestairwell But to try current master, do the following:

1. Download this repo's zip file (green button on the Github homepage)
2. Open the zip, open the folder `qgis2web-master`, and copy all its contents
3. Using Finder, open your home folder, and drill down to .qgis2/plugins/qgis2web
4. Paste the files you copied, overwriting everything
5. Restart QGIS 

Let us know how it goes.

**Comment by echoesinthestairwell** [comment]
thanks so much. it took me a moment to find those hidden .something files.
but i did. and it works beautifully now.

very best,
mahmood

**Comment by tomchadwin** [comment]
Really glad it's fixed. Thanks for testing and letting us know.

**Comment by ankbhargava** [comment]
Hi,

Thanks for all the great work on the QGIS2Web plugin. I have v3.16 for Mac and unable to see the Layers icon. Cant find out the root folder to replace the files downloaded from Github. Could use some help. Thanks in advance!
