### ISSUE TITLE
Leaflet web map error with layer list, label and measure

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#433]
I am getting an error in my resulting web map when the following criteria is used.

- Layer with label
- Imperial Measure Option
- Expanded Layer List Option

I am using master version and I also had this issue last week.

Below is the error displayed in Chrome developer tools
```
Uncaught TypeError: Cannot read property 'popupPane' of undefined
    at e.initialize (leaflet.draw.js:10)
    at new e (leaflet.js:5)
    at Object.o.tooltip (leaflet.js:7)
    at e.bindTooltip (leaflet.js:7)
    at pointToLayer (index.html:116)
    at Function.geometryToLayer (leaflet.js:8)
    at e.addData (leaflet.js:8)
    at e.addData (leaflet.js:8)
    at e.initialize (leaflet.js:8)
    at new e (leaflet.js:5)
```

To replicate simply add the airports layer, add a label based on the NAME field, export web map with EXPANDED LAYER LIST and IMPERIAL MEASURE

**Comment by tomchadwin** [comment]
Confirmed, but is the layers list a red herring? I think it fails with no layers list - ie just labels plus imperial measure. Do you confirm?

**Comment by tomchadwin** [comment]
Looks like it was an incompatibility because of an old Leaflet.draw version. I've updated the plugin. Can you test now and see if the problem is resolved? It seems to be for me.

**Comment by boesiii** [comment]
Works.
