### ISSUE TITLE
geolocation centered on the map

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#436]
I am looking for a way to keep the geolocation marker  on map instead of manually re center it while is tracking my position on mobile. Any help is appreciated.

**Comment by tomchadwin** [comment]
I don't think this is a common enough requirement for it to be included in the plugin. You'd have to edit the exported code. That said, if someone can take both a Leaflet and an OL export from qgis2web (as simple as possible as a map), and implement this in those exports, I can take a look at pulling it into the plugin.

I'll close for now, but do reopen if someone does manage to create such examples.
