### ISSUE TITLE
leaflet map not publishing on github pages, new master

### ISSUE THREAD

**Issue by echoesinthestairwell** [tomchadwin/qgis2web#438]
hello,

thank you again for all the work on the plugin. i'm seeing a behaviour after the recent update of the master that i think may be due to changes in the code (although it may be a github issue). its about how the maps render (or not) when published from github repositories as github pages. (it's the only way i have at the moment of publishing my maps.)

in an earlier version of the plugin, lines 9 and 30 of the html.index contained references to leaflet cdns for js and css at unpkg.com. the hrefs were http not https, so on github the map would not render, only the heading of the page. following advice here: http://stackoverflow.com/questions/38136637/leaflet-with-github-pages-not-rendering , i replaced the hrefs for the cdns for js and css with those found here: https://cdnjs.com/libraries/leaflet/ . now the map rendered beautifully. with one problem: the layer list no longer collapsed to icon on mouseout. which makes the map problematic for mobile use.

so i went back and exported a version of the map with the newish (as of 2017.03.13) master version of the plugin to see if it made a difference. i looked at line 9 and 30 of the index.html to see if i needed to replace the hrefs to the leaflet cdn for js and css with https links. however, those references were no longer in the head and body of the index.html. a search didn't turn them up anywhere in the index.html. so i uploaded the map to github and generated github page. only now i got a 404 error. even though it all looks good on github as far as the creation of the github page

. the same map renders fine in the browser when i click the local index.html file.

could this be due to recent changes in the code?

thank you again in advance.

![screen shot 2017-03-15 at 10 09 27 pm 2](https://cloud.githubusercontent.com/assets/13191448/23982681/283e8046-09cc-11e7-89ed-236bd46c5c13.png)
![screen shot 2017-03-15 at 10 08 10 pm 2](https://cloud.githubusercontent.com/assets/13191448/23982696/460630f6-09cc-11e7-8bd2-0456c1dd1799.png)

**Comment by tomchadwin** [comment]
Um, I can see the map at that address:

https://echoesinthestairwell.github.io/boycottmap3.8.0

**Comment by tomchadwin** [comment]
The only change you need to make is to alter the URL for font-awesome to `https` (line 9) - that should make the icon reappear. I'll close this issue - reopen if there's still a problem.

**Comment by tomchadwin** [comment]
Re: the Leaflet JS and CSS addresses

In the qgis2web dialog, the setting `Data export/Mapping library location' dictates whether Leaflet/OpenLayers is pulled in from a CDN, as your previous example was, or whether local copies of the files are included with the export. If you look at the file in question, you can see lines 9 and 29 link so `leaflet.css` and `leaflet.js`, but in local directories, rather than from the CDN. Hope that makes sense.

**Comment by echoesinthestairwell** [comment]
thanks tom, that points me in the right direction. it seems like the map not rendering was a browser issue, firefox downloading an update of itself and going sideways in all kind of unforeseen ways until it lets you know the update is ready to install, as it does.
