### ISSUE TITLE
Eliminate CDNs

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#439]
Users have the option to use a CDN for the mapping library. I am not convinced how useful this is, and I think, for the sake of simplification, this option should perhaps be removed, and the library always be shipped with the export. This should guarantee that maps work eg when offline, and also avoid http/https conflicts. It also simplifies the GUI.

There are also some ancillary elements which are pulled in from remote locations (font-awesome, perhaps other libs). These should all also be included locally, for the same reason.

Does anyone disagree?

**Comment by simonwiles** [comment]
can the http/https issue can be avoided by specifying the script `src` as:
`<script src="//cdnjs.cloudflare.com/ajax/libs/openlayers/4.0.1/ol.js"></script>`
??

**Comment by tomchadwin** [comment]
It breaks the preview, because the pseudo-protocol is file://, not http(s)://.

**Comment by kannes** [comment]
In support of this I also want to point out the benefit on user privacy by using local copies.

**Comment by tomchadwin** [comment]
@hannes Agreed, but it is only an option at the moment. You can already choose to use your own local copies. I'm asking if having the *option* to use the CDNs is worth having.

**Comment by boesiii** [comment]
I have always used local option so I don't think it is worth having.

**Comment by tomchadwin** [comment]
The reason to allow it is for cases where the user has severely limited storage, so having the libraries remote means less space is required for the map. However, I can;t imagine anyone is so tight for space that this is an issue. Using a CDN is also potentially slower, since an extra DNS lookup is required.

**Comment by boesiii** [comment]
What if you moved it to the settings section?

**Comment by tomchadwin** [comment]
Done in master
