### ISSUE TITLE
raster layer encode to json

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#44]
![raster_to_json](https://cloud.githubusercontent.com/assets/7377897/7569687/b1645204-f80a-11e4-8c87-8dd74684ffe7.png)
Is it common to save a raster file as JSON? Maybe deselect the encode to JSON option for raster

**Comment by tomchadwin** [comment]
Yes, I know this needs to be done. I couldn't do it before because of the issue fixed with https://github.com/tomchadwin/qgis2web/commit/fcdd8e17210ed44e12708d3a6b85185798b774c1. I'll try implementing it now, and see if it works.

**Comment by tomchadwin** [comment]
Fixed in master, and same fix applied to cluster code.
