### ISSUE TITLE
Crash with >1900 point features

### ISSUE THREAD

**Issue by franeque** [tomchadwin/qgis2web#441]
I am using latest version of the plugin (2.10.0) and loading a shapefile with 1946 points. When I use the "search" option previously selected when cooking the web result, it gets frozen I think while reading every feature, and then it does not respond anymore, even when it seems to get unfrozen. I think that the trouble is the search as you type function it runs. I also tried to paste an ID directly so it has not to search, but this is a known bug, does not search nor find anything. Please, try to fix it in any way to make it a greater plugin, I love this plugin as all other users.
Regards,

Frank

**Comment by pcav** [comment]
I have just tried with 10k points, and it does not crash

**Comment by tomchadwin** [comment]
The search facility is provided by plugins:

https://github.com/stefanocudini/leaflet-search

https://github.com/webgeodatavore/ol3-search-layer

I'm afraid I'd have to suggest you open tickets on those repos.
