### ISSUE TITLE
Error exporting to OL3

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#443]
Using master I get the following error when exporting.

```
File "C:/Users/eboesenberg/.qgis2/python/plugins\qgis2web\olLayerScripts.py", line 400, in layerToJavascript
layers = re.search(r"layers=(.*?)(?:&|$)", source).groups(0)[0]
NameError: global name 're' is not defined

```

**Comment by tomchadwin** [comment]
Fixed in master. Please test.

**Comment by boesiii** [comment]
New error

```
File "C:/Users/eboesenberg/.qgis2/python/plugins\qgis2web\olLayerScripts.py", line 406, in layerToJavascript
QCoreApplication.translate("QgsWmsProvider",
NameError: global name 'QCoreApplication' is not defined
```

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Fixed in master - please test.

**Comment by tomchadwin** [comment]
Many apologies for all of these import errors, @boesiii, and thanks so much for reporting each of them. They are all as a result of my refactoring work on #266, and nothing at all to do with the work @nyalldawson has been doing. Hopefully you've tracked down most of them, but it certainly exposes the gaps in the test coverage.

**Comment by boesiii** [comment]
Still same error.

**Comment by tomchadwin** [comment]
Apologies - failed to commit. Should be sorted now. Please test.

**Comment by boesiii** [comment]
Works!
