### ISSUE TITLE
WMS basemap doesn't work

### ISSUE THREAD

**Issue by ffierm** [tomchadwin/qgis2web#445]
Hi,
I'm trying to use a WMS basemap from:
http://geomap.reteunitaria.piemonte.it/WEBCAT/CAPABILITIES/wms_coto_ortofoto_1979.xml (EPSG 3003)
Qgis2Web doesn't preview anything and don't export this basemap (I'm using qgis 2.14.4, qgis2web 2.10.0, win10, x64).

Any suggestion?

Thanks in advance,
Francesco.

**Comment by tomchadwin** [comment]
Make sure your project is in the same projection, and make sure you check "Match project CRS" in qgis2web. If that doesn't work, we'll have to ask for some more information to investigate.

**Comment by ffierm** [comment]
Hi, 
I've tried to use EPSG 32632 (both PROJECT, LAYER) + "Match project CRS" and EPSG 3003 (both PROJECT, LAYER)+ "Match project CRS". No good news. In the qgis2web preview box the page is blank but is displayed the layer name. This is the index.html:
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <link rel="stylesheet" href="css/leaflet.css" /><link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"><link rel="stylesheet" href="css/L.Control.Locate.min.css" />
        <link rel="stylesheet" type="text/css" href="css/qgis2web.css">
        <link rel="stylesheet" href="css/MarkerCluster.css" />
        <link rel="stylesheet" href="css/MarkerCluster.Default.css" />
        <style>
        #map {
            width: 1568px;
            height: 886px;
        }
        </style>
        <title></title>
    </head>
    <body>
        <div id="map">
        </div>
        <script src="js/qgis2web_expressions.js"></script>
        <script src="js/leaflet.js"></script><script src="js/L.Control.Locate.min.js"></script>
        <script src="js/leaflet-heat.js"></script>
        <script src="js/leaflet.rotatedMarker.js"></script>
        <script src="js/OSMBuildings-Leaflet.js"></script>
        <script src="js/leaflet-hash.js"></script>
        <script src="js/leaflet-tilelayer-wmts.js"></script>
        <script src="js/Autolinker.min.js"></script>
        <script src="js/proj4.js"></script>
        <script src="js/proj4leaflet.js"></script>
        <script src="js/leaflet.markercluster.js"></script>
        <script>
        var crs = new L.Proj.CRS('EPSG:3003', '+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs', {
            resolutions: [2800, 1400, 700, 350, 175, 84, 42, 21, 11.2, 5.6, 2.8, 1.4, 0.7, 0.35, 0.14, 0.07],
        });
        L.ImageOverlay.include({
            getBounds: function () {
                return this._bounds;
            }
        });
        var map = L.map('map', {
            crs: crs,
            continuousWorld: false,
            worldCopyJump: false, 
            zoomControl:true, maxZoom:28, minZoom:1
        })
        var hash = new L.Hash(map);
        map.attributionControl.addAttribution('<a href="https://github.com/tomchadwin/qgis2web" target="_blank">qgis2web</a>');
        L.control.locate().addTo(map);
        var bounds_group = new L.featureGroup([]);
        function setBounds() {
            if (bounds_group.getLayers().length) {
                map.fitBounds(bounds_group.getBounds());
            }
            map.setMaxBounds(map.getBounds());
        }
        function geoJson2heat(geojson, weight) {
          return geojson.features.map(function(feature) {
            return [
              feature.geometry.coordinates[1],
              feature.geometry.coordinates[0],
              feature.properties[weight]
            ];
          });
        }
            var overlay_Ortofoto1979ComunediTorino0 = L.tileLayer.wms('http://geomap.reteunitaria.piemonte.it/WEBCAT/CAPABILITIES/wms_coto_ortofoto_1979.xml', {
                layers: 'coto_ortofoto_1979',
                format: 'image/png',
                uppercase: true,
                transparent: true,
                continuousWorld : true,
                opacity: 1.0
            });
        map.addLayer(overlay_Ortofoto1979ComunediTorino0);
        var baseMaps = {};
        L.control.layers(baseMaps,{"Ortofoto 1979 Comune di Torino": overlay_Ortofoto1979ComunediTorino0,},{collapsed:false}).addTo(map);
        setBounds();
        </script>
    </body>
</html>

**Comment by tomchadwin** [comment]
I don't know what is stopping this from working. What software is the WMS - I see Map Proxy mentioned? The WMS support in qgis2web has only really been tested in Geoserver. Can anyone else help?

**Comment by enzogis** [comment]
Hi,
for that service , the url for GetMap request is different from that of Capabilities

if you read capabilities from [http://geomap.reteunitaria.piemonte.it/WEBCAT/CAPABILITIES/wms_coto_ortofoto_1979.xml](http://geomap.reteunitaria.piemonte.it/WEBCAT/CAPABILITIES/wms_coto_ortofoto_1979.xml)

you could see that the url defined for GetMap request is:
http://geomap.reteunitaria.piemonte.it/mapproxy/service?

The generated code from qgis2web has the first url string for the layer:
now I don't know if it is a misconfiguration of [MapProxy](https://mapproxy.org/) or a bug or an additional feature to develop ...

A workaround is to substitude by hand the url for the layer

In case of OpenLayers , replace url string in layers.js :

```
var lyr_Ortofoto1979ComunediTorino0 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "http://geomap.reteunitaria.piemonte.it/mapproxy/service?",
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
                              params: {
                                "LAYERS": "coto_ortofoto_1979",
                                "VERSION": "1.3.0"},
                            })),
                            title: "Ortofoto 1979 Comune di Torino",
                            opacity: 0.5,
                          });


```
In case of Leaflet, replace url string in index.html
```
            var overlay_Ortofoto1979ComunediTorino0 = L.tileLayer.wms('http://geomap.reteunitaria.piemonte.it/mapproxy/service?', {
                layers: 'coto_ortofoto_1979',
                format: 'image/png',
                uppercase: true,
                transparent: true,
                continuousWorld : true,
                opacity: 1.0
            });

```

If i'm not wrong, hope that this helps!

**Comment by tomchadwin** [comment]
@enzogis That is incredibly useful. Thank you! Now we just need to figure out how to get the other URL from the QGIS API.

**Comment by ffierm** [comment]
@tomchadwin, @enzogis:  Thanks a lot for the suggestions and for the (great and useful) workaround. These super tips  are showing (another time) the power of (Free and  Libre) Open Source Software

**Comment by tomchadwin** [comment]
OK, there's a slightly better way to achieve this - no code editing required - but it's still not perfect.

Instead of connecting to the WMS address you used, connect directly to http://geomap.reteunitaria.piemonte.it/mapproxy/service?. Your layer is listed there, and you can sdd that to QGIS. That then seems to export fine.

It's not a perfect solution because:

1. I get a QGIS warning - Returned legend image is flawed
2. I don't know how easy it would be for users to figure out the second URL themselves if they had this same issue

**Comment by tomchadwin** [comment]
I'll close this for now. It would be good to know if the workaround worked, so do let us know.

**Comment by ffierm** [comment]
Yes, the workaround works great (thanks to @enzogis for the detailed suggestions).
Thank to @tomchadwin for GIS2WEB (really a great plugin)
