### ISSUE TITLE
OpenLayers preview not showing

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#447]
leaflet shows OK, OL throws an error:
===
```
qgis2web produced an error:

Traceback (most recent call last):
File "/home/paolo/.qgis2/python/plugins/qgis2web/maindialog.py", line
305, in previewMap
preview_file = self.createPreview()
File "/home/paolo/.qgis2/python/plugins/qgis2web/maindialog.py", line
267, in createPreview
dest_folder=utils.tempFolder()).index_file
File "/home/paolo/.qgis2/python/plugins/qgis2web/olwriter.py", line 89,
in write
folder=dest_folder)
File "/home/paolo/.qgis2/python/plugins/qgis2web/olwriter.py", line 125,
in writeOL
exportStyles(layers, folder, clustered)
File "/home/paolo/.qgis2/python/plugins/qgis2web/olStyleScripts.py",
line 38, in exportStyles
name = compile_to_file(fieldName, "label_%s" % sln,
NameError: global name 'compile_to_file' is not defined

```

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Fix committed to master - please test.

**Comment by pcav** [comment]
Checked, no error now, but still OL preview is not shown.
Thanks.

**Comment by tomchadwin** [comment]
Not as a result of the Settings tab checkbox being checked?

**Comment by pcav** [comment]
Not, this is unchecked.

**Comment by tomchadwin** [comment]
Can you export and open in browser, F12 > Console. Any errors? Perhaps zip and upload the whole export?

**Comment by tomchadwin** [comment]
I also found another missing import, so do please try master now and see if it comes back to life. Alternatively, if this is data you can get to me, I'll try to recreate.

**Comment by pcav** [comment]
Confirmed in master. I do not see errors in browser. Output attached.
[qgis2web_2017_03_25-09_42_28_979043.zip](https://github.com/tomchadwin/qgis2web/files/869871/qgis2web_2017_03_25-09_42_28_979043.zip)

**Comment by tomchadwin** [comment]
I'll take a look at it this morning. Can you check the QGIS qgis2web log as well?

**Comment by pcav** [comment]
OK, probably got it:

```
2017-03-25T10:34:22	2	Traceback (most recent call last):
			  File "/home/paolo/.qgis2/python/plugins/qgis2web/olStyleScripts.py", line 73, in exportStyles
			    layer_alpha)
			  File "/home/paolo/.qgis2/python/plugins/qgis2web/olStyleScripts.py", line 283, in getSymbolAsStyle
			    svg = xml.etree.ElementTree.parse(sl.path()).getroot()
			NameError: global name 'xml' is not defined
```

**Comment by tomchadwin** [comment]
Ah, great. Easily fixable. Give me an hour or two. Apologies for all of these import errors. It really shows up the gaps in the test suite.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by pcav** [comment]
Tested:
```
			  File "/home/paolo/.qgis2/python/plugins/qgis2web/olStyleScripts.py", line 74, in exportStyles
			    layer_alpha)
			  File "/home/paolo/.qgis2/python/plugins/qgis2web/olStyleScripts.py", line 286, in getSymbolAsStyle
			    svgWidth = re.sub("px", "", svgWidth)
			NameError: global name 're' is not defined
```

**Comment by tomchadwin** [comment]
Confirmed. More missing imports, and categorization on nulls failing. Fixed now in master - please test.

**Comment by pcav** [comment]
Checked: no more errors in the log, but still no preview.

**Comment by tomchadwin** [comment]
Export, check browser console (F12 foe dev tools).

**Comment by pcav** [comment]
I cannot see anything obvious.

**Comment by tomchadwin** [comment]
If there's nothing in:

- QGIS qgis2web log
- browser console
- QGIS Python console (unlikely)

then upload your export. If still nothing is apparent, I'll have to get access to your project and data.

Usual questions:

- no scale-based visibility preventing things from showing up
- any possible CRS issues

**Comment by pcav** [comment]
I can't see anything in the above. No scale-dependent visibility, all layers in EPSG:3857
Attached my export.
[qgis2web_2017_03_25-16_10_23_146280.zip](https://github.com/tomchadwin/qgis2web/files/870125/qgis2web_2017_03_25-16_10_23_146280.zip)
I can send you project & data if you wish.

**Comment by tomchadwin** [comment]
Ah, there is an error. It looks as though this expression you use:

```
Itinerario || '-' || year(inizio) || '\n ' || boat
```

is not escaping the newline `\n`. That is resulting in a JS newline which causes a syntax error. Let me look into it.

cc @NathanW2

**Comment by tomchadwin** [comment]
Fixed in master. Please test.

**Comment by pcav** [comment]
Fine, works now.
Thanks.
