### ISSUE TITLE
"Preview on startup" resets every time the plugin is launched

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#448]
The state of the checkbox "Preview on startup" is always reset to unchecked when closing the popup (state is not saved)

**Comment by tomchadwin** [comment]
Cannot recreate. The checkbox retains its state through a QGIS restart for me.

To clarify: this setting is not saved to your project, but as an application-wide setting. Can you definitely confirm that he following fails:

1. Open QGIS
2. Open some data
3. Start qgis2web
4. Change the state of the "Preview on startup" checkbox
5. Close qgis2web
6. Restart QGIS
7. Open some data
8. Start qgis2web

Does the state of the checkbox persist?

**Comment by tomchadwin** [comment]
Please try the following:

1. Open QGIS Python console

2. `from PyQt4.QtCore import QSettings`

3. `QSettings().remove("qgis2web/previewOnStartup")`

Then see if the state of the Preview on startup checkbox behaves.

**Comment by pcav** [comment]
Following the instructions the setting behaves as expected (it is not reset to null, state is remembered).

**Comment by tomchadwin** [comment]
OK. Thanks. Not sure how that saved setting ended up in an unsavable state. Glad it's fixed.

**Comment by pcav** [comment]
You mean, it's fixed in a next version? Without `QSettings().remove("qgis2web/previewOnStartup")` it still behaves improperly.

**Comment by tomchadwin** [comment]
I mean I don't think many others will encounter this problem. I'd they do, I'll reopen and investigate further, perhaps by querying the data type of that saved setting.

**Comment by pcav** [comment]
OK, thanks.

**Comment by ignaciodt** [comment]
I had the same issue, fixed with instructions.

**Comment by Jeroen-GroeneBij** [comment]
I have the same issue, using qgis2web 3.4.0
I have not tried the manual fix yet.
