### ISSUE TITLE
Close feedback dialog on success

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#450]
I strongly think we need to close the feedback dialog automatically when the operation it is feeding back on successfully completes. Perhaps we can add a second's pause. At the moment, I don't like the extra click required to clear it. On failure, it should remain open.

**Comment by boesiii** [comment]
I kind of like seeing the feedback although it is an extra click.

**Comment by tomchadwin** [comment]
OK. I guess I could make it a Settings tab option?

**Comment by boesiii** [comment]
That settings tab is kind of lonely!

**Comment by tomchadwin** [comment]
Ha, you spotted my ulterior motive!

**Comment by tomchadwin** [comment]
Implemented. Settings option possibly to follow.
