### ISSUE TITLE
No preview and non visible export after Simplify

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#452]
Hello,

After using Simplify (Vector - Geometrytools), the qgis2web plugin does not show a preview in OL and reports an error in Leaflet.
The export in OL does produce the expected folders and files, but the index.html does not show anything in Firefox. F12 webconsole says:

```SyntaxError: invalid switch statement  Gem_2016_AW_Klein0_style.js:4
ReferenceError: style_Gem_2016_AW_Klein0 is not defined
```

Below is the error message from qgis2web Leaflet:
qgis2web produced an error:

```
Traceback (most recent call last):
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\maindialog.py", line 305, in previewMap
preview_file = self.createPreview()
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\maindialog.py", line 267, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 98, in write
folder=dest_folder)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 243, in writeLeaflet
extent)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 317, in writeVectorLayer
outputProjectFileName)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletStyleScripts.py", line 41, in getLayerStyle
case '%s':""" % cat.value().replace("'", "\\'")
AttributeError: 'QPyNullVariant' object has no attribute 'replace'
```

The same things happens when I use www.mapshaper.org to simplify the shapefile.

I am using Simplify to reduce the original shapefile filesize, so the web map file is effectively about 5MB or preferably less (the layer file size of the webmap is often 3 to 4 times the size of the shapefile).

Details:
Qgis version 2.14
Qgis2web version 2.12.0

**Comment by tomchadwin** [comment]
If you are happy editing some code in a text editor, can you try the following:

1. From the plugin folder, open leafletStyleScripts.py in a text editor
2. Replace line 41 with the following:
```python
            if not cat.value is None and cat.value() != "":
```
3. Restart QGIS

Then try your Simplified dataset again and see if it works.

**Comment by tomchadwin** [comment]
Ah, wait. Is it possible that Simplify has altered your field names or contents? If so, do you need to update your categorized style to reflect the new values. Could that be it?

**Comment by Jeroen-GroeneBij** [comment]
I am not that good at editing: error message at loading the plugin :)

What exactly should I change? Below is line 39 up to 48
```
if cat.value() != "":
                style += """
                case '%s':""" % cat.value().replace("'", "\\'")
            else:
                style += """
                default:"""
            style += """
                    return %s
                    break;""" % styleCode
        style += """`
```

I apply the categorized styles after simplifying, so it is probably not about altered field names or content?

**Comment by tomchadwin** [comment]
Make sure the indentation remains the same after your editing. The line you should be changing is:

```python
            if cat.value() != "":
```

You should change it to:

```python
            if not cat.value is None and cat.value() != "":
```

As I say, keep the indentation the same.

**Comment by tomchadwin** [comment]
If there is still an error, paste it here. By the way, welcome to Github! Your bug report was very usefully detailed and comprehensive - much appreciated.

**Comment by Jeroen-GroeneBij** [comment]
Thanks for the welcome

Editing went good.
However, still no preview in OL and an error-code in Leaflet

```
qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\maindialog.py", line 305, in previewMap
preview_file = self.createPreview()
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\maindialog.py", line 267, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 98, in write
folder=dest_folder)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 243, in writeLeaflet
extent)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 317, in writeVectorLayer
outputProjectFileName)
File "C:/Users/Jeroen/.qgis2/python/plugins\qgis2web\leafletStyleScripts.py", line 41, in getLayerStyle
case '%s':""" % cat.value().replace("'", "\\'")
AttributeError: 'QPyNullVariant' object has no attribute 'replace'
```

**Comment by tomchadwin** [comment]
Did you restart QGIS after making that change to the script?

**Comment by Jeroen-GroeneBij** [comment]
Yes I did restart Qgis.

Meanwhile I have made some progress using the unmodified plugin.
Trying to replicate the problem with minimal changes I found that:
- Open a vector layer (.shp) and the plugin works fine.
- Changing the Vector Layer Properties Style > to Categorized rendering, with an original attribute and the plugin works fine.
- Changing the Vector Layer Properties Style > Categorized rendering with an added attribute and the plug shows the mentioned behaviour (maybe something to do with the way I added it).
- Saving the work as a Qgis project doesn't immediately help, however...
- Closing and reopening the newly saved project (without even closing Qgis) and the plugin works fine again...

This applies both to 'simplified' and 'non-simplified' shapefiles.

So I think it has something to do with me adding an attribute and then Qgis repairing some mistake on opening the saved project.

**Comment by tomchadwin** [comment]
You mean adding an attribute/field/column to a layer? If so, are you saving the layer as well as the project? That said, you shouldn't have to save. I'll see if I can recreate.

**Comment by tomchadwin** [comment]
OK, I've recreated this issue - thanks for discovering it. Looking into it now.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.
