### ISSUE TITLE
Move Layer options Visible and Cluster high in the list

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#456]
If you have a layer with many attributes, the Visible and Cluster check boxes can get buried.  Should they be moved above the popup fields?

**Comment by tomchadwin** [comment]
Agreed - an excellent suggestion. I'll look at it soon. In time, the cluster option will be removed, but only once QGIS3 is LTD. I'm considering getting rid of the visible option as well, using each layer's overall checkbox for visibility.

**Comment by tomchadwin** [comment]
Done in master. Please test.
