### ISSUE TITLE
<html_exp> attribute no longer works with leaflet

### ISSUE THREAD

**Issue by shanmugamg** [tomchadwin/qgis2web#459]
I was creating nice popup's with <html_exp> as an attribute with leaflet. It worked quite well with qgis2web version 2.10.0. (QGIS 2.18.4)

Today upgraded my QGIS to 2.18.5 and qgis2web to 2.13.0. The <htm_exp> no longer works as expected.
I reverted back to qgis2web version 2.10 and it works well.

I assume, the extensive code refactoring from 2.10 to 2.13 created some issues. Hope this can be fixed.

with 2.10.0
![image](https://cloud.githubusercontent.com/assets/5705862/24488355/d6e54030-1548-11e7-8e13-f9f8701d6ebb.png)

with 2.13.0
![image](https://cloud.githubusercontent.com/assets/5705862/24488635/c3b27a80-154a-11e7-9b53-0fd2209ac558.png)

**Comment by tomchadwin** [comment]
No, it's no longer supported. You can achieve that popup layout (or very near to it) like this:

1. Set the edit widget of each field you don't want to appear to Hidden. 

2. Set the field with the picture to an Image edit widget

3. Set an alias of "Tel: " for the phone number field

4. In qgis2web, set all of the popup field headers to "none", apart from the phone field, which you should set to Inline

You can then anyways edit the output to tweak the result to add your colours and text sizes back in.
