### ISSUE TITLE
Exported maps is without images.

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#460]
Probably bug in images export. Tiff should be exported as PNG in /data folder, but no PNG there...

**Comment by tomchadwin** [comment]
Any messages in the qgis2web log?

**Comment by kelv-cz** [comment]
2017-03-31T10:43:09	1	Unable to execute algorithm
			Wrong parameter value: c:\users\galileo\appdata\local\temp\example01490949788_piped_3857.tif
2017-03-31T10:43:16	0	GDAL execution console output
			ERROR 1: Translating source or target SRS failed:
			
			USER:100001
			
			Usage: gdalwarp [--help-general] [--formats]
			
			    [-s_srs srs_def] [-t_srs srs_def] [-to "NAME=VALUE"]
			
			    [-order n | -tps | -rpc | -geoloc] [-et err_threshold]
			
			    [-refine_gcps tolerance [minimum_gcps]]
			
			    [-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height]
			
			    [-ovr level|AUTO|AUTO-n|NONE] [-wo "NAME=VALUE"] [-ot Byte/Int16/...] [-wt Byte/Int16]
			
			    [-srcnodata "value [value...]"] [-dstnodata "value [value...]"] -dstalpha
			
			    [-r resampling_method] [-wm memory_in_mb] [-multi] [-q]
			
			    [-cutline datasource] [-cl layer] [-cwhere expression]
			
			    [-csql statement] [-cblend dist_in_pixels] [-crop_to_cutline]
			
			    [-of format] [-co "NAME=VALUE"]* [-overwrite]
			
			    [-nomd] [-cvmd meta_conflict_value] [-setci] [-oo NAME=VALUE]*
			
			    [-doo NAME=VALUE]*
			
			    srcfile* dstfile
			
			
			
			Available resampling methods:
			
			    near (default), bilinear, cubic, cubicspline, lanczos, average, mode,  max, min, med, Q1, Q3.
			
2017-03-31T10:43:16	1	Unable to execute algorithm
			Wrong parameter value: c:\users\galileo\appdata\local\temp\example01490949795_piped_3857.tif

**Comment by tomchadwin** [comment]
Would you mind adding this information to https://github.com/tomchadwin/qgis2web/issues/148? It's the same issue - different GDAL versions needing different param lists.

**Comment by tomchadwin** [comment]
@kelv-cz #148 seems now to be fixed, so it would be great to hear whether it has solved the bug for you as well.
