### ISSUE TITLE
GeoServer WFS Error

### ISSUE THREAD

**Issue by piersonj** [tomchadwin/qgis2web#461]
First, thank you for all the work you, and your collaborators, have put into this plugin.  I have been trying to use GeoServer WFS in QGIS and qgis2web trying to to export an OpenLayers project.  
QGIS: 2.18.3
qgis2web: 2.14.0
GeoServer: 2.10.2
Ubuntu Server (GeoServer): 16.04
Tomcat: 8

Data: GeoServer demo: tasmania_water_bodies, tasmania_state_boundaries, tasmania_roads, tasmania_cities
The WFS layers load into QGIS, but not into qgis2web preview or export.
qgis2web & Chrome consoles: "SyntaxError: Parse error" that points to the WFS url. 
CORS enabled on Tomcat8, JSONP enabled on GeoServer

Thank you very much for all your work and any help.

![image](https://cloud.githubusercontent.com/assets/26822132/24560214/0f002d20-15ff-11e7-8ce2-36332d826afe.png)
![image](https://cloud.githubusercontent.com/assets/26822132/24560234/2778d5f0-15ff-11e7-8be0-e429dc335116.png)
[qgis2web_2017_03_31-10_44_56_747000.zip](https://github.com/tomchadwin/qgis2web/files/886377/qgis2web_2017_03_31-10_44_56_747000.zip)

**Comment by tomchadwin** [comment]
Thanks for the kind words - much appreciated. This will be a little tricky to debug. The address of your Geoserver instance is not reachable by us out here:

```
http://http://postgis:8080/geoserver
```

That http address is one local to the internal network on which the Geoserver sits. Is that server - `postgis` - accessible externally, and, if so, what is its public address?

**Comment by piersonj** [comment]
Unfortunately just the internal network.  This is why I've been testing what I can do with the GeoServer demo data before really getting things rolling.  I am very new to working with coding at all, but the only thing I noticed were differences in the url found in the index.html:

_http://postgis:8080/geoserver/topp/ows??SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=topp:tasmania_water_bodies&SRSNAME=EPSG:4326&outputFormat=text%2Fjavascript&format_options=callback%3Agettopptasmania_water_bodies1Json_

and the url in the GeoServer GeoJSON preview:

_http://postgis:8080/geoserver/topp/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=topp:tasmania_water_bodies&maxFeatures=50&outputFormat=text%2Fjavascript_

with both of those compared to the url that I used while testing a standalone app (ignoring the bbox):

_http://postgis:8080/geoserver/topp/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=topp:tasmania_water_bodies&maxFeatures=50&outputFormat=application/json&srsname=EPSG:4326&bbox=' + extent.join(',') + ',EPSG:4326_

I don't even know where to begin to make my GeoServer publicly available, but if you know of a publicly available WFS I could test, I would greatly appreciate it.

**Comment by tomchadwin** [comment]
What happens if you paste the generated WFS URL directly into a browser? I think the error you are seeing is because the map fails to handle a Geoserver error XML message. We need to see what that error is.

**Comment by tomchadwin** [comment]
The testing Geoserver I currently use is:

http://balleter.nationalparks.gov.uk/geoserver/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=dnpa_inspire:con_areas&SRSNAME=EPSG:27700

**Comment by piersonj** [comment]
I tested the wfs you linked above and it worked.  Attached is a text file with the url created by qgis2web, the xml response in Chrome and the qgisw2web console error.  I truly appreciate all the help with this, it is great to have this kind of help when I'm really an analyst and not a developer my any means.
[qgis2web_xml_response.txt](https://github.com/tomchadwin/qgis2web/files/891377/qgis2web_xml_response.txt)

**Comment by tomchadwin** [comment]
In Geoserver, is your layer available in EPSG:4326? If not, try enabling that and retry qgis2web.

**Comment by tomchadwin** [comment]
Any progress on this issue?

**Comment by piersonj** [comment]
I finally got it all working to display WFS layers.  I had to change the declared SRS and then tell GeoServer to project from native to declared. Thank you very much for your help, I really appreciate it.

Justin

**Comment by tomchadwin** [comment]
Ah, really glad you got it sorted.
