### ISSUE TITLE
Unwanted/inexistant export save path on linux "C:\....

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#463]
Versione installata: 2.14.0 (in /home/ubuntu/.qgis2/python/plugins/qgis2web)
Versione disponibile: 2.14.0 (in Repository plugin ufficiale QGIS)

Hi Tom, 
default save (and preview) path was perfect before, 
the system temporary "/tmp/" directory was detected from python sys function...
Now there is an issue with default save path....
Please verify if path exist and if not please made the default path to system temp 

I get a default save path into my home workdir:
```
C:\Users\MARCOB~1.URB\AppData\Local\Temp\qgis2web

so i get this path 

/home/ubuntu/C:\Users\MARCOB~1.URB\AppData\Local\Temp\qgis2web
```
Hei i'm on linux here i don't want to go back to windows

Below the log of qgis2web export window:
```
Creating OpenLayers map...
Exporting libraries... done
...
Exporting... done
Writing HTML... done
Success
Exported to C:\Users\MARCOB~1.URB\AppData\Local\Temp\qgis2web
```
Thank and best regards 
Marco

**Comment by tomchadwin** [comment]
I didn't realize @nyalldawson was a Windows fan. I'll look into it.

**Comment by tomchadwin** [comment]
I can't see where this could have come from in the code. Is it possible that the project was saved on a Windows machine at some stage? That would have saved the selected output folder to the project.

**Comment by marcobra** [comment]
Yes is a project coming from windows...

**Comment by tomchadwin** [comment]
That's the explanation. The export folder location is saved to the project. I'm not sure there's a solution to instances where a project is shared between OSes. Closing for now.
