### ISSUE TITLE
Export OL3: linestyles no offset, no meter units

### ISSUE THREAD

**Issue by Jorishin** [tomchadwin/qgis2web#464]
When exporting, my line styles go wrong in multiple ways:
1) to simulate a single sided buffer, I apply the style: 6 meters buffer with a 3 meter offset.
result: the offset is not taken into account at export, and the buffer is interpreted in pixels, not in meters. They change while zooming.

Exporting with Leaflet takes only 1 symbol layer into account, but that is a documented issue.

![schermafbeelding 2017-04-02 om 17 47 26](https://cloud.githubusercontent.com/assets/12510749/24588656/c270ee70-17cc-11e7-8fee-e544e0cedcf8.png)

**Comment by tomchadwin** [comment]
I'm afraid I'm not familiar enough with QGIS's style options to know exactly what your settings are as they are in Dutch. The units issue is already noted: #144.

**Comment by Jorishin** [comment]
The line consists of 2 symbol layers: one plain, one (the one in the screengrab) : Thinkness of 6 meters ("map units”), offset of -3 meters (“map units)

**Comment by tomchadwin** [comment]
I've checked the API reference docs for both Leaflet and OL, and I don't think either support an offset for lines, so I'm afraid this probably isn't going to work. Apologies - will close the issue as a `wontfix`, but purely because I don't think it's possible.

**Comment by Jorishin** [comment]
OK, thanks for al the good work you do anyway!
I have a workaround: create  a separate layer with a one sided buffer 

Joris

**Comment by tomchadwin** [comment]
Pleased you found a solution. Thanks for letting us know.
