### ISSUE TITLE
Points cluster - Objects

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#470]
When I cluster points if I click on a point is recognized as an object.
![pointclusterobject](https://cloud.githubusercontent.com/assets/25204391/24869594/b918b248-1de1-11e7-8042-2dac1dfe9d63.png)
Without cluster selected I get labels.
![pointnoclusterlabel](https://cloud.githubusercontent.com/assets/25204391/24869644/e427417a-1de1-11e7-8357-6d390253fed9.png)

**Comment by tomchadwin** [comment]
Acknowledged. I don't think I have a solution with the current cluster code. If we could replace it with a proper plugin, we could maybe solve this issue.

**Comment by tomchadwin** [comment]
I also meant to say that the popups work when you zoom in pat where the points are clustered, I think?

**Comment by Sortronic** [comment]
No, unfortunately....
![pointcluster](https://cloud.githubusercontent.com/assets/25204391/24912574/8aa41e0a-1e9c-11e7-82e7-a056cbb4e822.png)

**Comment by tomchadwin** [comment]
Since I think the solution to this is #333, I'll close this.
