### ISSUE TITLE
OL3 - with selected line Style lost

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#471]
Maybe is part of known issues but I think it would be good to know how to change behavior of selected items, specially for lines, like keeping style modifying size and color.
![selecteditemloststyle](https://cloud.githubusercontent.com/assets/25204391/24869887/9ffbeff4-1de2-11e7-8e90-d6997e78bf4c.png)

**Comment by tomchadwin** [comment]
I'm not sure I fully understand. Are you talking about the Highlight on hover option? If so, the highlight style used is a fill using the colour set in QGIS project properties as "Selection colour". What do you think needs to be changed?

**Comment by Sortronic** [comment]
Is not highlight on hover, what you see on the picture is the result of search layer zoom in.
 What I am looking for is having a thicker line, on mobile devices is very hard to tap on the line and trigger the popup window, but as you see the layer selected is rendered with a very thin line. I have tried to see inside the map's files but I couldn't find any reference to these settings. 
I have looked in QGIS and I think OL3 overrides the setting in QGIS since is set to purple color but the map it renders light blue with a thin line.

This is the map:

![notselected](https://cloud.githubusercontent.com/assets/25204391/24914721/12aad1bc-1ea3-11e7-8823-035db72ac0bd.png)

In QGIS if I select the line, well the color is purple, and it's ok, but the size is kept:

![qgisselected](https://cloud.githubusercontent.com/assets/25204391/24914800/53d82306-1ea3-11e7-972f-35f30db62eff.png)

the OL3 map instead renders a thin line:

![selected](https://cloud.githubusercontent.com/assets/25204391/24914845/74e9ed7c-1ea3-11e7-9cbb-f5d16a1e43e1.png)

**Comment by tomchadwin** [comment]
To clarify, are you specifically talking about the highlight style used for layer search results?

**Comment by Sortronic** [comment]
Correct

**Comment by tomchadwin** [comment]
Isn't this the same issue as #465?

**Comment by Sortronic** [comment]
Maybe, in this case I am pointing out the style issue that I didn't realize at #465.
But yeah, I think they all gravitate around the same issue.

**Comment by tomchadwin** [comment]
I'm afraid I'll have to give the same advice - all on the OL layer search plugin's repo. Sorry.
