### ISSUE TITLE
Clustering option doesn't work if "Layer search" is activated

### ISSUE THREAD

**Issue by ffierm** [tomchadwin/qgis2web#473]
Hi,
in the latest version of QGIS+QGIS2WEB, the clustering option doesn't works if I choose, in Layers and Groups frame, the option "Cluster". I'm using qgis 2.18.6, qgis2web version: 2.16.0, windows 10
Thanks in advance.
Ciao,
Francesco.

**Comment by tomchadwin** [comment]
1. Are you talking about Leaflet exports?
2. I think Leaflet clusters are broken even if you don't set Layer search. It shows both cluster and unclustered points. Is that what you are seeing?

**Comment by tomchadwin** [comment]
Possibly related to #472

**Comment by tomchadwin** [comment]
No, after a fix for #472, I can now reproduce this issue, definitely triggered by Layer search. Investigating.

**Comment by ffierm** [comment]
Hi Tom, Thanks a lot for having correct the title... 

1.
Yes, even if we are talking about the "Leaftlet export"  the problem exists in the preview also. If I switch from "Leaflet" to "Openlayer", qgis2web produce an error (maybe related to #472 ):

2.
If we use Leaflet, clustering works fine without using "Layer search".


ERROR
Traceback (most recent call last):
File "C:/Users/d018631/.qgis2/python/plugins\qgis2web\maindialog.py", line 313, in previewMap
preview_file = self.createPreview()
File "C:/Users/d018631/.qgis2/python/plugins\qgis2web\maindialog.py", line 275, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/d018631/.qgis2/python/plugins\qgis2web\olwriter.py", line 86, in write
folder=dest_folder)
File "C:/Users/d018631/.qgis2/python/plugins\qgis2web\olwriter.py", line 279, in writeOL
f.write(templateOutput)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 2077: ordinal not in range(128)

**Comment by tomchadwin** [comment]
OK, can you try Leaflet now - I've committed a possible fix to master. I'll look at OpenLayers now.

**Comment by tomchadwin** [comment]
OpenLayers issue looks different - a character-encoding issue, and could be the same or related to #454. Are you able to share your layer? I'll close this issue for now,

**Comment by ffierm** [comment]
In effect, we have to manage a list of names coming from different countries... (Lleó, Škvarková, Staroveški...)

**Comment by tomchadwin** [comment]
Names of what? Layers? Fields? Values in fields?

I've handled international characters in many place in the plugin, but plainly there are still places where it fails. I do need actual examples so I can recreate the issue, or it is very difficult, if not impossible, to find which part of the code is failing to handle the non-ASCII characters.

**Comment by ffierm** [comment]
Values in fields... (sorry)

**Comment by tomchadwin** [comment]
Thanks - just what I need. However, I still can't recreate the issue. Here's what I've done:

1. Opened QGIS
2. Opened the layer `airports.shp` (from the qgis2web plugin folder, `test/data/layer`)
3. Changed the value of the `Name` field for feature ID 1 from NOATAK to Škvarková
4. Started qgis2web - no error with either OpenLayers or Leaflet
5. Changed the qgis2web `Layer search` to airports:NAME
6. Still no error

So there must be something else which differs between your setup and mine. Any ideas what that could be?

**Comment by tomchadwin** [comment]
OK, I've fixed an encoding/decoding error in master - can you test and see if things are now fixed for you?

**Comment by ffierm** [comment]
It works, now (both Leaflet and OL)! 
Thank You!

**Comment by tomchadwin** [comment]
Ah, splendid. Thanks for testing and reporting back.
