### ISSUE TITLE
previwe not avalaible - qtwebit is missing

### ISSUE THREAD

**Issue by Axgro12** [tomchadwin/qgis2web#474]
Hi!
I installed the plugin on QGis 2.14.5 Essen and I use Ubuntu 16.10. When I open the pulgin i have this message: "Preview is not available since QtWebKit dependency is missing on your system"
I installed QtWebKit (or, at least, I Hope...) but it doesn't work. Is there anyway to solve?

Thanks

**Comment by tomchadwin** [comment]
I don't know, I'm afraid. Sorry, but I'm not a Linux user. Can anyone else help?

**Comment by tomchadwin** [comment]
Of course, you can still export without the preview.

**Comment by tomchadwin** [comment]
Closing for now - I'll reopen if anyone has any way forward with this. I guess the issue you are having could be to do with missing Python bindings for QtWebkit. @mbernasocchi, I saw you post about WebKit on the QGIS dev list - can you help here?

**Comment by mbernasocchi** [comment]
should be fixed starting from yesterday's 2.18 nightly. and from 2.18.8.

its a mix of various issues,
ubuntu > 16.04 have no pyqt webkit bindings and there was a qgis packaging error (solved yesterday).

as of now you can build qgis 2.18 yourself and copy the QtWebKit.so file to the dist-packages folder

sudo cp /home/marco/dev/QGIS/218/build/output/python/PyQt4/QtWebKit.so /usr/lib/python2.7/dist-packages/PyQt4/

**Comment by tomchadwin** [comment]
@mbernasocchi Thanks so much! Really good news.

@Axgro12 When QGIS 2.18.8 is released, please upgrade to that, and this issue should be resolved.

**Comment by jekhor** [comment]
Doesn't work with 2.18.9 (debian packages from qgis.org)

**Comment by tomchadwin** [comment]
@jekhor What specific distro are you on?

@mbernasocchi , @jef-n Any ideas? Why would someone not have either QtWebkit or the Python bindings?

**Comment by tomchadwin** [comment]
@jekhor Can you also give some specific details? How does it fail? What do you see?

**Comment by jekhor** [comment]
Sorry, I hurried. This was f**ing 'No module named QtWebKit.QWebView' error at plugin loading. Seems eliminated after some of packages/modules installation/removing magic...
Debian unstable. Likely that removing of all other failed modules help.

**Comment by tomchadwin** [comment]
Ah, splendid. Glad you got it working again. The whole QtWebkit thing has been a nightmare.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
