### ISSUE TITLE
"This plugin is broken" error

### ISSUE THREAD

**Issue by dimix7** [tomchadwin/qgis2web#483]
I'm trying to install the plugin but i get the following text after install:

"This plugin is broken. Python said:

No module named parameters"

Anyone else experienced this problem?

I managed to install an older version of the plugin(2.0.0) with no problems, but if I try to update it to the latest version (2.16.2) i still get the error and the plugin becomes "Invalid".

Here is the stack trace I'm getting:

```
Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] QGIS version: 2.18.6 Las Palmas, 5f369b0

Python Path: C:/Users/Dim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python C:/Users/Dim/.qgis2/python
C:/Users/Dim/.qgis2/python/plugins C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27 C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packagesC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PILC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Dim/.qgis2//python
C:\Users\Dim.qgis2\python\plugins
C:\Users\Dim.qgis2\python\plugins\mmqgis/forms
C:\Users\Dim.qgis2\python\plugins
```

**Comment by tomchadwin** [comment]
I don't think I've seen this before, and so it's going to be tricky to solve. Can you check the various logs (View > Panels > Log Messages Panel)?

**Comment by tomchadwin** [comment]
One thing to check: do you have a folder called processing in the following location:

C:\Users\Dim.qgis2\python\plugins\

If so, rename it to something temporary, and restart QGIS.

**Comment by dimix7** [comment]
Ok so first the logs:
**General:**

> 2017-05-03T10:44:58	0	QGIS starting...
> 2017-05-03T10:45:15	0	Python support ENABLED :-) 
> 2017-05-03T10:46:20	0	Application state:
> 			QGIS_PREFIX_PATH env var:		C:/PROGRA~1/QGIS2~1.18/apps/qgis
> 			Prefix:		C:/PROGRA~1/QGIS2~1.18/apps/qgis
> 			Plugin Path:		C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins
> 			Package Data Path:	C:/PROGRA~1/QGIS2~1.18/apps/qgis/.
> 			Active Theme Name:	default
> 			Active Theme Path:	C:/Users/Dim/.qgis2///themes\default\icons/
> 			Default Theme Path:	:/images/themes/default/
> 			SVG Search Paths:	C:/PROGRA~1/QGIS2~1.18/apps/qgis/./svg/
> 					C:/Users/Dim/.qgis2//svg/
> 			User DB Path:	C:/PROGRA~1/QGIS2~1.18/apps/qgis/./resources/qgis.db
> 			Auth DB Path:	C:/Users/Dim/.qgis2//qgis-auth.db
> 			
> 2017-05-03T10:46:20	0	QGIS Ready!

**Plugins:**

>  2017-05-03T10:45:15	0	Loaded Coordinate Capture (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/coordinatecaptureplugin.dll) 
>  2017-05-03T10:45:15	0	Loaded Dxf2Shp Converter (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/dxf2shpconverterplugin.dll) 
> 2017-05-03T10:45:15	0	Loaded eVis (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/evis.dll)
> 2017-05-03T10:45:15	0	Loaded Geometry Snapper (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/geometrysnapperplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Georeferencer GDAL (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/georefplugin.dll)
> 2017-05-03T10:45:16	0	Loaded GPS Tools (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/gpsimporterplugin.dll)
> 2017-05-03T10:45:16	1	Failed to load C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassplugin7.dll (Reason: Cannot load library C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassplugin7.dll: The specified module could not be found.)
> 2017-05-03T10:45:16	1	Failed to load C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassprovider7.dll (Reason: Cannot load library C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassprovider7.dll: The specified module could not be found.)
> 2017-05-03T10:45:16	1	Failed to load C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassrasterprovider7.dll (Reason: Cannot load library C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/grassrasterprovider7.dll: The specified module could not be found.)
> 2017-05-03T10:45:16	0	Loaded Heatmap (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/heatmapplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Interpolation plugin (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/interpolationplugin.dll)
> 2017-05-03T10:45:16	0	Loaded OfflineEditing (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/offlineeditingplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Oracle Spatial GeoRaster (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/oracleplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Raster Terrain Analysis plugin (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/rasterterrainplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Road graph plugin (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/roadgraphplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Spatial Query Plugin (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/spatialqueryplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Topology Checker (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/topolplugin.dll)
> 2017-05-03T10:45:16	0	Loaded Zonal statistics plugin (Path: C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/zonalstatisticsplugin.dll)
> 2017-05-03T10:45:19	0	Loaded Group Stats (package: GroupStats)
> 2017-05-03T10:45:21	0	Loaded mmqgis (package: mmqgis)
> 2017-05-03T10:45:21	0	Loaded OGR2Layers (package: OGR2Layers)
> 2017-05-03T10:45:26	0	Loaded OpenLayers Plugin (package: openlayers_plugin)
> 2017-05-03T10:45:54	0	Loaded Processing (package: processing)
> 2017-05-03T10:45:56	0	Loaded qgis2web (package: qgis2web)
> 2017-05-03T10:45:56	0	Loaded Affine Transformations (package: qgsAffine)
> 2017-05-03T10:45:56	0	Loaded DB Manager (package: db_manager)
> 2017-05-03T10:45:56	0	Loaded GdalTools (package: GdalTools)
> 2017-05-03T10:46:08	0	Loaded MetaSearch Catalogue Client (package: MetaSearch)

**Python error**

> 2017-05-03T10:45:55	1	Traceback (most recent call last):
> 			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
> 			    plugins[packageName] = package.classFactory(iface)
> 			  File "C:/Users/Dim/.qgis2/python/plugins\qgis2web\__init__.py", line 28, in classFactory
> 			    from .qgis2web import Qgis2Web
> 			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			  File "C:/Users/Dim/.qgis2/python/plugins\qgis2web\qgis2web.py", line 30, in <module>
> 			    from qgis2webProvider import qgis2webProvider
> 			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			  File "C:/Users/Dim/.qgis2/python/plugins\qgis2web\qgis2webProvider.py", line 26, in <module>
> 			    from qgis2webAlgorithm import exportProject, exportVector, exportRaster
> 			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			  File "C:/Users/Dim/.qgis2/python/plugins\qgis2web\qgis2webAlgorithm.py", line 34, in <module>
> 			    from processing.core.parameters import (ParameterVector,
> 			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			ImportError: No module named parameters
> 			
> 

I renamed the "Processing" folder as you suggested and Eureka! IT WORKS!

PS: I don't know how to remove formatting on github, so there are some misrepresentations in the logs pasted. Here are the[ logs without the github formatting](https://shrib.com/#JmZ3RBoWUxyddnTVbtyv)

**Comment by tomchadwin** [comment]
Glad that sorted it for you - you had two conflicting versions of Processing installed - common enough, and I've had the same happen to me. You can safely delete the folder you renamed.

PS  Surround code blocks in triple backticks (`) to format them on Github. See https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by dimix7** [comment]
Great! Thanks a lot, again!
If I have some questions about the usages of the plugin, where would be the proper platform to ask them?

**Comment by tomchadwin** [comment]
If it's a bug or a feature request, open an issue here. If it's a "how do I?", use Stack Exchange. You'll often not know which it is, and I don't mind at all where you ask. Just have a thick skin for when strict mods like @anitagraser reprimand you.
