### ISSUE TITLE
Add select all/deselect all layers in "Layers List"

### ISSUE THREAD

**Issue by bwmoths** [tomchadwin/qgis2web#485]
Is it possible to add a 'button' to select all layers / deselect all layers in the layers list once the 'maps' have been exported for use in a website, browser etc. Please.

**Comment by misterphilipj** [comment]
I would definitely use this, I have one map with 30 different layers in it.  Categorizing into different parents and children layers would also help.

**Comment by bwmoths** [comment]
I want to use QGIS2WEB to produce species distribution maps and have up to 250 layers to a map so this is probably esential ! To turn all these layers on or off individually is not an option. I agree with the 'Parent - Children' idea, I could organise the displays of species in Genus or Family groups which would make the resultant maps much more usefull. Also I use the TomBio plugin to import the layers in the first place and there is a fascility to organise the data layers by a higher classification.

**Comment by tomchadwin** [comment]
If you use categorized renderers, you can group your layers thematically. I don't really want to add a toggle all control, as the layer control already often gets pretty big, especially on mobile. I'd look at how to add that feature manually to the exported map.

**Comment by bwmoths** [comment]
Re: [tomchadwin/qgis2web] Add select all/deselect all layers in "Layers List" (#485)


Hi 

'Categorised renderers' might go a little way to improve the situation but not enough to make qgis2web usable as far as I am concerned. I cannot see how this function can be added manually to the exported maps so sadly I will have to abandon qgis2web !

Regards
Martin


Martin Love FRES FLS
"VIRGO"
Treluggan Boatyard
Landrake
Saltash
Cornwall
PL12 5ES

07884 308454







If you use categorized renderers, you can group your layers thematically. I don't really want to add a toggle all control, as the layer control already often gets pretty big, especially on mobile. I'd look at how to add that feature manually to the exported map.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




--

**Comment by tomchadwin** [comment]
@bwmoths I'm sure someone else would be able to add the functionality you need. Can anyone help Martin?

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
