### ISSUE TITLE
Respect symbol levels

### ISSUE THREAD

**Issue by fgillen01** [tomchadwin/qgis2web#486]
Hi all,

How do I get qgis2web to respect the symbol levels I have created within a layers symbology?

![image](https://cloud.githubusercontent.com/assets/13051473/25797389/efbac936-33d4-11e7-8a1f-69c13284f569.png)

Trying to create drive time buffers like this..

![image](https://cloud.githubusercontent.com/assets/13051473/25797436/1f75a1be-33d5-11e7-8ed4-4447ce7b3b2d.png)

But they show up in Leaflet like this...

![image](https://cloud.githubusercontent.com/assets/13051473/25797459/3afa04fc-33d5-11e7-992f-012f9a005695.png)

Any help would be appreciated.

Finbar

**Comment by tomchadwin** [comment]
Firstly, I'm afraid multiple symbol layers are not supported in Leaflet exports, so it will not work. They are meant to work in OpenLayers exports, though I have not tested them recently. If they do, I don't know whether symbol levels are respected or not (I wasn't even aware of them).

**Comment by tomchadwin** [comment]
I've confirmed that multiple symbol layers *are* supported in OpenLayers exports, but I've also confirmed that symbol levels are *not* respected. Hopefull a fix will be possible soon.

**Comment by tomchadwin** [comment]
@fgillen01 I've added to support for symbol levels *in OpenLayers exports only*. Can you test master branch and report back? Thanks.

**Comment by fgillen01** [comment]
Hi Tom,

Will test on Monday.

Finbar

On 12 May 2017 14:18, Tom Chadwin <notifications@github.com> wrote:

@fgillen01<https://github.com/fgillen01> I've added to support for symbol levels in OpenLayers exports only. Can you test master branch and report back? Thanks.

**Comment by fgillen01** [comment]
Hi Tom,
Downloaded latest version from QGIS plugin repository. Tested OpenLayers option but now working. Any queries, get back to me
Finbar

**Comment by tomchadwin** [comment]
Did you mean "not" working? I've not released a new version with this fix yet. To test it, download master branch from here (Github), and overwrite the plugin files in your .qgis2 folder.

**Comment by fgillen01** [comment]
On 17 May 2017 2:51 p.m., Tom Chadwin <notifications@github.com> wrote:

Did you mean "not" working? I've not released a new version with this fix yet. To test it, download master branch from here (Github), and overwrite the plugin files in your .qgis2 folder.

**Comment by fgillen01** [comment]
Hi Tom,
Yeah I meant it was not working. I downloaded the plugin from the master branch and it is not working with OpenLayers. It does not show the layer on the map but there is a reference to it in the layer list.
