### ISSUE TITLE
Problem using rasters when using Leaflet with visibility unchecked

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#488]
When a WMS is used but is turned off by default in a leaflet map the resulting map does not include the WMS and an error complaining about not finding a layer is noted in developer tools.  Openlayers is not affected.

To test I used this WMS
`http://ows.mundialis.de/services/service?`

**Comment by tomchadwin** [comment]
You mean when "Visible" is unchecked?

**Comment by boesiii** [comment]
Yes.

**Comment by tomchadwin** [comment]
Confirmed. Broader issue which also affects raster (non-WMS) layers.

**Comment by tomchadwin** [comment]
Fixed in master. World's shortest bug.
