### ISSUE TITLE
Raster layer visibility not being saved

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#490]
The layer visibility setting for a WMS layer is not being saved to the project.  I am using the latest release.  If I uncheck the "Visible" setting for a WMS layer and restart Qgis the check box is checked.

![visibility](https://cloud.githubusercontent.com/assets/2079638/25866061/2af9f924-34c3-11e7-8736-cdcbbc0c134c.PNG)

**Comment by tomchadwin** [comment]
Also affects all rasters

**Comment by tomchadwin** [comment]
Fixed in master - same as the previous error.

**Comment by boesiii** [comment]
Solved.

**Comment by tomchadwin** [comment]
Splendid.
