### ISSUE TITLE
Leaflet multiple symbol layer support

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#491]
With help from @perliedman on Gitter, I've got a sample Leaflet map working with symbolLayers faked with multiple layers. Tested with layers list. I'll try to code it up now, and then we can test it with other features. There are bound to be things which won't immediately work.

**Comment by tomchadwin** [comment]
If it works, it will solve #486 for Leaflet.

**Comment by tomchadwin** [comment]
So the process will be:

1. Generate a new `style_` function for each symbol layer
2. Create a new layer for each symbol layer using the new `style_`
3. Attach listeners to each *existing* layer to add the new ones when the original is added to the map (paying attention to layer zIndices), and remove when removed

**Comment by tomchadwin** [comment]
```javascript
function style_airports0() {
    return {
        pane: 'pane_airports0',
        radius: 4.0,
        opacity: 1,
        color: 'rgba(0,0,0,1.0)',
        dashArray: '',
        lineCap: 'butt',
        lineJoin: 'miter',
        weight: 1,
        fillOpacity: 1,
        fillColor: 'rgba(39,147,25,1.0)',
    }
}
map.createPane('pane_airports0');
map.getPane('pane_airports0').style.zIndex = 401;
map.getPane('pane_airports0').style['mix-blend-mode'] = 'normal';
var layer_airports0 = new L.geoJson(json_airports0, {
    attribution: '<a href=""></a>',
    pane: 'pane_airports0',
    onEachFeature: pop_airports0,
    pointToLayer: function (feature, latlng) {
        var context = {
            feature: feature,
            variables: {}
        };
        return L.circleMarker(latlng, style_airports0(feature))
    }
});

function style_airports0_1() {
    return {
        pane: 'pane_airports0',
        radius: 8.0,
        opacity: 1,
        color: 'rgba(0,0,0,1.0)',
        dashArray: '',
        lineCap: 'butt',
        lineJoin: 'miter',
        weight: 1,
        fillOpacity: 1,
        fillColor: 'rgba(175,147,25,1.0)',
    }
}
var layer_airports0_1 = new L.geoJson(json_airports0, {
    attribution: '<a href=""></a>',
    pane: 'pane_airports0',
    onEachFeature: pop_airports0,
    pointToLayer: function (feature, latlng) {
        var context = {
            feature: feature,
            variables: {}
        };
        return L.circleMarker(latlng, style_airports0_1(feature))
    }
});

function style_airports0_2() {
    return {
        pane: 'pane_airports0',
        radius: 12.0,
        opacity: 1,
        color: 'rgba(0,0,0,1.0)',
        dashArray: '',
        lineCap: 'butt',
        lineJoin: 'miter',
        weight: 1,
        fillOpacity: 1,
        fillColor: 'rgba(175,147,175,1.0)',
    }
}
var layer_airports0_2 = new L.geoJson(json_airports0, {
    attribution: '<a href=""></a>',
    pane: 'pane_airports0',
    onEachFeature: pop_airports0,
    pointToLayer: function (feature, latlng) {
        var context = {
            feature: feature,
            variables: {}
        };
        return L.circleMarker(latlng, style_airports0_2(feature))
    }
});

layer_airports0.on('remove', function(e){
    map.removeLayer(layer_airports0_1);
    map.removeLayer(layer_airports0_2);
});
layer_airports0.on('add', function(e){
    map.addLayer(layer_airports0_1);
    layer_airports0_1.bringToBack();
    map.addLayer(layer_airports0_2);
    layer_airports0_2.bringToBack();
});

map.addLayer(layer_airports0);
```

**Comment by tomchadwin** [comment]
Branch for this work:

https://github.com/tomchadwin/qgis2web/tree/leafletSymbolLayers

**Comment by tomchadwin** [comment]
This is now working for sing;e symbol renderer JSON layers only, and it breaks other layers. Please do try it and see if it works for you.

Categorized/graduated/rule-based are going to be difficult. I started to think about them but it made my head hurt, so I stopped for the moment.

**Comment by tomchadwin** [comment]
This was proving too complex and difficult. Happily, @perliedman then wrote https://github.com/perliedman/leaflet-multi-style. Amazing!

I've now integrated it - the tests are all now broken, but I'd still very much appreciate any testing. I'll look at the test tomorrow.

**Comment by Gagandeepchani** [comment]
Dear Tomchadwin,
Is it possible to add multiple "Layer search"? like cascading view
Example:- First layer search - First question (Country name = India), 
               Second layer search-  Second question (Name of province = Rajasthan) In this case only 
               provinces from India should 
                be options.
               Third layer search -  Third question (Name of district = Hanumangarh) (In this case only 
                districts from Rajasthan should appear as the option).
Thank you
