### ISSUE TITLE
Too much data in attributes causes bug, is there a way to customize the box that pops up to be wide to prevent this bug, or to shrink the size of the popup?

### ISSUE THREAD

**Issue by misterphilipj** [tomchadwin/qgis2web#493]
You will see here on this map no issues, I have reduced the size of the attribute tables so the bug is not present : http://www.tularecog.org/wp-content/gismaps_maps/test/index.html#10/37.1641/-119.3170

You WILL see the bug here when hovering the mouse over the layer "2012" in teal, look for the teal dots and hover the mouse over.  The map goes haywire, because there is too much data in the attribute table.  Rather than deleting or hiding data, I would like to show as much as possible in the popup by customizing the size, width, or font of the popup.   http://www.tularecog.org/wp-content/gismaps_maps/test3/index.html#10/37.5527/-119.6878

I think this issue is explained very easily so I'm not attaching any screenshots, but if someone wants a video I can post a video of what is occurring.  I have tried both versions of the map exports and all settings.

I have the latest version of QGIS and latest version of qgis2web.  

Thanks for any feed back :)

**Comment by tomchadwin** [comment]
You'll have to edit the exported code, I'm afraid. The plugin handles the more common case of less popup data.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by andreaordonselli** [comment]
I have just released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
