### ISSUE TITLE
[Question / Enhancement] Encrypted Json data

### ISSUE THREAD

**Issue by Cec78** [tomchadwin/qgis2web#494]
Hi,
I was wondering if it would be possible to produce a webmap with encrypted json data, in order to publish the webmap in a website and make not possible for users to see/download these data.
Thank you for your answer.
Céc.

**Comment by tomchadwin** [comment]
Not really. The only way you can achieve that is by having another software layer server-side to obscure the data. I stand to be corrected.

**Comment by Cec78** [comment]
Hi Tom,

Thank you for your answer, we will think about it.

Regards.

Céc.
