### ISSUE TITLE
Make the resulting HTML output conformant with standard (X)HTML

### ISSUE THREAD

**Issue by Frederikssund** [tomchadwin/qgis2web#495]
Although the the generated "index.html" file generated by qgis2web works, it's not conformant with any HTML standard. 

Several types of CMS requires  html to be conformant with ex. xhtml, so it would be nice to have qgis2web to produce conformant xhtml.

This is the manual steps required to convert a qgis2web - using the leaflet option - "index.html" to xhtml

Take the file "index.html" from Qgis2Web and:

2. Delete all text from the start of the file until (include the line):
```
 <Meta charset = "utf-8">
```

3. Insert the following text which is definitions of charter encoding (utf-8) and document type (XHTML 1.0 Transitional):

```

<? Xml` version = "1.0" encoding = "utf-8"?>
<! DOCTYPE html PUBLIC "- // W3C // DTD XHTML 1.0 Transitional // EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<Html xmlns = "http://www.w3.org/1999/xhtml">
    <Head>


```
4. All links that refer to files with the surname ".css" and "styles" tags must have the definition:
```
type = "text / css"
```
 embedded

Valid xhtml 'link' example:
```
<Link rel = "stylesheet" type = "text / css" href = "css / leaflet.css" />
```
Valid xhtml 'style' example:
```
      <Style type = "text / css">
        Html, body, #map {
            Width: 100%;
            Height: 100%;
            Padding: 0;
            Margin: 0;
        }
        </ Style>
```
5. All script tags, incl. Those referring files with surnames ".js" must have the definition:
```
type = "text / javascript"
```
embedded

Valid xhtml 'script' example:
```
<Script type = "text/javascript" src = "js/qgis2web_expressions.js"> </ script>
```
6. To avoid that the validator barfs over html text in javascript strings you have to Insert the following immediately after all the script - "includes".

```
<Script type = "text / javascript">
// <! [CDATA [>
```
(Lots and lots of javascript - not to be interpreted as HTML)

```
//]]>
</ Script>
```
7. Make sure that all empty tags are closed with "/>" and not only ">"

8. Validate the file at https://validator.w3.org/ with encoding utf-8 and XHTML 1.0 transitional

It would be quite simple to implement the individual necessary change (There is "just" a lot of code pieces to change ;-)

**Comment by tomchadwin** [comment]
I don't want to comply with XHTML. Can we concentrate on HTML5? Work was done on this some time ago, but new development could well have made the output invalid again. I'll investigate.

**Comment by tomchadwin** [comment]
It was @garprogram who did all the work (thanks! ):

https://github.com/tomchadwin/qgis2web/commits?author=garprogram

**Comment by Frederikssund** [comment]
I'll close this issue and continue with comments in #496
