### ISSUE TITLE
Point Layers do not show up in layer list when Cluster is checked

### ISSUE THREAD

**Issue by azstumbler** [tomchadwin/qgis2web#503]
Qgis ver 2.18.9, qgis2web ver 2.19.0 

When exporting to leaflet and a point layer is marked to be a Cluster it is not appearing in the layer list. Only if cluster is not checked will it show up, either in preview or exported. So if there are multiple point layers and clustering is used on them then they are either all on or can not be clustered to have any visibility control.

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Although I was actually trying to fix #504, it's possible that https://github.com/tomchadwin/qgis2web/commit/579dff8a353353479751c18d957159bd72c30e38 fixed this issue. Can you try current master and report back?

**Comment by azstumbler** [comment]
It is working now. But an interesting thing is if the point layer is the last layer listed then every point is showing even though it is set to being not visible. If it is then made visible not only are the points visible but also the clusters over the points. So unless the cluster layer is the first layer then the points the clusters are calculated from are also visible. This shows up in both preview and when exported.

**Comment by tomchadwin** [comment]
I can't recreate that. I've got two layers in a project, the point layer being the bottom one. I open qgis2web, and select Cluster for the point layer. I set Add layers list to "Expanded".

Whether I make that layer visible or not, it works. I never see the unclustered points.

**Comment by azstumbler** [comment]
The point layer I am using has about 20,000 points in it and while trouble shooting the original issue I had unchecked the minify  GeoJSON files and neglected to re-enable it. Once I did it displayed correctly regardless of where it was in the list of layers.

**Comment by tomchadwin** [comment]
That's interesting. Shouldn't make any difference, but I'm glad it did.

**Comment by tomchadwin** [comment]
Released as 2.20.0 and pushed to QGIS plugins repo.
