### ISSUE TITLE
Question: How do I add image into the data of "hover on popup?" 

### ISSUE THREAD

**Issue by misterphilipj** [tomchadwin/qgis2web#506]
I would like to add images to my data, when I hover over popup. I read through the forum and it looks like this is possible. I do not understand the explanations though. Do I need to have a link to the file in my CSV that I import, or do I do that within QGIS, or at some step in Qgis2web?  Is there any HTML code involved linking to the picture? 

Thanks!

**Comment by tomchadwin** [comment]
See https://github.com/tomchadwin/qgis2web/wiki/fields,-attributes,-and-popups (last screenshot on page).
