### ISSUE TITLE
Leaflet simple marker shapes

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#508]
All non-SVG markers currently come out as circles: need to add eg square, triangle - all shapes listed here:

http://qgis.org/api/classQgsSimpleMarkerSymbolLayerBase.html#af8d976b7bb349cc3fb182e0ff295a81d

No idea how to do this yet.

**Comment by tomchadwin** [comment]
Possibly with this (untested):

https://github.com/rowanwins/Leaflet.SvgShapeMarkers

Never used it, and don't know if it's compatible with Leaflet 1, but I'll investigate.

**Comment by tomchadwin** [comment]
It works perfectly - thanks, @rowanwins! We'll reopen the issue if people want shapes which have not yet been implemented.

**Comment by rowanwins** [comment]
Glad you found the module of use @tomchadwin !

**Comment by tomchadwin** [comment]
@rowanwins I certainly did. Thanks again! You might even get a PR from me for more shapes, if my SVG is up to it.

**Comment by tomchadwin** [comment]
Released as 2.21.0 and pushed to QGIS plugins repo.

**Comment by tomchadwin** [comment]
Doesn't work in LTR - why?

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.
