### ISSUE TITLE
Qgis crashes when using a label that has multiple fields

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#51]
same as

https://github.com/volaya/qgis-ol3/issues/41

If you have a label in Qgis similar to  "PIPE_DIAM" || "PIPE_MATL" then Qgis will crash when exporting to OL3 but does not crash when exported to Leaflet

**Comment by marcobra** [comment]
Using plugin git on  qgis (2.9 master nightly) 
qgis also crash on layer with a multi line splitted labels on  previews
i'm testing  with a filtered layer and the splitting chars are ">>"

preview with LL and OL3 give this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 159, in previewLeaflet
    layers, groups, popup, visible, json, cluster, labels = self.getLayersAndGroups()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 219, in getLayersAndGroups
    if item.json:
AttributeError: 'TreeGroupItem' object has no attribute 'json'
```

-----------------------------------------------------------------------

- export to LL made a white page visualization

- ol3 export made qgis crash

**Comment by tomchadwin** [comment]
@marcobra I don't think that error is connected to labels, and I think it should be fixed. I don't knw about multiline labels, though - can you test again and report back?

**Comment by marcobra** [comment]
Yes testing with release 0.13.5 is working

thank

**Comment by tomchadwin** [comment]
I've just committed a fix for OL3 labels. Can people test? I should say that I've not recently been able to recreate the QGIS crash from this issue. I'd like to know what other people experience. To clarify: this doesn't get expression-based labels working - it just catches one error which they produce. Let me know how it works for you.

**Comment by boesiii** [comment]
I get an error in the preview pane and when I try and export.

Traceback (most recent call last):
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\maindialog.py", line 107, in saveMap
    MainDialog.saveOL(self)
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\maindialog.py", line 247, in saveOL
    outputFile = writeOL(self.iface, layers, groups, popup, visible, json, cluster, labels, params, folder)
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\olwriter.py", line 91, in writeOL
    f.write(replaceInTemplate(settings["Appearance"]["Template"] + ".html", values))
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\olwriter.py", line 147, in replaceInTemplate
    with open(path) as f:
IOError: [Errno 2] No such file or directory: u'C:/Users/username/.qgis2/python/plugins\\qgis2web\\templates\\.html'

**Comment by tomchadwin** [comment]
Very odd - do you have an item in the Template dropdown selected? There's only one provided as default - basic.

**Comment by boesiii** [comment]
For some reason the Template dropdown was blank, after selecting "basic" it works as expected and the label expression does not cause an error in Qgis for ol3

**Comment by tomchadwin** [comment]
Closing for now. If QGIS crashes again with expressions in labels, do reopen

**Comment by tomchadwin** [comment]
Expressions in labels are now supported in master, so please test to see whether concatenation is working for you. Only basic expressions are supported at the moment, so report failures, and we'll see what can be developed.
