### ISSUE TITLE
Is there a way to update dynamically the map after the export ?

### ISSUE THREAD

**Issue by ossantr** [tomchadwin/qgis2web#512]
Hi, 

I work on a map with a layer of points and I’m looking for a way to update dynamically the layer on the map (which had been export by qgis2web) after the selection of some features on a form. At the visual level, the objective is that the points which don't respect the features I have selected no longer appears on the map.
Do you know if someone already find a solution to this ?
During my tests, I find a way to change the information in JSON,  after that I reload the div which contains the map but there is an error (a variable isn’t defined). I can develop more what I try to do and show a bit of the code but I’m not sure that what I tried is a solution.

I’m sorry if the question has been already asked or if my english is not perfect…

Thank you in advance for your answer or your trail.

**Comment by boesiii** [comment]
Dynamic? No.  You should be able to edit the JSON files manually.  

Q2W does not work with selected features.  Why not select the features in QGIS and export to a shapefile then each time you need to update,

**Comment by ossantr** [comment]
The objective is that the visitors of the site should be able to select some features of the layer point and that the map evolve dynamically according to the choices of the user.

**Comment by tomchadwin** [comment]
That's an interesting question. Persistent I'd you removed the layer and then re-added it?

**Comment by ossantr** [comment]
I finally found a way to do it by simply modified the file with all the data of the layer, delete the div id="map", recreate it, add him the attribute id="map" and relaunch the script which is on the index.html file.

I can show the code I used if it's useful.

The only limit of this method is that you need to reload the entire map every time you want to launch a new search on it. Otherwise, it works good!

Thank you so much for your help and anwser !

**Comment by tomchadwin** [comment]
I don't have a better answer for this, so I'll close this issue.

**Comment by Hosaana** [comment]
> I finally found a way to do it by simply modified the file with all the data of the layer, delete the div id="map", recreate it, add him the attribute id="map" and relaunch the script which is on the index.html file.
> 
> I can show the code I used if it's useful.
> 
> The only limit of this method is that you need to reload the entire map every time you want to launch a new search on it. Otherwise, it works good!
> 
> Thank you so much for your help and anwser !

Hello Ossantr!
Can you please share the code you used to modify the file with data?I can be very useful for me ,I am using qgis2web but I do not know how to update data after the map is exported.

Thank you very much!

Hosiana
