### ISSUE TITLE
Export project from processing toolbox gives "Global name 'getPopup' is not defined"

### ISSUE THREAD

**Issue by janddd** [tomchadwin/qgis2web#515]
Hello,

I'm trying to automate some map creation and was hoping to do this through the processing toolbox.

Whenever I press Export project I get the following Python error:

global name 'getPopup' is not defined.

`2017-06-29T00:25:57	2	Uncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/Users/jande/.qgis2/python/plugins\qgis2web\qgis2webAlgorithm.py", line 79, in processAlgorithm
			    writer.cluster) = self.getLayersAndGroups()
			  File "C:/Users/jande/.qgis2/python/plugins\qgis2web\qgis2webAlgorithm.py", line 108, in getLayersAndGroups
			    layerPopups = getPopup(layer)
			NameError: global name 'getPopup' is not defined` 

Export vector layer works fine.

Workflow:
1. open new project
2. add vectorlayer
3. save project
3. press 'export project' from the qgis2web processing toolbox

Not sure if i'm doing this wrong or encountering a bug. Could anyone point me in the right direction?

I've tested this on qgis 2.18.2 and qgis 2.14 standalone

Example data included.

Thanks in advance!

[dataset.zip](https://github.com/tomchadwin/qgis2web/files/1110410/dataset.zip)

**Comment by tomchadwin** [comment]
Confirmed. The method for populating popups was changed in the export vector layer algorithm, but not in the export project one.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by janddd** [comment]
Tested, it works now. Thanks for the quick fix!

**Comment by tomchadwin** [comment]
Great - thanks for confirming so quickly.
