### ISSUE TITLE
No variable width for line objects

### ISSUE THREAD

**Issue by RobShaw77** [tomchadwin/qgis2web#516]
Hi

I'm not sure if this a bug or an unavilable feature, but when I export lines that have gradient width styled to them then this is not reflected in the web map. Is this something that is possible please?

Thanks
Rob

**Comment by tomchadwin** [comment]
I'm afraid I don't know how to do this in Leaflet or OL. Does anyone know if it's possible?

**Comment by tomchadwin** [comment]
The only way I've found to achieve this is to break your lines up intimate segments, and apply different widths to each. I'll close this issue for now. Sorry not to have a better solution.
