### ISSUE TITLE
Leaflet scale dependent layer

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#517]
Latest release of qgis2web on QGIS 2.14.16.  Adding a scale dependency to layer results in a blank canvas in leaflet preview and output.  Working fine in OL.

**Comment by tomchadwin** [comment]
Urg. Confirmed. Mistakenly published a deliberate JS error as part of trying to achieve #499. Thanks for spotting it. Fixing it now.

**Comment by tomchadwin** [comment]
Fixed in master. Sorry about that.
