### ISSUE TITLE
ol.Geocoder does not work

### ISSUE THREAD

**Issue by OliverRoe** [tomchadwin/qgis2web#519]
Hi everybody,

I used the qgis2web plugin for some months during 2016. After updating to the newest version in QGIS and creating an Openlayers webmap today, it seems that the address search does not work anymore. I can type in a zipcode, City or street but there are no results.

Either QGIS, not the plugin console shows any error.
I am using QGIS-Version "2.14.8-Essen" and have version 2.21.1 of qgis2web installed via QGIS repository.
I tested on Firefox 52.2.1 and MS Edge.

This is what the adress search looks like after confirming with Enter:
![zipcode eingabe](https://user-images.githubusercontent.com/29855197/28016042-f957edbe-6572-11e7-9764-1ebb09a17d6d.png)

This is what the Firfox Logging says:
![errorfirefox](https://user-images.githubusercontent.com/29855197/28015954-a2dafa9e-6572-11e7-95be-0d0f014bf3d8.png)

If I use an older version of the open layers geocoder ( Version: v2.0.1; Built: 2016-04-30T13:57:19-0300 and replace ol.geocoder.js, ol.geocoder.min.css and ol.css files, change the class names of the button respectively, the address search works again. So it seems to me that something in the open layers geocoding code has changed ... but I am not quite familiar with java script so I did not managed it to exactly find out what is going wrong.

Thank you for your help in advance!

**Comment by tomchadwin** [comment]
Would you be able to upload your failing export, and then browse to it online? I wonder whether the AJAX request just won't work these days with a local file - that's what the error implies.

**Comment by OliverRoe** [comment]
Hi, you are right. It works online but not with the local file. Is there any way to make it work with local files also?

**Comment by tomchadwin** [comment]
Not that I can think of, I'm afraid. It's a reflection of the increased security of browsers. Sorry.
