### ISSUE TITLE
Standardize how vector data is projected when exported

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#52]
My data is epsg 2272 and when I export it to OL3 the features are exported to epsg 3857, which is good.  When I export to Leaflet the features are exported as latitude and longitude coordinates which is not good for me because the precision set the coordinate very low and features are displayed incorrectly.

**Comment by boesiii** [comment]
A quick fix would be to have Leaflet ignore the precision field.

**Comment by tomchadwin** [comment]
This is where my GIS knowledge reaches its limit. Having started out on qgis2leaf, I was used to specifying 4326. Is 3857 more appropriate?

**Comment by boesiii** [comment]
Yes 3857 is more appropriate because most basemap tiles (OSM, Mapquest, Google, Bing) use 3857.

**Comment by tomchadwin** [comment]
OK, and if this is changed, will we be able to get the Leaflet precision field working properly?

**Comment by boesiii** [comment]
yes

**Comment by boesiii** [comment]
Helpful info about 3857 vs 4326
http://gis.stackexchange.com/questions/48949/epsg-3857-or-4326-for-googlemaps-openstreetmap-and-leaflet

**Comment by boesiii** [comment]
Nevermind my PR because I didn't really look at how the epsg was getting set in leaflet.  There is an easier way.

**Comment by tomchadwin** [comment]
I've read that thread before. You can tell how much it helped me.

**Comment by tomchadwin** [comment]
I don't think this is a genuine problem (based largely on comments from @riccardoklinger on #54), so I'll close for the moment. Comment if you think I should reopen.
