### ISSUE TITLE
Web Map generated from QGIS2WEB loses layer after ~12 hours

### ISSUE THREAD

**Issue by MooreMapping** [tomchadwin/qgis2web#520]
I've created a web map using both the Leaflet and OpenLayers options in QGIS2WEB. I uploaded the entire output file to my website file manager and used "<iframe>" to call the map to a webpage. When first created, the maps work fine, but after about 12 hours or so, when I try to open the map again, it can no longer find the layer. The Leaflet version will still load the basemap without the layer, but the OpenLayers version doesn't load anything. 

I'm new to both QGIS2WEB (and really webmapping in general) and to GitHub, so I apologize if this question has already been answered and would greatly appreciate being pointed in the right direction.

![image](https://user-images.githubusercontent.com/30117186/28117754-acc39fc8-66dc-11e7-8479-8603ffa9701a.png)

**Comment by tomchadwin** [comment]
I think this wins the prize for most bizarre problem. Can you post the URL for the map?

**Comment by MooreMapping** [comment]
The map is here: http://mooremaps.x10host.com/Austin-Zoning/. But I just re-uploaded the original file from my hard drive to my website file manager, so the map is currently working.

**Comment by boesiii** [comment]
It looks like X10 removes files larger then 10MB after 4 hours.

https://x10hosting.com/community/threads/news.196269/

**Comment by MooreMapping** [comment]
Oh, that would certainly be the problem then. Thank you for that. Guess I'll work on a workaround.

**Comment by tomchadwin** [comment]
Goodness. Nice catch, @boesiii. Have you checked the minify JSON option? That would reduce the filesize. Or if you are able, you could use the precision dropdown as well (fewer decimal places in coordinates = smaller files). Other than that, you'l have to split your layer into multiple ones, which is far from ideal.

I'll close this issue, if that's OK.

**Comment by MooreMapping** [comment]
I will try those options and see what I can do. Thank you @tomchadwin and @boesiii  for your help!
