### ISSUE TITLE
name 'QWebPage' is not defined

### ISSUE THREAD

**Issue by bfg9000it** [tomchadwin/qgis2web#523]
I'm using the archlinux user repository qgis 2.18.11
(https://aur.archlinux.org/packages/qgis/)
and I'm getting this error when I try to install qgis2web plugin.

I'm aware that is not a general error: using osgeo live distro or windows plugin works.

I'm not a python guy and I cannot figure what kind of python additional package could be necessary. May be some kind of "pyqt" related?

**Comment by tomchadwin** [comment]
Can you paste the actual error? You probably need QtWebkit, and I have no idea if it is available for archlinux. Apologies for not being able to support your environment - I have no archlinux knowledge. However, to investigate further, try looking at the following issues:

https://github.com/tomchadwin/qgis2web/issues/309
https://github.com/tomchadwin/qgis2web/issues/474

Let us know if you make any progress.

**Comment by tomchadwin** [comment]
Closing with no feedback.

**Comment by bfg9000it** [comment]
Sorry for my delay,

I can only say that archlinux package QtWebkit is installed as a dependency
of Qgis (2.3.4 version).

I've tested also the Ltr Qgis version (2.14.18) but the error is the
same: "name
'QWebPage' is not defined".




2017-08-14 14:49 GMT+02:00 Tom Chadwin <notifications@github.com>:

**Comment by tomchadwin** [comment]
How about the Python bindings for QtWebkit?

**Comment by bfg9000it** [comment]
It seems everything is installed? This is the list:

pyqt4-common 4.12.1-1 [installed]
Common PyQt files shared between python-pyqt4 and python2-pyqt4

pyqt5-common 5.9-1 [installed]
Common PyQt files shared between python-pyqt5 and python2-pyqt5

python-pyqt4 4.12.1-1 [installed]
A set of Python 3.x bindings for the Qt toolkit

python-pyqt5 5.9-1 [installed]
A set of Python 3.x bindings for the Qt5 toolkit

python2-pyqt4 4.12.1-1 [installed]
A set of Python 2.x bindings for the Qt toolkit

python2-pyqt5 5.9-1 [installed]
A set of Python 2.x bindings for the Qt5 toolkit


2017-08-22 17:50 GMT+02:00 Tom Chadwin <notifications@github.com>:

**Comment by boesiii** [comment]
Is it a problem installing the plugin or running the plugin?  Please post the error message?

**Comment by bfg9000it** [comment]
Both install and also when qgis starts:
I can see only this dialog

[image: Immagine incorporata 1]

Python message. May be I can activate a debug mode?
Sorry but messages are in italian...


2017-08-22 19:13 GMT+02:00 boesiii <notifications@github.com>:

**Comment by bfg9000it** [comment]
These are the messages when qgis starts
May be something related with QGIS2compat?

[bfg@bfg-wks ~]$ qgis
Warning: loading of qt translation failed
[/usr/share/qt4/translations/qt_it_IT]
Warning: QCss::Parser - Failed to load file  "/style.qss"
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: File o
directory non esistente
Warning: QFileSystemWatcher: failed to add paths:
/home/bfg/.qgis2//project_templates
Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack
"mWidgetStack", which already has a layout
QGIS2compat: setting qgis.PyQt = qgis2compat.PyQt
Warning: libpng warning: iCCP: known incorrect sRGB profile

2017-08-22 19:46 GMT+02:00 Bfg Bfg9000it <bfg9000it@gmail.com>:

**Comment by tomchadwin** [comment]
I really don't know enough to be able to help much with this - I'm really sorry. You could try posting either to the QGIS developer mailing list, or on their Gitter/IRC channels.

**Comment by bfg9000it** [comment]
Thank you very much for your effort,

This is something specific and related to archlinux packages. I'll try to
investigate as possible.

Your plugin is fantastic and I'm still using it in a osgeo live virtual
machine...



2017-08-23 11:16 GMT+02:00 Tom Chadwin <notifications@github.com>:

**Comment by bfg9000it** [comment]
FYI may be the issue in ArchLinux is related with QtWebKit that was removed from PyQt4 for security assessments.
https://www.archlinux.org/todo/phasing-out-qtwebkit/

**Comment by tomchadwin** [comment]
Yes, more broadly, the issue was that Qt wanted people to stop using QtWebkit and start using QtWebEngine instead. The problem was (probably still is?) that QtWebEngine does not have comparable functionality to QtWebkit, so it's not an ideal replacement yet. I believe an independent group then took on QtWebkit with a view to developing and maintaining it going forwards. However, I don't know the status of that project, nor any details of how to use it.

I'll close this issue for the moment, since I don't think it's something qgis2web can fix itself. However, if you come across any solutions, do post them here - it will help others.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
