### ISSUE TITLE
QGIS2Web always shows blue vector layers in leaflet-map

### ISSUE THREAD

**Issue by STGiese** [tomchadwin/qgis2web#524]
I tried QGIS2Web for sharing data. The QGIS-Project contains one WMS and two vector data (shape). One dataset is categorized by id, where id=0 is colored green and id=1 is colored white with layer transparency set to 50%. But it doesn't matter how I set the style...the resulting map alway shows a blue vector data. I added a screenshot where  you can see on the left side the result of the export and on the right side the setting in qgis...
Any idea???
![qgis2web_leafletblue](https://user-images.githubusercontent.com/17124261/28610227-e0334258-71e7-11e7-9706-f7bf0ea0a898.jpg)

**Comment by tomchadwin** [comment]
I'll check categorising on a numeric field and see if that issue has recurred. Can anyone else recreate this issue?

**Comment by tomchadwin** [comment]
Confirmed - categorizing on a numeric field didn't work. I've tried committing a fix. Could you check master and report back?
