### ISSUE TITLE
Leaflet does not load OSM - the background is white

### ISSUE THREAD

**Issue by DarekLesniewski** [tomchadwin/qgis2web#525]
Hi Tom

Leaflet does not load OSM and others map
The background is white.

Qgis2web version  2.22.0.
Qgis version 2.14.1.

Best regards
Darek

![webpage](https://user-images.githubusercontent.com/26086867/28614706-0a1d44d8-71f7-11e7-8e83-0b33196e380c.png)

**Comment by tomchadwin** [comment]
Any errors in the browser console or network tab?

**Comment by tomchadwin** [comment]
Closing with no feedback. Reopen if still an issue.
