### ISSUE TITLE
Time series maps?

### ISSUE THREAD

**Issue by mistyblue17** [tomchadwin/qgis2web#527]
First of all, this plugin awesome!! I am longing for there to be a way to export time-series maps from QGIS so they can be shared as an interactive web map without having to spend hours recreating them through trial-and-error of web mapping APIs with this capability. I use the TimeManager plugin to be able to visualize time series data in my maps, but currently, it seems QGIS2Web only exports the active timeframe displayed by TimeManager to a Leaflet map. I think it would be ideal if there was a way to combine the TimeManager plugin (https://github.com/anitagraser/TimeManager) with QGIS2Web. If you're interested, I would be willing to work with you on trying to develop this because a lot of people would greatly benefit from being able to move maps of time series data to the web as we move forward in the digital era of web mapping and big data.

**Comment by ruz76** [comment]
There is time extension for qgis2web available at https://github.com/ruz76/qgis2web_time_extension/
You can see sample output (from previous version) at http://gisak.vsb.cz/ruzicka/time/#14/49.8380/18.1578 We can cooperate to add functionality you are interested to have in it.

**Comment by mistyblue17** [comment]
Thank you!!! I'm very excited to give this a try.

Misty

**Comment by tomchadwin** [comment]
Please try the branch I have created for integrating time2web with qgis2web:

https://github.com/tomchadwin/qgis2web/tree/time2web

I have made no changes other than those documented in the time2web repo. Please can people test and confirm it works?

@anitagraser, @carolinux, it would be great to get your feedback on this. I've never worked with time-dimensional data, so I'm not the best person to evaluate.

**Comment by tomchadwin** [comment]
NO feedback, so I've released it as 2.23.0 - we'll see what feedback we get. I have one minor GUI issue, but I'll raise that on @ruz76's repo.
