### ISSUE TITLE
Clickable links in Popup

### ISSUE THREAD

**Issue by butte37** [tomchadwin/qgis2web#528]
Hi and thanks for qgis2web.

I made a map with points.
every point have data in a popup, including a link.

All shows fine, but how on earth is anyone able to click the link in the popup ?
When moving the pointer to the link, the popup off cource dissapears.

What am i missing ?

Try and see what i mean here.
www.nordek.dk/ff
GO TO DENMARK
Zoom in so you can see the points as stars, then and first then, you can show the popups.
Also, im on a very very fast server, but i got hundred of thousands of points, so it is a litte slow at first.
But when the map appear, its all loaded and fine.

Thanks.

**Comment by tomchadwin** [comment]
Is this because you selected the option "Show popups on hover"? If so, I can only suggest you don't set that option. Or am I wrong?

**Comment by butte37** [comment]
Thats so stupid, that im imbarrassed.
Thanks for the help.

I followed a tutorial that had the popup on hover option turned on, and i didnt think there where any other way to see it. I will now follow myself out of here.

**Comment by tomchadwin** [comment]
Nonsense - not stupid at all. Glad there's an easy solution
