### ISSUE TITLE
Pop Ups with Chart Functionality??

### ISSUE THREAD

**Issue by fgillen01** [tomchadwin/qgis2web#529]
Hi,

Another query Tom! Are there any plans to add chart functionality to the pop ups within qgis2web? 

![image](https://user-images.githubusercontent.com/13051473/29276322-1fbad954-8106-11e7-9d13-9fa8212d39bb.png)

Regards
Finbar

**Comment by tomchadwin** [comment]
In a word, no. I'd be happy to accept a pull request if anyone else wants to develop this, but it's not core functionality, and would probably add a lot of complexity to the GUI. Approaching the issue as @rus76 has with his time feature, separating it out as a plugin to qgis2web, would possibly be the best approach.
