### ISSUE TITLE
popup field label does not appear in processing algoritm Export project

### ISSUE THREAD

**Issue by janddd** [tomchadwin/qgis2web#534]
Hi Tom,

I think I have encountered another bug in the processing algorithm for qgis2web.

Workflow:
1. Open new project
2. Add vectorlayer
3. open Qgis2web plugin - set inline label for field and set export folder
4. press export button (using openlayers)
Resulting map: popup has field label
5. run Export project from processing toolbox
Resulting map: popup field has no field label

Manually saving the project before running the algorithm has no effect.

Dataset:
[dataset.zip](https://github.com/tomchadwin/qgis2web/files/1260683/dataset.zip)

PS.
I did some digging and when I open the projectfile in notepad I see this. I guess it does save the labeling options, they just don't get fetched by the processing algorithm?

      <customproperties>
        <property key="qgis2web/Visible" value="true"/>
        <property key="qgis2web/popup/pc3code" value="inline label"/>
      </customproperties>

Any ideas?

Cheers.

**Comment by tomchadwin** [comment]
Does it work if you use the export vector layer algorithm instead of the export project one?

**Comment by janddd** [comment]
Yes using the Export vector layer algorithm the field labels appear if I specify them in the algorithm menu (field name = value). This gives only room for one layer though?

**Comment by tomchadwin** [comment]
I'm not saying it's an alternative. It's just useful for me to narrow down where the bug is. I'll investigate.

**Comment by tomchadwin** [comment]
OK, as far as I can tell, the popup code in the export project algorithm was completely wrong. I've committed a possible fix to master. Can you test and report back?

**Comment by janddd** [comment]
Hi Tom, 

Just tested the fix for OL and Leaflet. 
Works perfect, thanks again for the quick response!

Cheers,

Jan

**Comment by tomchadwin** [comment]
Thanks for testing and reporting back so quickly. I'll try to release a version with the fix soon.
