### ISSUE TITLE
Search tool placement

### ISSUE THREAD

**Issue by mireks19** [tomchadwin/qgis2web#537]
I have problem with placement of search tool on the map http://www.wroclaw.pios.gov.pl/mapa/test/index.html#9/50.9584/16.3063 -it's only test map for show this issue. On map are two search tool, and when I write something to search (ex. potok) in upper search tool, the list of found objects is always coverd by lower search tool. How to make that the list of found objects would be always on top, uncovered by search tool? Maybe place z-index somwhere? 

Thanks

**Comment by tomchadwin** [comment]
So you must have manually added the second search tool? I'm afraid I can't offer any solution to something introduced by editing the output. Sorry, but it's not really an issue for qgis2web itself.

**Comment by mireks19** [comment]
Thank you for answer. In fact, it's not a qgis2web issue. It rather a leaflet issue in inability to searching more than one attribute in one searching tool. So I had to add manually second search tool for another attribute to search. Problem is that the list of scores is always under second search tool. So I will have to live with this ;)

Regards 
Mirek
