### ISSUE TITLE
Change default Leaflet export from EPSG:4326 to EPSG:3857

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#54]
This is a tentative proposal, as deduced from #52. Is it the correct thing to do?

**Comment by boesiii** [comment]
I say yes because the precision input will greatly affect the data displayed on a Leaflet map versus a OL3 map because the units for epsg 3857 is meters (I think) where as the units in a Leaflet map are decimal degrees.

**Comment by tomchadwin** [comment]
I'm not sure that this is the right approach. As I understanhd it, GeoJSON's "default" CRS is EPSG:4326. I still don't feel fully informed about this whole subject, though, so I am happy to be persuaded again.

**Comment by riccardoklinger** [comment]
No, you're completely right, default crs for leaflet geojsons is EPSG 4326!
We have used 4326 as default in QGIS2leaf since *ever* ... why is there a
discussion?!

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
@riccardoklinger Because the default CRS of common tiled basemaps (OSM/Google/Bing) is EPSG:3857? I think.

**Comment by riccardoklinger** [comment]
Yes, this is right! commom basemaps operate on 3857. but leaflet doesn't
care and use basemaps as they are in 3857 and uses geojsons as well as
simple points/markers/polygons .... in 4326 and combines both worlds.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
@riccardoklinger So is #52 not required?

**Comment by riccardoklinger** [comment]
I was surprised that this was ever opened but thought it was a need for
your "reprojecting" issues. But looking at this issues shows me, that there
is a big black hole. Openlayers is more flexible when it comes to
projections. Leaflet is somehow tailored around 4326 to fit with different
needs.

check this about projections in openlayers:

http://dev.openlayers.org/apidocs/files/OpenLayers/Projection-js.html#OpenLayers.Projection.getUnits

I would suggest to alter the default crs for the openlayers export and use
always 4326 to create a common export for leaflet and openlayers geojsons.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
I'll have to look into this. So the OL3 JSON export matches the source CRS? And doesn't explicitly state what CRS it is in?

I need to understand this because at the moment, I'm using qgis2leaf's writeAsVectorFormat for the Leaflet export, and qgis-ol3's writeAsVectorFormat for the OL3 export. The duplication needs to be eliminated, but I need to know which one to base the shared function on. At the moment I don't know which one is best.
