### ISSUE TITLE
Hidding some fields

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#540]
Sometimes I have layers with many fields (columns) of data. In exported map is (after click on layer element) every field as one row and i have to delete some of them in source code (index.html). http://q2w.obci.cz/qgis2web-many-fields-ugly.png

It could be useful disable to show fields in "Export to web map" window. Maybe checkbox in every row or new option in select "labels"? 
http://q2w.obci.cz/qgis2web-many-fields-solution.png

**Comment by tomchadwin** [comment]
Set a field's edit widget in QGIS to Hidden, and it will not appear in your popup:

https://github.com/tomchadwin/qgis2web/wiki/fields,-attributes,-and-popups
