### ISSUE TITLE
nothing displayed after x

### ISSUE THREAD

**Issue by przytula** [tomchadwin/qgis2web#541]
having qgis 2.18.12 windows and latest qgis2web installed
having a layer and different polygon on top
as long as I keep it to 54 : all ok
whenever I add more and export : no errors produced - all ok
but opening the index.html does not display anything
reducing to 54 gives correct output again
any help on this - any logging about internal error ?
best regards, Guy Przytula

**Comment by boesiii** [comment]
What do you mean by 54?  54 layers?

**Comment by przytula** [comment]
a tif on which I draw 54  polygons on top

**Comment by przytula** [comment]
![q2web](https://user-images.githubusercontent.com/6675471/30498031-7d6ec5de-9a55-11e7-9954-751b65f87373.png)
something like this

**Comment by boesiii** [comment]
Are you able to share your QGIS project file and data?

Are the 54 polygons in one shapefile or some GIS file?

**Comment by przytula** [comment]
I can create a tar file and upload

**Comment by przytula** [comment]
I can share dropbox folder : my email guy at przytula dot net
ship me a mail and I will give a share

**Comment by tomchadwin** [comment]
No need for Dropbox. Just drag and stop a zip into a reply on this thread.

**Comment by przytula** [comment]
but the file is 2G and not allowed :max 10Mb

**Comment by przytula** [comment]
[kermt.zip](https://github.com/tomchadwin/qgis2web/files/1308393/kermt.zip)
[SHAPES.zip](https://github.com/tomchadwin/qgis2web/files/1308394/SHAPES.zip)
[cvs.zip](https://github.com/tomchadwin/qgis2web/files/1308397/cvs.zip)
the project-shapes and csv+csvt

**Comment by przytula** [comment]
![71028a010009](https://user-images.githubusercontent.com/6675471/30513186-2ab357ce-9aff-11e7-89c0-040f44a3c411.jpg)

**Comment by tomchadwin** [comment]
OK, I've loaded the project files and vectors, and it works in Leaflet export. It doesn't in OpenLayers - I'll investigate why. Which output format were you using?

**Comment by tomchadwin** [comment]
Hrm. Never seen this error before (number 58 - https://openlayers.org/en/v4.2.0/doc/errors/#58):

```
Duplicate item added to a unique collection. For example, it may be that you tried to add the same layer to a map twice. Check for calls to map.addLayer() or other places where the map's layer collection is modified.
```

**Comment by tomchadwin** [comment]
No idea what has caused this. Can anyone figure it out?

**Comment by przytula** [comment]
using openlayers - will also check with leaflet

**Comment by przytula** [comment]
using openlayers - also checking with leaflet

**Comment by przytula** [comment]
maybe this is the error
the layers are called kermt_x 
I can see for different layers, some other files are created kermt_41 kermt_42 for kermt_4
the problem occured when adding layer kermt_55
maybe the qgis2web already created a file kermt_55 as subfile of kermt_5 and now handling file kermt_5 and trying to create also file kermt_55

**Comment by przytula** [comment]
with leaflet the final map is displayed, but layer kermt_55 is not present on this map although selected and present before generating the web-map

**Comment by boesiii** [comment]
Why do you have 55 different KERMT shapefiles?  Why not combine them into one file?

**Comment by przytula** [comment]
I am new to this soft (qgis) and did not know about this
I will try and see if posssible to have different polygon created in the same file

**Comment by boesiii** [comment]
[all_kermt.zip](https://github.com/tomchadwin/qgis2web/files/1310728/all_kermt.zip)

**Comment by tomchadwin** [comment]
@przytula Yes, a single file is the best way to approach this - thanks @boesiii.

However, I do think you've uncovered a bug, even if it's one which the single layer approach will avoid. I'll keep investigating.

**Comment by przytula** [comment]
thanks
but now all is groupd in 1 object - I joined each shape with a csv to get detailed info about each piece of land..   this we loose, with 1 shape
I will try to rename my shapes to avoid overlapping names and see

**Comment by boesiii** [comment]
You should be able to join the data from your CSV to the shapefile based on an attribute.  Which CSV column are you joining.

**Comment by przytula** [comment]
id with perceel from csv

**Comment by tomchadwin** [comment]
OK, I figured out the problem - you were right, but the specifics of this instance are interesting. Each layer when it is exported has a count digit appended, and the layers list is read *from the bottom* in order to get the stacking order correct in the webmaps. The layers therefore become:

kermt_56**0**
kermt_55**1**
kermt_54**2**

etc, etc.

By a very unusual coincidence, counting like this, your layer `kermt_5` is therefore the 52nd layer, meaning that it has "51" appended to it. This results in a layer name of "kermt_5**51**". This is obviously the same as your layer "kermt_55**1**".

I'll see if I can add another underscore between the original layer name and the count suffix, which will fix this. I believe it will only ever result in this problem in very specific and uncommon circumstances, though.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by przytula** [comment]
downloaded latest version and tested - all ok for me
thanks for all help
best regards, Guy Przytula

**Comment by tomchadwin** [comment]
Brilliant. Thanks for confirming.
