### ISSUE TITLE
Shaking map

### ISSUE THREAD

**Issue by mpbotti** [tomchadwin/qgis2web#544]
Hi Tom, my last maps suffer of a shaking issue I cannot fix. No matter the configuration I choose the problem persists, and the only solution I found is to pan or zoom the map a little bit. I believe the issue is related with the map extent, but I cannot confirm that yet. The next gif shows the map at it´s starting point (when you open the index.html).

Installed version: 2.26.0, with Leaflet output
Not Python errors... only two minor warnings...
Not tested on OpenLayers...
Sometimes the problem appears in the preview window...

![mymap](https://user-images.githubusercontent.com/29799871/30704206-644997ce-9ec8-11e7-8700-eed523f4f7b9.gif)

If you have any clue, I´ll be glad to hear ´bout it...
Regards,
M.

**Comment by boesiii** [comment]
Do you have "Highlight on hover" or "Show popups on hover" checked on?

Have you tried to narrow it down to a specific layer?

**Comment by tomchadwin** [comment]
This could be caused by the setting "Restrict to extent". Could you check? In other words, if you have that option checked, uncheck it and let us know if that stops the shake.

**Comment by mpbotti** [comment]
Hi boesiii, thx for you help. I have to answer no to your first question, both options are off. Regarding the second consult, I´ve played with both options without any luck.

Tom, you hit the nail on the head!... althogh I'm sure I´ve tested that option before, the problem is gone as soon as I´ve unchecked that tick... To get the same map reaction I´ve reconfigure "Min zoom level" and that made the trick (I understand that the "Restrict to extent" option is a shortcut to get same result...).

Many thanks to both,
M.

**Comment by tomchadwin** [comment]
Glad it worked. Thanks for letting us know.
