### ISSUE TITLE
Labelgun implementation broke OL graduated layers

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#545]
Wholeheartedly, I think. Looks difficult to fix. *sigh*

**Comment by tomchadwin** [comment]
Does anyone confirm?

**Comment by boesiii** [comment]
In a new blank project file I added a line layer, categorized the layer, and added a label then opened Q2W and the preview gave me problems, eventually I was presented with a script error and was able to export but the resulting page was blank with no errors.

**Comment by tomchadwin** [comment]
I think it might even be broken without labels.

**Comment by westiswhere** [comment]
I'm also having this issue. I'm a novice at this, but in case it is helpful, here's what I've found. 
- With OpenLayers selected; the preview shows everything but the graduated style--the outlines to my shapes show up, and the popups seem to work just fine. The one exception to this is that below all the fields that should appear in the popup, there is the number that was used in calculating the graduated style--even though that field is hidden. This field doesn't show up in the panel where you can set the header or inline label, only on the preview screen's popup.
- With Leaflet selected, however, nothing from my map is visible or able to be interacted with.
- I don't have any labels on any layer. 

I'm really very green at this, so it's possible I'm making other errors, but it does seem to be the same issue you're describing.

(Also, thanks! I've had such fun and gotten a lot out of using the plug-in, this particular bug notwithstanding.)

**Comment by tomchadwin** [comment]
@westiswhere I'm afraid that sounds like a different problem. Could you upload your project and layer files to a new issue?

**Comment by tomchadwin** [comment]
The other disappointing thing is that my attempts to get JS errors to trigger test failures #499 plainly haven't worked.

**Comment by tomchadwin** [comment]
Ah, some good news. It's only graduated that's affected. Categorized and rule-based are fine. I've got a hack of a failing output to work, so I now just need to plumb that back into the style export code. Light at the end of the tunnel, I hope.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Released as 2.27.1 and pushed to QGIS plugins repo.
