### ISSUE TITLE
Incorrect labelFont string in _style.js for labelled layers

### ISSUE THREAD

**Issue by pgauthier-git** [tomchadwin/qgis2web#549]
Version: 2.28.0 on QGIS 2.18.4

I'm exporting a labelled point layer to openlayers and I had problem making the annotation size change.
I noticed that the code in the _style.js file was looking like this:

var style_MAT_ANNOTATIONS_1 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = ""
    var labelText = "";
    size = 0;
    var labelFont = "font: '10.725px \'MS Shell Dlg 2\', sans-serif'";
    var labelFill = "rgba(0, 0, 0, 1)";
    var textAlign = "left";
    var offsetX = 8;
    var offsetY = 3;
    if (feature.get("TEXTE") !== null) {
        labelText = String(feature.get("TEXTE"));
    }
    var style = [ new ol.style.Style({
        image: new ol.style.RegularShape({radius: 1.0 + size, points: 4,
            radius2: 0, angle: Math.PI / 4, stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}), fill: new ol.style.Fill({color: 'rgba(9,219,44,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill)
    })];

    return style;
}

Changing the font size was not resulting in any change in the resulting web page and some investigation showed that the labelFont string was incorrect.

Removing the extra ' and font: fixed the issue:
var labelFont = "10.725px \\'MS Shell Dlg 2\\', sans-serif";

Thanks,
Pierre

**Comment by tomchadwin** [comment]
Ah, thanks very much for spotting that. Looking into it now.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by pgauthier-git** [comment]
Tested as fixed.

**Comment by tomchadwin** [comment]
Splendid. Thanks for confirming so quickly.

**Comment by tomchadwin** [comment]
Released as 2.29.0 and pushed to QGIS plugins repo.
