### ISSUE TITLE
Avoiding unnecessary reproject/warp raster files

### ISSUE THREAD

**Issue by geoglis** [tomchadwin/qgis2web#552]
Am I right saying, that simple geotiff files are always reprojected to CRS 3857, independent from the project CRS and the raster CRS, as mentioned in #267 ? 

I just tried to publish a bunch of solitary raster files and a WMS, all together in one CRS, but the rasters are always reprojected with overlapping wedges at their borders, despite setting "match project CRS".

Is there a means to prevent qgis2web from reprojecting the raster and using them in their original CRS 4647, for example changing the qgis2web-code slightly as in #33 ?  The WMS also makes problems in my configurations, apparently as well due to the reprojections?

Here some OpenLayers code fragments and some files from one of my tests:

**index.html:**
```
<script src="http://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>
        <script>proj4.defs('EPSG:**4647**','+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=32500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs');</script>

```
**layer.js:**
```
                            source: new ol.source.ImageStatic({
                               url: "./layers/dop20rgb_32513_5972_1_sh_20140.png",
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
                                projection: 'EPSG:**3857**',
                                alwaysInRange: true,
                                //imageSize: [5000, 5000],
                                imageExtent: [1023897.968988, 7150537.458860, 1025597.089768, 7152230.713869] 
```

**qgis2web.js:**
```
var map = new ol.Map({
    controls: ol.control.defaults({attribution:false}).extend([
        expandedAttribution,new measureControl()
    ]),
    target: document.getElementById('map'),
    renderer: 'canvas',
    overlays: [overlayPopup],
    layers: layersList,
    view: new ol.View({
         maxZoom: 28, minZoom: 1, projection: 'EPSG:**4647**'
    })
});
```

BTW: #551, that my colleague opened, is meanwhile corrected manually from me in layers.js

Any help and tips ar appreceated.

[OL-Codeparts.zip](https://github.com/tomchadwin/qgis2web/files/1349191/OL-Codeparts.zip)

**Comment by tomchadwin** [comment]
Yes, I believe you are right, and rasters are warped to 3857 *even when "Match project CRS" is checked*. That doesn't seem right to me, and needs to be investigated.

The issue has probably not been raised as much as it might because OL reprojects rasters client-side. However, warping a raster from the correct CRS into the wrong one and then back again certainly seems foolish.

**Comment by tomchadwin** [comment]
I've made an initial commit to master to start to investigate this. Rasters are now **not** reprojected if:

"Match CRS" is checked

and

layer CRS is the same as project CRS

It looks OK in OpenLayers, but is not yet working in Leaflet. Can you have a look at the OpenLayers output and see if it fixes your issue?

**Comment by tomchadwin** [comment]
The second part of this issue is that, when a warp **is** required, it's being warped to EPSG:3857, not the project CRS. I've tried changing this, but it's not working. When you test, can you let me know whether you think further changes are still required? In other words, is the **correct** transform being applied?

**Comment by geoglis** [comment]
It works nearly, raster are no more reprojected, fine. But my geotif files are stored in the layers directory with file extension png, but they are still tifs. There is an artificial renaming in the code, I think.
Bytheway: They are bigger now, my uncompressed geotifs were 71 MB, now they are 95 MB, both same size and uncrompressed and only 71 MB in RAM, says InrfanView.

**Comment by tomchadwin** [comment]
OK, I'll look at the remaining incorrect 3857 code - thanks for pointing it out.

Thanks for spotting the TIFF/PNG issue. That's my error - it's just renaming the file. However, we will have to convert to PNG, even if no warp is required, as TIFFs will not display in the browser. I'll look into it.

**Comment by tomchadwin** [comment]
In master, the TIFFs are now converted to PNGs even if no reprojection is necessary. Can you test and report back. I'll look atthe the extent CRS issue next.

**Comment by geoglis** [comment]
Not really ok, now png are created in the original CRS, but they a wrong, much too small and no content, see attachment. Normaly the have about 40 MB. Maybe the gdal_translate paramters are not ok?
Why not gdal_warp as usual with s_srs and t_srs the same?
[layers.zip](https://github.com/tomchadwin/qgis2web/files/1362825/layers.zip)

**Comment by geoglis** [comment]
Still nearly the same situation, pngs are defect. s. attachment.
How can I debug the gdal_transform calls and its parameters?
[layers_20170910_UTC+1_15_46.zip](https://github.com/tomchadwin/qgis2web/files/1368660/layers_20170910_UTC.1_15_46.zip)

**Comment by geoglis** [comment]
Yeah, it looks like being ok now. I will test it tomorrow again with a larger number of different arial photos. Thanks!

**Comment by tomchadwin** [comment]
I've only implemented this change in OpenLayers, and not yet in Leaflet, so I'll do that as soon as I can. I did get one result I didn't like the look of in OpenLayers. I'll try to recreate and describe here to see whether you can recreate.

**Comment by geoglis** [comment]
Ok, let me know. I will comment my further tests here tomorrow.

**Comment by tomchadwin** [comment]
OK, here's how I recreate what might be a problem. Please note that I am not a GIS person, so this could simply be my not understanding CRS/projection issues:

1. Create a new QGIS project
2. From the `/test/data/control` folder within the qgis2web plugin directory, add the airports vector layer (.shp) and the test raster layer (.png)
3. Right-click the airports layer in the ToC and click "Set Project CRS from Layer" to project your project in EPSG: 2964
4. Right-click the test layer in the ToC and click "Zoom to Layer" - you should see the raster rotated to a diamond orientation
5. Start qgis2web
6. In the qgis2web dialog, check "Match project CRS"
7. Add a basemap for reference
8. Select OpenLayers webmap format
9. Update preview or Export

I see the basemap, rotated with respect to EPSG:3857, but no raster.

1. Can you conform?
2. If so, is there a reason this is not a failure?

**Comment by tomchadwin** [comment]
Ah, I think I've found and corrected my error. Do please test thoroughly (OpenLayers only) and let me know if you think it is working.

**Comment by geoglis** [comment]
Somewhere you mixed up width and hight of the rasters images when converting the raster, my raster images are distorted, dimension of width of original raster is now in transformed raster image the dimension of hight and vice versa. I didn't find the place in the code. And the WMS layer are not displayed, I will investigate it further.

**Comment by tomchadwin** [comment]
Leave WMS - it's unrelated, so another issue can be opened if required.

Re: width/height, I need a couple of details:

1. Is the exported raster file itself OK if opened outside the map?
2. Are you exporting to OpenLayers or Leaflet?

**Comment by geoglis** [comment]
Raster file looks distorted outside, in OL it's ok :-) (reprojected??)

**Comment by tomchadwin** [comment]
To confirm:

1, The source raster is in the same projection as the project?
2. You have checked "Match project CRS" in qgis2web?

**Comment by geoglis** [comment]
Yes to both

**Comment by tomchadwin** [comment]
Any chance you can upload your source raster?

**Comment by geoglis** [comment]
Here is [one file](https://app.box.com/s/wva7hgiq3gfgbuxp4opwdnc5jnxy92ez) from several, don't be confused by the black area on the right, it's ok. It has 8056 x 6544 pixel, the resulting in OL dir .\layers has 6544 x 8056 pixel.

**Comment by geoglis** [comment]
Here another smaller test with QGIS 2.14.19 and the master from yesterday (where to version numbers?), one with "match CRS" and one without. OL-Clients are OK, but raster image in "mathc CRS" version in dir ./layers is distorted, raster quality is therfore worse. Project and original file included.
[raster_XY.zip](https://github.com/tomchadwin/qgis2web/files/1374877/raster_XY.zip)
Didn't you add a transform in your code for the case of CRS match in project and layer, there might be the error at coosing X and Y dimensions of the raster image.

**Comment by tomchadwin** [comment]
OK, I think I found the X/Y swap and fixed it in master. The odd thing is that it's been there for as long as I can remember. Can you test and report back?

**Comment by tomchadwin** [comment]
Will close for now as fixed. Let us know if it works for you, or if you still have issues.
