### ISSUE TITLE
OpenLayers not working with custom projection (coordinate system)

### ISSUE THREAD

**Issue by swen100** [tomchadwin/qgis2web#553]
Hi Tom,

we have a problem with the OpenLayers-export with a coordinate system other than wgs84 or webmercator. After exporting, the definition of the map-variable inside qgis2web.js contains only the term of the epsg-code of the coordinate system. When we open the client, no wms-request gets send. 
After some investigating I found a solution: replace the epsg-code with a projection-variable. Then it works fine.

inside qgis2web.js before editing:
```js
...
var map = new ol.Map({
    controls: ol.control.defaults({attribution:false}).extend([
        expandedAttribution
    ]),
    target: document.getElementById('map'),
    renderer: 'canvas',
    overlays: [overlayPopup],
    layers: layersList,
    view: new ol.View({
        maxZoom: 28, minZoom: 1, projection:  'EPSG:4647'
    })
});

map.getView().fit([32512426, 5971056, 32514555, 5972430], map.getSize());
...

```

after:
```js
...
var projObj = new ol.proj.Projection({
    code: 'EPSG:4647',
    units: 'm',
    extent: [32000000,5900000,33000000,6000000]
});
var map = new ol.Map({
    controls: ol.control.defaults({attribution:false}).extend([
        expandedAttribution
    ]),
    target: document.getElementById('map'),
    renderer: 'canvas',
    overlays: [overlayPopup],
    layers: layersList,
    view: new ol.View({
        maxZoom: 28, minZoom: 1, projection: projObj
    })
});

map.getView().fit([32512426, 5971056, 32514555, 5972430], map.getSize());
...
```
Extremly important at this point was, that the projection-variable contains informations about an extent. Otherwise it didn't work neither. Does the wms-layer-entry in qgis contain this informationen?

my index.html contained:
```html
<script src="http://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>
<script>proj4.defs('EPSG:4647','+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=32500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs');</script>
```

my layer-definition was:
```js
var lyr_onmapsLayoutNetze_1 = new ol.layer.Tile({
    source: new ol.source.TileWMS(({
        url: "http://onmaps.de/phpWMS4?key=secret",
        attributions: [new ol.Attribution({html: '<a href=""></a>'})],
        params: {
            "LAYERS": "onmaps_pipeline",
            "TILED": "true",
            "VERSION": "1.1.0"
        }
    })),
    title: "onmaps, Layout Netze"
});
```
Here u can find an offical example for wms using a custom projection:
http://openlayers.org/en/latest/examples/wms-image-custom-proj.html

**Comment by tomchadwin** [comment]
Thanks for your patience. I've not been aware of this issue - I've frequently tested OL with "Match CRS" checked, and the output seems to have been correct (to my non-geographer eyes). I'm not aware of the requirement to define the extent, but perhaps it is CRS-dependent.

If defining an extent is a good approach, I don't know how easy it is to get an extent from a CRS. I'll investigate.

Can anyone who understands projections more than me (most people) else shed light on this?

**Comment by tomchadwin** [comment]
Can you upload your project file so I can try to recreate the issue?

**Comment by geoglis** [comment]
Here is an example config, still not corrected. I think for the extent you can take the values you use when the option "fit to layers extent" in Scale/Zoom  is choosen. I am in a hurry, more tomorrow.
[with_WMS_qgis2web_2017_10_17-14_33_00_983000.zip](https://github.com/tomchadwin/qgis2web/files/1391157/with_WMS_qgis2web_2017_10_17-14_33_00_983000.zip)

**Comment by tomchadwin** [comment]
No, I meant your original QGIS project and layers, not the exported map. Are yo uable to upload the `.qgs`?

**Comment by tomchadwin** [comment]
Closing without feedback. Comment and I can reopen.

**Comment by geoglis** [comment]
Hi,
here is a project file and the web result with the actual version of qgis2web, with WMS not working. 
After inserting a projection object with an extent and referencing it in var map ist works:

var projObj = new ol.proj.Projection({
    code: 'EPSG:4647',
    units: 'm',
    /* extent: [32000000,5900000,33000000,6000000] */
	extent: [32502277,5970203,32513486,5971984]
});

var map = new ol.Map({
.........
         /* maxZoom: 28, minZoom: 1, projection: 'EPSG:4647' */
         maxZoom: 28, minZoom: 1, projection: projObj
    })
});

Here I used a very narrow manual extent for testing.
I think in qgis2web you should use those values, that you use with the option "Scale/Zoom Extent: Fit to layer extent" (and "restrict to extent"). It actually gives this result in var map:

extent: [32195914.757476, 5205164.484426, 33032085.493082, 6117225.183748], maxZoom: 28, minZoom: 1, projection: 'EPSG:4647'

Using this extent in the new var projObj gives a good result for the whole project extent.

[qgis2web_2017_11_06-08_26_06_600000.zip](https://github.com/tomchadwin/qgis2web/files/1445386/qgis2web_2017_11_06-08_26_06_600000.zip)
[AKW_Brunsbuettel_teil.zip](https://github.com/tomchadwin/qgis2web/files/1445441/AKW_Brunsbuettel_teil.zip)

**Comment by tomchadwin** [comment]
OK, this is interesting. I'm using master branch, which has new `getFeatureInfo` code for querying WMSes. I can confirm that the tiles do not render, but if I click, I get feature info back (ignoring an authentication prompt).

Still trying to work out what's stopping the tiles from being requested. Adding the definition as the plugin already does should be enough, though I see that it does not specify the projection in the WMS layer definition (as opposed to the static image layer, which, as you can see, does specify the projection).

**Comment by tomchadwin** [comment]
Right, I still don't have an explanation, but can you try this. Instead of the changes you have been making, can you add this line to the beginning of `layers/layers.js`:

```javascript
ol.proj.get("EPSG:4647").setExtent([32195914.757476, 5205164.484426, 33032085.493082, 6117225.183748]);
```

That seems to make it work for me. I found another instance of this issue online, but with no resolution:

https://gis.stackexchange.com/questions/146796/non-default-projection-requires-extent-when-using-ol-layer-tile-in-openlayers-3

@ahocevar did you ever come across another instance of this problem? We seem to be experiencing it here, and there was no answer to that GIS.SE question, though I see you commented.

**Comment by tomchadwin** [comment]
OK, I've made a change to master branch here, adding in the projection extent as best I can determine it. Can you test and report back? I'll close for now.

**Comment by geoglis** [comment]
I will test it tomorrow, Thanks!

**Comment by geoglis** [comment]
Ok, it works, but only restricted in the initial extent the client starts, no zooming out possible.
What's about using the value you get with the option "Scale/Zoom Extent: Fit to layer extent" (and "restrict to extent"). In my map project they are very big:
[14455509.193560, -10650436.140445, 48320255.479410, 10650436.140445]
but the client works and I can use the WMS when zooming out of the initial extent.

**Comment by geoglis** [comment]
not completly solved, my workaround with the big extent mentioned above was manually edited. When you use the extent value similar to the option "Scale/Zoom Extent: Fit to layer extent" for the extent borders of the web project, then it might work good.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.
