### ISSUE TITLE
Why are you remove categorization? this generate various errors.

### ISSUE THREAD

**Issue by maellson** [tomchadwin/qgis2web#554]
The remotion of categorization was generate various error in script, one of principals this layers list, thatr simply stoped.

**Comment by tomchadwin** [comment]
Categorization has not been removed, at least not intentionally. Can you give more details of the issue you are having?

**Comment by tomchadwin** [comment]
I'll close this for now - please do reply with more info, and I'll reopen.

**Comment by tomchadwin** [comment]
This could have been as a result of another bug, which is hpoefully now fixed. Please can you update to the latest version of the plugin and try again?

**Comment by tomchadwin** [comment]
Released as 2.29.0 and pushed to QGIS plugins repo.

**Comment by maellson** [comment]
The new version is same problem.
farte of error:
"Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y (file:///E:/DOC_MAELSON/Documents/MAELSON/KMLS%20BAIRROS/NET/qgis2web_2017_10_10-08_50_21_775000/js/leaflet.js:1:2054)
    at Function.v.extend (file:///E:/DOC_MAELSON/Documents/MAELSON/KMLS%20BAIRROS/NET/qgis2web_2017_10_10-08_50_21_775000/js/leaflet.js:1:15095)
    at file:///E:/DOC_MAELSON/Documents/MAELSON/KMLS%20BAIRROS/NET/qgis2web_2017_10_10-08_50_21_775000/js/leaflet.pattern.js:6:34
    at file:///E:/DOC_MAELSON/Documents/MAELSON/KMLS%20BAIRROS/NET/qgis2web_2017_10_10-08_50_21_775000/js/leaflet.pattern.js:6:7077 "

and in the HTML file example:
function style_VELAME_5_0(feature) {
            switch(feature.properties['TIPO_DE_CO'].toString()) {**Uncaught TypeError: Cannot read property 'toString' of null**
                default:
                    return {
                pane: 'pane_VELAME_5',
                opacity: 1,
                color: 'rgba(0,0,0,0.98)',
                dashArray: '',
                lineCap: 'butt',
                lineJoin: 'miter',
                weight: 1.0, 
                fillOpacity: 1,
                fillColor: 'rgba(203,201,201,0.98)',
            }
