### ISSUE TITLE
Set interactive:false for some layers

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#555]
Map with more layers. Some of them (all lines) should not use hover effect and should not react on click. 
Now I have to edit finished map - index.html and put "interactive:false," in code for these layers. 

Is it possible to set it in qgis or qgis2web before export? 
Maybe new option.

**Comment by tomchadwin** [comment]
To stop popups, can you try setting all that layer's edit widgets to Hidden? As for per-layer highlight, I think that's #132

**Comment by kelv-cz** [comment]
"layer's edit widgets to Hidden"  - please,  where is in qgis this option?

-

**Comment by tomchadwin** [comment]
Double-click the layer in the layers list, click "Fields" in the left-hand pane of the dialog, and then click the buttons in the "Edit widget" column to change them.

**Comment by kelv-cz** [comment]
Thanks, 
with all fields "hidden" is no effect after click, but hover effect (yellow lines) is active.  Could I set interactive:false in qgis or in window "Export to web map"?  Or only solution is to edit exported index.html in code?

**Comment by tomchadwin** [comment]
Yes, as I say, there is currently only a single "hover" setting across the whole map. I'll close this issue, because the requested feature to set hover highlighting per-layer is already raised in #132.

**Comment by riccardoklinger** [comment]
Sorry for "opening" this issue once more. Assuming I have a layer with lots of fields it would be more convenient to leave the fields as they are and simply add a "interactive" checkbox to the layer export dialog which adds the interactive:false attribute to the js for the layer. --> will look into it and create a PR.
