### ISSUE TITLE
KeyError: 3006 when exporting vector map

### ISSUE THREAD

**Issue by LukeWB** [tomchadwin/qgis2web#556]
I've run into a problem with exporting a (fairly large) vector shapefile using QGIS 2.12.12 and QGIS2Web 2.28.

Whenever I try export the map I run into the following error:

An error has occurred while executing Python code: 

KeyError: 3006 
Traceback (most recent call last):
  File ....\qgis2web\maindialog.py", line 336, in saveMap
    feedback=self.feedback)
  File  ....\olwriter.py", line 86, in write
    folder=dest_folder)
  File  ....\olwriter.py", line 122, in writeOL
    popup, json, restrictToExtent, extent, feedback)
  File  ....\qgis2web\utils.py", line 183, in exportLayers
    iface, extent, precision, crs, optimize)
  File  ..../.qgis2/python/plugins\qgis2web\utils.py", line 196, in exportVector
    cleanLayer = writeTmpLayer(layer, popup, restrictToExtent, iface, extent)
  File  ..../.qgis2/python/plugins\qgis2web\utils.py", line 128, in writeTmpLayer
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 3006

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.12 Las Palmas, a6c461b 

I've checked that all the geometries are valid and tried restricting the extend to the canvas with no joy.  And when I try use the console in QGIS2Web nothing seems to write to it when the error fires.

**Comment by tomchadwin** [comment]
OK, I've tried adding a fix to master. Are you able to test it and report back? Thanks to @Gustry for the fix!

**Comment by LukeWB** [comment]
Looks like the fix has resolved the problem. Thanks heaps!

**Comment by tomchadwin** [comment]
Splendid. Thanks for letting us know.

**Comment by tomchadwin** [comment]
Released as 2.29.0 and pushed to QGIS plugins repo.
