### ISSUE TITLE
Raster layer failing to load in browser, missing underscore in filename

### ISSUE THREAD

**Issue by mvdmerwe** [tomchadwin/qgis2web#558]
index.html contains the line:

var img_SeriousCrashHM_0 = 'data/myRasterLayer_0.png';

While the file's actual path is: 

data/myRasterLayer0.png

**Comment by mvdmerwe** [comment]
Apologies, I saw this issue has been reported earlier

**Comment by tomchadwin** [comment]
Released as 2.29.0 and pushed to QGIS plugins repo.
