### ISSUE TITLE
No polygon layer in leaflet output from a categorized choropleth

### ISSUE THREAD

**Issue by DOSull** [tomchadwin/qgis2web#559]
When I make a leaflet map from a categorized polygon layer the polygon layer fails to appear in the exported web map.  My Firefox web console reports this error:

ReferenceError: style_tractsOGRGeoJSONMultiPolygon_0_0 is not defined

so something to do with how the styling information is getting built and stored.  Unfortunately, my JS is not up to debugging further,.

The Openlayers map output is as expected.  I've successfully used earlier versions of qgis2web to make such maps.

QGIS 2.18.13 Las Palmas
qgis2web 2.28.0

**Comment by tomchadwin** [comment]
I believe this issue has been fixed in current master, and I hope to release a new version in the next few days which includes the fix.

**Comment by tomchadwin** [comment]
The issue was related to https://github.com/tomchadwin/qgis2web/issues/551 (thought that was rasters).

**Comment by tomchadwin** [comment]
Released as 2.29.0 and pushed to QGIS plugins repo.

**Comment by DOSull** [comment]
I am not sure if this has fixed the problem.  I still get the Reference error to a _0_0 suffixed style issue and no polygons appear in the output map. The OL3 map is fine, and the leaflet map is fine if the polygons are 'single symbol'; the problem only arises when the polygons are classified into different colors.

**Comment by tomchadwin** [comment]
OK, I've tried to recreate this using the QGIS test data and qgis2web test style (the files are in the `test` folder within the plugin installation folder). It works fine. Are you able to upload your project and layer so we can have a look and see if we can recreate the bug?

**Comment by DOSull** [comment]
Here's a zip with the project and two layers that does it on my machine. I made the smaller Alameda county selection (362 tracts) to test if it was the number of objects maybe causing the issue, but that layer doesn't work either.
[qgis2web-559.zip](https://github.com/tomchadwin/qgis2web/files/1395108/qgis2web-559.zip)

**Comment by tomchadwin** [comment]
Hrm. I'm afraid that project works for me, with either layer or, indeed, both. Can you definitely confirm the version of qgis2web? Very odd. Perhaps you could upload your exported map? I can't figure this out yet.

**Comment by DOSull** [comment]
Thanks for the speedy responses! Here's the exported map.
[qgis2web_2017_10_18-08_12_08_418145.zip](https://github.com/tomchadwin/qgis2web/files/1395153/qgis2web_2017_10_18-08_12_08_418145.zip)
According to plugin manager the version is definitely 2.29.0. I'm on a mac if that has any bearing.

**Comment by tomchadwin** [comment]
OK, the whole style function is missing. Can you look at the qgis2web log and see if anything is reported there (View > Panels > Log Messages Panel > qgis2web)?

**Comment by DOSull** [comment]
There is no qgis2web specific log that I can see, just the 'Plugins' tab.  That has the following:

2017-10-18T08:11:18	0	Loaded Georeferencer GDAL (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libgeorefplugin.so)
2017-10-18T08:11:18	0	Loaded GPS Tools (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libgpsimporterplugin.so)
2017-10-18T08:11:18	0	Loaded Heatmap (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libheatmapplugin.so)
2017-10-18T08:11:18	0	Loaded Interpolation plugin (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libinterpolationplugin.so)
2017-10-18T08:11:18	0	Loaded Raster Terrain Analysis plugin (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/librasterterrainplugin.so)
2017-10-18T08:11:18	0	Loaded Road graph plugin (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libroadgraphplugin.so)
2017-10-18T08:11:18	0	Loaded Spatial Query Plugin (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libspatialqueryplugin.so)
2017-10-18T08:11:18	0	Loaded Topology Checker (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libtopolplugin.so)
2017-10-18T08:11:18	0	Loaded Zonal statistics plugin (Path: /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis/libzonalstatisticsplugin.so)
2017-10-18T08:11:18	0	Loaded Clusterpy - Spatially constrained clustering (package: clusterpy_qgis_plugin)
2017-10-18T08:11:19	0	Loaded Contour plugin (package: contour)
2017-10-18T08:11:19	0	Loaded Elevation (package: elevation)
2017-10-18T08:11:19	0	Loaded Freehand raster georeferencer (package: FreehandRasterGeoreferencer)
2017-10-18T08:11:20	0	Loaded MetaSearch Catalogue Client (package: MetaSearch)
2017-10-18T08:11:20	0	Loaded mmqgis (package: mmqgis)
2017-10-18T08:11:20	0	Loaded PCA (package: PrincipalComponents)
2017-10-18T08:11:21	0	Loaded Processing (package: processing)
2017-10-18T08:11:21	0	Loaded qgis2web (package: qgis2web)
2017-10-18T08:11:21	0	Loaded QuickMapServices (package: quick_map_services)
2017-10-18T08:11:21	0	Loaded QuickOSM (package: QuickOSM)
2017-10-18T08:11:21	0	Loaded Rectangles Ovals Digitizing (package: rectovalDigit)
2017-10-18T08:11:22	0	Loaded SimpleSvg (package: simplesvg)
2017-10-18T08:11:22	0	Loaded TileLayer Plugin (package: TileLayerPlugin)
2017-10-18T08:11:22	0	Loaded Indicatrix mapper (package: tiss)
2017-10-18T08:11:22	0	Loaded DB Manager (package: db_manager)

Under the 'Python warning' tab, there is this:

2017-10-18T08:11:19	1	warning:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/Users/dosullivan/Library/Python/2.7/lib/python/site-packages/mpl_toolkits': missing __init__.py
			  file, filename, etc = imp.find_module(subname, path)

followed by a bunch more

**Comment by tomchadwin** [comment]
I'm a bit baffled, to be honest. I can try and fire a Mac back up, but it will take some work to get up-to-date, as I've not used it for a while.

**Comment by DOSull** [comment]
Hmm.  If you're baffled, I'm clueless!  I was looking in in File > Preferences > Advanced > Python Plugins, and see that there is a setting for qgis2leaf set to 'true' still there (I used to have that plugin many months ago).  Switching it to 'false' doesn't fix the problem, but I wonder if there is some system clean up issue lurking in there somewhere.

**Comment by tomchadwin** [comment]
You're sure there's no qgis2web tab in the log messages panel? No sideways scroll buttons to reveal hidden tabs?

**Comment by DOSull** [comment]
There doesn't seem to be - no sideways scroll available. I might see if I can completely uninstall and reinstall with only qgis2web present, see if it works then, although I tried disabling QuickMapServices and QuickOSM which seem the most obvious potential conflicts and that didn't help.

**Comment by tomchadwin** [comment]
No, I wouldn't spend time on that - it didn't sound like your installation is bad. Try opening the QGIS Python console, highlighting one of the layers in the QGIS layers list, and typing the following into the console:

```python
iface.activeLayer().rendererV2()
```

What is the output in the console?

**Comment by DOSull** [comment]
Too late... :( I reinstalled, although it seems to have made no difference.  Here's the response in the console:

<qgis._core.QgsGraduatedSymbolRendererV2 object at 0x11d8028a0>

I'm away from my machine for an hour or so now...

**Comment by tomchadwin** [comment]
OK, another command for the console, with the layer still highlighted in the QGIS layers list:

```python
iface.activeLayer().rendererV2().ranges()[0].symbol().symbolLayerCount()

**Comment by DOSull** [comment]
-4555056

**Comment by tomchadwin** [comment]
Really? The layer was definitely highlighted? I get (and it should be): 1.

**Comment by DOSull** [comment]
Yes. Further if I up-arrow and repeat the command, I get different negative numbers each time.

**Comment by tomchadwin** [comment]
Just for my own sanity, can you copy and paste the code into the console? You probably did that before, but just in case of typos.

**Comment by DOSull** [comment]
apologies for the existential crisis, but I did copy and paste before - does this mean there is something up with my installation? I assume you are using this number to loop over things that need adding to the map... but only for the leaflet output for some reason (keep in mind OL3 is working)

**Comment by tomchadwin** [comment]
The output should be the number of symbol layers in the symbol for your first range in your graduated layer. It only has one symbol layer, so it should output 1, as it does in my installation. I'm afraid I just have no idea what could cause the weirdness you are getting. I'll ask on the QGIS dev list and see if anyone has come across this before (I've already asked on QGIS Gitter).

**Comment by DOSull** [comment]
I should note that this is for a lab assignment in a class I teach, and that my teaching assistant has also had the problem with getting a leaflet output (also on a mac) so I don't think this is exclusive to my installation (although my TA hasn't run these checks)

**Comment by tomchadwin** [comment]
Also on a Mac?

**Comment by DOSull** [comment]
also on a mac, yes

**Comment by tomchadwin** [comment]
Asked on QGIS dev mailing list: https://lists.osgeo.org/pipermail/qgis-developer/2017-October/050191.html

**Comment by tomchadwin** [comment]
OK, in some bizarre coincidence, I was working on something totally different, but in the process of debuggin that, I got the random large negative number for `symbolLayerCount()`. This allowed to me dig around a big, and correct a couple of things which I can now see failed with those negative numbers. I;ve committed those to master. Can you test, and report back to let us know if there has been any improvement?

**Comment by DOSull** [comment]
There doesn't seem to be any improvement, although I am not accustomed to installing from a zip file and may have done this incorrectly.

**Comment by tomchadwin** [comment]
Did you restart QGIS after unzipping into the plugin folder?

**Comment by DOSull** [comment]
I did restart.  I'm still getting -ve numbers reported in the console in response to the iface... command, although I suppose that's expected.  OpenLayers map is still fine.  Leaflet map still has no polygons, and has the missing style error in the web console.

**Comment by tomchadwin** [comment]
That's disappointing. While I do not understand why the negative numbers appear, their presence should not now cause an error. I'll look further into the code and see if I can find any other instances where the fix I implemented might also be required.

**Comment by tomchadwin** [comment]
Also, just to confirm, are you unzipping the master version into the folder listed in the Plugin Manager as the qgis2web installation folder?

**Comment by tomchadwin** [comment]
Right, I found some more incorrect code, and applied the same fix. Can you download master and try again?

**Comment by DOSull** [comment]
That seems to have done the trick. Not thoroughly tested, but I can now make a Leaflet choropleth map! Really appreciate the effort on this.

**Comment by tomchadwin** [comment]
Ah, splendid news. Thanks for your patience, for testing and reporting back, and for uncovering the bug. I still don't know what causes those negative numbers (and no reply to my question on the QGIS dev mailing list), but given that they are there, at least we are now handling them.
