### ISSUE TITLE
HTML display option for popups

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#56]
Make use of the QGIS layer properties display tab setting to display HTML in the popup. This will allow us to get rid of the html_exp functionality from qgis2leaf.

**Comment by tomchadwin** [comment]
Struggling to find the map tip settings in the QGIS API...

**Comment by miloskroulik** [comment]
Were you looking for http://qgis.org/api/classQgsMapTip.html?

**Comment by tomchadwin** [comment]
That's the map tip itself. I want the HTML content.  Is it  QgsVectorLayer::displayExpression()

**Comment by tomchadwin** [comment]
No longer really needed with popup header options.
