### ISSUE TITLE
JavaScript Problem message appears with PIN labels

### ISSUE THREAD

**Issue by UnderJollyRoger** [tomchadwin/qgis2web#562]
I have a Parcel map with 2692 features. The only labels I have on are the 16 digit parcel identifying number or PIN. In Labels I give them drop shadows and buffers. In the Export to Web Map window I give it the OSM B&W basemap and fill it out thus:
![image](https://user-images.githubusercontent.com/32503258/32063079-eb35b838-ba3b-11e7-9ee7-b62bdf51b3e7.png)

When I hit the Update preview button there is a 10 second delay then this message appears:
![image](https://user-images.githubusercontent.com/32503258/32062723-f68244d2-ba3a-11e7-9224-dc2b34d9c45c.png)
I select No. There is another pause then the message comes back. I hit No again. Then the map draws but all the PINs are bunched up making it not at all legible. They shouldn't even be displayed at full extent because back in Label Rendering I set the scale-based visibility to min: 1, max: 1200. There is significant loss of drawing speed and once zoomed in to larger scales where the PINs should be visible they aren't. If I export and open the html it has the same errors. Here I'm zoomed in all the way in the web app where you should see the PINs:
![image](https://user-images.githubusercontent.com/32503258/32064198-cc81b9c0-ba3e-11e7-92b2-81e4e9d547e2.png)

1. I'm using QGIS 2.18.13 and qgis2web version 2.29.0
2. Could not find related issue
3. Confirmed by repeating the process.
4. If I simply turn the labels off the map with draw fine with no lack of drawing speed and the Java message does not appear. I seems to work as it should.
5. 
-No Python error.
-Link to data: http://www.willcogis.org/website2014/gis/Data/Wilmington.zip 

Please let me know if you need anymore info. Thank you.
Jared

**Comment by tomchadwin** [comment]
The popup saying there is a problem with the script doesn't happen for me once the map is exported and opened in Chrome, so I wouldn't worry about it, but just click through as you have.

s for the scale-dependent labels, I think you might have uncovered an incompatibility with Labelgun (@jamesmilneruk), which might be tricky to solve. I'll try to look into it.

**Comment by JamesMilnerUK** [comment]
@UnderJollyRoger can you please post: 
The browser you're using
Any output from the web console of the browser (in Chrome Ctrl+Shift+I)

**Comment by UnderJollyRoger** [comment]
I'm using Firefox.
It's Ctrl+Shift+J from FF. I selected all of what I'm guessing is the output:

`12:40:43.243: ErrorCollector: enabled  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.243: Capabilities: registered test hasSVG; classname=has-svg  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.244: Capabilities: registered test hasCSSOM; classname=has-cssom  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.244: Capabilities: registered test hasHover; classname=has-hover  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.244: Capabilities: registered test hasTouch; classname=no-touch  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.245: Capabilities: registered test hasAnimation; classname=has-anim  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.259: bcTruncate 1 (4ms; total: 4ms):  <div class="bd">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.417: Control: got DOMReady  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.433: creating inline player view  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.441: reading/clearing playlist state  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.474: PeekabooList refresh: discography  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.488: bcTruncate 2 (2ms; total: 6ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.488: bcTruncate 3 (0ms; total: 6ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.489: bcTruncate 4 (0ms; total: 6ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.489: bcTruncate 5 (0ms; total: 6ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.489: bcTruncate 6 (0ms; total: 6ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.490: bcTruncate 7 (1ms; total: 7ms):  <p>  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.490: bcTruncate 8 (0ms; total: 7ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.490: bcTruncate 9 (0ms; total: 7ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.491: bcTruncate 10 (1ms; total: 8ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.491: bcTruncate 11 (0ms; total: 8ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.492: bcTruncate 12 (0ms; total: 8ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.492: bcTruncate 13 (0ms; total: 8ms):  <span class="comment-contents">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.492: bcTruncate 14 (0ms; total: 8ms):  <p class="section-title">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.492: bcTruncate 15 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.493: bcTruncate 16 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.493: bcTruncate 17 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.493: bcTruncate 18 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.493: bcTruncate 19 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.493: bcTruncate 20 (0ms; total: 8ms):  <span class="comment-author">  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.574: Facebook SDK loaded  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:40:43.677: Google Plus SDK loaded  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:41:06.414: playlist loading track 0  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:41:06.418: Cookie comm channel playlist started listening.  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:41:06.419: Cookie comm channel playlist sending message stop Array [ "stop" ]  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:50:15.932: playlist loading track 0  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:50:15.935: Cookie comm channel playlist sending message stop Array [ "stop" ]  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:56:04.879: playlist loading track 0  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
12:56:04.906: Cookie comm channel playlist sending message stop Array [ "stop" ]  global_head_bundle_min_bb9343d9530b9653fbbf9f1304c1a722.js:340:37
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. y@file:///C:/qgis2web/Wilmington%20Zoning/qgis2web_2017_10_26-12_52_22_232000/js/leaflet.js:5:2048
v.extend@file:///C:/qgis2web/Wilmington%20Zoning/qgis2web_2017_10_26-12_52_22_232000/js/leaflet.js:5:14706
@file:///C:/qgis2web/Wilmington%20Zoning/qgis2web_2017_10_26-12_52_22_232000/js/leaflet.pattern.js:6:26
@file:///C:/qgis2web/Wilmington%20Zoning/qgis2web_2017_10_26-12_52_22_232000/js/leaflet.pattern.js:6:2
  leaflet.js:5:1905
TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "PLACES_AUTOCOMPLETE_1ST_RESULT_TIME_MS", key: "null"  TelemetryStopwatch.jsm:363
`

**Comment by tomchadwin** [comment]
@jamesmilneruk I don't think there is a problem in Labelgun itself, just that the code qgis2web uses to show and hide labels at different zooms worked without Labelgun, but needs to be rewritten to accommodate it. I'll try to snip out that code to post here to see if you have any thoughts.

**Comment by tomchadwin** [comment]
```javascript
if (map.hasLayer(layer)) {
    if (map.getZoom() <= minZoom && map.getZoom() >= maxZoom) {
        layer.eachLayer(function (layer) {
            layer.openTooltip();
        });
    } else {
        layer.eachLayer(function (layer) {
            layer.closeTooltip();
        });
    }
}
```

**Comment by tomchadwin** [comment]
OK, I might have fixed the issue which made labels appear at all scales. Can you try current master and report back?

**Comment by UnderJollyRoger** [comment]
@tomchadwin It's still hung up on labels. I tried two different things.

1.) Labels will not draw with scale-based visibility on (I have them drawing once it's at 1:2000 and larger). When you at first open the link (it opens at scale that shows the whole city) all the labels draw but are a jumbled mess, and this message appears (twice). When you zoom in they're gone.
![image](https://user-images.githubusercontent.com/32503258/32458811-3e9a2bf2-c2f3-11e7-82eb-5d4dc5a06bcf.png)

2.) With scale-based visibility off the message still appears twice, and the labels draw. But it's real shaky and there's no shadow or buffer. If i hover over the pop-up it blinks on and off making it a challenge to click the hyper link. The PINs are simultaneously blinking on and off too.

**Comment by tomchadwin** [comment]
I'm afraid it's always going to struggle with labelling that many features. The problem is that the way Leaflet works is to enable all the labels, subsequently hide them depending on zoom level, and then perform the same check whenever the user zooms. There's not an easy way to avoid that (at least, not one I'm aware of).

Have you tried OpenLayers export format instead? That handles scale-dependent labelling instrinsically to the layer style, though I have no idea if that means it performs better. Worth testing.

The other alternative is to serve the layer as a WMS, as the labelling can then be handled server-side. No idea if that is an option for you.

**Comment by UnderJollyRoger** [comment]
Ok, what you said here about Leaflet is pretty much what i see it doing too. 

I have tried OpenLayers. Unfortunately, nothing draws when I use this option--either when exported or in the Update preview:
![image](https://user-images.githubusercontent.com/32503258/32519616-f8ae5b14-c3d2-11e7-9617-cddd63733996.png)

A server could be an option too, thanks for pointing that out. All in all, it's not absolutely crucial that the labels show. The pop-ups have all the info displayed anyway. It's just that might have been a nice extra dressing. 

Thanks for the great plug-in anyway.
