### ISSUE TITLE
Error with layer_1_style.js when exporting polygon with outline style set to No Pen OpenLayers

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#564]
I am using Qgis 2.18.13 and the latest q2w.

When I try and export a project with one polygon layer and the outline style is set to "No Pen" I get a javascript error in my browser (Chrome).  

`Unexpected token , Line 21`

The same happens with a polyline layer.

It looks like Q2W is adding an extra comma before the fill part of the code.

**Comment by tomchadwin** [comment]
Leaflet or OL?

**Comment by tomchadwin** [comment]
Confirmed in OL.

**Comment by tomchadwin** [comment]
Maybe fixed in master - please test and report back.

**Comment by boesiii** [comment]
The polygon style is fixed but the same happens with a polyline pen style.

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Maybe fixed in master - please test and report back.

**Comment by tomchadwin** [comment]
Same issue with points... *sigh*

**Comment by tomchadwin** [comment]
Maybe fixed in master - please test and report back.
