### ISSUE TITLE
referencing proj4.js with secure https

### ISSUE THREAD

**Issue by geoglis** [tomchadwin/qgis2web#568]
I have problems using the web project created with qgis2web on a web server when using https.
The script reference 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>`
can not be loaded.
Might it be a good idea to use https for this reference in general when creating index.html?

**Comment by tomchadwin** [comment]
But if we use https by default, won't that lead to a security warning if viewed on http? How about locally?

**Comment by tomchadwin** [comment]
The best solution is to bundle a copy of proj4.js with the exported map instead of calling it from its CDN. I'll try to get that done.

**Comment by tomchadwin** [comment]
Related to #439.

**Comment by geoglis** [comment]
Can't try on an simple http-Server, my be there are problems with referencing to https, I am not familiar with that. Anyone who knows?
Option locally might be the better option. Shall we close this?

**Comment by tomchadwin** [comment]
OK, I've made proj4.js local. Can you try master branch now?

**Comment by geoglis** [comment]
Tested it, works fine. Thanks.

**Comment by tomchadwin** [comment]
Thanks for letting me know.
