### ISSUE TITLE
 Search field as in openstreetmap

### ISSUE THREAD

**Issue by fanou77** [tomchadwin/qgis2web#57]
Hello,

Is it possible to have a search field as in openstreetmap to position a city on the map?

Thanks (Sorry for my english)
Stéphane

**Comment by tomchadwin** [comment]
Yes, this is another feature which needs to be copied over from qgis2leaf.

**Comment by tomchadwin** [comment]
Done for Leaflet in master and 0.10.0 (pushed to QGIS repo)

**Comment by tomchadwin** [comment]
Does anyone know the best way to do address search in OL3?

**Comment by fanou77** [comment]
Thanks a lot.

**Comment by tomchadwin** [comment]
OL3 search now added to master
