### ISSUE TITLE
Line and text styles lost when QGis2web is applied 

### ISSUE THREAD

**Issue by Nicolas1978** [tomchadwin/qgis2web#571]
Hello

I have tried to check that in issues folder but I have not been able to find the answer

Here is my example of a map in QGIS
![image](https://user-images.githubusercontent.com/29180100/32700266-82ba44fe-c7ba-11e7-88d1-97927bca2ea2.png)

And here is what I obtain in QGIS2WEB
![image](https://user-images.githubusercontent.com/29180100/32700326-39a5bfd6-c7bb-11e7-8ebf-e1fe55e2b37f.png)

I have lost my line and text styles. I have tried many settings but I am not able to find how I can keep the predifined styles

Any help will be appreciated.

Thanks

Nicolas

**Comment by tomchadwin** [comment]
Can you upload your project file and layers?

**Comment by tomchadwin** [comment]
Can yuo also say whether you are trying to export as OpenLayers or Leaflet?

**Comment by Nicolas1978** [comment]
You can find atached the project and the result

[QGIS project.zip](https://github.com/tomchadwin/qgis2web/files/1464840/QGIS.project.zip)
[qgis2web_result.zip](https://github.com/tomchadwin/qgis2web/files/1464841/qgis2web_result.zip)

I have used leaflet for this example but I have problems with both

**Comment by tomchadwin** [comment]
I'm afraid QGIS MarkerLines are not yet supported, so it's just failing over to default style. Sorry.

**Comment by tomchadwin** [comment]
Raised as feature request in #572.
