### ISSUE TITLE
index.html is empty

### ISSUE THREAD

**Issue by przytula** [tomchadwin/qgis2web#578]
using qgis 2.18.13 on wind 10 pro with qgis2web 2.31
having layers available and started : qgis2web
all is done : no errors on screen/display
when opening the created index.html file : nothing is shown - no errors but empty page
the file is not empty - just not displayed
any logging/tracing that can be provided
it worked before (because you already worked on it : created files overlap..) but since ?? it does not create any page anymore
thanks for all update
best regards, Guy Przytula

**Comment by tomchadwin** [comment]
Once it is exported and the blank page is open in your browser, press F12 and click on the `Console` tab. Copy any errors you find there and paste them here. Uploading your project file and layers would also help us to recreate the issue.

**Comment by przytula** [comment]
![image](https://user-images.githubusercontent.com/6675471/32983364-8ab68478-cc93-11e7-8ef5-a31698b354d6.png)
this is what I see in browser : nothing in console window

**Comment by przytula** [comment]
and this before pressing export : just a rectangular block (hover says 17)
![image](https://user-images.githubusercontent.com/6675471/32983424-a8daa79e-cc94-11e7-986b-668a4c696b85.png)

[kermt.zip](https://github.com/tomchadwin/qgis2web/files/1484889/kermt.zip)
[SHAPES.zip](https://github.com/tomchadwin/qgis2web/files/1484890/SHAPES.zip)
[oat.zip](https://github.com/tomchadwin/qgis2web/files/1484893/oat.zip)
the project - shapes and join file with data

**Comment by przytula** [comment]
mistake

**Comment by tomchadwin** [comment]
I don't understand what is happening here. Anyone else have any ideas?

**Comment by boesiii** [comment]
You had precision set to 1, change it 15 and it will work.

**Comment by tomchadwin** [comment]
Ah, spot on. Thanks, @boesiii. Setting Precision to "maintain" is probably the best setting.
