### ISSUE TITLE
QGIS2Web Map Takes around 11 seconds to load in Browser (Chrome)

### ISSUE THREAD

**Issue by smarymacdonald** [tomchadwin/qgis2web#579]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by smarymacdonald** [comment]
https://s3.amazonaws.com/forests-settled-urban-landscapes.org/maps/qgis2web_2017_10_17-15_leaflet/index.html#6/49.160/-75.553

Here is the map I am referring to.  Ideally, the map would load faster.  Is that something that I can control on my end or is it just the nature of the software?

**Comment by boesiii** [comment]
Each of your layers has over a 1000 features and one of the layers is a polygon and some of your polygons have many vertices.  You might be able to speed up your rendering by limiting your attributes included in the export and by reducing the precision.  Your gains may be minimal because I think the bottleneck is really your number of features and browsers can only crunch so much data at a time.

**Comment by tomchadwin** [comment]
It's your layer which is exported as `CenSubDv3_0.js` which, when exported, comes out at 37.5MB, which is enormous. Options to reduce the file size are:

### In QGIS
- simplify the geometry
- crop the extent of the features
- reduce the amount of data stored in the attribute table
- reduce the number of fields in that layer

### In qgis2web
- set the `Precision` option lower
- select "Minify GeoJSON files"
- if you are happy to select "Restrict to extent" and set the extent to "Canvas extent", only the features within that extent are exported

Other than that, you have to look to some other way of serving your vector data, such as WFS or vector tiles.

**Comment by smarymacdonald** [comment]
Thank-you
