### ISSUE TITLE
Layer Search not Displaying (leaflet)

### ISSUE THREAD

**Issue by smarymacdonald** [tomchadwin/qgis2web#580]
![x_layersearchissue](https://user-images.githubusercontent.com/11263663/33182351-ae5c7e9e-d041-11e7-8f38-ca1d686a9158.PNG)

I cannot get the layer search to display in either the preview or the browser once exported.

**Comment by tomchadwin** [comment]
I can't recreate this with the test data. Can you therefore export to a browser, press F12 ro display the dev tools, click on the Console tab, and paste here any errors you find there?

**Comment by tomchadwin** [comment]
Ah, wait, I think I have recreated the problem. Looking into it now.

**Comment by tomchadwin** [comment]
No, my mistake - I can't recreate the issue. Can you do what I said in the comment above?

**Comment by smarymacdonald** [comment]
I am almost certain that the 'Search Layers' was checked for this version:
https://s3.amazonaws.com/forests-settled-urban-landscapes.org/UrbanForestryFootprint/bylaws/index.html#4/57.47/-93.87

Unfortunately I do not have access to the server and am still waiting for my boss to post the version I am working with now.

This is the error that results from loading the html on my current version:
 SCRIPT5009: 'cluster_NumberofBylawsPertainingtoTrees12' is not defined

**Comment by smarymacdonald** [comment]
I tried doing all the same things with a different layer and it worked fine.  There must be something about my shp that is preventing the 'Layer Search' from functioning properly.

**Comment by tomchadwin** [comment]
No, I don't think that one you linked to has the search enabled at all.

Are you able to get the browser console output?

**Comment by smarymacdonald** [comment]
unfortunately the above error is the only one I am getting:
SCRIPT5009: 'cluster_NumberofBylawsPertainingtoTrees12' is not defined

**Comment by tomchadwin** [comment]
Urg. I do apologize - I missed that you had already posted it. I can't work this out, I'm afraid. Are you able to upload your QGIS project file and your layers?

**Comment by smarymacdonald** [comment]
[qgis2web_2017_11_23-10_20_34_878000.zip](https://github.com/tomchadwin/qgis2web/files/1500183/qgis2web_2017_11_23-10_20_34_878000.zip)

I also tried all the same parameters without clustering just in case that was causing the issue and I got a similar error:
SCRIPT5009: SCRIPT5009: 'layer_NumberofBylawsPertainingtoTrees0' is not defined

**Comment by smarymacdonald** [comment]
No need to apologize I appreciate your time and effort!

**Comment by tomchadwin** [comment]
I need the QGIS project file and layers, not the qgis2web output webmap. Thanks.

**Comment by smarymacdonald** [comment]
True. 
[Test_580.zip](https://github.com/tomchadwin/qgis2web/files/1501954/Test_580.zip)

**Comment by smarymacdonald** [comment]
My problem arises as soon as I add additional layers to the web map.  If I create a map with only the layer that I want to search on, the search works fine.

**Comment by tomchadwin** [comment]
Thanks for your patience. There was an error in the way the layer names were being used in the layer search. I've committed a fix. Are you able to test master branch and report back?

**Comment by smarymacdonald** [comment]
It works!  Thank-you!

**Comment by tomchadwin** [comment]
Splendid. Thanks for letting me know.
