### ISSUE TITLE
Add OSM layer qgis2web version 2.31.0

### ISSUE THREAD

**Issue by PabloYepez** [tomchadwin/qgis2web#581]
Hi, 

In the version 2.31.0, I couldn't add OSM layer to the map. When you export the map the OSM layer does not appear. I added by my self in the HTML code.

**Comment by tomchadwin** [comment]
How are you trying to add OSM?

**Comment by tomchadwin** [comment]
Closing without feedback. Comment here to reopen.

**Comment by PabloYepez** [comment]
Sorry because of the delay. In the console of qgis2web you can select the OSM (list of differents OSM), in previous versions I can use it. But now even if you pick one in the html code doesn't appear.

When you export the map.This part is missing in the new version, so you can't see the OSM:

`		var basemap0 = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
            maxZoom: 28
        });
		basemap0.addTo(map);`
