### ISSUE TITLE
eats up whole disk space when OpenLayers Plugin WMS-Layer is visible

### ISSUE THREAD

**Issue by noerw** [tomchadwin/qgis2web#582]
Steps to reproduce (caution: will lock up your whole machine until `/tmp` storage is full):

1. in `qgis 2.18.14` install `qgis2web 2.31.0` & `OpenLayers Plugin 1.4.5`
2. in a new project, add the default OpenStreetMap tiles via the OpenLayers Plugin (+ make sure the layer is visible)
3. launch the qgis2web plugin, and make sure a preview is generated
4. watch your `/tmp` storage (if you can, that is :upside_down_face:):
    ![qgis2web2](https://user-images.githubusercontent.com/7880552/33244171-cfb93006-d2f2-11e7-8336-d4bd24317468.png)

I don't know what qgis2web is trying to do, but it's certainly not the right thing.
Maybe we can filter layers from OpenLayers Plugin before generating a preview, as background maps are provided by leaflet/openlayers anyway?

edit: #504 seems to be related

**Comment by tomchadwin** [comment]
Hrm. I thought OpenLayers layers were being excluded. I'll have a look.

**Comment by tomchadwin** [comment]
Ah, no, it was QMS layers which were excluded, I think. I'll check.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test, and report back.

**Comment by noerw** [comment]
Thank you, it works!
However I now get an Error in the OL preview (not with leaflet):
```
qgis2web produced an error:

Traceback (most recent call last):
  File "/home/xxx/.qgis2/python/plugins/qgis2web/maindialog.py", line 318, in previewMap
    preview_file = self.createPreview()
  File "/home/xxx/.qgis2/python/plugins/qgis2web/maindialog.py", line 280, in createPreview
   dest_folder=utils.tempFolder()).index_file
  File "/home/xxx/.qgis2/python/plugins/qgis2web/olwriter.py", line 89, in write
   folder=dest_folder)
  File "/home/xxx/.qgis2/python/plugins/qgis2web/olwriter.py", line 112, in writeOL
   fullextent = bounds(iface, False, layers, matchCRS)
  File "/home/xxx/.qgis2/python/plugins/qgis2web/olwriter.py", line 282, in bounds
   return "[%f, %f, %f, %f]" % (extent.xMinimum(), extent.yMinimum(),
  AttributeError: 'NoneType' object has no attribute 'xMinimum'
```

This only occurs, when no other layers are present, so I guess this is a different bug

**Comment by tomchadwin** [comment]
Thanks for confirming the fix. Yes, that new error is because you have no layers. Do feel free to add that as a new issue, though I don't think I'll give it too much priority, as it's not that critical.
