### ISSUE TITLE
Layers list does not work correctly in leaflet

### ISSUE THREAD

**Issue by gHupf** [tomchadwin/qgis2web#587]
Hi there,

I tried to add a layers list using qgis2web (newest version) on several layers. My problem ist that the layers list is not displayed correctly in leaflet (OL works fine). Some of the layers work, but two of them do not. The ones not working are both categorized layers with 9+ categories. Smaller categorized layers with only 4 layers do display correctly. Reducing the number of categories does not work though. Not sure if this helps.

qgis2web log shows the following error message for one of the layers:

`Traceback (most recent call last):
			  File "C:/Users/.../.qgis2/python/plugins\qgis2web\leafletScriptStrings.py", line 424, in addLayersList
			    new_layer = "'" + legends[safeLayerName] + "':"
			KeyError: u'LaDaDiMassnahmenPoint_0'`

And the error occurs for expanded and collapsed layers list.

**Comment by tomchadwin** [comment]
I've just used the test point dataset and created a categorized map with a large number of categories. The layers list works fine, so the problem must have a different cause. Can you upload your QGIS project file and layer?

**Comment by gHupf** [comment]
[test.zip](https://github.com/tomchadwin/qgis2web/files/1535173/test.zip)

I can't upload the whole project so I added the two categorized layers in a new project. After saving the layers as new ones, the layers list in leaflet suddenly worked for the point layer. But not for the one with lines. They are exactly the same as before though. They are both categorized with the attribute "Typ".

**Comment by tomchadwin** [comment]
I can't load the lines layer:

```
Data source is invalid (Unable to open C:\Users\tchadwin\Desktop\cat layers list\test_linien.shx or C:\Users\tchadwin\Desktop\cat layers list\test_linien.SHX.Try --config SHAPE_RESTORE_SHX true to restore or create it)
```

**Comment by gHupf** [comment]
[test2.zip](https://github.com/tomchadwin/qgis2web/files/1535208/test2.zip)

I forgot a file, sorry. I also added the style for the line layer. It probably is the problem.

**Comment by tomchadwin** [comment]
Thanks for finding this bug and reporting it so quickly. I've committed a fix to the QGIS2 branch - are you able to download that and test?

**Comment by gHupf** [comment]
Works perfectly, thanks!
