### ISSUE TITLE
Add layer list not working

### ISSUE THREAD

**Issue by amegt** [tomchadwin/qgis2web#588]
When creating the web map in leaflet with no layers list everything works fine. Although when I Add layers list it renders a blank preview. Many of the names are in french and have accents, is this an issue?

![capture1](https://user-images.githubusercontent.com/34378668/33776725-4a3f98da-dc10-11e7-9a34-83ef766752f1.PNG)
![capture2](https://user-images.githubusercontent.com/34378668/33776816-9931aad2-dc10-11e7-8198-c30b1bc5cf54.PNG)

Here is the bug report: Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. undefined
index.html:554SyntaxError: Parse error

[error report.docx](https://github.com/tomchadwin/qgis2web/files/1543356/error.report.docx)

**Comment by tomchadwin** [comment]
Ah, no, it's the apostrophe. I'll try to fix it.

**Comment by tomchadwin** [comment]
I've committed a possible fix for this to the QGIS branch here. Can you download and test? I've also made the same fix to master for QGIS3.

**Comment by amegt** [comment]
Thank you, but I am not sure how I am suppose to download and test.

**Comment by tomchadwin** [comment]
Click on the `Code` link above, then change the `Branch` dropdown from "master" to "QGIS2". Then click the green download button, and choose download zip. Own the zip, and copy the contents of the "qgis2web-master" folder into your qgis2web plugin folder - C:\Users\[your_username]\.qgis2\python\plugins\qgis2web on Windows. Then restart QGIS.

**Comment by amegt** [comment]
Thank you for the precision. I have tested it and now there is an error in line 449 and the Add layer list still gives me a blank map.
SyntaxError: Parse error index.html:449

[error report.docx](https://github.com/tomchadwin/qgis2web/files/1556139/error.report.docx)
Thnk you for this precious help

**Comment by tomchadwin** [comment]
That looks like the fix did not work. I've since released it - are you able to use the QGIS Plugins Manager to upgrade qgis2web to version 2.33.0? Let us know if that works.

**Comment by amegt** [comment]
I have updated qgis2web to version 2.33.0 and I still get a blank map when I try to aldd layers list. Is there something I can change in the names of the layers or something else? Thank you

**Comment by amegt** [comment]
I have tried with only 3 layers, removed all accents, apostrophe and it still gives me a blank preview. Also only leaflet works when no layer list is selected, Open Layers never works.

**Comment by tomchadwin** [comment]
Can you upload your project file and the three layers?

**Comment by amegt** [comment]
I just removed all special characters from the source files of the 3 layers and now it works. Is there an easy way to change the name of the source file without having to redo everything?

**Comment by tomchadwin** [comment]
You really shouldn't have to. If the plugin fails with special characters, that's a bug which needs to be fixed. I just need the files so I can recreate the error, as that will point me towards where in the code the issue lies.

**Comment by amegt** [comment]
[Nouveau dossier.zip](https://github.com/tomchadwin/qgis2web/files/1568693/Nouveau.dossier.zip)

**Comment by tomchadwin** [comment]
Please accept my apologies - I had coded the fix incorrectly. It is now correct for Leaflet, and I've also hopefully fixed the OpenLayers export as well. Please download the QGIS branch as you did before, test, and report back.

**Comment by amegt** [comment]
Thank you, now it works both for Leaflet and OpenLayers. Although only the activated layers appears in the layers list.
![capture](https://user-images.githubusercontent.com/34378668/34161697-6f1ca7b4-e49f-11e7-916f-15bdb4979f00.PNG)

**Comment by tomchadwin** [comment]
Great. Thanks for reporting back.

**Comment by amegt** [comment]
Finally when I try to create the map with all the layers I still get an error when I try to add the layers Type de sols, Rivières principales and Grandes affectations du sol. It seems as the same type of errors as before (leaflet-scr.js:401).
[Carte Interactive.zip](https://github.com/tomchadwin/qgis2web/files/1576656/Carte.Interactive.zip)
 

Also, the html popups with text and images don't appear correctly in the web map.

This is what I used as coding for the html popup and I categorised as Photo the IMAGE_URL
<style>
h1 {color:red;}
p.question {color:black;}
</style>
<h1> [% "TITLE" %] </h1>
<br>
<img src="[% "IMAGE_URL" %]"width=300 height=300 />
<br>
<p class="question">L’évènement rejoint parfaitement la mission du COBAVER-VS qui est celle d’implanter la gestion intégrée de l’eau par bassin versant. L’un des grands objectifs du Plan directeur de l’eau (PDE) est de redonner accès aux plans d’eau à la population. Cette activité permet à la fois de sensibiliser la population sur le potentiel d’utilisation des rivières tout en faisant vivre aux participants une expérience hors du commun. Outre la Caisse Desjardins de Vaudreuil-Soulanges, le COBAVER-VS tient à remercier les partenaires de l’évènement, dont la municipalité de Rivière-Beaudette et son Comité des loisirs, la Société de Conservation et d’Aménagement du Bassin de la Rivière Châteauguay (SCABRIC), l’auberge The Abbey ainsi que la Fédération québécoise du canot et du kayak.
<br>
<p class="question">Le trajet sur l’eau…</p>
<p class="question">Le parcours de 20km débute à Glen Nevis en Ontario et se termine dans le noyau villageois de Rivière-Beaudette. Il faut savoir que la rivière Beaudette est un excellent cours d’eau pour s’initier aux sports de pagaie (canot et kayak), car sa pente est faible et ses rapides sont de niveau très facile. </p>
<a href="http://www.cobaver-vs.org/evenements/evenement/descente-en-canoe-kayak-de-la-riviere-beaudette-3e-edition-2/">
<br>
<p class="question">Pour de plus amples informations, consultez le site Internet du COBAVER-VS et le rapport en cliquant ici.</p>
<br>
