### ISSUE TITLE
q2w forgets last used dir

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#59]
So an user has to search it again and again

**Comment by tomchadwin** [comment]
Fixed in master, released in 0.11.0, pushed to QGIS plugins repo.

**Comment by pcav** [comment]
Thanks Tom!

**Comment by tomchadwin** [comment]
Let me know if it doesn't work...

**Comment by pcav** [comment]
Now it saves directly on /tmp, without asking.It is an acceptable behaviour, it makes sense, but I have a slight preference for leaving the user the possibility of selecting the folder.

**Comment by tomchadwin** [comment]
I've moved the folder selection from the dialog to the main UI, under Export settings. Click it, and you should get a directory browse dialog. Use that to select your export folder. It is initially populated with a tmp folder, but should retain your selection if you change it.

Let me know if it works or not.


Tom Chadwin, ICT Manager
Telephone: 01434 611530 Mob:
Web: www.northumberlandnationalpark.org.uk<http://www.northumberlandnationalpark.org.uk/>

IMPORTANT NOTICE - Disclaimer - This communication is from Northumberland National Park Authority (NNPA).The Authority’s head office and principal place of business is Eastburn, South Park, Hexham, Northumberland, NE46 1BS, United Kingdom. If you are not the intended recipient(s) please note that any form of disclosure, distribution, copying or use of this communication or the information in it or in any attachments is strictly prohibited and may be unlawful. If you have received this communication in error, please delete the email and destroy any copies of it. Any views or opinions presented are solely those of the author and do not necessarily represent those of NNPA.Contractors or potential contractors are reminded that a formal Order or Contract is needed for NNPA to be bound by any offer or acceptance of terms for the supply of goods or services Although this email and any attachments are believed to be free of any virus or other defects which might affect any computer or IT system into which they are received, no responsibility is accepted by the NNPA for any loss or damage arising in any way from the receipt or use thereof. Computer systems of this Authority may be monitored and communications carried out on them recorded, to secure the effective operation of the system and for other lawful purpose.

**Comment by pcav** [comment]
Oh, I see - sounds good, sorry for overlooking this.
Thanks.

**Comment by tomchadwin** [comment]
My fault. I didn't document the change.
