### ISSUE TITLE
QGIS3 crash on qgis2web exit after Leaflet preview

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#590]
Doesn't occur 100% of the time, and I don't yet have any idea of the cause. Can anyone help?

**Comment by tomchadwin** [comment]
Possibly only after a Leaflet preview?

**Comment by tomchadwin** [comment]
Yes - it doesn't seem to happen after an OL preview. Could this be some error handling which worked under Python 2, but it failing under 3? I don't know precisely what.

**Comment by tomchadwin** [comment]
The only clue I have so far (thanks to @NathanW2) is in the QGIS crash handler:

```
qWebKitVersion :
WKNotificationGetSecurityOrigin :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1431
WinMain mainwin.cpp:128
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 2.99.0-Master
QGIS code revision: 479358ea77
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601
```

Nathan says this point to Webkit (*sigh*), but I don't know how to investigate further or fix. Can anyone else help?

**Comment by tomchadwin** [comment]
Also, can people tell me whether this crash occurs with non-Windows OSes?

**Comment by slarosa** [comment]
> Also, can people tell me whether this crash occurs with non-Windows OSes?

Yes @tomchadwin, I also am getting the crash on macOS with latest QGIS master.

**Comment by tomchadwin** [comment]
Thanks, @slarosa.

If I add debug output at the beginning of the reimplemented `closeEvent()` call, they output doesn't appear when the crash happens. That either means that Qt is not firing the event, or the event is crashing before any commands in `closeEvent()` run.

**Comment by tomchadwin** [comment]
Fixed by @slarosa in https://github.com/tomchadwin/qgis2web/pull/612! Thanks so much, Salvatore!
