### ISSUE TITLE
Popup field labels problem

### ISSUE THREAD

**Issue by eoinomahony** [tomchadwin/qgis2web#595]
I am using 2.33.0 in 2.14 Essen. 

I have reduced the layer count to a single layer. In the main dialog, I change Popup fields to Inline or Header and the preview disappears and the project exports to a blank index.html. 

Screenshots below:

#1 
![image](https://user-images.githubusercontent.com/12271365/34156764-872b84e4-e4b6-11e7-92fa-319a907372fc.png)

#2 
![image](https://user-images.githubusercontent.com/12271365/34156784-a61bf85c-e4b6-11e7-85b7-0695b783019c.png)

**Comment by tomchadwin** [comment]
I'm afraid I can't recreate that at the moment. Can you upload your QGIS project file and layer?

**Comment by eoinomahony** [comment]
Here's the zipped SHP file I am using




[didata.zip](https://github.com/tomchadwin/qgis2web/files/1571739/didata.zip)

**Comment by tomchadwin** [comment]
Hrm. I still can't recreate the error:

![2017-12-19 13_37_27-export to web map](https://user-images.githubusercontent.com/7840213/34159631-d92d5f8c-e4c1-11e7-8ddc-6830a8afd521.png)

Can you upload your .qgs (QGIS project file)?

You can also look in the QGIS log and in the JS console - errors should appear in either or both of those locations.

**Comment by eoinomahony** [comment]
Here's the project file
[di data project file.zip](https://github.com/tomchadwin/qgis2web/files/1571890/di.data.project.file.zip)

**Comment by tomchadwin** [comment]
Thanks - I've got the problem now. Looking into it.

**Comment by tomchadwin** [comment]
I think there's a carriage return character at the end of your alias for `field_3`, "When did the incident occur?". Try deleting any trailing charcters from the alias and see if that fixes it. Let me know.

**Comment by eoinomahony** [comment]
Yes! That's it. Many thanks. That was a rudimentary copy and paste error.

**Comment by tomchadwin** [comment]
No, it's also a bug - I need to `strip()` the aliases. Glad you're sorted, though, and thanks for reporting back.
