### ISSUE TITLE
Travis for v3

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#596]
The existing Travis setup doesn't work with QGIS3. I've therefore tried to copy the following, thanks to @m-kuhn:

https://github.com/opengisch/projectgenerator/blob/master/.travis.yml

I've amended it and copied it to master, and, unsurprisingly, the first run has failed:

https://travis-ci.org/tomchadwin/qgis2web/builds/318694306

I don't know enough yet to understand the failure. Can anyone help?

**Comment by tomchadwin** [comment]
When? `before_script`? Or within the `stage`?

**Comment by m-kuhn** [comment]
In git

**Comment by tomchadwin** [comment]
Why does docker pull `qgis/qgis` twice?

**Comment by tomchadwin** [comment]
OK, `pycodestyle` is now running. Have to see how to get the actual unit tests running next. Thanks for the help, @m-kuhn!

**Comment by tomchadwin** [comment]
I've got a good way toward getting this working, but am stuck on two issues:

https://travis-ci.org/tomchadwin/qgis2web/builds/319263013

The first is QtWebKit again:

```
1) ERROR: Failure: ImportError (No module named 'PyQt5.QtWebKitWidgets')
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python3.5/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.5/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.5/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.5/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.5/imp.py line 234 in load_module
      return load_source(name, filename, file)
    /usr/lib/python3.5/imp.py line 172 in load_source
      module = _load(spec)
    <frozen importlib._bootstrap> line 693 in _load
    <frozen importlib._bootstrap> line 673 in _load_unlocked
    <frozen importlib._bootstrap_external> line 665 in exec_module
    <frozen importlib._bootstrap> line 222 in _call_with_frames_removed
    test/test_qgis2web_dialog.py line 31 in <module>
      from olwriter import OpenLayersWriter
    olwriter.py line 26 in <module>
      from qgis2web.utils import (exportLayers, replaceInTemplate)
    qgis2web.py line 30 in <module>
      from maindialog import MainDialog
    maindialog.py line 55 in <module>
      from qgis.PyQt.QtWebKitWidgets import QWebView, QWebInspector, QWebPage
    /usr/lib/python3/dist-packages/qgis/PyQt/QtWebKitWidgets.py line 1 in <module>
      from PyQt5.QtWebKitWidgets import *
   ImportError: No module named 'PyQt5.QtWebKitWidgets'
```

The second is something @nyalldawson set up to test FTP - twisted:

```
2) ERROR: Failure: ImportError (No module named 'twisted')
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python3.5/dist-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /usr/local/lib/python3.5/dist-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    /usr/local/lib/python3.5/dist-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /usr/local/lib/python3.5/dist-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib/python3.5/imp.py line 234 in load_module
      return load_source(name, filename, file)
    /usr/lib/python3.5/imp.py line 172 in load_source
      module = _load(spec)
    <frozen importlib._bootstrap> line 693 in _load
    <frozen importlib._bootstrap> line 673 in _load_unlocked
    <frozen importlib._bootstrap_external> line 665 in exec_module
    <frozen importlib._bootstrap> line 222 in _call_with_frames_removed
    test/test_qgis2web_exporters.py line 28 in <module>
      from twisted.application import internet
   ImportError: No module named 'twisted'
```

Any help on these two very gratefully received.

**Comment by tomchadwin** [comment]
@m-kuhn @jef-n Any ideas on Webkit (sorry to be asking about it *again*. Would it be a case of asking for you to add it to the QGIS dockerfile? Or is the issue something else?

**Comment by m-kuhn** [comment]
Does a simple `apt-get install python-pyqt5.qtwebkit` inside the container help?

**Comment by m-kuhn** [comment]
E.g. instead of the JRE here which I don't think you need ;) https://github.com/tomchadwin/qgis2web/blob/master/.docker/Dockerfile#L6

**Comment by tomchadwin** [comment]
Thanks again, @m-kuhn, that's fixed it. I now just need to understand package and imports.

**Comment by m-kuhn** [comment]
Add a requirements.txt and install missing packages with this (inside the container)?

**Comment by tomchadwin** [comment]
No, it's not that there's missing packages. It's that I'm getting the error that qgis2web is not a package. In the upgrade to Python 3, I had to change the relative imports from `from maindialog` to `from .maindialog`. This worked in the plugin but failed in the tests. I've therefore changed it to `from qgis2web.maindialog`. In the tests, thus note fails specifically in the imports in `qgis2web.py`. See:

https://travis-ci.org/tomchadwin/qgis2web/builds/319309072#L943

**Comment by tomchadwin** [comment]
Right. I'm glad I didn't miss any other differences. I don't think I can restructure the repo easily from my phone, so unless I get some time over the holiday, this will probably have to wait until the new year.

Thanks again - I reallying needed help on this, and I think it's nearly there.

**Comment by m-kuhn** [comment]
I hope this gets some traction with other plugins as well, so happy to spread the knowledge.

**Comment by tomchadwin** [comment]
Nearly there, but not quite. I'm not getting my paths quite right yet...

**Comment by tomchadwin** [comment]
@m-kuhn I think it's nearly there now, but I've hit another permissions issue, which I don't know how to fix locally on Windows:

https://travis-ci.org/tomchadwin/qgis2web/jobs/324977547#L658

Can you help, or help me understand a way to fix this locally? I tried cloning `projectgenerator`, but the files were owned by my local Windows user, and the Windows git shell wouldn't allow be to `chown` the bash script to my possible guesses of `qgis` or `root`, as those users don't exist on my Windows machine.

**Comment by m-kuhn** [comment]
You need to set the executable flag (x)

I have never done this on windows, on linux I would use `chmod +x .docker/run-tests.sh` but according to this answer here, there's a git tool for it on Windows too https://stackoverflow.com/a/13593391/2319028

**Comment by tomchadwin** [comment]
I'm not sure that's it, as git shell says:

```bash
$ ls -l
total 6
-rw-r--r-- 1 tchadwin 1049089  115 Jan  4 10:45 docker-compose.travis.yml
-rw-r--r-- 1 tchadwin 1049089  222 Dec 27 16:48 Dockerfile
-rwxr-xr-x 1 tchadwin 1049089 2167 Dec 27 16:48 run-docker-tests.sh*
```

So it looks to me like `run-docker-tests.sh` has execute permissions (it's chmod 755). Still I'm trying that solution, and we'll see if that fixes it.

**Comment by m-kuhn** [comment]
That's what it says for me:
```
mku@localhost ~/dev/qgis2web (master) $ ls -al .docker/run-docker-tests.sh 
-rw-rw-r--. 1 mku mku 2132 Jan  4 12:07 .docker/run-docker-tests.sh
```

**Comment by m-kuhn** [comment]
Oh, looks like I was on the wrong branch (master), nevermind.

**Comment by tomchadwin** [comment]
Master is the right branch?

**Comment by m-kuhn** [comment]
Hmmm... and I double-failed, I just thought this issue here was actually a pull request. Let's see how the pull request does.

**Comment by tomchadwin** [comment]
Thank you - that's done it.

**Comment by tomchadwin** [comment]
Now getting an import error for processing:

https://travis-ci.org/tomchadwin/qgis2web/jobs/325040864#L818

The plugin imports processing successfully when used manually on a local installation (ie not in tests).

**Comment by m-kuhn** [comment]
QGIS does a lot of path mangling. Maybe you need to add `/usr/share/qgis/python/plugins` to `PYTHONPATH`.

`export PYTHONPATH=/usr/share/qgis/python/plugins:$PYTHONPATH`

**Comment by tomchadwin** [comment]
Ah, fantastic! That's done it. Thanks so much for all this help. Hopefully the questions will soon cease...

**Comment by tomchadwin** [comment]
OK, more progress, but a bunch of new issues:

https://travis-ci.org/tomchadwin/qgis2web/builds/325478599

First off, I no longer have my formerly mocked `IFACE` which was formerly defined here:

https://github.com/tomchadwin/qgis2web/blob/QGIS2/test/qgis_interface.py#L37

I appreciate the new approach no longer uses this, instead calling `qgis.testing.start_app()`. Does this mean I no longer need a dummy IFACE? If so, I guess that means I have to get rid of all the instances of passing `iface` down the call stack? Alternatively, do I instantiate some other form of `iface` under this approach, and pass that in instead?

**Comment by tomchadwin** [comment]
Ah, looking at the QGIS unit tests, is it just a case of using `qgis.testing.mocked.get_iface()`?

**Comment by tomchadwin** [comment]
> Does a simple apt-get install python-pyqt5.qtwebkit inside the container help?

Is that right, @m-kuhn? Isn't that the Python 2 bindings? Shouldn't it be `python-pyqt5.qtwebkit`?

If I try that, I get a different error, though, so I want to double-check which route to go down before wasting too much time.

**Comment by m-kuhn** [comment]
If there's a `python3-pyqt5.qtwebkit`, use that one !

**Comment by tomchadwin** [comment]
With Python 3 QtWebkit:

```
QPixmap: Must construct a QGuiApplication before a QPixmap
```

Not sure why this occurs under Travis and not locally.

**Comment by tomchadwin** [comment]
That error was due to a missing `qgis.testing.start_app()` in one of the test files. Looks like the WebKit tests are now kicking in, with lots of new errors to fix. Anyway, it means the `python3-` module was the one we needed.

**Comment by tomchadwin** [comment]
Hopefuly only one major test issue remains. As part of the new Docker-based testing technique, this repo has been restructured, so that the plugin code is within the `qgis2web` subdirectory. This seems to confuse code which opens a local file, such as when exporting SVG symbols:

https://travis-ci.org/tomchadwin/qgis2web/jobs/332394640#L1581
https://travis-ci.org/tomchadwin/qgis2web/jobs/332394640#L1663

I believe the same issue could be causing #607. To clarify, these errors only occur in Travis, not in plugin use. My guess is that this is because the whole repo is cloned over, instead of just the `qgis2web` subfolder.

The three ways of fixing the issue, if this is the explanation of the problem, are:

1. Change the plugin code to handle the test file structure
2. Change the test to compensate for the different file structure
3. Change the Travis setup to stop the test file structure differing from normal plugin use

I've tried quite hard to do 1, but it failed, and would be horribly hacky anyway. I've not looked at 2, but 3 would possibly be the best approach - anything which decreases the difference between test environment and production has to be A Good Thing.

@m-kuhn, any ideas on how to solve this? Have you run into the same issue?

**Comment by tomchadwin** [comment]
I think all is now well.
