### ISSUE TITLE
Html popups not working 

### ISSUE THREAD

**Issue by amegt** [tomchadwin/qgis2web#599]
I have been trying to add popups to my web maps with the html popups in the layer properties and I cannot get them to appear in the web map. I have long text, images and links to web sites so I cannot use only the fields. The popups work fine in qgis. Is there a way to work this?

 This is the code I used:
[html popup code.docx](https://github.com/tomchadwin/qgis2web/files/1579653/html.popup.code.docx)

**Comment by tomchadwin** [comment]
No, this is not supported. However, URLs within text will automatically be turned into clickable links. Also, if you set a field's edit widget type to  "Image", then images can also be exported.
