### ISSUE TITLE
Window too big, forgets resizing

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#60]
The plugin popup window is too big for small screens (buttons at bottom gets hidden), and does not remember the resizing setting when opening it again.

**Comment by tomchadwin** [comment]
Saving window size should be simple now that other settings persist via QSettings. Does the dialog resize gracefully, by the way?

**Comment by pcav** [comment]
The size does not seem to be remembered. The dialog resize gracefully.
BTW, now opening the dialog takes several seconds, I guess because of a weird reprojection in my case (4326 to 3857, with features extending outside the date line).
BTW2: the Clode button is missing on Gnome3.

**Comment by tomchadwin** [comment]
The slowdown is because now the preview is populated on startup. Previously it was blank. I could create a QSetting to disable preview on startup if it's of use.

**Comment by tomchadwin** [comment]
Added to master. Also, prior to 1.0.0betas, the GUI's different panes did not stretch sensibly when the whole dialog was resized, but that too should now be working OK.

Please test.
