### ISSUE TITLE
Support for MarkerCluster.LayerSupport?

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#603]
It will be cool, when more (points) layer could be in one cluster together. Like here:
https://ghybs.github.io/Leaflet.FeatureGroup.SubGroup/examples/subGroup-markercluster-controlLayers-realworld.388.html in future version of

**Comment by tomchadwin** [comment]
I'm not sure I want to support this, to be honest. Keeping the layers separate is probably a good thing, and users can choose to implement the code you link themselves if they want.
