### ISSUE TITLE
WMTS Basemap.at isn't working

### ISSUE THREAD

**Issue by scott1060** [tomchadwin/qgis2web#604]
Hi,

thanks for your great Qgis plugin. I'm trying to add a basemap from https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml but it doesn't appear as basemap. The background is just white.
I tried different qgis2web (2.31/.2.32/2.33), Qgis (2.16/2.16 german/english) and OS (win7/win10/ubuntu 14.02) versions. Nothing changed. 

Thanks

**Comment by tomchadwin** [comment]
Confirmed, I think, but I don't understand why. No errors, as far as I can see. Anyone else see what's wrong?

**Comment by boesiii** [comment]
There are 5 tilesets.  Which one are you trying to add?

**Comment by scott1060** [comment]
I just need the layer bmapgrau. Because this layer is not working I tried to add the other ones, but all of them are not working.

**Comment by tomchadwin** [comment]
OK, I've figured out the problem, but I don't yet have a solution. In the meantime, I can tell you how to edit the exported code to get it to work (I think). I need to know whether you are exporting as Leaflet or OpenLayers.

**Comment by scott1060** [comment]
It would be great if you can tell me how (and maybe why :) I should change the code.
I'm exporting as OpenLayers.

**Comment by tomchadwin** [comment]
I do apologize, but it turns out that the problem is more fundamental than I thought - qgis2web is pretty much *not* exporting WMTSes correctly. I don't yet have a solution for this, even with manual code editing, but I will still look further into it.

**Comment by tomchadwin** [comment]
OK, for the moment I think I do have a workaround (and you don't need to edit your exported code by hand):

1. Remove the WMTS from QGIS
2. Create a new XYZ layer, using the URL `http://maps2.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png`
3. Add to your canvas
4. Export via qgis2web

I still need to investigate how to achieve full WMTS functionality, but do let us know if this workaround works for you.

**Comment by tomchadwin** [comment]
I've asked for help with the underlying issue here:

https://gis.stackexchange.com/questions/268415/add-wmts-to-leaflet-using-its-getcapabilities-url

**Comment by scott1060** [comment]
Thanks for your workaround, its working also with other WMTS-Layer.

**Comment by tomchadwin** [comment]
Superceded by #610

**Comment by riccardoklinger** [comment]
Hi folks, sorry for digging this out. So it seems to me, there is a workaround in the definition of the layer but not in the actual export, right? I've seen the same behaviour with this WMTS (which is commonly used in German governmental and non-governmental institutions) http://sgx.geodatenzentrum.de/wmts_topplus_open/1.0.0/WMTSCapabilities.xml :
- layer appears in the layer tree (it shouldn't, if it is not exported)
- there is a getWMTS function in at least the OL-layer export scripts
