### ISSUE TITLE
https links in background maps

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#606]
Hi Tom,

I have used the OSM-HOT background layer from the list in qgis2web (version 2.33).
After uploading the map to my own website I noticed the security warning in my browser (unverified/unsecure, orange coloured lock). It is said that an unsecure page is less likely to be found in google search, not sure if this is true.

In the index file I noticed that the link to the OSM-HOT tilelayer uses the http: link instead of the https: link.

I have not tested any of the others layers, so this might be the only one.
Could you update the links for the background maps to https versions?

Thanks in advance.

**Comment by tomchadwin** [comment]
I'm afraid I can't easily fix this - if I make it either https or protocol neutral, it fails locally, and hence for the preview. I'm afraid the only option is to change to https by editing the code manually.

**Comment by Jeroen-GroeneBij** [comment]
Hi Tom,

 

Is this a Qgis issue then? That https fails within qgis so the preview will not work?

Maybe it will be addressed in qgis3?

 

Changing the code manually is always an option, but having https by default would be nice.

 

Gr.

Jeroen

 

 

Van: Tom Chadwin [mailto:notifications@github.com] 
Verzonden: donderdag 18 januari 2018 17:05
Aan: tomchadwin/qgis2web <qgis2web@noreply.github.com>
CC: Jeroen-GroeneBij <mail@groenebij.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tomchadwin/qgis2web] https links in background maps (#606)

 

I'm afraid I can't easily fix this - if I make it either https or protocol neutral, it fails locally, and hence for the preview. I'm afraid the only option is to change to https by editing the code manually.
