### ISSUE TITLE
OL points drift when using SVG markers and zooming out

### ISSUE THREAD

**Issue by AndySpeed** [tomchadwin/qgis2web#611]
In OpenLayers, when I use an SVG point marker on a map and then zoom out, the SVG points are drifting further away from their original location - i.e. the points are only accurate at a zoomed in scale.

I have uploaded as a temporary example the output here:

https://www.touringcars.net/qgis/qgis2web2/index.html

This is output using the latest version of qgis2web (I have only edited layers.js to remove declutter to prevent point flicker).

![options](https://user-images.githubusercontent.com/36076610/35736859-7860befa-0821-11e8-8644-576b4be1f7c3.png)

In QGIS I am using the EPSG 27700 (British National Grid).

**Comment by tomchadwin** [comment]
Interesting. My guess is that this could be caused by incorrect setting of the reference point on the symbol. In other words, could it be that the SVG is not centred on the coordinates, but has them at eg top left? Does that sounds possible?

**Comment by AndySpeed** [comment]
The symbols position correctly within QGIS but not in qgis2web output. Are you suggesting it could be an issue with the SVG symbol itself?

**Comment by tomchadwin** [comment]
No, I mean that in the web export, the SVGs are not correctly aligned with the points they are symbolizing. This would be because qgis2web could be setting the "reference point" of the SVG styles to something inappropriate, such as a corner, rather than their centre.

**Comment by AndySpeed** [comment]
I think that sounds plausible, because the issue is probably still there even when zoomed in, but its just more pronounced at a zoomed out scale in relation to the boundaries.

**Comment by tomchadwin** [comment]
That was my thought, but I've just checked, and the anchor is set to the middle of the SVG (specifically half the size). Three questions:

1. Is your SVG not square?
2. Does your SVG have a lot of margin?
3. What units are your SVG and anchor point set in?

**Comment by AndySpeed** [comment]
I think that's it, the SVG is not square. Thanks for pointing it out though - I guess this thread can be deleted. Not a qgis2web issue.

**Comment by tomchadwin** [comment]
No, it should be able to handle non-square SVGs.

**Comment by boesiii** [comment]
Where did the SVG come from?  Was it in the default QGIS symbol library?  Maybe try one of the defaults included with qgis and see if you still have problems.
