### ISSUE TITLE
Dev console disappeared

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#613]
In the QGIS3 migration, we seem to have lost the developer console which you should be able to enable in the preview window by pressing F12. My guess is that it either disappeared as part of @slarosa's bugfix (#612) or as part of my removal of the basemaps (https://github.com/tomchadwin/qgis2web/commit/fb80c5150c11e4f7c0446446c3db068abd8f5c5c#diff-29b7a2e10e446fb0e8a099e787eaaa9d). Any ideas, anyone?

**Comment by slarosa** [comment]
my fault, sorry...I will fix it just after dinner :-)

**Comment by tomchadwin** [comment]
Perfect - thanks so much, once again!
