### ISSUE TITLE
Polygon layer not showing on web map. QGIS2web latest version installed

### ISSUE THREAD

**Issue by astronaut4** [tomchadwin/qgis2web#615]
Hi there, 

The polygon layer District Borough Unitary Region is not showing on the map. Do you know why that is?

Also, do you have any tips on how to make the map run faster?

Thanks so much,

Panos

![github](https://user-images.githubusercontent.com/32511873/36256540-539b0f60-124b-11e8-8df5-d72bb53e60f6.JPG)

**Comment by boesiii** [comment]
Could you share your data and project file?

**Comment by astronaut4** [comment]
Hi Boessi, 

I tried to send you the project files here but it says that the files are not supported. 

I replied to the email I received with the files - have you received them ?

Thanks,

Panos

**Comment by boesiii** [comment]
No.  Put them in a zip file and upload it through the comment box.

**Comment by astronaut4** [comment]
It doesn't let me upload files larger than 10mb :(

**Comment by boesiii** [comment]
If you can't upload the file, you can try and send a smaller subset of your data.  

Do any of your attributes have special characters?

**Comment by astronaut4** [comment]
[Projects Map.zip](https://github.com/tomchadwin/qgis2web/files/1728135/Projects.Map.zip)

**Comment by boesiii** [comment]
[MAP1.zip](https://github.com/tomchadwin/qgis2web/files/1728260/MAP1.zip)
It is working for me.  

For some reason Qgis was not recognizing the coordinate system for the county regions so make sure you have it set to EPSG 7405.

**Comment by tomchadwin** [comment]
Thanks, @boesiii. I'll close for now - comment again if an issue still exists.
