### ISSUE TITLE
Polygon layer blank on webmap with undefined style

### ISSUE THREAD

**Issue by Yukisama12** [tomchadwin/qgis2web#616]
Hello, I'm tring to export my Polygon layer with graduated style on OS map. I have choosed the Openlayer then the layer was empty but the OS map shows when I hide the layer list. I have pressed F12 in qgis2web, the console says: "ReferenceError: undefined style " (can't find the variable: style ---Error for the js file). The layer with single-sample can export without problem. 
About the Polygon layer I have joined with a csv file and convert the string to real with length 16 and precision 2 in a new field. I have checked all the data set, there are no problem with the number. I have tried to convert these numbers into int, no output yet. Are there any ways to fix my problem... Thanks

**Comment by boesiii** [comment]
Zip your qgis project file and upload it here.

**Comment by Yukisama12** [comment]
I am tring to edit a test version to upload. I have deleted a lot of data, then the polygon appears on the web. Maybe it is the problem with numeric. Now I must check the data again...

**Comment by Yukisama12** [comment]
[Test.zip](https://github.com/tomchadwin/qgis2web/files/1730779/Test.zip)
I have uploaded this project and fand that the problem with value 0.00. I have update all of them with 0.01 then did't work... please help.. thanks

**Comment by boesiii** [comment]
I can confirm your error.  I don't think graduated polygons are a supported qgis2web feature when exporting to OL.  It does work with leaflet though.

**Comment by Yukisama12** [comment]
I am not sure, because I have tried with another dataset, it works. I have also tried with leaflet then due to the large number of dataset the script stop always...

**Comment by tomchadwin** [comment]
The error occurs because it currently sets the lower bound of a range as excluded. I'll change it and see whether it works.

**Comment by tomchadwin** [comment]
Please test the QGIS2 branch and report back. Thanks.
