### ISSUE TITLE
Direct db (Postgis) connection instead of json file

### ISSUE THREAD

**Issue by pieri70** [tomchadwin/qgis2web#619]
Hello developers
I am beginning to use qgis2web.
We usually use Lizmap Web Client to create standalone web applications.
Our data are on Postgis server.
With LWC/Qgis server data available on map request are updated to latest db modification.
Qgis2Web saves data as .js files (postgis dump and conversion to json file), this way they loose the db syncronization.
I know I can use php to serve query results as leaflet layers but for a common user as me it's almost impossible..
Is it possible to enhace Q2W so it let you decide if data must be a json dump or a direct db connection?

Thanks for your wonderful plugin
Have a nice day
Pietro

**Comment by tomchadwin** [comment]
I'm afraid qgis2web simply cannot do this. It exports webmaps which can be hosted anywhere (even locally). To allow direct dB connections would mean it would need to know what destination server it would be hosted on, and export different code accordingly - PHP, Python, .NET, etc.

Lizmap is different - it is both front-end *and* back-end, so it can achieve what you need.

An alternative which would work is if you can make a WFS of your dB data. qgis2web can incorporate those layers without exporting them as JSON, so if you update your dB, the webmap will automatically update. However, I'm aware this requires significant work to put this in place, but I'll close this issue as out of scope for qgis2web.
