### ISSUE TITLE
Labels not retaining buffers in OpenLayers 3

### ISSUE THREAD

**Issue by MooreMapping** [tomchadwin/qgis2web#627]
I am using qgis2web version 2.33.1 on QGIS 2.18.15.
I am trying to output a map with labels that have buffers (outline, stroke, etc.). The wiki says text will retain these in OL3, which is what I'm using. In an older version of qgis2web, I was able to add text buffers using 
`stroke: new ol.style.stroke({color: 'rgba(255, 255, 255, 1.0)', width: 3})`
in the style.js files, but that method no longer seems to work in the new structure of those files.
Here is what one of those files now look like (in my project):

```
var size = 0;
var placement = 'point';

var style_Districts1_2 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = ""
    var labelText = "";
    size = 0;
	var key = "";
    var labelFont = "bold\ 14.5px \'Georgia\', sans-serif";
    var labelFill = "rgba(161, 82, 17, 1)";
    var textAlign = "left";
    var offsetX = 8;
    var offsetY = 3;
    var placement = 'point';
    if (feature.get("District") !== null) {
        labelText = String(feature.get("District"));
    }
    var style = [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}), fill: new ol.style.Fill({color: 'rgba(164,85,20,0.0)'}),
        text: createTextStyle(feature, resolution, labelText, labelFont, labelFill, placement)
    })];

    return style;
};
```

How would I give my labels a buffer in this file?

Edit: Deleted the code I had added in attempt to add text buffer in the new style.js file.

**Comment by edse1991** [comment]
Hi! I had the same problem but was able to work around it with your help :) Add your stroke code to the functions.js file in the resources folder instead.  I added two new variables as well because I have categorized points and want to use different buffers for different categories. With the new variables I can do that in the style.js file.

functions.js

var createTextStyle = function(feature, resolution, labelText, labelFont,
                               labelFill, placement, bufferColor, bufferWidth) {

    if (feature.hide) {
        return new ol.style.Text(); 
    } 

    var textStyle = new ol.style.Text({
        font: labelFont,
        text: labelText,
        textBaseline: "middle",
        textAlign: "center",
        offsetX: 0,
        offsetY: 0,
        placement: placement,
        maxAngle: 0,
        fill: new ol.style.Fill({
          color: labelFill
        }),
        stroke: new ol.style.Stroke({
          color: bufferColor,
          width: bufferWidth
        })
    });
    return textStyle;
};

and styles.js

var size = 0;
var placement = 'point';
function categories_namn_0(feature, value, size, resolution, labelText,
                       labelFont, labelFill, bufferColor, bufferWidth) {
                switch(value.toString()) {case 'holme':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 4.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}), fill: new ol.style.Fill({color: 'rgba(110,69,200,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor, bufferWidth)
    })];
                    break;
case 'land':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 4.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}), fill: new ol.style.Fill({color: 'rgba(137,226,166,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor, bufferWidth)
    })];
                    break;
default:
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 4.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}), fill: new ol.style.Fill({color: 'rgba(235,112,60,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor, bufferWidth)
    })];
                    break;}};

var style_namn_0 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = feature.get("typ");
    var labelText = "";
    size = 0;
    var labelFont = "13.325px \'MS Shell Dlg 2\', sans-serif";
    var labelFill = "rgba(255, 0, 0, 1)";
    var textAlign = "center";
    var offsetX = 8;
    var offsetY = 3;
    var placement = 'point';
    var bufferColor = "rgba(0, 0, 0, 1)";
    var bufferWidth = 2;
    if (feature.get("namn") !== null ) {
        labelText = String(feature.get("namn")); labelFont = "13.325px \'MS Shell Dlg 2\', sans-serif";
    }

**Comment by MooreMapping** [comment]
Good catch. Adding the bufferColor and bufferWidth to the functions.js file then to the style.js files worked in so far as I was able to add text buffers. However, once I added the buffers, the labels were no longer in the correct positions. They all seem to have moved as far up and right as they could within their boundaries. Changing the offsetX and offsetY in the functions.js file changes all of the labels, but doing that in the individual style.js files doesn't appear to have any effect on the placement of the labels.

**Comment by edse1991** [comment]
Hmm, weird. As far as I understand, nothing should have been changed when it come to alignment. But at the same time, the offsets are not set by the function so I guess they are set from the values in the function.js file. You can always add more variables... (I think all these options should be possible to use: http://openlayers.org/en/latest/apidoc/ol.style.Text.html )

**Comment by jonywoker** [comment]
I am also having this Issue I tried to  do the buffer color but i wasn't successful, anybody could please explain me  a bit more. I am also trying to get this work. I had this solve when in qgis2web using the option leaflet by adding this to the leaflet.css code

/* general typography */
.leaflet-container {
	font: 12px/1.5 "Helvetica Neue", Arial, Helvetica, sans-serif;

    text-shadow:
    -1px -1px 0 #FFFFFF,
    1px -1px 0 #FFFFFF,
    -1px 1px 0 #FFFFFF,
    1px 1px 0 #FFFFFF; 
   
	}
but the open layer couldn't make it work thank you all.

**Comment by tomchadwin** [comment]
Thanks for your patience with this issue. Buffer width and colour should now export correctly from QGIS to OpenLayers (master branch only, and hence will only be released for QGIS3).
