### ISSUE TITLE
unicode error on loading plugin

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#63]
At plugin start before any plugin dialog showed, on trying to run plugin: project have only one layer called "p"

Thank

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/qgis2web.py", line 51, in run
    dlg = MainDialog()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 45, in __init__
    self.populateConfigParams(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 135, in populateConfigParams
    dlg.paramsTreeOL.itemWidget(subitem, 1).setCurrentIndex(comboSelection)
TypeError: QComboBox.setCurrentIndex(int): argument 1 has unexpected type 'unicode'

Versione Python:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

Versione di QGIS:
2.9.0-Master Master, exported

**Comment by tomchadwin** [comment]
Which plugin version?

**Comment by marcobra** [comment]
0.13.0 (in /home/ubuntu/.qgis2/python/plugins/qgis2web)

**Comment by tomchadwin** [comment]
0.13.1 now uploaded to QGIS repo, or try master from here, which has a few more commits. However, I'm not aware of any fixes for what you are observing. Could you try master, though, and see if you still have the issue?

**Comment by marcobra** [comment]
With 0.13.1 i still get same error... same error on latest git version...
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/qgis2web.py", line 51, in run
    dlg = MainDialog()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 45, in __init__
    self.populateConfigParams(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 135, in populateConfigParams
    dlg.paramsTreeOL.itemWidget(subitem, 1).setCurrentIndex(comboSelection)
TypeError: QComboBox.setCurrentIndex(int): argument 1 has unexpected type 'unicode'

**Comment by tomchadwin** [comment]
Very strange. In the QGIS Python console, could you do the following:

```python
from PyQt4.QtCore import QSettings
QSettings().remove("Extent")
QSettings().remove("Base layer")
QSettings().remove("Template")
```

Then reload the plugin and try again.

**Comment by marcobra** [comment]
ok now the error is gone

**Comment by boesiii** [comment]
I also had the same error on my home laptop which has Lubuntu.

**Comment by tomchadwin** [comment]
Thanks, both. The error has arisen because initially, the plugin saved the text of drop-downs. This changed to the index. What this means is that if you previously used the plugin version which saved as a string, that setting now persists, and the new version cannot load it, resulting in your error.

This will probably disappear as I intend to change the settings names, so the old ones will no longer be used. In the meantime, I guess I need to check the type of the drop-down settings before attempting to load them.

**Comment by tomchadwin** [comment]
OK, I think I've fixed this issue locally, but cannot commit the fix yet, as other work I am doing is currently non-functional. I'm going to close this issue, though.

**Comment by tomchadwin** [comment]
Reopened until fix committed

**Comment by tomchadwin** [comment]
Released as 0.13.2 and pushed to QGIS plugin repo

**Comment by tomchadwin** [comment]
Can you do the following in console:

```python
from PyQt4.QtCore import QSettings
print QSettings().childKeys()
print QSettings().allKeys()
```

**Comment by tomchadwin** [comment]
Sorry, and paste the results here, I should have said.

**Comment by tomchadwin** [comment]
Please do paste the QSettings dumps here. However, also try the following:

```python
 from PyQt4.QtCore import QSettings QSettings().remove("qgis2web/Extent") QSettings().remove("qgis2web/Base layer") QSettings().remove("qgis2web/Template")
```

**Comment by tomchadwin** [comment]
From @marcobra:

With release 0.13.2
after the previuos fail, reported here above, now plugin give me at startup
```
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/qgis2web.py", line 51, in run
    dlg = MainDialog()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 45, in __init__
    self.populateConfigParams(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 138, in populateConfigParams
    dlg.paramsTreeOL.itemWidget(subitem, 1).setCurrentIndex(comboSelection)
TypeError: QComboBox.setCurrentIndex(int): argument 1 has unexpected type 'unicode'
```
and the suggested, python console:
```
from PyQt4.QtCore import QSettings
QSettings().remove("Extent")
QSettings().remove("Base layer")
QSettings().remove("Template")
```
then reloading/running plugin, do not solve...

**Comment by tomchadwin** [comment]
Fixed in master - please test
