### ISSUE TITLE
QGIS export to OpenLayers/Leaflet Python Error3001

### ISSUE THREAD

**Issue by LovroLKP** [tomchadwin/qgis2web#630]
Hello, 
Im totally new to js and webmaps and Im having trouble exporting Point shapefiles. I allways get the same error, while other, Area shps are working fine.

[error3001.txt](https://github.com/tomchadwin/qgis2web/files/1843704/error3001.txt)

The file that doesnt load table:

![untitled-2](https://user-images.githubusercontent.com/37717550/37855762-37658150-2ef1-11e8-9e72-d1c44bae15bd.png)

I know we have a funny alphabet, but UTF-8 code shows characters just fine in Qgis browser.

I would appreciate any help you can offer.

**Comment by LovroLKP** [comment]
For this I was using the 2.18 version of QGIS, will try with the new one and your master version...

**Comment by tomchadwin** [comment]
I'll close this issue - do feel free to raise the other things you mention as new issues.
