### ISSUE TITLE
Point symbols in OL3 are not showing up

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#632]
If you try and export a map with only simple point symbols the exported map will briefly display the points but then they disappear.

I am using qgis 2.18.18
q2w 2.33.1

I don't get any errors in the console.

**Comment by tomchadwin** [comment]
Can you try getting rid of the `declutter` line from the style file?

**Comment by boesiii** [comment]
That fixed it.  It was in the layers.js file.

**Comment by tomchadwin** [comment]
Duplicate of #608?

**Comment by tomchadwin** [comment]
Released as 3.1.1 and pushed to QGIS plugins repo.
