### ISSUE TITLE
Toggling between OL and Leaflet triggers a full export

### ISSUE THREAD

**Issue by ulmm** [tomchadwin/qgis2web#633]
When I toggle between OpenLayers and Leaflet in the "Export" tab the full project is already exported to the defined folder. 

I'm not sure if this is wanted (or necessary for technical reasons) but I was surprised that I had a lot of _qgis2web_2018_... folders in _C:\\...\AppData\Local\Temp\qgis2web_ even though I only hit export once. :-)

I'm using QGIS 3.0.0 on Win 7 with the latest qgis2web plugin (3.0.0) from the official QGIS repo.

**Comment by tomchadwin** [comment]
That hopefully isn't your export folder, but your temp folder. Yes, each preview does a full export, but to a temp location.

**Comment by ulmm** [comment]
_C:\\...\AppData\Local\Temp\qgis2web_ was the default export folder after installing the plugin and I didn't change it because I had to move different exports to several other folders anyways. Opening the folder in the Explorer was easier than changing the export folder every time... 

Ok, so it's more a user problem. :-D 
But thanks for your quick reply and your work on this plugin! :+1:
