### ISSUE TITLE
Where are now maps for backgrounds?

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#635]
In QGIS 2.18 (and older) is in qgis2web "Export to web map" window in the right bottom corner select area with maps. OSM, OSM B&W, Stamen... many maps.

IN QGIS 3 (qgis2web 3) is not that select list. Where is it now? 

http://s.kelv.cz/qgis2web-2-3.png

**Comment by HerbFargus** [comment]
In the docs.

https://github.com/tomchadwin/qgis2web/wiki/basemaps
