### ISSUE TITLE
Blocking bug when trying to use the Leaflet Visualization or Export

### ISSUE THREAD

**Issue by asitemade4u** [tomchadwin/qgis2web#639]
Hi @tomchadwin , still trying the plugin on the fairly simple US Vote map I already tested it on. I have last version of both the plugin + QGis (3.0.1) installed on an Ubuntu 16.04 LTS.
- Visualization + export to OpenLayers works perfectly now
- Not the case when the target is Leaflet.
I get this error:
```
TypeError: a bytes-like object is required, not 'str' 
Traceback (most recent call last):
  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 327, in saveMap
    feedback=self.feedback)
  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 101, in write
    folder=dest_folder)
  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 316, in writeLeaflet
    titleStart = unicode(titleSubScript(title).decode("utf-8"))
  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletScriptStrings.py", line 372, in titleSubScript
    titleSub += webmap_head.encode('utf-8').replace("'", "\\'") + """';
TypeError: a bytes-like object is required, not 'str'
```
Thanks for your help. Again, if you wish, I can send any file you may need.

**Comment by asitemade4u** [comment]
Just an addition: the Export to Leaflet process seems to go on but is in an endless loop -- I had to shut down QGis with the process monitor.

**Comment by tomchadwin** [comment]
Bug confirmed - looking into it now.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by asitemade4u** [comment]
Hi Tom, I get an error when trying to install the plugin from the 
downloaded ZIP file of the master.

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by tomchadwin** [comment]
You have to tweak the zip:

1. Open the zip, and open qgis2web-master within it
2. Extract the folder qgis2web to a temporary location
3. Zip that qgis2web folder
4. Install *that* zip

Hope that works for you.

**Comment by asitemade4u** [comment]
OK, will do asap and let you know.

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by asitemade4u** [comment]
Works perfectly now, THX!

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by tomchadwin** [comment]
Ah, splendid. Thanks for reporting back.
