### ISSUE TITLE
External browser does not start in OSX

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#64]
The whole browser does not start, as if the default browser was not set (but it is).

**Comment by boesiii** [comment]
There have been some improvements in the latest versions, please upgrade and let us know if you are still seeing this.

**Comment by tomchadwin** [comment]
I don't have access to a Mac. Can someone confirm this bug?

**Comment by tomchadwin** [comment]
I believe this is a Qt bug. We can work around it with #296, so I'll close this.
