### ISSUE TITLE
My qgis2map doesn't have the option to select which popup fields to label. 

### ISSUE THREAD

**Issue by kikegoncen** [tomchadwin/qgis2web#641]
![imagen1](https://user-images.githubusercontent.com/38980902/39627814-aa62e652-4f6c-11e8-86f8-808d94835c02.png)

**Comment by kikegoncen** [comment]
thank you very much, indeed the problem was because of the layer groups 
cheers mate

**Comment by tomchadwin** [comment]
Great. Thanks for letting me know. Sorry groups don't work.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
