### ISSUE TITLE
Failure to show Raster layer on map

### ISSUE THREAD

**Issue by lewisdjl** [tomchadwin/qgis2web#643]
QGIS version 3.0.2
QGIS2WEB version 3.1.0

**Original error fixed. Raster wasn't in same projection as other layers.**

However, now on 'Update' or 'Export' the resulting map doesn't show the raster image. Depending of whether it's Leaflet or OpenLayers I either get a icon with a question mark or a blank image where the raster should be with a border.
I have tried saving the raster layer as different types but none of them have worked.
Is this an issue with the plugin or User error?
Any help greatly appreciated.
Lewisdjl

**Comment by tomchadwin** [comment]
Can you upload the project and raster?

**Comment by tomchadwin** [comment]
If yo uzip together prject and raster, that should allow you to upload it.

**Comment by lewisdjl** [comment]
[qgis project file.zip](https://github.com/tomchadwin/qgis2web/files/2219556/qgis.project.file.zip)
Hi Tom - I dropped the 3 layers I was working with into the same directory as the Project file. Hope you can work with this?

**Comment by lewisdjl** [comment]
Leave a comment

**Comment by tomchadwin** [comment]
We really need your QGIS project file as well. Can you upload that? Will close and reopen when you do.

**Comment by lewisdjl** [comment]
[Raster Python error.zip](https://github.com/tomchadwin/qgis2web/files/2405100/Raster.Python.error.zip)

Hi - all related files attached
thanks

**Comment by tomchadwin** [comment]
Thanks. The projections don't seem to be right - the vector is not in the appropriate place on the raster.

**Comment by boesiii** [comment]
The LSOA layer seams to be correct because it aligns nicely with OpenStreetMap but your TIF image is not in the right projection.  How did you get the image on the map?

**Comment by boesiii** [comment]
When I add your TIF as a layer Qgis is not able to figure out the correct projection

**Comment by lewisdjl** [comment]
Ok so the issue is with the raster. This was a left over rasters from our Mapinfo days. I guess they’re not compatible.
I’ll start again from scratch. Most of our rasters have the same issue in QGIS2WEB.
I just import them via ‘add raster layer’ option.
Thanks


David Lewis
Senior Information Specialist,
Finance, Contracting and Business Intelligence

NHS Northern, Eastern and Western Devon Clinical Commissioning Group
Direct Dial: 01392 675326| Email: david.lewis6@nhs.net<mailto:david.lewis6@nhs.net>
NEW Devon CCG | 2nd Floor Main Building|County Hall |Topsham Road | Exeter |EX2 4QL
[Description: Description: NHS2]
Healthy people, living healthy lives, in healthy communities

**Comment by boesiii** [comment]
Your raster does work with Qgis and Q2W.  You just need to figure out the original projection of the raster or use georeferencer to move and scale the raster.  See my files, as you can see it is not exact but you can adjust it more with the georeferencer.

[qgis2web_2018_09_25-08_42_43_168453.zip](https://github.com/tomchadwin/qgis2web/files/2415223/qgis2web_2018_09_25-08_42_43_168453.zip)
