### ISSUE TITLE
Appearance Feature Request (I would like to help)

### ISSUE THREAD

**Issue by paul-bsc** [tomchadwin/qgis2web#645]
Hi Tom and any other interested parties

I would be curious to find out what the appetite would be for graduating the Appearance settings to their own tab. 

My main motivation would be to allow a user to have more control over the final map that is produced.

This would mean we could:
- have a series of web application 'themes' to choose from that style the widgets consistently across Leaflet & OL3
- introduce additional plugins to allow for an overview map, printing, syncing two map views based on a given layer, etc

I would like to have a proper dialogue about this before diving into any implementation.

Cheers!

**Comment by paul-bsc** [comment]
I have looked at the Boundless WebApBuilder briefly in the past. I will take a look through it properly again.

In terms of themes (I probably should have rather said templates), I was thinking of first starting off with just having a qgis2web-style CSS that makes the web maps produced by the plugin have a uniform look and feel (regardless of the choice between Leaflet & OpenLayers). By this I simply mean styling all the widget elements in the same way as a first pass.

Once that's in, I would like to extend the template framework to include some different web app styles, for example;
- having  a template for a swipe/spyglass effect
- or a side panel that can be loaded with a histogram controlled by values in the map extent

I have no experience with Qt at all, so that will probably be the biggest upfront headache for me, but I'm sure once I get stuck into the code things will start to make sense. 

I have some time in the coming weeks that I would like to put towards this.

**Comment by tomchadwin** [comment]
Qt's not too bad - this is my only experience of it so it's largely PyQt. Just ask if you come across anything you can't figure out. I invariably won't know the answer, but two heads are better than one, and all that.

I think the only other thing I'd say at this stage, is that the plugin is meant to be quite lightweight - in other words, it is intended to create maps for people to include in their webpages. It's not really intended to create big web GIS apps. I'm not saying that's what you are proposing, but it's definitely something we want to keep in mind.

In the meantime, I'll try to see if I can wrestle the `.ui` file back into good order, and get it parsed and loaded as part of the plugin, without the extra compile step.

**Comment by tomchadwin** [comment]
OK, I think I've got it all working now in master. Instead of importing `ui_maindialog.py`, manually compiled and subsequently tweaked, `maindialog.py` now compiles `ui_maindialog.ui` when the plugin is run.

What this means is that you don't have to get involved with the UI code, but can now edit `ui_maindialog.ui` in Qt Designer.

I've not heavily tested this change yet, but hopefully it works. Please feel free to start investigating to see if you can make some progress. And thanks again!

**Comment by paul-bsc** [comment]
Brilliant! I should have some time to dedicate to this tomorrow, I will keep you in the loop on the progress made.

**Comment by paul-bsc** [comment]
So I've started working on this. You can track my progress here: https://github.com/paul-bsc/qgis2web/tree/ui-changes

So far, so good.
![image](https://user-images.githubusercontent.com/37061765/40789916-e12b6866-64f3-11e8-9061-43d897a8147d.png)

- I still need to move the data export parameters from the Appearance tab to the Export tab
- The 'Appearance' parameter group should probably be named something else in this configuration - widgets or plugins perhaps?

I have one thing I'm stuck on now, but I've run out of time today.. Hopefully can get it right tomorrow, unless you maybe have some insight?
- I had to comment out some stuff to get everything to load properly. You can find this at line 130 in ui_maindialog.py and 164 in maindialog.py
  - the reference to self.verticalLayoutWidget_2 should point to something else now, but everything I've tried hasn't been successful. Any ideas? 
- once this kink is ironed out, I will go through the UI code and refactor everything so that the variables are more descriptive

After this, I will start looking at some of the more exciting stuff I would like to add functionality-wise.

**Comment by paul-bsc** [comment]
Okay, so today I've made the following progress:

![image](https://user-images.githubusercontent.com/37061765/40840563-8eaa95da-65a7-11e8-89b6-f1af877c0c2e.png)


The main goal I have in mind at the moment is making sure that the output from OL or Leaflet are as similar/consistent as possible. This includes the output style, placement of widgets, etc. Once this is behaving I will start with some additional widgets such as the overview map, printing, etc.

- A user can now select an Accent Color in the appearance tab which will (eventually) style all of the widgets accordingly
 - At the moment this is just an arbitrary list that I included, but the idea is to swap it out for a color picker
  - Need to just look up the relevant Qt documentation to get this working
- The Leaflet Geocoder has been swapped out with https://github.com/perliedman/leaflet-control-geocoder so that we can style everything consistently as mentioned above


This is still very much a work in progress... I still need to finish up on the Leaflet side of things, then all that's remaining is making sure that the widgets are a consistent size between OL and Leaflet and we should have some pretty consistent outputs

**Comment by paul-bsc** [comment]
Also... The issue with the OL search not drawing in the proper place in the preview window? Is this because we are explicitly setting its location and there is some limitation as to what the preview renderer can interpret from the CSS? It's a really unfortunate bug, I will try look into fixing it.

I also wanted to find out if there is a specific reason OL is the default library? I'm sure there is some historical context for this...

**Comment by HerbFargus** [comment]
This is something that interests me, I'm a tad shoddy in the code department but I'm happy to test/provide feedback/logs if needed. it's looking good so far

**Comment by paul-bsc** [comment]
@HerbFargus That will be really excellent! I am hoping to at least have the UI stuff sorted this week, after which i will start with some of the additional plugins. Feedback will be excellent and very necessary for something like this as it impacts the user experience as well as the outputs produced.

FYI, Color Accent now works with the QGIS color picker. At the moment I've hardcoded that the widget symbols are white and the user selects the 'accent'. Obviously this will be an issue if the user wants lighter colored accents. Does it make more sense to have the option of selecting two accents? One for the symbol and another for the widget? Or should QGIS2WEB simply swap the symbol to black if it detects a light accent? Feedback would be very much welcome.

![image](https://user-images.githubusercontent.com/37061765/40877383-65f0d800-6680-11e8-9bb6-5fc002df8931.png)

**Comment by HerbFargus** [comment]
The simplest option is to just have one colour for the widgets but as you mentioned it could cause issues if anyone wants a light colour scheme. I'm quite fond of material design which generally has a primary colour and an accent colour and an accompanying light/dark pallette:

eg: [Material Design Colour Tool](https://material.io/tools/color/#!/?view.left=0&view.right=0&primary.color=FF6F00&secondary.color=0D47A1)

I think it would give people the most creative control to have:

- Widget Colour/Primary Colour
- Icon(Favicon?) Colour/Accent Colour

**Comment by paul-bsc** [comment]
The capability is now there to set the color for the background and icon for the widgets independently. I still haven't implemented it for all of the widgets yet; that will be part of what I work on this week.

Some of the icons are static images which I will swap out for their corresponding Font Awesome glyphs.
 
![image](https://user-images.githubusercontent.com/37061765/40886794-b6a5f906-673e-11e8-939d-d5610e770bf8.png)

**Comment by tomchadwin** [comment]
Sorry not to have responded - been camping this week.

Looking really good. Answers to your questions:

- Having to comment out lines from maindialog.py - you sorted this?
- OL widget placement: it's horrible. I have to try to keep a manual count of the number of widgets a user wished to display, and set the `top` CSS attribute accordingly. Leaflet handles ths automatically, taking care of placement for you, but OL doesn't (or didn't when I coded this). The major issue is that the code works for modern browsers (I think), but the preview windows uses QtWebkit, and I'm guessing that's a good few steps behind desktop browsers in implementation of some standards. For example, the Leaflet vector tile solution doesn't work in the preview window (from memory). If you can work out a better solution, I'd be very happy. The main thing I want to avoid, though, is rendering different code for the preview compared to the export - they should be identical.
- OL default map format: this is purely because the GUI was modified from the original qgis-ol3 plugin. I prefer Leaflet myself, so I'd be happy to change the default. There's an open issue for this somewhere.

**Comment by paul-bsc** [comment]
Progress is good.

![image](https://user-images.githubusercontent.com/37061765/40922178-d906eac2-6811-11e8-81a9-afbc8d7fb1c3.png)

Today I managed to get through the following:

- Scale bars are rendered identically in OL & Leaflet
- OL & Leaflet use a binocular image for the layer search to avoid confusion with the geocoder
- All existing Leaflet widgets are styled using the new styling controls
- Symbols are styled with the latest Font Awesome Glyphs for all Leaflet widgets except the layer list
- Font files are now side loaded with the web app when it is created.
  - This was a necessary side effect of the preview not being able to load the icons from the CDN.

Hopefully tomorrow I will be able to get the OL-side of things to the same state as the Leaflet outputs.

**Comment by paul-bsc** [comment]
@tomchadwin Just saw your comments. Hope camping was good!

The commented out thing was easily sorted. I was still wrapping my head around everything at that stage.

I spent a bunch of time today going through the Qt classes that drive the preview. It's unfortunate that the Webkit implementation is so behind. I saw there is a Chrome alternative, but many features have not yet been implemented so the QtWebkit implementation is still better from the literature I found.

I'm going to be focussing on OL tomorrow, so hopefully I can wrangle the preview to behave a little better.

I personally prefer Leaflet and would be happy with it as the default as well.

The Leaflet vector tile issue you mention is interesting. I will take a look at that tomorrow as well, perhaps there is something that can be done.

**Comment by paul-bsc** [comment]
QtWebEngine is what I was referring to. It is based on Chrome.

The Leaflet and OL outputs are aligned for the most part. I've intentionally left the widgets smaller on OpenLayers as it's closer to the default sizing. 

Leaflet:
![image](https://user-images.githubusercontent.com/37061765/40975738-383413d4-68cc-11e8-8a32-a3903b8860c5.png)
![image](https://user-images.githubusercontent.com/37061765/40975950-d7d834c4-68cc-11e8-966a-be9093af2dae.png)


OpenLayers:
![image](https://user-images.githubusercontent.com/37061765/40975754-442cc258-68cc-11e8-9a35-d0c3f17c73ba.png) 
![image](https://user-images.githubusercontent.com/37061765/40975904-bb569994-68cc-11e8-849f-6ca7a4a69946.png)


I managed to get the Search widget to draw in the correct place in the preview for OL, although it still isn't honoring some of the other CSS. I think I have worked out why it messed up the render; perhaps fixing this would potentially fix some other rendering issues as well? The only way I could get the Search widget to fall in the correct place was to add a touch-specific CSS tag for its top position. This leads me to believe that the preview is rendering a 'touch' version of the page (or at least mixing touch and 'normal' styling elements). Further evidence for this is the fact that the OL widgets are significantly larger in the preview than when the page is opened in a browser. Perhaps if we could somehow disable this behavior then it would render better? I experimented with forcing a user-agent which had no effect, so I'm not really sure how else to address the issue. There isn't anything I could find in the Qt documentation for the QtWebView settings.

I am going away for a couple of days. The only thing remaining is to update the help file... if someone is keen to make the necessary changes, that would be great, otherwise I will get to it next week when I can. 

Please let me know how you would like to proceed. I have merged the changes into my forked master... not sure if there is something else you need from me at this stage?

**Comment by tomchadwin** [comment]
If you are happy with it, make a pull request against master. I look forward to it.

Interesting idea about touch classes - I'll take a look at what causes them to take effect, and see if I can make any sense of it.

**Comment by tomchadwin** [comment]
A couple of issues before I make a release with this new functionality:

- (trivial) I don't like the default dark control colours - any chance you can default to the default Leaflet (pale grey) colours?

- I'm not keen on the update preview button being moved under the map, and I would also rather that the map format, update preview, and export buttons were always visible, rather than just being on the export tab. I tried to wrestle with Qt Designer to achieve this, but failed. Would you be able to have a go?

**Comment by paulds8** [comment]
Hi Tom

Apologies for the radio silence.

Colours
No problem. Easy to change. 

Layout
Do you want these buttons moved out of the export section entirely? Perhaps as a permanent bottom row on the left of the view?

I will have some time to look at this probably on Friday.

**Comment by tomchadwin** [comment]
> Do you want these buttons moved out of the export section entirely? Perhaps as a permanent bottom row on the left of the view?

Yeah - I'd like it to look as it did before your work, so those buttons bottom-left, but for them not to be within one of the tabs, and hence always visible. That's what I couldn't quite achieve.

Oh, one other tiny gotcha - make sure the first tab has focus in QtDesigner when you save the UI, so that it has focus when the plugin starts.

And thanks again for all the work.

**Comment by tomchadwin** [comment]
OK, all tests now fixed, and a new 3.2.0 released with all this work. Thanks so much!

I'll close this issue - if you want to work on more customization options, just open new specific issues accordingly.

**Comment by tomchadwin** [comment]
Specific customization possibilities:

- title font size/colour and background
- popups ditto
- search field ditto
