### ISSUE TITLE
Multiline popup field

### ISSUE THREAD

**Issue by gHupf** [tomchadwin/qgis2web#647]
If I use Multiline Fields in QGIS 3.0.3 and export them to qgis2web, the popup fields are not displayed correctly. Is this somehow possible? I know I can edit the code, but that's a lot of work.

**Comment by tomchadwin** [comment]
Can you describe "not displayed correctly" with a bit more detail, and upload a screenshot?

**Comment by tomchadwin** [comment]
Closed without feedback - comment and I can reopen.
