### ISSUE TITLE
Problem with Polygons

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#650]
I am using the latest version (2.34) and when I export a polygon layer I get an error in the browser, "Unexpected token ," on line 22.  And when I look on line 22 I see:

`    , fill: new ol.style.Fill({color: 'rgba(233,230,219,1.0)'}),`

If I remove the first comma the problem is fixed.

**Comment by boesiii** [comment]
I am using the lakes shapefile shipped with the plugin.
[lakes.zip](https://github.com/tomchadwin/qgis2web/files/2076735/lakes.zip)

**Comment by tomchadwin** [comment]
Got it - stroke style: no pen causes the bug. Thanks.

**Comment by tomchadwin** [comment]
As a temporary workaround until the fix, change the stroke style to Solid Line, and make the stroke colour transparent.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by boesiii** [comment]
I downloaded master but master is for Qgis 3.0.  How do I download a compatible version for Qgis 2.18.18?

**Comment by tomchadwin** [comment]
Since the code for each is in its own branch, fixes to 3 have to be backported manually to 2. I'll try to get to it.

**Comment by tomchadwin** [comment]
Fixed in QGIS2 branch. Can you download that branch to test, @boesiii?

**Comment by boesiii** [comment]
Works!
