### ISSUE TITLE
non-ASCII symbols in labels

### ISSUE THREAD

**Issue by Xeenych** [tomchadwin/qgis2web#651]
Looks like qgsi2web is unable to hande non-ASCII labels.
It produces output, but chrome console says:
Uncaught SyntaxError: Invalid or unexpected token qgis2web_expressions.js:760 
Uncaught SyntaxError: Invalid or unexpected token index.html:72

**Comment by tomchadwin** [comment]
Is it a plain label (ie just the contents of a single field), or does the label use an expression (the error message looks as though it possibly does).

**Comment by Xeenych** [comment]
Yes, most of my labels are field-driven, and some of them are expressions

**Comment by tomchadwin** [comment]
Can you upload your project and layer file?

**Comment by Xeenych** [comment]
[1.ZIP](https://github.com/tomchadwin/qgis2web/files/2084216/1.ZIP)
My project is very big. Here is one layer.

**Comment by tomchadwin** [comment]
I've not been able to recreate the issue from the files you uploaded. Can you check and let us know if it's still an issue?
