### ISSUE TITLE
Error Code when export point layer with cluster option

### ISSUE THREAD

**Issue by fidschy** [tomchadwin/qgis2web#653]
I am using version 3.1.1 of qgis2web with QGIS 3.03
I want to display a point layer as a cluster. When exporting I get the following error message:

![grafik](https://user-images.githubusercontent.com/40431271/41661016-f2b305d0-749d-11e8-974a-6c4b98578014.png)

When using version 2.34.0 of qgis2web with QGIS 2.18 the export works with the cluster option.
Is there any way to solve the problem.

Thank you

**Comment by tomchadwin** [comment]
Fix committed to master. Please test and report back.

**Comment by fidschy** [comment]
I'm not sure what exactly I have to do.
I have changed the file 'leafletScriptStrings.py' in the directory '..\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis2web\'. When starting QGIS I got an error message that qgis2web can't be started.
Can you please tell me which files I need to exchange?

Thank you

**Comment by tomchadwin** [comment]
Apologies. Try following the instructions in this reply: https://github.com/tomchadwin/qgis2web/issues/620#issuecomment-369883234.

**Comment by fidschy** [comment]
Fantastic, thank you very much, now it works!

**Comment by tomchadwin** [comment]
Great - thanks for reporting back.
