### ISSUE TITLE
 AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by rduivenvoorde** [tomchadwin/qgis2web#655]
Testing in QGIS3 master

Trying out a time a geojson layer, my layer is not showing in the Time tab.

But clicking the 'Add Time' button shows the following error:

![an error has occurred while executing python code _003](https://user-images.githubusercontent.com/731673/41905421-661bb250-793b-11e8-8bfa-4a17b229f222.png)

```
Easy reproducible in ipython:

In [3]: os.walk('/tmp').next()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-caadf6fd63e0> in <module>()
----> 1 os.walk('/tmp').next()

AttributeError: 'generator' object has no attribute 'next'
```
While in QGIS 2.18 it works...

**Comment by tomchadwin** [comment]
I don't know the Time code at all well. However, I do know that you have to export your map first, and then use the Time tab to add the time functionality. Is that what you did?
