### ISSUE TITLE
Visible layers not 'visible' when published to web

### ISSUE THREAD

**Issue by lewisdjl** [tomchadwin/qgis2web#664]
QGIS: V 3.0.2
QGIS2WEB: 3.1.1

Please see attached file to example.
In QGIS2WEB the top layer is set to 'visible' when publishing but on the map it doesn't appear.
the last layer is a Google maps background and this is set to NOT be 'visible' when publishing. As you can see from the attachment Google maps IS visible.
I have noticed this other projects I have published to web. It's as if the layers 'visibility' is out of sync???
Also noticed Pop-ups were not active even though 'pop-ups on hover' is selected.

Thanks
David

![q2gis](https://user-images.githubusercontent.com/39260464/43081828-0f0fa42e-8e82-11e8-9c75-798b53735a86.JPG)

**Comment by tomchadwin** [comment]
I'm afraid I don't have much experience of working with Google Maps in QGIS, OpenLayers, or Leaflet. It's not something I generally recommend, as I don't know whether such use is acceptable under Google's licensing. Sorry not to be able to help further.

**Comment by tomchadwin** [comment]
Can you reduce the complexity of your project by removing layers, and seeing whether the issue remains? For example, if you remove all layers except the problematic top one, does it still fail to appear?

**Comment by lewisdjl** [comment]
Hi Tom. Thanks for looking.
I have removed layers and the issue still remains. The only way around this is to remove the ‘visible’ flag on the top layer you need to be shown. i.e. I want the map to open with the last two layers (Google and NEW Devon & Torbay Boundary). I’ve had to untick the  ‘visible’ flag on the ‘NEW Devon & Torbay’ layer, which still is visible(which is what I want) but this turns off the layer above from showing. Had I not of done that the 18-64 population would have been displayed on opening the map.


[cid:image002.jpg@01D43F8C.DA4B8260]
David Lewis
Senior Information Specialist,
Finance, Contracting and Business Intelligence

NHS Northern, Eastern and Western Devon Clinical Commissioning Group
Direct Dial: 01392 675326| Email: david.lewis6@nhs.net<mailto:david.lewis6@nhs.net>
NEW Devon CCG | 2nd Floor Main Building|County Hall |Topsham Road | Exeter |EX2 4QL
[Description: Description: NHS2]
Healthy people, living healthy lives, in healthy communities

**Comment by boesiii** [comment]
Can you upload your data files and project file?

**Comment by lewisdjl** [comment]
[Demographics 2.zip](https://github.com/tomchadwin/qgis2web/files/2332425/Demographics.2.zip)

hopefully I've zipped all you need?
thanks

**Comment by tomchadwin** [comment]
No, we need your QGIS project file and the individual layer. Without that, we can't recreate the issue and then investigate it. I'll close this for now, and will reopen it if you can upload the files.

**Comment by lewisdjl** [comment]
[Demographics.zip](https://github.com/tomchadwin/qgis2web/files/2404984/Demographics.zip)
hopefully this has what you need now. I've included the Project file this time.
Thanks in advance

**Comment by tomchadwin** [comment]
Really sorry, but the project file doesn't seem to match the layer file in that zip. Can you remove all layers from your project apart from the one which displays the errors, then zip the project and that layer, and then upload.

I'm sorry to be so specific, but I have to ask you to do as much work as possible to allow me to investigate the problem. Otherwise, I just just don't have the time to make sense of the unneeded data. Hope you understand.

**Comment by lewisdjl** [comment]
Sorry Tom this is my fault. Is there a way save everything from your map to the same location i.e. csv, shapefiles and project file?

I’ve done it again this morning but when I open the project file I get the ‘handle bad errors ‘box.

It’s because my base file are not saved in same location as the project file.



David Lewis
Senior Information Specialist,
Finance, Contracting and Business Intelligence

NHS Northern, Eastern and Western Devon Clinical Commissioning Group
Direct Dial: 01392 675326| Email: david.lewis6@nhs.net<mailto:david.lewis6@nhs.net>
NEW Devon CCG | 2nd Floor Main Building|County Hall |Topsham Road | Exeter |EX2 4QL
[Description: Description: NHS2]
Healthy people, living healthy lives, in healthy communities

**Comment by tomchadwin** [comment]
No, there's no easy way, but then, I don't really want lots of layers. Remove all layers from your project apart from a single one which triggers the error, then upload that .qgs project file and that layer file in a zip. It doesn't matter if the path doesn't work - I can use the Handle bad layers dialog so long as there's only that single layer. Thanks.

**Comment by boesiii** [comment]
i have looked at your data and it is still missing the following files

- imd lsoa.csv

- rank by lsoa.csv

- devon_lsoa_populations_min_field.csv

- new devon and torbay ccg boundary shapefile

- new version devon stp lsoa shapfile

- stp practice list sizes.csv

**Comment by boesiii** [comment]
The only files included in the files you attached where the qgis project file and a DXF file.
