### ISSUE TITLE
JSon layer outputfiles without the underscore and number..????

### ISSUE THREAD

**Issue by NvBgm** [tomchadwin/qgis2web#666]
Hello,

Why ussing on the JSon output files the underscore and number expand ??
Is it possible to do not ???

Example:

JSonfile_5.js  or JSonfile.js

**Comment by NvBgm** [comment]
Sorry wrong button....

**Comment by tomchadwin** [comment]
It's there because QGIS layers can have the same name, so the number is required to ensure the filenames are unique.
