### ISSUE TITLE
WMS maps disappear from zoom level 19 and up in leaflet

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#667]
It appears that no matter what WMS map I include in QGis and export to leaflet, the WMS maps disappear when zooming further in than zoom level 18 (eventhough it is possible to zoom further in in QGis). Is it a parameter hard coded somewhere?

Example: http://byogtrafik.ramboll.dk/SandBox/Signs/#18/55.67491/12.36751

It is an issue with latest QGis2Web version both in QGis 2 and 3

**Comment by tomchadwin** [comment]
You're right - apparently that's the default Leaflet behaviour:

https://leafletjs.com/reference-1.0.0.html#tilelayer-wms

So, to change it, find the following in your code (open index.html in a text editor):

```javascript



var overlay_DTKSkrmkortdmpet_1 = L.WMS.layer("http://kortforsyningen.kms.dk/service?servicename=topo_skaermkort&client=QGIS&version=1.1.1&login=magerlin&password=kortfors", "dtk_skaermkort_daempet", {
   format: 'image/png',
   uppercase: true,
   transparent: true,
   continuousWorld : true,
   tiled: true,
   info_format: 'text/html',
   opacity: 1,
   identify: false,
  });
```

Add an extra option:

```javascript
maxZoom: 20
```

Let us know if that works.

**Comment by magerlin** [comment]
It works!
