### ISSUE TITLE
Tiling Option for Larger Imagery/Rasters

### ISSUE THREAD

**Issue by huntergallant** [tomchadwin/qgis2web#669]
I think an option to render larger imagery/raster files as tiles would be extremely useful and extend the functionality of QGIS2Web. Say it includes GDAL2Tiles like options to render as x/y/z.png directories rather than a single PNG overlay. I work with large UAV/drone datasets with imagery easily a few GBs in size. If I could setup my project in QGIS with my typical overlays (polys and lines) over my high-resolution basemaps and simply run QGIS2Web, I would be a happy person.

**Comment by tomchadwin** [comment]
Since other plugins achieve this, I don't think it's something I can add in at the moment, though all contributions are very welcome. Have a look at QTiles, I think, though I've never used it myself.

**Comment by HerbFargus** [comment]
I've used custom tiles generated by qtiles and then used the xyz tiles in qgis 3 to add it as my basemap, I modified a few things manually for sliders and whatnot but it's doable:

https://herbfargus.github.io/oregoncity/

**Comment by boesiii** [comment]
I just added a feature request to the bug tracker. (https://issues.qgis.org/issues/19729)

In any case you should be able to "hack" the output from qgis2web to include the tile layer just like Herb.

**Comment by TheThunder777** [comment]
I also work with drone photography and have found that a workflow ( in QGIS 2 ) that includes the following:
1. Create tiled layer using "QTiles" plugin or similar
2. Add tiled layer to QGIS - there are tutorials for this.
3. Export using Qgis2Web
4. Modify layers.js to remover the "base" property on aerial photo.

All done.

**Comment by tomchadwin** [comment]
Just to revisit this: now that there is a processing algorithm for this, I started to implement a "Tile" option for local rasters. However, I've decided finally not to do this, for the following reasons:

- tiling can be an intensive process, and repeating it for each qgis2web preview and export would be a needless performance hit (and would fill up hard drives)
- a simple checkbox is not enough, as one really needs to specify zoom levels
- exposing zoom levels and other option would complicate the GUI

The recommendation is therefore definitely to generate the tiles yourself, and then include them in your QGIS project for qgis2web to export.
