### ISSUE TITLE
OL3 broken

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#67]
When using the current master version, it does not create the necessary files for OL3.

**Comment by boesiii** [comment]
I have tried version 0.8.0 and still the same.

**Comment by tomchadwin** [comment]
It's working for me, with some test data I have. What happens when you try?

**Comment by boesiii** [comment]
After I click the export button, my browser will open but index.html is not created.  The export folder has the "layers" folder but nothing in it and it has the resources folder with some the the OL3 files but nothing else, no index.html

**Comment by boesiii** [comment]
I am using Win7 64bit

**Comment by tomchadwin** [comment]
I'm W7x64 as well. Can you try changing the export location? I have a feeling that something is not right with all of your saved qgis2web settings. Changing each one *should* rectify that.

**Comment by boesiii** [comment]
If "Delete unused fields" is unchecked it works, but if it is checked then nothing works.

**Comment by boesiii** [comment]
I am not even sure what it means by "unused" fields.

**Comment by tomchadwin** [comment]
Unused fields are those not displayed in the pop-up. "Delete unused" means delete those unused fields from the JSON exported.

**Comment by boesiii** [comment]
It seams that the issue is when the plugin first starts the Base Layer option has no value.  Somewhere it should be set a default on "None"

**Comment by tomchadwin** [comment]
Is this issue still present, or is it now fixed in master?

**Comment by boesiii** [comment]
It is still present in master.
