### ISSUE TITLE
"Geolocate User" function throws a security issue when used in the final leaflet map

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#670]
Pressing then geolocate icon in a produced leaflet map returns an error: Only secure origins are allowed
![image](https://user-images.githubusercontent.com/1887531/44832746-0e1b2a80-ac2c-11e8-8e38-d7a51f3ad989.png)

Try it here: http://byogtrafik.ramboll.dk/SandBox/Kbh/Victor

I am aware this is probably not strictly QGis2Web, but some  new security things setup in Chrome? But perhaps some changes in Qgis2web can avoid this?

The error message links to this document: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

I get the error message in Chrome, Mozilla and Opera and both in Windows and on Android.

No problem in Internet Explorer

**Comment by tomchadwin** [comment]
This is a Chrome security feature. It does not allow user location data to be transmitted over HTTP, but only over HTTPS. The only solution is to serve your site over HTTPS. Doing so carries many other benefits, and is pretty much expected these days, so I'd recommend you look into it.
