### ISSUE TITLE
placement option gets dismissed when using categorized style in OL

### ISSUE THREAD

**Issue by Andre-J** [tomchadwin/qgis2web#671]
If I use a categorized style, with labelling along line features, the placement variable is not handed over:

<code>

     function categories_Strecken_0(feature, value, size, resolution, labelText,
                       labelFont, labelFill) {
                switch(value.toString()) {case 'abgebaut':
                    return [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(177,177,177,1.0)', lineDash: null, lineCap: 'square', lineJoin: 'bevel', width: 8}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement)
    }),new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(255,255,255,1.0)', lineDash: [10,5], lineCap: 'square', lineJoin: 'bevel', width: 4}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement)
    })];
                    break;

    ,,,,,,

    var placement = 'line';
    if (feature.get("Strecke") !== null && resolution > 0 && resolution < 28) {
        labelText = String(feature.get("Strecke"));
    }
    
    var style = categories_Strecken_0(feature, value, size, resolution, labelText,
                          labelFont, labelFill);

    return style;
    };

</code>

Adding the placement variable to the function parameters seems to return the desired rendering.

Rule-based labelling is not affected from this.

**Comment by tomchadwin** [comment]
At the moment, I can't get lines to label at all, which is a little worrying. Investigating.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by Andre-J** [comment]
Sorry, it does not work. The style files for my line layers end with

>    var style_Strecken_2 = ;

which throws an error in the browser error console. The old version closed with

>    return style;
>    };

Apart from that, I would really see this in QGIS 2.18 LTR as well.

**Comment by tomchadwin** [comment]
That error is a symptom when an error is written to the qgis2web log. Can you check it (View > Panels > Log messages > qgis2web)?

**Comment by Andre-J** [comment]
`2018-09-28T08:05:46     CRITICAL    Traceback (most recent call last):
              File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles
              bufferColor, bufferWidth) = getLabelFormat(layer)
              File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 191, in getLabelFormat
              min = float(palyr.scaleMin)
             AttributeError: 'QgsPalLayerSettings' object has no attribute 'scaleMin'`

**Comment by tomchadwin** [comment]
You uncovered an unrelated bug to do with scale-dependent labelling in OL. I've committed a fix to master. Can you test?

As for QGIS2, I think it's unlikely that I'll be able to backport fixes. QGIS3 become LTR in a few months. If anyone else can help out, I'd be very grateful.

**Comment by Andre-J** [comment]
Tested now: Lines show up, but no labels. And point layers show nothing at all. The same QGIS project exports well on QGIS 2.18 with this output (after some tweaks on the js code): http://karte.nrwbahnarchiv.bplaced.net/

**Comment by tomchadwin** [comment]
I really need your project and layer file to find out what is wrong. I don't have enough info without them.

**Comment by tomchadwin** [comment]
My best guess at the moment is that the conversion between scale and resolution is not correct. QGIS sets scale-dependent visibility on map scale, but OL sets it on resolution. For ages, the conversion from QGIS to OL was done with this formula:

```python
resolution = 1 / ((1 / scale) * 39.37 * 90.7)
```

I guess for whatever reason, this is no longer correct. I'll see whether OL5 expects different measurements here.

**Comment by tomchadwin** [comment]
The above formula is:

```
resolution = 1 / ((1 / scale) * INCHES_PER_MAP_UNIT * DOTS_PER_INCH)
```

I don't know where the value of 90.7 for DPI came from, but I can't see it being very wrong (the two traditional values for DPI are 72 and 96, though real-world values tend to be higher these days).

39.37 is inches per *metre*. I don't know if projections are making this value incorrect, but your project, at least, is in EPSG:3857, whose unit is metres, I believe? Perhaps the fact that your vector layers are in EPSG:4326, whose unit is degrees, could be causing an issue. At this stage, I am not sure.

Any help gratefully received.

**Comment by tomchadwin** [comment]
Reference for the formula:

https://github.com/openlayers/ol2/blob/e85a087c8fb857648aa7c5e4f771d1d2a13fc48b/lib/OpenLayers/Util.js#L1101

Yes, it's OpenLayers *2*.

**Comment by Andre-J** [comment]
Looking inside the js code, it seems that you swapped the minResolution and maxResolution for all layers in layers.js, and the resolution values in all layers style files for scale-dependent label display as well.

Apart from that, I would like to see text buffers as a default setting. It makes labelling along a line readable.

**Comment by tomchadwin** [comment]
> you swapped the minResolution and maxResolution

What do you mean? That the minResolution value is assigned to the maxResolution property, and vice versa?

**Comment by Andre-J** [comment]
Yes, the minResolution value should be the smaller one, and maxResolution the larger one. As it stands now, the valid Resolution is empty, hence nothing is drawn in all zoom levels. Same for the labels, where `resolution > 28 and resolution <0` means "never".

**Comment by tomchadwin** [comment]
Good grief - I think you're right. How on earth has this stupid error crept in?

**Comment by Andre-J** [comment]
Yes, works now as expected.

**Comment by tomchadwin** [comment]
Perfect! Thanks for all the help reporting and testing. It's very much appreciated indeed.
