### ISSUE TITLE
Feature suggestion: Set max zoom for Geolocate User

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#672]
Geolocate User zooms in depending on the accuracy of the GPS signal as I understand it.

In some of my use it has been zooming in too far so your miss the overview.

A first simple solution allowing for manual correction in generated index.html will be to replace 

`        L.control.locate().addTo(map);`

with

`map.addControl(L.control.locate({
       locateOptions: {
               maxZoom: 19
}}));`

in the generated index.html.

A final solution would be to be able to specify maxZoom for Geolocate inside Qgis2web,

**Comment by tomchadwin** [comment]
I like the sound of this idea. Are you able to make a pull request with it?

**Comment by magerlin** [comment]
No I am sorry - I have never found the time to dig into python or javascript programming even though I would like to....

The code above I found on the net and by luck it worked :-)

**Comment by tomchadwin** [comment]
Completely understood, and thanks for the fully-worked and tested suggestion. That's the bulk of the work, so I'll see if I can incorporate it at some stage.

**Comment by tomchadwin** [comment]
Added to master. Please test and report back if you can.

**Comment by magerlin** [comment]
As far as I can see the Geolocate function is now limited to the general maxzoom, which probably is  a fair general way of setting it. 

In my actual use the maps were used for field surveys and I needed very high zoom levels for the survey-part while for navigation between survey spots I manually had set up the maxzoom for geolocate at a lower zoom-level to keep the overview while biking between survey spots. But it might be a too specific issue to handle in the plugin.....
