### ISSUE TITLE
Two files contain "known incorrect sRGB profile"s

### ISSUE THREAD

**Issue by kannes** [tomchadwin/qgis2web#673]
Two files from this plugin are responsible for warnings being printed to the terminal on QGIS launch, see https://issues.qgis.org/issues/19747 or https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

```
  ./qgis2web/images/search-icon.png:
   Total length of data found in critical chunks            =      1141
pngcrush: iCCP: known incorrect sRGB profile
--
  ./qgis2web/icons/layer.png:
   Total length of data found in critical chunks            =       261
pngcrush: iCCP: known incorrect sRGB profile
```
To fix you can process them via `pngcrush -ow -rem allb -reduce`. The -reduce flag is not needed but will also do a lossless 90% file size reduction. :)

**Comment by tomchadwin** [comment]
Thanks! A PR would be welcome...

**Comment by tomchadwin** [comment]
*Awfully* good of you!
