### ISSUE TITLE
grouped layers 

### ISSUE THREAD

**Issue by Rafael-Guzman** [tomchadwin/qgis2web#678]
hello Tom, 

I have this qgis map that has layer groups, the web map comes out nice because it shows the group name on the legend and then the layers within, but I dont see how to enable the inline label or header label for each layer. is this possible ?

![image](https://user-images.githubusercontent.com/37252212/45383682-28102200-b5c9-11e8-8168-e237456b8adc.png)

**Comment by tomchadwin** [comment]
I'm afraid this is not supported at the moment. Layer Groups are just not well supported at all in the plugin, I'm afraid. Contributions very welcome.

**Comment by tomchadwin** [comment]
Sure, or you can just put them on a share and give people the local path - with some exceptions, the maps don't have to served over HTTP/S.

**Comment by boesiii** [comment]
Since it is just HTML and javascript you don't need Apache.
