### ISSUE TITLE
OL browser crash if zoom out beyond earth in EPSG:3067

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#679]
Raised and discussed here: https://twitter.com/vsaarinen/status/1041209070630449152

**Comment by tomchadwin** [comment]
Possible fix is to update proj4js to latest stable (2.5.0). Awaiting confirmation.

**Comment by tomchadwin** [comment]
Fix hopefully confirmed.

**Comment by NeliHarbuzava** [comment]
@tomchadwin thank you. I found this problem in my own project with Openlayers and mobile browsers. Upgrading proj4js to version 2.5.0 helps.

**Comment by tomchadwin** [comment]
@NeliHarbuzava Thanks for confirming. I *think* I've updated the proj4js which ships with qgis2web, so I'm hoping it all works now.
