### ISSUE TITLE
putting map in the wordpress

### ISSUE THREAD

**Issue by Rafael-Guzman** [tomchadwin/qgis2web#682]
hello team, 

do you guys know if possibly this could be put in a wordpress page, the whole structure?, and keeping the theme and all in place, avoiding to use iframes

regards,

**Comment by tomchadwin** [comment]
Yes, but I've not tried it myself. I'd make a new qgis2web template which is an incomplete HTML page - no html, head, or body tags, but everything else left in. This will probably break the qgis2web preview.  

Export your map, and copy the contents of your exported index.html into your WordPress page somehow (I don't know how to do that). The tricky bit will be uploading all the other exported flies and altering the paths in the HTML to the upload path. I hope that makes sense.

**Comment by tomchadwin** [comment]
I'll close this for now, but do comment with further questions - this is of use to others.
