### ISSUE TITLE
Layer not showing with Leaflet Export

### ISSUE THREAD

**Issue by pticle94** [tomchadwin/qgis2web#685]
Hello,

Using QGIS 3.2.3 with qgis2web 3.3.0.

I have a QGIS project with 5 active layers:
![image](https://user-images.githubusercontent.com/43582655/46066499-05f3d380-c175-11e8-9437-3bc4626ca609.png)

Here are the settings used for the Leaflet export:
![image](https://user-images.githubusercontent.com/43582655/46066604-36d40880-c175-11e8-8c62-b28c33ba1213.png)
![image](https://user-images.githubusercontent.com/43582655/46066609-39366280-c175-11e8-947e-bf45bdcbc7f6.png)
![image](https://user-images.githubusercontent.com/43582655/46066612-3c315300-c175-11e8-824c-ae3745af5ae4.png)
![image](https://user-images.githubusercontent.com/43582655/46066617-3e93ad00-c175-11e8-8c56-01853457718b.png)

And here is the result:
![image](https://user-images.githubusercontent.com/43582655/46067327-d5ad3480-c176-11e8-9d1e-125d12a62f1a.png)

![image](https://user-images.githubusercontent.com/43582655/46067430-16a54900-c177-11e8-91a6-c6e05f2f95dc.png)

It seems that the layer MSR_50M has an issue with the projection (it is the mountain relief that is not placed where mountains should be....).

And the layer GMTED2010_mea_merged (it is the colour of the land) is not shown in the result.

Can you tell me what I do wrong ?

Regards,
Clément.

**Comment by tomchadwin** [comment]
Please read the guidance on reporting bugs:

https://github.com/tomchadwin/qgis2web/blob/master/README.md#reporting-bugs

If you can open separate issues for each problem, it is easier for other to help.

Some suggestions: try checking the "Match project CRS" box; look at the qgis2web log to see if any errors have been thrown.

**Comment by pticle94** [comment]
Hello Tom,

I deleted from my previous post the part concerning the files in temp folder.

Where can I find qgis2web logs ?

**Comment by tomchadwin** [comment]
> Where can I find qgis2web logs ?

In QGIS, View > Panels > Log Messages

Look for a qgis2web tab - if nothing has been logged, no such tab will exist.

**Comment by tomchadwin** [comment]
Closing after no feedback. Comment, and I can reopen.
