### ISSUE TITLE
OL visibility very broken

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#686]
It seems like the Visibility checkbox for layers in the qgis2web dialog is mismatched to the wrong layer - I don't yet know precisely how. Can anyone confirm?

**Comment by boesiii** [comment]
I confirm.  It looks like it is off by a factor of 1.  If a layers visibility is unchecked the layer above seems to take the setting.

**Comment by tomchadwin** [comment]
That's kind of what I thought, but I didn't have enough layers to be sure. I'll investigate. Thanks.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by boesiii** [comment]
It works for me.
