### ISSUE TITLE
buildNonPointJSON Error

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#69]
When I try and export a nonpoint layer I get an error.

File "C:/Users/eboesenberg/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 257, in writeLeaflet
new_obj += buildNonPointJSON("", safeLayerName)
TypeError: buildNonPointJSON() takes exactly 3 arguments (2 given)

To fix the error:
Line 257 
new_obj += buildNonPointJSON("", safeLayerName, usedFields)

**Comment by tomchadwin** [comment]
Fixed in master
