### ISSUE TITLE
Support for geometries which includes z (KeyError 1001)

### ISSUE THREAD

**Issue by axelande** [tomchadwin/qgis2web#692]
I have some geometries with z geometries, when I try to use them I gets a KeyError 
```
...\qgis2web\utils.py", line 129, in writeTmpLayer
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 1001
```

I'm not aiming for 3d support but it would be nice to be able to publish them in 2d as QGIS manage.

**Comment by boesiii** [comment]
I have added your geometry type to utils.py and have created a pull request to merge my changes.  Once the pull request is processed q2w should work with your data. <br/><br/> In the mean time to get q2w to work with your data you need to modify utils.py.  Add the following code at line 55 to utils.py<br/><br/>QgsWkbTypes.PointZ: 'Point',

**Comment by tomchadwin** [comment]
Thanks, for the fix, @boesiii!
