### ISSUE TITLE
"Unshow field"

### ISSUE THREAD

**Issue by axelande** [tomchadwin/qgis2web#694]
Among the popup fields it would be nice to have an option to exclude a field. So there are 4 options "no label", "inline label", "header label" and "exclude this field"

**Comment by boesiii** [comment]
To exclude a field, you need to set the field widget type to Hidden in the layer properties in qgis.
![field widgets](https://user-images.githubusercontent.com/2079638/47655666-e2e98480-db63-11e8-8254-51130ded1b00.PNG)

**Comment by tomchadwin** [comment]
Thanks for the reply, @boesiii!
