### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#697]
Web pages generated in last version of QGIS2WEB have this in console: 

leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y (http://s.kelv.cz/x/js/leaflet.js:5:2048)
    at Function.v.extend (http://s.kelv.cz/x/js/leaflet.js:5:14706)
    at http://s.kelv.cz/x/js/leaflet.pattern.js:6:34
    at http://s.kelv.cz/x/js/leaflet.pattern.js:6:7077

Example on: http://s.kelv.cz/x 

That map will stop working in future in Google Chrome?

**Comment by tomchadwin** [comment]
I'm afraid that's a Leaflet issue, and, since we're using the latest version of Leaflet, it should probably be raised there. qgis2web makes no explicit use of `L.Mixin.Events`. Unless this is triggered by some specific feature/map widget etc?

**Comment by kelv-cz** [comment]
Without  <script src="js/leaflet.pattern.js"></script> is console clear. Probably problem in that file.

**Comment by tomchadwin** [comment]
Confirmed that it's probably a Leaflet plugin. Maybe qgis2web isn't using the latest version of one. Ref: https://github.com/Leaflet/Leaflet/issues/5358

But which plugin? If we can find out, we can try a PR to get it fixed on their repo.

**Comment by kelv-cz** [comment]
Without this line <script src="js/leaflet.pattern.js"></script> is console clear.  Probably problem in that file. 
Example: http://s.kelv.cz/x2/

**Comment by tomchadwin** [comment]
Thanks! Turns out there's already an issue on their repo:

https://github.com/teastman/Leaflet.pattern/issues/16

But it's still open, so I guess the fix hasn't been merged in yet?

**Comment by kelv-cz** [comment]
"But it's still open, so I guess the fix hasn't been merged in yet?"

I have last QGIS (3.4.1-Madeira) and last qgis2web (3.3.1).

**Comment by tomchadwin** [comment]
I mean the fix for Leaflet.pattern has not been merged.

**Comment by tomchadwin** [comment]
I'd post on that issue on their repo to ask for an update.
