### ISSUE TITLE
The map is oscillating when opening

### ISSUE THREAD

**Issue by Polperobis** [tomchadwin/qgis2web#699]
Hello,
Is there an explanation why this map http://ekipaj.com/Atlas/ is oscillating (wobbling ?) when opening the project ? Once you have zoomed once it stops. As you can see in the Url bar, the zoom level is continuously changing.
Regards

**Comment by tomchadwin** [comment]
Various settings are fighting over how to position your map. Try one of the following:

- turn off "Restrict to extent"
- make the min zoom slightly smaller (I think - I get min and max zoom very confused...)
- slightly reposition the map on the canvas

Hope this works.

**Comment by Polperobis** [comment]
Turn off "Restrict to extent" solves the problem.
Thanks++
