### ISSUE TITLE
Leaflet preview/export: if "match project crs" is checked the base layer is not showed

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#70]
with release  0.13.5
in Settings:
if "Match project CRS" is set 
the base layer (all base layers) is not showed in LL preview/export
Works fine with OL3 preview/export

Thank
Marco

**Comment by tomchadwin** [comment]
OL3 export ignores the CRS setting (still to be implemented). Leaflet export uses it. The basemap tiles eversion will only serve their tiles if they have them in the matching CRS.
