### ISSUE TITLE
Leaflet: Missing URL from the xyz layer

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#701]
Hello,
case:
Hyperlink written within qgis-layer-properties-qgis server-description-URL field for a xyz layer openstreet monochrome:
![grafik](https://user-images.githubusercontent.com/31866672/49252034-4563c800-f423-11e8-9c04-1a50f278dda0.png)

Export as openlayers: good
![grafik](https://user-images.githubusercontent.com/31866672/49252079-67f5e100-f423-11e8-9af5-c80b416db6e2.png)

Export as leaflet (same enviroment): missing/false
![grafik](https://user-images.githubusercontent.com/31866672/49252207-ab504f80-f423-11e8-915a-4a570f4f299f.png)

For other layers the individuel HyperLink with export leaflet are correct, only xyz layers are not correct - missing the URL.
I want to export within leaflet - any ideas?

Is this a bug or do I anything wrong?

Thank you and greetings, Jürgen

QGIS 3.4.2
qgis2web 3.4
Windows 10
Firefox

**Comment by tomchadwin** [comment]
Looks like a bug to me. I'll investigate.

**Comment by jukos** [comment]
Hello,
I saw the changes. Thank you.
But I have two notes to this:
1.  To set a own description is not possible, problem above.
2. Excuse me please....but the text/link to openstreetmap is not correct.
Correct would be: 
© OpenStreetMap contributors

an the word OpenStreetMap with link to
https://www.openstreetmap.org/copyright/en

These are the rules of openstreetmap.
This correct link would be enough (for me), I would not use another solution (description....).

Thank you and greetings
