### ISSUE TITLE
Leaflet: Basemap layer visibility

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#703]
Hello,

for basemaps:
Layer visible although visible field is unchecked.
preview=export 
![grafik](https://user-images.githubusercontent.com/31866672/49509142-cb996780-f884-11e8-9cc8-0ab3a54d877e.png)

A bug?

QGIS 3.4.2
qgis2web 3.4
Windows 10
Firefox

**Comment by tomchadwin** [comment]
Confirmed as a bug - thanks. Will investigate when I can.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by tomchadwin** [comment]
Released as 3.5.0 and pushed to QGIS plugins repo.

**Comment by jukos** [comment]
Super! Thank you very much.
