### ISSUE TITLE
OpenLayers ZoomOut "-" on Chrome/Opera

### ISSUE THREAD

**Issue by dbmz** [tomchadwin/qgis2web#708]
Hello. The ZoomOut "-" with OpenLayers, only with Chrome & Opera, is not a "-" but some sort of an "a".

![openlayerszoom](https://user-images.githubusercontent.com/8203636/52393492-2012bc00-2a5b-11e9-96fe-df28bb36ee46.jpg)

Thanks

**Comment by tomchadwin** [comment]
The zoom control is part of OpenLayers itself. Do raise the issue on their repo at https://github.com/openlayers/openlayers/issues, and see what response you get.

**Comment by dbmz** [comment]
Hello Tom,
Should QGIS2Web with Open Layers display the scale line?
I see

        .ol-scale-line {
            background: none !important;
        }
        .ol-scale-line-inner {
            border: 2px solid #f8f8f8 !important;
            border-top: none !important;
            background: rgba(255, 255, 255, 0.5) !important;
            color: black !important;
        }

but the scale line doesn’t appear.
(QGIS 3.4.4; Windows 10)

Thanks from daniel
