### ISSUE TITLE
qgis2web opens in IE

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#709]
Hi,

Today I decided to try out qgis3.4.4 and the latest qgis2web 3.4.0 on windows 10.

I am probably missing a setting somewhere, but the qgis2web exports are opened automatically in IE, where Firefox is my default browser in Windows10.
Using qgis 2.18.28 and qgis2web 2.34.0 on Windows10 all exports are opened in Firefox.

Edit with new info:
I just opened a 2.18 project in 3.4, exported the webmap and it opened in Firefox. Does this suggest it is a setting qgis itself?

What setting am I missing?

**Comment by tomchadwin** [comment]
The code which opens the browser when you export is:

https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/maindialog.py#L342

It uses the Python `webbrowser` module:

https://docs.python.org/3/library/webbrowser.html

From that doc page:

> If the environment variable BROWSER exists, it is interpreted as the os.pathsep-separated list of browsers to try ahead of the platform defaults.

Do you have the environment variable `BROWSER`?

I'm afraid I'll close this one. as qgis2web is not controlling the browser used. If I'm wrong, do comment, and I can reopen.

**Comment by Jeroen-GroeneBij** [comment]
Hi Tom,

Following advice from Richard Duivenvoorde testing a line the Python Console
QDesktopServices.openUrl(QUrl('http://qgis.org'))
It opens Firefox and not IE

Does this shed any light on the issue?

**Comment by Jeroen-GroeneBij** [comment]
I have new info on this issue:

I tested the following:
Start qgis 3.4 (with q2w 3.6.0) and add a layer (not a project).
open q2w, no change to settings, export (Leaflet), the webmap opens in my default browser Firefox
close q2w
open q2w, change export folder to a different drive and folder on my desktop (not a network drive), the webmap still opens in my default browser
close q2w
open q2w, change export folder to a network drive folder and the export opens in IE.

This behaviour is unique to qgis 3.4, in qgis 2.18 this doesn't happen.
Does this help yopu in any way to pinpoint the problem?

I will share this new info also to the qgis-user-list, since this might be related to qgis3.
