### ISSUE TITLE
rule-based style visibility messed up

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#710]
Using gqis 3.4.4. and qgis2web 3.4.0 I am having troubles with rule-based styling.
Building the the exact same project in qgis 2.18.28 and qgis2web 2.34.0 works perfect.
Opening the 2.18 project within 3.4 doesn't show improvement and rules out a mistake in building the project directly in 3.4.

The preview and the export shows just one colour, in stead of all 5 colours used in the rule-based styling.
I usually build a rule based styling starting with a gradual based style, then changing it to rule-based and editing the rules (in stead of writing the entire rule and make a typo).

I have attached the qgis files and the export files. I haven't found the style file. I can save it in qgis3, but I do not know where it is saved (2.18 let's me choose where to save the .qml file)

[VVM.zip](https://github.com/tomchadwin/qgis2web/files/2850799/VVM.zip)
[qgis2web_2019_02_11-12_10_47_442719.zip](https://github.com/tomchadwin/qgis2web/files/2850800/qgis2web_2019_02_11-12_10_47_442719.zip)

**Comment by tomchadwin** [comment]
Confirmed - investigating.

**Comment by tomchadwin** [comment]
Are you able to download the master branch from here? I've made a fix which sorts out the problem for me. Let us know.

**Comment by Jeroen-GroeneBij** [comment]
This seems to work, at least for this project. I haven't tested it yet on more complex projects
I did notice two things:
1) since my qgis version still opens the export in IE: it didn't show in IE, it gave a 404 ( but I don't remember if the 'formal version' did show something in IE, I think it was a blank page. 
Opening the export in Firefox does show the map as it is intended.
2) There is a large amount of 'python warnings' in the message-log, all related to qgis2web.

**Comment by tomchadwin** [comment]
1. Discussed in #709 
2. If you can paste some of the warning here (as a new issue), I can look into them - without them, I'm in the dark

**Comment by tomchadwin** [comment]
Thanks for testing and confirming the other fix, by the way. Very much appreciated.

**Comment by tomchadwin** [comment]
Released as 3.5.0 and pushed to QGIS plugins repo.
