### ISSUE TITLE
Javascript SyntaxError when layer name contains an apostrophe (')

### ISSUE THREAD

**Issue by patrice-geo** [tomchadwin/qgis2web#711]
-**qgis2web version:**  3.4.0
  - **Browser JS console errors:** `SyntaxError: missing : after property id [Learn More] index.html:553:102 `
    - **Here is the code causing the bug**:  `L.control.layers(baseMaps,{'<img src="legend/TerritoiredactiondelaSCMB_6.png" /> Territoire d'action': layer_ [...]`

**Comment by tomchadwin** [comment]
Possibly fixed in master branch. Can you test and report back?

**Comment by tomchadwin** [comment]
Released as 3.5.0 and pushed to QGIS plugins repo.
