### ISSUE TITLE
Large GIS Files - Export Crashes

### ISSUE THREAD

**Issue by jtolar2** [tomchadwin/qgis2web#714]
Hi Tom,

I am trying to export a large dataset through qgis2web to the default browser (Internet Explorer); screenshoted below for size reference:

![image](https://user-images.githubusercontent.com/46802221/52671511-64c4b880-2f6f-11e9-9bfa-40666280a5f1.png)

![image](https://user-images.githubusercontent.com/46802221/52672548-444a2d80-2f72-11e9-93f8-31019e2fa4bd.png)

No qgis2web specific error arises in the Log Messages Panel. The closest thing I can get is if through qgis2web if I press the 'Update preview' button, the below error message is generated:

![image](https://user-images.githubusercontent.com/46802221/52671425-2cbd7580-2f6f-11e9-99cb-b763c26e54cb.png)

Are you aware of any techniques I can employ (e.g. simplifying symbologies) to support qgis2web successfully exporting large files?

I have zipped / attached all files for reference (approx. 167MB):
https://www.dropbox.com/s/3uxk44k7zruhcbu/Large%20GIS%20File.zip?dl=0

**Comment by tomchadwin** [comment]
I'm afraid browsers will simply struggle with this amount of data. Your best alternative is to try to get the data hosted and presented via WFS. To be honest, though, qgis2web might not handle such big files very well. Sorry not to have better news.

**Comment by jukos** [comment]
Hello jtolar2,
you could try to dissolve the layer.

I have testet only one layer with 90,000 polygones (3 columnes). After dissolve I have 133 objects.
**Vector ‣ Geoprocessing Tools - dissolve**
Also could help: qgis2web export precision: ....6...(for example)
For qgis2web leaflet the export and the site-speed is ok. 
My example: OSM data via overpass turbo: Southeast of australia, search-word  wizard: landuse=*

Good luck!

**Comment by tomchadwin** [comment]
I'll close this, as it's more a data management issue.
