### ISSUE TITLE
Unwanted labels

### ISSUE THREAD

**Issue by glangberg2** [tomchadwin/qgis2web#715]
I am using the latest release of qgis2web with Qgis 3.4.4. I have 2 layers each containing multiple polygons  set to "no labels" in Qgis, but webmaps have labels. When I set the edit widget for the field which appears as a label to 'hidden', the word 'undefined' appears on my web map.

**Comment by boesiii** [comment]
Are you using the latest version?  Can you include a screenshot of your q2w settings?  Can you include a screenshot of your output map?  Can you include a copy of your data and qgis project file?

**Comment by tomchadwin** [comment]
I wonder if it is failing to observe the state of the labelling drop-down ("No labels"/"Single labels"), and is using whatever is in the "Label with" field regardless. Do you have something in "Label with"? If so, can you remove it and retest?

**Comment by Jeroen-GroeneBij** [comment]
I had a similar experience today and was about to open an issue when I saw this one.
Using an existing project, which had no labels and g2w showed no labels, I added labels to a layer, opened q2w, noticed in the preview the labels and decided I did not want to see labels. So I turned the label setting in the qgis layer back to 'no labels',  but q2w kept showing labels. Even after closing and restarting qgis, the project now always shows labels in q2w, but not in qgis. Label setting is still 'no labels'.

I am not sure whether this is a qgis bug or a q2w bug.
Here is the qgis project:
[vvm_leden.zip](https://github.com/tomchadwin/qgis2web/files/2881831/vvm_leden.zip)
[qgis2web_2019_02_19-21_07_08_191883.zip](https://github.com/tomchadwin/qgis2web/files/2881832/qgis2web_2019_02_19-21_07_08_191883.zip)

**Comment by tomchadwin** [comment]
Definitely seems like a qgis2web bug. I'll try to recreate and investigate.

**Comment by tomchadwin** [comment]
Confirmed (Leaflet and OpenLayers). Investigating.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by Jeroen-GroeneBij** [comment]
Fix for leaflet works both on existing case and new case.

Fix for OL works both on existing case and new case.

**Comment by tomchadwin** [comment]
Brilliant: thanks very much for testing and letting us know. I'll do release fairly soon  -just trying to make some progress on some of the issues exposed in #706

**Comment by Jeroen-GroeneBij** [comment]
for the record, I tested only in qgis3

**Comment by tomchadwin** [comment]
That's all that's supported now:

https://twitter.com/tomchadwin/status/1099994809824104449
