### ISSUE TITLE
request: use of multiple styling on layer

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#719]
Hi Tom,

Recently I created a map consisting of one layer with 40 attributes. All 40 attributes use the same rule based styling.  I now learned to use the layer styling panel to easily switch between the styles and so have a quick view of the results. Think of a survey and each question is a different attribute. Each municipality answers all questions and I can now easily see the answers in a map.

However, building a webmap I need 40 layers, each layer with it's own style.
Is there any way for qgis2web to make use of the multistyling possibilities of qgis?
Or is there any trick to show and choose between the styling of each attribute using just one single layer in the export?

Greetings,
Jeroen

**Comment by tomchadwin** [comment]
I'm afraid this is probably a how-to type question, and hence this is not the best place to ask it. This is for bug and feature requests. I recommend asking on https://gis.stackexchange.com/. I'll close this issue, not least because I don't have an answer.
