### ISSUE TITLE
Build against Travis CI

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#72]
I would really like to get qgis2web's GH repo hooked into Travis, to catch stupid errors I make when committing/releasing. I am struggling to understand what is involved. I think I need to do the following:

- [x] enable Travis webhook in repo
- [x] add .travis.yml to repo
- [x] edit .travis.yml to set up test environment (install QGIS and dependencies, install test data, run tests)
- [x] write tests (perhaps in nose)

I don't want a lot of tests at the moment. What I need initially are:

- [x] load test data
- [x] load plugin
- [x] run plugin
- [x] qgis2web export to OL3
- [x] qgis2web export to Leaflet

Can anyone help with getting this set up? It's all new to me.

**Comment by tomchadwin** [comment]
OK, it looks like @timlinux has done quite a lot of this work automatically as part of the Plugin Builder. How splendid. Still looking into it - how to call it as part of the Travis process.

**Comment by boesiii** [comment]
The page below was easy to follow

https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by tomchadwin** [comment]
Thanks, @boesiii. I think I'm getting somewhere...

**Comment by tomchadwin** [comment]
With lots of help from @akbargumbira, this is now a lot further on. The plugin is loading in the test. I now need to call each export routine by simulating clicking the Preview OL3 and Preview Leaflet buttons. I've had a go in the non-master branch, but even with a deliberate error in leafletWriter.py, it passes Travis. That means I am not calling the click button code correctly. Can anyone help?

**Comment by timlinux** [comment]
@tomchadwin which one fails? This?:

https://github.com/tomchadwin/qgis2web/blob/master/test/test_qgis2web_dialog.py#L51

Try looking also at the QTest framework for interactively testing UI elements....

**Comment by tomchadwin** [comment]
Rather amended in another branch:

https://github.com/tomchadwin/qgis2web/blob/LayerTree-API/test/test_qgis2web_dialog.py#L42
https://github.com/tomchadwin/qgis2web/blob/LayerTree-API/test/test_qgis2web_dialog.py#L49

As you can see, this is very simple testing - I want to trap Python errors, rather than test for specific results. I want to "click" both the "Preview OL3" button and the "Preview Leaflet" one. I've dropped some junk code into the function called by "Preview Leaflet", so the result I want from Travis at the mo is for test_OL3() to pass, and test_Leaflet() to fail. At the moment, both pass, so the buttons can't be being clicked correctly.

**Comment by akbargumbira** [comment]
I think your tests are fine. I don't get it why clicking Preview OL3 and Leaflet should throw python error as if I click it with empty project, those actions are fine. 

To be more comprehensive, you should also load a qgs project before running the dialog so that the MainDialog's got some layers and groups to play with.

**Comment by tomchadwin** [comment]
I'm talking about the LayerTree-API branch, not master. That's where I merged in the test code, and that's where I added the deliberate fail in the Leaflet export routine:

https://github.com/tomchadwin/qgis2web/blob/LayerTree-API/leafletWriter.py#L42

So it can't be being called, I think. Any ideas?

**Comment by tomchadwin** [comment]
Yes, I also plan to add layers to work with - the plugin handles a matrix of different layer gemoetries (point, line, poly), types (JSON, WMS, WFS, raster), and styles (single, categorized, graduated), so the chance for unit tests for many of these combinations is perfect. But I need to get the exports to call before looking at how to load data.

**Comment by tomchadwin** [comment]
I can't get the buttons to click in the test - no idea why - so I've switched to calling the connected functions instead. That's working to a certain extent, but I've got the old missing iface issue in those functions when run as a test. I'll see if I can make sense of how @akbargumbira has injected the dummy IFACE in all the work he's already done here, to try to make the functions run correctly both in production and test.

**Comment by akbargumbira** [comment]
Have you tried debugging it? My PR for that was simply having iface in the
dialog as parameter in the constructor and have it as class field that can
be used by other stuffs in that class. This iface is provided by plugin
context, so for the test, I pass the mock iface to that.

On Thu, Jul 2, 2015 at 6:47 PM, Tom Chadwin <notifications@github.com>
wrote:

> I can't get the buttons to click in the test - no idea why - so I've
> switched to calling the connected functions instead. That's working to a
> certain extent, but I've got the old missing iface issue in those functions
> when run as a test. I'll see if I can make sense of how @akbargumbira
> <https://github.com/akbargumbira> has injected the dummy IFACE in all the
> work he's already done here, to try to make the functions run correctly
> both in production and test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchadwin/qgis2web/issues/72#issuecomment-117995950>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by tomchadwin** [comment]
I think I've managed to sort it all out in the LayerTree-API branch - the export routines are being called, and are now passing, after I passed iface into them. Travis passes, so it's looking good. What do you think?

**Comment by akbargumbira** [comment]
I just checked your changes. Normally one would check the expected result, not just running the method itself. For example in your case something like:
```
    def test_OL3(self):
        """Export to OL3 (test_qgis2web_dialog.test_OL3)."""
        self.dialog.previewOL3()
        # Check the expected result
        self.preview is set to the correct URL
        self.labelPreview is set to the right text
```

And also, it would be better to have tests for OL and Leaflet Writer itself in which the core functionality resides there

**Comment by tomchadwin** [comment]
The test as it currently stands is simply there to catch Python errors - I've made releases to the QGIS repo in the past which have had such errors, so this is to prevent that happening again.

The next stage is to load a project, as you suggested, and test against different kinds of actual data. At the moment, I am happy simply to test for Python errors. To do more than that would involve probably testing the output (HTML, CSS, JS) against correct output templates, which would take a huge amount of work to set up. At the moment, I don't think it's worth it.

Thanks again for all the help - still no idea why the QTest mouse click approach did not fire the export functions, but I think I'm happy with where we are now.

**Comment by akbargumbira** [comment]
No worries, I am happy to help. @timlinux once told me that I need to remember him whispering 'Akbar, make unittest, make unittest' to me whenever I feel lazy to make unittest :)

But really true that unittests make it easier for detecting if something is wrong easily. From detecting inadvertently what's wrong in QGIS itself (when the new one released), bugs in PyQT, and all other small bugs that won't be easily tracked without unittests.

I also noticed that some of the modules in your plugin are quite messy (I don't mean to offend you). For example leafletWriter, it's got one killer function ```writeLeaflet``` consists of 600 LOC. I am sure that one day, it's gonna slap you when it's got some bugs in it :) So, designing the code itself (at least to be nicely read) is very important for detecting errors.

**Comment by tomchadwin** [comment]
I am totally not offended by that at all. writeLeafet came from qgis2leaf, which was @riccardoklinger's first ever attempt at Python. My contributions were *my* first ever attempt at Python. It used to be much, much worse than it is now, I can tell you:

https://github.com/Geolicious/qgis2leaf/blob/f062f49a808307c49c01b524993247d1e9425d86/qgis2leaf_exec.py

So, it's much better than it was, but it needs a lot more work, not just to break up that massive function, but also to deduplicate - see https://github.com/tomchadwin/qgis2web/blob/master/leafletScriptStrings.py for severe duplication of functionality. Again, it's much better than it was, but there is lots and lots more to do.

More fundamentally, eventually the core export routine should be shared for OL3 and Leaflet, rather than two totally separate functions. writeLeaflet and its associated functions need to be in much tidier shape before than can happen, though.

**Comment by tomchadwin** [comment]
I've expanded the testing, and most run fine and pass. However, two give this error:

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

What causes this error?

**Comment by tomchadwin** [comment]
Baffled by the above namespace issue. It appears to have disappeared. What's more, it appears to have occurred in one build, but not in an identical one. Anyway, it's not occurring now.

**Comment by tomchadwin** [comment]
The error is intermittent, randomly affecting any unit test. I'm therefore going to ignore it unless anyone can advise me otherwise and explain it.

I therefore next want to know how to load a project in the tests so that I can test against data. Any ideas?

**Comment by tomchadwin** [comment]
I think I've now managed to write tests to load a project of test data, and then export it to Leaflet and OL3. I'll open a new ticket to build a proper test suite.
