### ISSUE TITLE
Openstreetmap not showing using EPSG:28992

### ISSUE THREAD

**Issue by lammertshans** [tomchadwin/qgis2web#721]
Hi 

I am trying to display some points on a map in The Netherlands. I notice that none of the background maps are being displayed. If i look at the file layers.js in the qgis2web_ directory there can't be find RD new Amersfoort EPSG:28992 ? How can i make it to work?

![screenshot layers js](https://user-images.githubusercontent.com/48010310/53398169-42885d00-39a9-11e9-9a13-438f4858ae3c.jpg)
![screenshot datapoints js](https://user-images.githubusercontent.com/48010310/53398170-42885d00-39a9-11e9-89e6-fb938d7802e0.JPG)

**Comment by tomchadwin** [comment]
Please give the details asked for when you opened this issue? Without them, it's difficult to help. Specifically:

- qgis2web version
- how are you adding OpenStreetMap?
- your qgis2web settings (specifically whether you have checked "Match project CRS"

**Comment by lammertshans** [comment]
Hi Tom,

- I use Qgis version 3.4.4 with 0.1.0 of web2qgis
- I'm add openstreetmap using the openlayer plugin version 2.0.0, the add map button in the overview
- When in add the map it commes in as EPSG:3857 and when i change that to our dutch standard EPSG:28992 the map disappears. 

(?)

**Comment by tomchadwin** [comment]
The OpenLayers plugin for QGIS is not supported. It is strongly recommended that you switch to QuickMapServices. Try that, and see whether that allows your OSM layer to be exported.
