### ISSUE TITLE
Leaflet export getfeatureinfo Unexpected token

### ISSUE THREAD

**Issue by vfonsecaz** [tomchadwin/qgis2web#723]
Plugin version: 3.5.0
Qqis version: 3.6.0 (ubuntu)

Having 3 wms layers to export and having one of them without the "Enable GeaFeatureInfo" option enabled throws `Uncaught SyntaxError: Unexpected token ,`

`var layer_limite_concelho_1 = L.WMS.layer("server", "layer", {
            format: 'image/png',
            uppercase: true,
            transparent: true,
            continuousWorld : true,
            tiled: true,
            info_format: 'text/html',
            opacity: 1,
            **identify: false,,**
            attribution: '',
        });`

So there's an extra comma in the **identify** layer attribute

If i enable GetFeatureInfo for all three layers there's no error.

Workaround:

Edit leafletScriptStrings.py

line: 336
replace 
`            identify: false,"""`
with 
`            identify: false"""`

**Comment by tomchadwin** [comment]
Confirmed: if multiple WMSes, fails unless all have GetFeatureInfo. Investigating.

**Comment by vfonsecaz** [comment]
> Confirmed: if multiple WMSes, fails unless all have GetFeatureInfo. Investigating.

exactly. looks like if the first wms layer added to the map has identify:false, all the other layers won't have GetFeatureInfo working

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.
