### ISSUE TITLE
unexpected result updating preview on new map

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#725]
Hi Tom,

Testing the fix for #715 I noticed some unexpected behaviour and a little interference issue between qgis3 and qgis2web.

Try the following in qgis3 on windows10:
Open a map, open qgis2web so the preview shows. Do not close q2w.
Then, start a new qgis project and discard the former one, open another map and click the qgis2web button to open q2w (which is al ready open) / or go to the windows pane and click preview.

First thing I noticed:
Now qgis3 gives a warning about the map in the preview of q2w not being available any more.
Which is sort of expected, but it would be nice though when q2w just updates the preview to the new project.
Closing q2w and starting q2w again shows the preview of the new project.

Second thing I noticed:
After closing and starting q2w, qgis3 doesn't seem to acknowledge everything is okay again. From the moment the warning first came up, my mouse pointer changes to a blue spinning circle, like qgis3 is waiting for something.
It doesn't go away after closing and starting q2w again.
I have to close qgis3 for this to resolve...

**Comment by tomchadwin** [comment]
Your second issue I know of. The change from cursor to spinner is done manually in qgis2web code, and reverted manually in code when the export completes. If the script throws an error, the spinner remains in place. You can try to restore it by opening the QGIS Python console, and typing:

```
QApplication.restoreOverrideCursor()
```

The other issue I wasn't aware of. The dialog was originally blocking, so you couldn't return to the main QGIS window until the qgis2web dialog was closed. I changed this based on @NathanW2's influence (blocking dialogs = bad). Perhaps this demonstrates that this might not have been the best idea.

**Comment by Jeroen-GroeneBij** [comment]
well, I often 'forget' to close the q2w window, so if you mean closing the q2w window when you say 'until the qgis2web dialog was closed' then I have to go with the current setting. Not being able to do anything in qgis3 before closing q2w would probably give me a lot of frustration :)

A solution might be that when starting a new project in qgis and discarding the current one, it automatically closes the qgis2web window / dialog,
This would then be similar to an open attribute table, that closes automatically when starting a new project and discarding the other one.
This might be an easier solution then having q2w automatically update toe the new project?

**Comment by tomchadwin** [comment]
It's a good suggestion. I'll see if there is a QGIS project close signal I can connect to.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by Jeroen-GroeneBij** [comment]
The fix does seem to work.
Whenever I start a new project, the q2w window is closed.

During testing I did notice a related thing: adding new layers to a project will not show up in the q2w window when using Update preview. This applies both to the current version and the fix.

new canvas, add a layer, open q2w, add a new layer, press Update preview - it doesn't show the new layer(s). Never noticed it and bothered before. Is it intended behaviour? Or should Update preview also show new layers?
Any changes made to existing layers (styling, attribute data, etc.) do show up on Update preview.

Should I open a new Issue?

**Comment by tomchadwin** [comment]
Yeah, that's how it has always been. As I say, it did used to be a blocking dialog, so this functionality was never required. Update preview simply regenerates the map according to the current plugin settings. I guess one way to do things would be to add another button "Update layers", or some such.

**Comment by Jeroen-GroeneBij** [comment]
I am used to closing the dialog and running it again, a new button would just remove one click from this process. So I think it doesn't add much value.

I think the fix really does add value. Whether this is a dialog or a panel, a plugin or a standard feature from qgis, whenever you start a new project, all windows/panels should be closed or cleared.
