### ISSUE TITLE
Leaflet export not showing borders for points

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#73]
I exported a point shapefile to leaflet and the borders for the points are not being displayed.  In the leaflet html the weight property is set to 0.0, so the border width is not being parsed correctly.

**Comment by tomchadwin** [comment]
Simple, categorized, or graduated?

**Comment by boesiii** [comment]
simple

**Comment by boesiii** [comment]
I am not sure about the other but i will test

**Comment by tomchadwin** [comment]
Just tested simple, and I have a border. Can you screenshot your style settings?

**Comment by boesiii** [comment]
![pointstyle](https://cloud.githubusercontent.com/assets/2079638/8336296/79d27cd8-1a71-11e5-951e-a9862d744e4d.PNG)

**Comment by tomchadwin** [comment]
I have those settings, and I have a border. However, I also have weight: 0. I wonder if this is a difference between browsers. I'm only testing in the GUI preview. How are you viewing?

Also, I would argue that weight: 0 is correct given that Outline width = 0. Seems odd that QGIS renders the border. Try changing Outline width.

**Comment by boesiii** [comment]
The GUI preview is different then the browser.

I changed the outline width in Qgis and I can start to see a border in Leaflet, but the Qgis border weight  does not equal Leaflet border weight.  For some reason the leaflet border weight never goes past 1.0

**Comment by tomchadwin** [comment]
That sounds like a calculation error in how the border is determined by the plugin. I'll look at how it's done and report back.

By the way, the whole line weight is a little inaccurate to my mind, as the QGIS units are mm (designed for print), not pixels (designed for web). A multiplier to get something plausible is probably needed (and was being used at one stage, I seem to remember), so let's see how far we can get.

I'm ignoring the QGIS option to specify weight in map units. No idea how to implement that in Leaflet.

**Comment by tomchadwin** [comment]
There was no multiplier. qgis2leaf had *5. I've toned that down after a visual check to *4, and added that to master. Can you have a look and see if that works?

WARNING - there might be some instances of multiplying strings, not numbers, resulting in a blank output map and nonsense in the output code:

```javascript
weight: 10.1.01.01.0
```

Let me know if you see one of these, and if so what symbol renderer (simple/categorized/graduated), and what geometry type (point/line/poly).

**Comment by boesiii** [comment]
It looks like you changed the wrong setting because something happened to the line style weights, I now have a weight of 5.05.05.05.0 for a line style and not a point style

**Comment by boesiii** [comment]
Sorry didn't read your entire post.

My previous comment is about a simple line style

**Comment by boesiii** [comment]
The point style looks good but I have to remember to change my line weight in Qgis

**Comment by boesiii** [comment]
For categorized lines there are two default clauses which cause an html error

**Comment by boesiii** [comment]
Graduated lines look fine

**Comment by tomchadwin** [comment]
For two defaults, check you don't have two categories with no value.

**Comment by boesiii** [comment]
I categorized values based on an integer field and for some reason Qgis added a blank value even though there was no value after I removed the blank value, it appears correct.

**Comment by tomchadwin** [comment]
Yes, that happens to me frequently. It's how I discovered the two defaults issue you described. Don't know if it's a QGIS bug, or if it's meaningful behaviour. If the latter, I need to understand it in order to handle it. If the former, I guess we could just take the first category with no value as the default, and ignore all others. 

Will get rid of the 1.01.01.01.0 thing when I can. Have to convert values to floats before multiplying them by 4. Probably won't be till Friday, though.

**Comment by tomchadwin** [comment]
@boesiii, is this issue now fixed?

**Comment by boesiii** [comment]
Yes

**Comment by tomchadwin** [comment]
Thanks very much.
