### ISSUE TITLE
popup doesn't show information of all covering features

### ISSUE THREAD

**Issue by reginaldc** [tomchadwin/qgis2web#731]
Hi devs,

I have a layer in which two features are drawn with the same geometry.
I produced a map with open layers (using the latest version of qgis2web 3.6.0).
When I click on the mapfeatures the attributes of only one feature are shown in the popup.

Regards,

**Comment by tomchadwin** [comment]
Can you share your data?

**Comment by reginaldc** [comment]
Hi Tom,

Yes, I have attached the project in a zip file.
The parcel with multiple features is the green one next to house number 86.

Regards,
[http://doc.ingelmunster.be@doc.ingelmunster.be/gisprojecten/monument.zip](url)

**Comment by reginaldc** [comment]
If I reply on your email with the zipfile attached a get a notification that the attachment is too big (7 Mb).

If I have a valid mail adress of you  I can copy the files with wetransfer.

**Comment by tomchadwin** [comment]
Can you drag and drop the zip onto a reply on this issue?

**Comment by reginaldc** [comment]
No this is when I get the notification that the zip file is to large (7 Mb) while the server only accepts mails up to 4 Mb.


Reginald Carlier
Deskundige GIS
Gemeente Ingelmunster, Oostrozebekestraat 4, 8770 Ingelmunster
T+32 51 33 74 39www.ingelmunster.be
Schrijf je in op onze nieuwsbrief!
Raadpleeg onze disclaimer 
Van: Tom Chadwin <notifications@github.com>
Verzonden: woensdag 27 maart 2019 13:54
Aan: tomchadwin/qgis2web <qgis2web@noreply.github.com>
CC: Reginald Carlier <Reginald.Carlier@ingelmunster.be>; Author <author@noreply.github.com>
Onderwerp: Re: [tomchadwin/qgis2web] popup doesn't show information of all covering features (#731)


Can you drag and drop the zip onto a reply on this issue?

**Comment by reginaldc** [comment]
I notice that in the layers folder there is a layer which has a size of 8 MB unzipped.
I could remove that file I guess. I don't know if the other layers will render then?

**Comment by tomchadwin** [comment]
No, not via email. View this issue in a browser, and add a reply in the textbox - you can drag and drop a file there. Apparently the limit is 25MB:

https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by reginaldc** [comment]
[monument.zip](https://github.com/tomchadwin/qgis2web/files/3016645/monument.zip)

**Comment by tomchadwin** [comment]
Thanks for the upload. I've recreated the problem. It seems like the popup was limited to a single feature during @olakov's development of eg OpenLayers clustering. I'll try removing the limit, but it might well have unintended side-effects. It must have been introduced for a reason. Let's see.

**Comment by reginaldc** [comment]
Hi Tom,

I downloaded master and unzipped it. I renamed the folder to qgis2web. Then I copied the folder to my profile folder : > Roaming > QGIS > QGIS3 > profiles > april 
I started qgis with the QGIS april profile and exported my project but all the styling is gone, no aerial foto, no buildings, no monument features show up ???
[qgis2web_2019_03_29-13_21_47_548637.zip](https://github.com/tomchadwin/qgis2web/files/3022608/qgis2web_2019_03_29-13_21_47_548637.zip)

**Comment by tomchadwin** [comment]
I don't suppose you have your project and layer files to upload here?

**Comment by reginaldc** [comment]
Hi Tom,
I used QPackage to make a folder of the project and the associated files. Then I zipped it.
[qgis2web monument.zip](https://github.com/tomchadwin/qgis2web/files/3165820/qgis2web.monument.zip)
Regards,

**Comment by reginaldc** [comment]
Thanks a lot Tom!

I see that you solved the problem.

Great work

**Comment by tomchadwin** [comment]
Ah, great. So I can close this issue?

**Comment by reginaldc** [comment]
Yes, I didn't test it with leaflet so far but if I have time I will test it.

Thanks a lot for this nice plugin.

**Comment by riccardoklinger** [comment]
@reginaldc is this solved now?

**Comment by reginaldc** [comment]
Yes works fine now.
I tested it and now all the features are shown.

thanks a lot for fixing it
