### ISSUE TITLE
Problem with Openlayers export on QGIS 3.4

### ISSUE THREAD

**Issue by geraldo** [tomchadwin/qgis2web#733]
There is one layer which gives the a Javascript error on Openlayers export. The layer style function doesn't get written and layer_style.js file looks like that:

```
var size = 0;
var placement = 'point';

var style_AdministracionsCompetents_4 = ;
```

The layer uses an SVG marker, but other layers with SVG markers just work fine.

**Comment by tomchadwin** [comment]
Can you look in the log: View > Panels > Log Messages > qgis2web?

**Comment by geraldo** [comment]
Sorry, just saw that there is a new version of qgis2web, the error message just posted was for qgis2web 3.5.0

After updating to qgis2web 3.6.0 (also on QGIS 3.4.4) the same layer get's exportet, but doesn't appear on the map. The layer style function looks like that:

```
var size = 0;
var placement = 'point';

var style_AdministracionsCompetents_4 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = ""
    var labelText = "";
    size = 0;
    var labelFont = "10px, sans-serif";
    var labelFill = "rgba(0, 0, 0, 1)";
    var bufferColor = "";
    var bufferWidth = 0;
    var textAlign = "left";
    var offsetX = 8;
    var offsetY = 3;
    var placement = 'point';
    if ("" !== null) {
        labelText = String("");
    }
    var style = [ new ol.style.Style({
        image: new ol.style.Icon({
                  imgSize: [5, 5],
                  scale: 3.0,
                  anchor: [7, 7],
                  anchorXUnits: "pixels",
                  anchorYUnits: "pixels",
                  rotation: 0.0,
                  src: "styles/town-hall.svg"
            }),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })];

    return style;
};
```

**Comment by geraldo** [comment]
> Can you look in the log: View > Panels > Log Messages > qgis2web?

There aren't any specific errors for qgis2web in tabs General, Plugins nor Python warning. Should there be a own tab for qgis2web logs?

**Comment by tomchadwin** [comment]
> Also in the legend it is shown correctly.

The legend icons are converted to PNGs, which is why they might work when the map markers don't.

> Should there be a own tab for qgis2web logs?

Yes, but only if anything is explicitly logged to it - looks like nothing has been.

Two possibilities occur:

- I don't suppose your layer name/alias has an apostrophe in it?
- Something about the sizing, as you say

**Comment by geraldo** [comment]
>     * I don't suppose your layer name/alias has an apostrophe in it?
No apostrophe and other strange characters in it.

>     * Something about the sizing, as you say
Maybe related to #732?

After restarting QGIS actually the marker shows up also on Openlayers, but another strange thing happens: Only some of the markers on this layer show up, the rest is hidden. Zooming in makers them appear. It's not a cluster as clicking on a marker opens the popup.

**Comment by tomchadwin** [comment]
> Only some of the markers on this layer show up, the rest is hidden. Zooming in makers them appear.

That is the default behaviour, in order to avoid overlapping labels.
