### ISSUE TITLE
How to display related data in a pop-up?

### ISSUE THREAD

**Issue by sindile** [tomchadwin/qgis2web#734]
I am trying to display data in a related table in a pop-up, but this seems not to work even though I am able to see the records using the identify tool in QGIS.
Defining a relation
![image](https://user-images.githubusercontent.com/1027916/54862030-cd583f80-4d3c-11e9-9752-4729fc22decf.png)
Output of using identify tool in QGIS
![image](https://user-images.githubusercontent.com/1027916/54862038-e82ab400-4d3c-11e9-9012-a71168a69a71.png)

In essence I would like to see the records from regions and airport_relation in a pop-up.

Is it because this feature is not supported out of the box by qgis2web, if so is there perhaps a work around that one can use.

**Comment by sindile** [comment]
I have come up with this solution, create a field owner in the regions table and populate it with
relation_aggregate('airport_relation','concatenate', title("owner_name"), concatenator:=', ')
I will still leave this ticket open just in case there is a better solution.

**Comment by tomchadwin** [comment]
> Is it because this feature is not supported out of the box by qgis2web

I'm afraid so, yes. Thanks for reporting back with your workaraound.
