### ISSUE TITLE
SVG Shape Markers plugin needs updating

### ISSUE THREAD

**Issue by robintw** [tomchadwin/qgis2web#735]
**Summay:** The version of the Leaflet SVG Shape Markers plugin which is included with qgis2web is outdated, and has a bug with display of square or diamond symbols in Firefox. This is fixed in the latest release, which should be incorporated into qgis2web.

I am using v3.6 of qgis2web, but I can see that the .js file for the plugin in the qgis2web repo (https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/js/leaflet-svg-shape-markers.min.js) was updated on the 23rd Dec 2017, and the fix was committed to the Leaflet SVG Shape Markers repo on the 15th June 2018 (https://github.com/rowanwins/Leaflet.SvgShapeMarkers/commit/b4d2aeedda05638baeadf20d0cbff29d22df80b1)

The bug in Firefox with the square or diamond markers is that they simply do not appear - with no errors in the JS console. Other symbols (circle, triangle, x etc) all work fine.

I don't think this issue really needs data providing or screenshots of qgis2web settings, as it should be a pretty simple fix, but let me know if you need anything else.

**Comment by tomchadwin** [comment]
Thanks! I'll test and see. Keeping up with plugin updates is something I struggle with.

**Comment by robintw** [comment]
Just wanted to say thanks @tomchadwin - a fix in 6 minutes is pretty impressive, regardless how simple the fix is! As an open-source maintainer myself I know how infrequently you get praise in GH issues, and how often they're just complaints about things not working. So...thank you very much for fixing this so quickly, and thank you for qgis2web: it's been great for some projects I'm working on at the moment, and seeing the code that qgis2web creates is helping my knowledge of leaflet. Thanks!

**Comment by tomchadwin** [comment]
Thanks very much for the kind words. If it were a harder fix, I don't think you'd have got the same turnaround...
