### ISSUE TITLE
preserve lines style for layer with roads

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#736]
I don't know if it is an issue or me doing it wrong. I have a vector layer of roads whit rules styled that show right in Qgis. Once made the file in Qgis2Web I loose the size, the style is there but the lines when zooming in become very thin. Are hours looking for a solution, can you help me?

**Comment by tomchadwin** [comment]
It's difficult to know without seeing the problem. Can you upload a simple project and layer so others can recreate the issue?

**Comment by tomchadwin** [comment]
Closing without feedback. Comment and I can reopen.
