### ISSUE TITLE
The measure control fails to remove all the added overlays

### ISSUE THREAD

**Issue by agiudiceandrea** [tomchadwin/qgis2web#737]
It seems that after having stopped using the measure control, some overlays remain unremoved but invisible.

In a test map created with qgi2web, before using the measure control, `map.getOverlays().getLength()` reports **1**.
```
0 | element: div#popup.ol-popup
```
Starting use the measure control, `map.getOverlays().getLength()` reports **3**:
```
0 | element: div#popup.ol-popup
1 | element: div.tooltip.hidden
2 | element: div.tooltip.tooltip-measure | innerHTML: ""
```

During the draw of the first measure, `map.getOverlays().getLength()` reports **3**:
```
0 | element: div#popup.ol-popup
1 | element: div.tooltip.hidden
2 | element: div.tooltip.tooltip-measure | innerHTML: "0,13 km"
```

After ending draw the first measure, `map.getOverlays().getLength()` reports **4**:
```
0 | element: div#popup.ol-popup
1 | element: div.tooltip.hidden
2 | element: div.tooltip.tooltip-static | innerHTML: "0,13 km"
3 | element: div.tooltip.tooltip-measure | innerHTML: ""
```

After I click again on the measure control button to stop using it, then `map.getOverlays().getLength()` reports **2**:
```
0 | element: div#popup.ol-popup
1 | element: div.tooltip.tooltip-static | innerHTML: "0,13 km"
```
Anyway the remnant measure tooltip is not visible (thanks to $( ".tooltip" ).remove();)

As a probably inelegant workaround, I've managed to remove the unremoved overlays, using a variable that stores the number of overlays in the map at the start of the measure control (it seems is always 1, for popup overlay), and then remove (with splice) them at the end.

```javascript
var measuring = false;
var overlaysIndex; // stores the number of overlays in the map before the measure control starts
measureControl = function(opt_options) {

[...]

  var this_ = this;
  var handleMeasure = function(e) {
    if (!measuring) {
        this_.getMap().addInteraction(draw);
        overlaysindex = map.getOverlays().getLength();
        createHelpTooltip();
        createMeasureTooltip();
        measuring = true;
    } else {
        this_.getMap().removeInteraction(draw);
        measuring = false;
        this_.getMap().removeOverlay(helpTooltip);
        this_.getMap().removeOverlay(measureTooltip);

        // removes the overlays added by the measure control
        this_.getMap().getOverlays().getArray().slice(overlaysIndex).forEach(function(overlay) {
          this_.getMap().removeOverlay(overlay);
        });

        $( ".tooltip" ).remove();
        measureLayer.getSource().clear();
    }
  };
```

**Comment by tomchadwin** [comment]
Apologies for the basic question, but is this likely to be a real problem? It's a bug, of course, but possibly not one which is likely to have a serious effect (memory leakage likely to be negligible).

The measure code was lifted from the OL examples page (from memory): https://openlayers.org/en/latest/examples/measure.html. I wonder if that displays the same issue?

**Comment by tomchadwin** [comment]
Closing without feedback. Comment and I can reopen.

**Comment by agiudiceandrea** [comment]
You are right, it's only a little bug and it also affects the OL example page.

**Comment by andreaordonselli** [comment]
I tried to use your method @agiudiceandrea but it doesn't work for me.
I have another similar problem and I opened a post here #998 , can you help me?
Thanks.
