### ISSUE TITLE
Update the data on the map (Version 2.18 of QGIS)

### ISSUE THREAD

**Issue by ossantr** [tomchadwin/qgis2web#741]
Hi,

I'm currently working with the attached qgis2web module of the 2.18 version of QGIS. i'm trying to find a way of updating the data which show on the map (after the export).

The idea is simply to dynamically limit the number of points that appear on the map based on certain properties. I succed to do it on a previous version on changing the variable which contains the json data (using AJAX) and then deleting and recreating the map. But it doesn't seems to work on this version. I can dynamically modify as I want the data (still using AJAX) but when I delete and recreate the map the change doesn't appear, the full map is reacreate with all the point.

In your opinion is it a good way to do ? Or do you think there is a more simple way to implement it?

I hope that I succeed to be clear! I can show some code if it's useful. Thanks a lot for your help and suggestions :)

**Comment by tomchadwin** [comment]
I'm afraid this is probably the wrong place to ask this question - this tracker is for bug reports and feature requests. Additionally, qgis2web v2 is now unsupported. I would suggest that you ask your question at https://gis.stackexchange.com/, though I imagine the users there would want more specific details of your code, and of how it "doesn't seem to work".
