### ISSUE TITLE
Time Extension/Funcionality 

### ISSUE THREAD

**Issue by moni1865** [tomchadwin/qgis2web#742]
Sorry, I know this question has been asked and answered before but I am new and confused. The time functionality is not working for me. From previous posts, I gather that I am supposed to export map and then add the time. I did that but when I opened the index-time file nothing was there but two empty boxes from the time slider.Also, my data field format is YYYY but I would prefer YYYY-MM-DD. Please help

**Comment by moni1865** [comment]
I figured "export the map, then go back and time." My error was that I was not opening the index-time html file. I also changed my data field format to YYYY. But when I opened the index-time file nothing was there but two empty boxes from the time slider. What am I doing wrong?

**Comment by boesiii** [comment]
This is probably the wrong place to ask this question.  This issue tracker is for bug reports and feature requests.  I would suggest that you ask your question at https://gis.stackexchange.com/ and make sure you tag qgis2web.

**Comment by tomchadwin** [comment]
Tagging @ruz76

**Comment by ruz76** [comment]
@moni1865 Could you please send me some data to test the functionality to jan.ruzicka.vsb@gmail.com There may be hidden things that the code can not process.

**Comment by tomchadwin** [comment]
Closing without feedback. Leave a comment if the issue is still present and I can reopen,

**Comment by wstaelens** [comment]
am I correct that this functionality doesn't work?

**Comment by ruz76** [comment]
Yes. Sorry about that, but we did not continue the development. The main reason was that the extension was basically hack of existing code, so it was difficult to maintain it.
