### ISSUE TITLE
Not necessarily an issue: only show fields when data is present (for popups)?

### ISSUE THREAD

**Issue by jefferycsauer** [tomchadwin/qgis2web#743]
Hi there, 

This is not necessarily an issue, but wanted to post here. Is is possible to populate fields that have data, rather than always showing the same set of pre-defined fields on a popup (even when a given field may have no data)? 

QGIS 3.6
QGIS2WEB 3.6.0

Best,

Jeff

**Comment by boesiii** [comment]
@jefferycsauer You can control what fields you can see in the initial qgis2web dialog by using the Form tab in Qgis Layer Properties.  Under layer properties, form tab, highlight field, change widget type to Hidden.
![layerp](https://user-images.githubusercontent.com/2079638/57249096-0eb55d80-7012-11e9-92a4-ee13f32c2f7e.PNG)

**Comment by jefferycsauer** [comment]
Hi @boesiii , 

Thanks for the rapid response! I am aware of the hidden feature, I think my original post was not clear. 

For a given variable - like your CAD_LLO - imagine that some of the rows have NoData (or NULL). I am interested in displaying CAD_LLO _when there is data_, but hiding the field in the popup when there is NoData. 

I.e. I would like to replicate this ESRI post: https://community.esri.com/community/gis/web-gis/arcgisonline/blog/2017/07/18/conditional-field-display-with-arcade-in-pop-ups

**Comment by boesiii** [comment]
Woops!  I see what you need.  
If your popup fields are set to "no label" and your data has true NULL values then your popup should display only the fields with data.  If the popup fields are set to "inline labels" then it will display all fields even if no values are present.  Is it possible to not display those "inline labels" when fields have no data?  No, the current version of qgis2web does not support it but you could possibly modify the resulting javascript code.

**Comment by jefferycsauer** [comment]
Ah, thanks again! The need to fix it in javascript was also suggested on stackexchange. 

Closing for now!

**Comment by boesiii** [comment]
I have a fix for you.  Please tell me the Stackexchange link and I will add it there.

**Comment by jefferycsauer** [comment]
@boesiii ah, what a savior! https://gis.stackexchange.com/questions/321894/replicating-conditional-popup-of-arcgis-online-in-qgis2web
