### ISSUE TITLE
layer search improvements?

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#747]
Hello Tom,

Using qgis3.4.5 and q2w 3.7 I have a few questions about the Layer search element.

The index.html has the following code added which for me has no functionality.
`resetLabels([layer_VVMleden_0]);
        map.on("zoomend", function(){
            resetLabels([layer_VVMleden_0]);
        });
        map.on("layeradd", function(){
            resetLabels([layer_VVMleden_0]);
        });
        map.on("layerremove", function(){
            resetLabels([layer_VVMleden_0]);
        });`
When I disable or remove those lines, nothing seems to change. What is it for?

Another issue with the above lines is the way the layer name is build up. The layer name in the rest of the index.html is layer_VVM_leden_0, In the lines above it misses one _
Is this intentional, or is it a bug?
And changing the layername for the correct one still doesn't show me what these lines are for.

**Comment by tomchadwin** [comment]
Those lines are there to remove overlapping labels. However, if the layer names are wrong, that does need fixing. I'll look into it.
