### ISSUE TITLE
Popup function is not working with multiple layers 

### ISSUE THREAD

**Issue by gobinathp** [tomchadwin/qgis2web#754]
Hi fellas, I'm using QGIS2Web updated plugin, and I have an issue with pop-up when multiple layers loaded/generated. I attached the below screenshots

![image](https://user-images.githubusercontent.com/6542202/59327408-0fbf6600-8d07-11e9-9b0f-a84b50842c44.png)

The above screenshot is showing the pop-up details single layer(it's working fine)

![image (1)](https://user-images.githubusercontent.com/6542202/59327449-2fef2500-8d07-11e9-99e6-294281774778.png)

The above screenshot is loaded with multiple layers(morethan 8layers), I want to show the feature details- popup information for the topmost visible layer.

- not able to view top most layer feature details(pop-up)

Note: I'm beginner for JavaScript and OpenLayers so I just changed the code for LayerSwitcher to move right to left.. and - I would like to make pop-up permanently visible on the right-side(how do I do that).

**Comment by gobinathp** [comment]
I found the issue, Layers should not be grouped as follows, **Layers should be separate to enable pop-up functionalities.**


![image](https://user-images.githubusercontent.com/6542202/59838411-7af2e300-936c-11e9-8183-615f4c3ae745.png)

**Comment by tomchadwin** [comment]
Ah, yes. Layer groups simply are not well supported in qgis2web - apologies.

**Comment by gobinathp** [comment]
> Ah, yes. Layer groups simply are not well supported in qgis2web - apologies. See #175

@tomchadwin, Thanks, you guys have done a great job, so no need of apologies.. thanks again. keep it up, guys.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
