### ISSUE TITLE
Python Error with QGis2Web on QGis 3.6.3 Noosa

### ISSUE THREAD

**Issue by rhartings** [tomchadwin/qgis2web#755]
I'm receiving a Python Error when trying to create a web map using QGIS2Web and for the life of me cannot figure out what to do.

Running QGIS 3.6.3 Noosa Windows 10 Professional

KeyError: 100 Traceback (most recent call last): File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 60, in run self.dlg = MainDialog(self.iface) File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 156, in init self.autoUpdatePreview() File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 320, in autoUpdatePreview self.previewMap() File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 323, in previewMap preview_file = self.createPreview() File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 286, in createPreview dest_folder=utils.tempFolder()).index_file File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write folder=dest_folder) File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 130, in writeOL popup, json, restrictToExtent, extent, feedback, matchCRS) File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 220, in exportLayers iface, extent, precision, crs, optimize) File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 233, in exportVector cleanLayer = writeTmpLayer(layer, restrictToExtent, iface, extent) File "C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 162, in writeTmpLayer uri = TYPE_MAP[layer.wkbType()] KeyError: 100

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] QGIS version: 3.6.3-Noosa Noosa, 0c5774c068

Python Path: C:/PROGRA~1/QGIS 3.6/apps/qgis/./python C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins C:/PROGRA~1/QGIS 3.6/apps/qgis/./python/plugins C:\Program Files\QGIS 3.6\bin\python37.zip C:\PROGRA~1\QGIS 3.6\apps\Python37\DLLs C:\PROGRA~1\QGIS 3.6\apps\Python37\lib C:\Program Files\QGIS 3.6\bin C:\PROGRA~1\QGIS 3.6\apps\Python37 C:\PROGRA~1\QGIS 3.6\apps\Python37\lib\site-packages C:\PROGRA~1\QGIS 3.6\apps\Python37\lib\site-packages\win32 C:\PROGRA~1\QGIS 3.6\apps\Python37\lib\site-packages\win32\lib C:\PROGRA~1\QGIS 3.6\apps\Python37\lib\site-packages\Pythonwin C:/Users/Rodney/AppData/Roaming/QGIS/QGIS3\profiles\default/python C:\Users\Rodney\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins C:/Users/Rodney/Google Drive/QGis

**Comment by boesiii** [comment]
It looks like one of your layers has no geometry.  Any chance you can send a sample of your date and qgis file?

**Comment by rhartings** [comment]
Unfortunately I can not upload files but yes it was the lack of geometry in a couple of layers.  That's all I needed to get it figured out.  Thank you for the help.

**Comment by tomchadwin** [comment]
Thanks to a major contribution from @jef-n, I think this issue is already fixed in master. It just hasn't made its way into a release yet.
