### ISSUE TITLE
message on max zoom level

### ISSUE THREAD

**Issue by nitrokevin** [tomchadwin/qgis2web#759]
Hi sorry for the generic question, please delete if not allowed.

I'm just wondering if it is possible to set a message to display when you reach the maximum zoom level eg "For more personalised information please use our enquiry form"

**Comment by tomchadwin** [comment]
It's not something which would be implemented in the plugin. You'd be best off searching for how to do this in either Leaflet or OpenLayers, or asking on Stack Exchange if you can't find an answer. Sorry not to have more for you.

**Comment by riccardoklinger** [comment]
Hi nitrokevin, if you need some customized qgis2web version, just contact me. Maybe I can help.

**Comment by nitrokevin** [comment]
Hi riccardoklinger that would be great can I email you? Or send me an email at kevinneal at avid-design.co.uk
