### ISSUE TITLE
Open Layers - Measurement Issue

### ISSUE THREAD

**Issue by gobinathp** [tomchadwin/qgis2web#763]
issue - no **delete option** for **measured line/polygon** please go-through the following screenshots to understand the issue

![image](https://user-images.githubusercontent.com/6542202/60108324-0a8dfc80-9786-11e9-98a1-340ee9fb35a5.png)

- in the above screenshot, no option to delete so we need to refresh the page every time
-**other options as I have Leaflet but I'm getting symbology issues**(I opened a separate issue for that- this image just to show I'm helpless since I faced two different errors - by using leaflet I have an advantage of getting measurement control with options of **Finish Measurement and Delete**)

![leaflet](https://user-images.githubusercontent.com/6542202/60110102-2515a500-9789-11e9-9bd2-6e0c467da4c5.gif)

@tomchadwin hope this information helps.

**Comment by tomchadwin** [comment]
Is it a problem that you cannot delete measurement lines?

**Comment by gobinathp** [comment]
Yes, exactly, that's the problem. I don't get any options to delete the measured lines, in OpenLayers 

- is it possible to measure polygon, I'm new to this so if my questions are irrelevant sorry to trouble you guys

**Comment by tomchadwin** [comment]
No, what I meant is: does it matter that you cannot delete the measurement lines?

> is it possible to measure polygon

Do you mean area measurement, rather than just length/perimeter?

**Comment by gobinathp** [comment]
No, what I meant is: does it matter that you cannot delete the measurement lines?
> yes, I need to delete the measured lines, because I have around 10 more layers, the past measured line is disturbing the next measurement/layers so I would like to delete the old measurement.

Do you mean area measurement, rather than just length/perimeter?
>yes, I meant area measurement, if I am getting it will be more helpful.

**Comment by jipexu** [comment]
Yes it will be great to have a way to remove the mesurements line after use ...

**Comment by jipexu** [comment]
Hi
Yep never noticed but it's really a gap between the implementation of measurement tool between an export for leaflet and an export  for openlayer ...

**Comment by andreaordonselli** [comment]
Complete lenght and area measurement is here #971
Look in the code for inserting `sketch = null;`

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/80defd3c5753ca2bee0ebb72a0e0c4e65a7c207d) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.0)
