### ISSUE TITLE
enhancement: basemaps... switch to https

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#766]
Currently I assume that the plugin is using TMS layers as basemaps. Unfortunately most users use the QUickmapservices plugin for basemaps in QGIS. This is fine for working in QGIS. Yet, the TMS's in Quickmapservice seem to use mostly http instead of https. I would like to use https for the external ressources instead of http as the hosted qgis2web web map might be used in a ssl-secured environment but the basemap is delivered in http. this will break the whole https-connection to the qgis2web webmap.
maybe go with a try / except statement. I asked quickmapservices already, whether they will change to https only but they were not very "open" to this proposal.

**Comment by tomchadwin** [comment]
From memory only, does HTTPS fail in the preview? Regardless, you are right that we need to find a solution to this, since HTTP is all but deprecated for end-user client connections now.

**Comment by riccardoklinger** [comment]
no works fine in preview. Tried with a ssl TMS :
https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}
this was showing great in the preview as well as on the exported map.

**Comment by tomchadwin** [comment]
Thinking about this again, don't we have to leave the responsibility for this up to the user? Don't they set the URL in QGIS, and hence can choose HTTP or HTTPS?

**Comment by tomchadwin** [comment]
Confirmed that for manually added XYZ layers, the user explicitly sets the URL including the protocol (tested with OSM HTTP and HTTPS). I think this is therefore a QuickMapServices issue, so will close here.
