### ISSUE TITLE
basic attribution updates

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#767]
Hi,

The standard attribution refers to http://leafletjs.com
Could this be updated to https://leafletjs.com

And while at this issue, do you think QGIS (https://www.qgis.org) should be added to the attribution?
Although qgis2web al ready implies the use of qgis, I think it would be nice to name QGIS separately.
QGIS - qgis2web - Leaflet

**Comment by tomchadwin** [comment]
Thanks for raising this. Yes to point one - that should definitely be changed. Not sure about adding QGIS attribution. I guess it's probably a nice idea.
