### ISSUE TITLE
abstract info box styling

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#768]
Happy to merge this. I'd like to make a couple of changes before we make a release, though:

- the font in the abstract is different to eg the attribution
- the control (hovered and mouseout) should use the colours defined for widgets in the qgis2web appearance tab

_Originally posted by @tomchadwin in https://github.com/tomchadwin/qgis2web/pull/764#issuecomment-507592483_

**Comment by tomchadwin** [comment]
Fixed in master by @riccardoklinger - thanks!
