### ISSUE TITLE
Gradient Layer not showing with qgis2web export

### ISSUE THREAD

**Issue by fidelle** [tomchadwin/qgis2web#772]
I am trying to export a map of population census data throufh qgis2web. It is a population density map but when I export it, it loses all its features. I am not sure why. When it is just a single color it seems to plot just fine.I have tried on several laptops and run into the same issue. #685 
<img width="677" alt="Screen Shot 2019-07-08 at 1 43 28 PM" src="https://user-images.githubusercontent.com/20359201/60831184-f931f080-a186-11e9-9586-8aa28c22be22.png">
<img width="1014" alt="Screen Shot 2019-07-08 at 1 44 32 PM" src="https://user-images.githubusercontent.com/20359201/60831195-0058fe80-a187-11e9-9568-693a0a22fb2a.png">

**Comment by tomchadwin** [comment]
Can you upload your layer and project files?

**Comment by fidelle** [comment]
[PopulationCensus.qgz.zip](https://github.com/tomchadwin/qgis2web/files/3377507/PopulationCensus.qgz.zip)

**Comment by fidelle** [comment]
The other files are too large to be uploaded

**Comment by boesiii** [comment]
Your graduated symbology is based on an expression using a base 10 logarithm and I don't believe that is supported in QGIS.  You should add a new field and populate it with those logarithm values and use that new column for your symbology.

**Comment by fidelle** [comment]
Doing that makes the graph appear. But now my hover overs and labels show the log of population instead of the actual population value. Is there a way to fix that?

**Comment by boesiii** [comment]
Make sure your popups fields are set to POPULATION and not the new field you created.

**Comment by tomchadwin** [comment]
Thanks for finding the explanation, @boesiii. I'll try to base 10 log into the expression code, so that this issue doesn't arise in the future.

**Comment by tomchadwin** [comment]
OK, there were two issues here:

- the log10 implementation in JS was wrong, and I've now fixed it
- expressions in the graduated renderer column are not supported, I'm afraid, and I've not done anything about that, as it's quite a big job (I'll see if I can add support in time)

More broadly, expressions.data-driven values are only supported in a few places, but QGIS supports them all over the place. It would be great to add this support in more widely.

I'll close this issue for now, and will open one specific to the second issue above.
