### ISSUE TITLE
Return to North when rotating Openlayers missing

### ISSUE THREAD

**Issue by myfta** [tomchadwin/qgis2web#774]
The export to an Openlayers map works fine for me, a problem arises when I rotate the map from its north to the top of the screen alignment. It should display an arrow icon/button on the top right of the map with an arrow on it. When you click the button the map resets to its original alignment. On qgis2web maps this icon is missing.

Is something in the qgis2web scripts that is suppressing/hiding this button?

**Comment by tomchadwin** [comment]
> Is something in the qgis2web scripts that is suppressing/hiding this button?

The arrow is there for me *when the map is exported and viewed in Firefox (in my case). The button doesn't appear in the preview. Is that the case for you, or does it fail to appear in your exported map?

**Comment by myfta** [comment]
I does not appear in the exported map (Opera and Firefox). But I have done some tests now. If I export a map with no layers and therefore does not use the layer control (collapsed or expanded) it does appear, so it seems the layer control is obscuring the north arrow.

**Comment by tomchadwin** [comment]
Ah, OK. Thanks for testing. The issue probably needs to be raised on the layer switcher repo:

https://github.com/walkermatt/ol-layerswitcher/issues

**Comment by myfta** [comment]
As a workaround I have edited qgis2web.js to move the layerswitcher down the screen (was top: 0.5em). That makes it well clear of return to the north arrow when it appears.

`.layer-switcher {
    top: 5em;
    right: 0.5em;
    text-align: left;`

There is potentially another issue that [https://github.com/walkermatt/ol3-layerswitcher](url) is replaced by [https://github.com/walkermatt/ol-layerswitcher](url)
