### ISSUE TITLE
travis testing is currently testing only against latest

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#777]
It seems like the travis testing module uses the latest version of qgis. Due to better maintainability we should change this to tests against the LTR instead of latest releases which might use a newer version of QT or other components.

**Comment by riccardoklinger** [comment]
Furthermore, at the moment both test jobs are run with "latest" qgis. I think it was supposed to have one test with latest and the other with the LTR. in /.docker we have the definition for latest version (which is referenced in the travis log:
![image](https://user-images.githubusercontent.com/7377897/61596642-8a34ad00-ac06-11e9-968d-9b4d211ce653.png)
and in travis.yml we have the string descriptions for both jobs, but the use the same parameters.

**Comment by riccardoklinger** [comment]
here are some screens that make me think, that travis always uses qgis "latest":
- run .2 with "release-3_0:
![grafik](https://user-images.githubusercontent.com/7377897/61718605-a0a44b00-ad63-11e9-87fa-a19a48723eae.png)
line 242 shows its using a variable which is confirmed somehow in line 248: s
![grafik](https://user-images.githubusercontent.com/7377897/61718713-ce898f80-ad63-11e9-87ec-86462e6b73ef.png)
. until line 302 we seem to be in docker-build installation part.
we see same commands in lines 305/306 but now we have lost the reference to the env parameter set in travis.yml and it is using "latest":
![grafik](https://user-images.githubusercontent.com/7377897/61718927-30e29000-ad64-11e9-83c8-0662227fbb06.png)
So it seems, we are building twice the same machine but we are just using one in the end (the one that is using qgis latest)....

**Comment by akuckartz** [comment]
Why not test both?

**Comment by riccardoklinger** [comment]
no, don't get me wrong: I would love to stick with two tests one for LTR and one for latest. But if you check my prior comment, it does not look like it is done right now. It seems to me, that both travis steps tests test against QGIS latest (which was updated to 3.8 just a few days ago...)

**Comment by riccardoklinger** [comment]
PR #790 is fixing this.
