### ISSUE TITLE
Error exporting to Leaflet and OL3

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#78]
In maindialog.py on line 198, writeLeaflet needs 19 variables passed to it but currently it is only passing 18.  The line should read as follows (I think?):

outputFile = writeLeaflet(self.iface, folder, 600, 400, 1, layers, visible, "", cluster, "", "", "", "", labels, 0, 0, json, params, popup)

http://gis.stackexchange.com/questions/153532/qgis2web-error-when-exporting-to-leaflet-ol3/153537#153537

**Comment by tomchadwin** [comment]
Acknowledged. Stupid oversight on my part.

**Comment by tomchadwin** [comment]
Fixed in master. Will push to QGIS plugin repo as 0.14.1

**Comment by tomchadwin** [comment]
Thanks, @boesiii for logging this - I'm not getting StackExchange qgis2web alerts yet - must sort that out.
