### ISSUE TITLE
Display sub items in Legend

### ISSUE THREAD

**Issue by dassouki** [tomchadwin/qgis2web#79]
This is a feature request to give qgis2web users the ability to add, remove, and modify legends based on the symbology in the QGIS canvas

**Comment by tomchadwin** [comment]
This should already be possible in Leaflet export, using the method from qgis2leaf - see that plugin's documentation. It's not possible in OL3, and the Leaflet method is not ideal, so this is definitely a valid feature request.

**Comment by tomchadwin** [comment]
Committed to master. Please test and feed back.

**Comment by dassouki** [comment]
Just got this .. might test this next week :D

**Comment by tomchadwin** [comment]
I should have said, it's only done for Leaflet, not OL3.

**Comment by tomchadwin** [comment]
Leaflet export should now automatically generate legend icons - no need to use the old qgis2leaf technique (legend_exp/icon_exp).

**Comment by tomchadwin** [comment]
Recently also implemented in OL, so closing.
