### ISSUE TITLE
add reset filter button

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#796]
as there are filters, It would be great to have a button to reset all filters back to their initial state

**Comment by Jeroen-GroeneBij** [comment]
As soon as I select 1 feature, there is no way to get all features visible again, apart from ctrl-clicking each one of them.
Is this what you mean with reset filter?

If so, then yes please, because without it, the filter function to me is worse than no filter at all :)

**Comment by riccardoklinger** [comment]
Please reopen. I need to implement this.

Von meinem iPhone gesendet

**Comment by tomchadwin** [comment]
I just implemented it in https://github.com/tomchadwin/qgis2web/commit/4e75cbc1672aa380788b5d57477d8d4230d65dd7

**Comment by tomchadwin** [comment]
Apologies - I only implemented it for strings. Will look at other types now.

**Comment by riccardoklinger** [comment]
Ah, Great!

Von meinem iPhone gesendet

**Comment by tomchadwin** [comment]
I've now added resets for numeric (slider) and datetime (date picker) filters. Can you have a look when you get the chance, @riccardoklinger? Let me know if anything else needs to be done.

**Comment by tomchadwin** [comment]
I should say, it needs a bit of CSS to tidy it up.
