### ISSUE TITLE
Leaflet appearance settings - base layer not showing

### ISSUE THREAD

**Issue by mixedbredie** [tomchadwin/qgis2web#8]
When I export my QGIS project as a Leaflet project the Base layer selected in Appearance under Settings does not appear in the final map output.

In my test project I have two layers (PostGIS polygons) and a base layer (WMS) and they all appear correctly.

**Comment by tomchadwin** [comment]
Ah, yes, the basemap UI settings are not pulled into the Leaflet export yet - thank you.

**Comment by tomchadwin** [comment]
Fixed in master
