### ISSUE TITLE
OpenStreetMap attribution

### ISSUE THREAD

**Issue by iamnunocaldeira** [tomchadwin/qgis2web#803]
hello, noticed the export html, doesn't include attribution when using OpenStreetMap or derivates. Please add as this is a violation of the license. Add the attribution and hyperlink as requested on https://www.openstreetmap.org/copyright

**Comment by riccardoklinger** [comment]
hi @iamnunocaldeira 

it really depends on you! If you use the quickmapservice plugin to display OSM basemap in your qgis project you will do just fine as QMS is already taken care of the attribution. The attribution is then also shown in the webmap ( leaflet and OL):
![image](https://user-images.githubusercontent.com/7377897/63850758-1a4bdc00-c995-11e9-8562-beb6df98a3bd.png)
![image](https://user-images.githubusercontent.com/7377897/63850774-29cb2500-c995-11e9-9286-3158cea36915.png)
The metadata like attribution and license is controled inside the layer itself and is noot a function of qgis2web:
![image](https://user-images.githubusercontent.com/7377897/63850900-6bf46680-c995-11e9-8b3c-1627d8883e3a.png)

**Comment by riccardoklinger** [comment]
how do you add the OSM layer in QGIS? Make sure to add the information in the properties.

**Comment by riccardoklinger** [comment]
hey @iamnunocaldeira I will close this now as there was ne reaction. If your issue is still valid, please reopen this issue.

Best, Riccardo
