### ISSUE TITLE
Differentiate OL3 and Leaflet UI options

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#81]
At the moment, the UI confusingly presents all options. Not all options are implemented in OL3 and Leaflet export. This means that users are misled as to options available. It would be better if the UI greyed out options unavailable in the currently selected output format.

**Comment by boesiii** [comment]
What would be the basis of why the options are greyed out? The last picked export button?  What about adding different lists/areas, with names such as Leaflet Options and OL3 Options?  How about just adding some text to the option "Leaflet Only".

**Comment by tomchadwin** [comment]
That was my first thought, but the UI would get pretty complex. I was thinking instead of getting rid of the four export/preview buttons, and replacing them with one export, one preview, and one select OL3 or Leaflet (combo or radio buttons). Enable disable options according to that last control's selection.

That said, I've not really done any UI development, so I'll have to see if I can figure out how to do it.

**Comment by boesiii** [comment]
Now I understand.

**Comment by tomchadwin** [comment]
Just committed that UI change to master. I think it works pretty well. Now to figure out how to disable the relevant options according to which map format is selected.

**Comment by boesiii** [comment]
Looks good!

**Comment by tomchadwin** [comment]
OK, I think I've started to achieve this. Try current master - when you choose OL3 or Leaflet, individual settings should disable and enable in the Options pane according to whether they are supported in each output map format.

Next job will be to do the same for per-layer options in the Layers and Groups pane.

**Comment by tomchadwin** [comment]
The per-layer options are now enabled/disabled according to availability in each map format. Please test
