### ISSUE TITLE
Swipe option between layers

### ISSUE THREAD

**Issue by adamsss92** [tomchadwin/qgis2web#810]
Hi,

It is possible to export web map (using qgis2web) and then add the "swipe" feature like this: https://openlayers.org/en/latest/examples/layer-swipe.html? I'm newbie in javascript developing. If it is possible, could you show me which .html / .js file should i edit and add some new part of code?

Best regards,
Adam

**Comment by tomchadwin** [comment]
I'm afraid you're probably better off asking this on [GIS Stack Exchange](https://gis.stackexchange.com/). I don't think it's really a feature request, and it's definitely not a bug. Sorry not to be more help.

**Comment by riccardoklinger** [comment]
There are not so many use cases where a swipe tool Is of use. If you add one, you also need to define the map components visible on each side of the slide. Could be an interesting add to swipe between basemaps. Everything else is quite hard to implement.

Von meinem iPhone gesendet
