### ISSUE TITLE
Apostrophe in Filter value breaks the javascript output

### ISSUE THREAD

**Issue by TLDuhamel** [tomchadwin/qgis2web#811]
Similar to issue #711  

I am using the filter conditions in 3.8.0 experimental
My Filter is on a 'School name' string field.
Some of these names include apostrophes. It appears the apostrophes are breaking the script:

`schoolname_options_str  += '<option value="St Dominic's Catholic School (Blockhouse Bay)">St Dominic's Catholic School (Blockhouse Bay)</option>';`

![image](https://user-images.githubusercontent.com/2009756/65118449-33e5be00-da3f-11e9-9c3a-a21eb9acac72.png)

**Comment by tomchadwin** [comment]
Are you able to have a look at this, @riccardoklinger?
