### ISSUE TITLE
Travis tests failing on master

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#812]
See: https://travis-ci.org/tomchadwin/qgis2web/jobs/586078330

I don't get these failures locally, so fixing them on Travis is proving tricky. If anyone can recreate the error, reply to this thread, and we can take it from there.

**Comment by volcan01010** [comment]
@tfh-galbraith and I will have a look at this this morning.

**Comment by tomchadwin** [comment]
Thanks! The core question is: why arethese tests passing against QGIS 3.4 LTR, but failing against QGIS master?

**Comment by volcan01010** [comment]
It's something to do with how symbols are created.  All tests fails at the same point:

```python
ipdb> ll                                                                                                                                                                                      
    466 def is25d(layer, canvas, restrictToExtent, extent):
    467     if layer.type() != layer.VectorLayer:
    468         return False
    469     if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
    470         return False
    471     vts = layer.customProperty("VectorTilesReader/vector_tile_source")
    472     if vts is not None:
    473         return False
    474     renderer = layer.renderer()
    475     if isinstance(renderer, QgsNullSymbolRenderer):
    476         return False
    477     if isinstance(renderer, Qgs25DRenderer):
    478         return True
    479     symbols = []
    480     if isinstance(renderer, QgsCategorizedSymbolRenderer):
    481         categories = renderer.categories()
    482         for category in categories:
    483             symbols.append(category.symbol())
    484     elif isinstance(renderer, QgsGraduatedSymbolRenderer):
    485         ranges = renderer.ranges()
    486         for range in ranges:
    487             symbols.append(range.symbol())
    488     elif isinstance(renderer, QgsRuleBasedRenderer):
    489         rules = renderer.rootRule().children()
    490         for rule in rules:
    491             symbols.append(rule.symbol())
    492     else:
    493         renderContext = QgsRenderContext.fromMapSettings(canvas.mapSettings())
    494         fields = layer.fields()
    495         if restrictToExtent and extent == "Canvas extent":
    496             request = QgsFeatureRequest(canvas.extent())
    497             request.setFlags(QgsFeatureRequest.ExactIntersect)
    498             features = layer.getFeatures(request)
    499         else:
    500             features = layer.getFeatures()
    501         renderer.startRender(renderContext, fields)
    502         for feature in features:
    503             symbol = renderer.symbolForFeature(feature, renderContext)
    504             symbols.append(symbol)
    505         renderer.stopRender(renderContext)
    506     for sym in symbols:
--> 507         sl1 = sym.symbolLayer(1)
    508         sl2 = sym.symbolLayer(2)
    509         if (isinstance(sl1, QgsGeometryGeneratorSymbolLayer) and
    510                 isinstance(sl2, QgsGeometryGeneratorSymbolLayer)):
    511             return True
    512     return False
    513 
```

The symbols don't have a symbolLayer(1) - all the generated symbolLayers have length 1.

```python
ipdb> symbols                                                                                                                                                                                 
[<qgis._core.QgsFillSymbol object at 0x7f463bcb9ca8>, <qgis._core.QgsFillSymbol object at 0x7f463bcc01f8>, <qgis._core.QgsFillSymbol object at 0x7f463bcc05e8>, <qgis._core.QgsFillSymbol object at 0x7f463bcc0678>, <qgis._core.QgsFillSymbol object at 0x7f463bc440d8>]
ipdb> [len(s) for s in symbols]                                                                                                                                                               
[1, 1, 1, 1, 1]
```

**Comment by tomchadwin** [comment]
OK, this function detects whether something is 2.5d or not. Can you add something really high up in the function to return False if the number of symbol layers != 2?

**Comment by volcan01010** [comment]
@tfh-galbraith confirms that it also fails in 3.6.3. https://github.com/qgis/QGIS/releases/tag/final-3_6_3

**Comment by tfh-galbraith** [comment]
well, on the `release-3_6` docker image, which is probably the same or very close to the `final-*` tags

**Comment by tomchadwin** [comment]
But not in 3.4. Must be some QGIS change between those versions. Not sure what.

**Comment by volcan01010** [comment]
Maybe.  We're trying to figure out what change to QGIS made it break.  The ranges are created by the QgsRendererRange class.  There were a few changes to recently.

**Comment by tomchadwin** [comment]
Find out which of the earlier `return False`s was triggered in 3.4.

**Comment by tfh-galbraith** [comment]
ac0326a3517263cc2b9311aa01aeb2c5453ce21b

**Comment by tomchadwin** [comment]
I think it would always have raised an error if it tried to access a non-existent symbol layer. <=3.4, the whole `is25d` function must have returned false before it even tried to detect `symbolLayer(1)`. If you can find out in 3.4 where precisely `is25d` returns false in that test, that should point us towards where things have changed >3.4.

**Comment by volcan01010** [comment]
The behaviour when you try to get a symbol layer that doesn't exist has changed since 3.4.  In 3.4:

```python
ipdb> sl1 = sym.symbolLayer(1)                                                                                                                                                                
ipdb> sl1 is None                                                                                                                                                                             
True
```

**Comment by tomchadwin** [comment]
No no. What I'm saying is that <=QGIS3.4, the code never reached the `symbolLayer(1)` line, because `is25d` had already returned false. Now, for some reason, `is25d` must not be returning false where it was, so the code is reaching the failing symbolLayer(1) call, which it is not intrended to do. So, if you have a QGIS 3.4 install, find out where `is25d` exits in that test scenario (symbol vector layer with single symbol renderer), and then investigate why that is no longer returning false.

As I say, whatever the cause, the solution is probably returning false from `is25d` early on if `len(symbolLayers()) == 0` (or even != 3, from memory).

**Comment by volcan01010** [comment]
Demonstration of change in behaviour:

```python
ipdb>                                                                                                                                                                                         
> /usr/src/qgis2web/utils.py(509)is25d()
    508         sl1 = sym.symbolLayer(1)
--> 509         sl2 = sym.symbolLayer(2)
    510         if (isinstance(sl1, QgsGeometryGeneratorSymbolLayer) and

ipdb> sl1                                                                                                                                                                                     
ipdb> import os                                                                                                                                                                               
ipdb> os.getenv('QGIS_TEST_VERSION')                                                                                                                                                          
'release-3_4'
ipdb> sl1 is None                                                                                                                                                                             
True
```

versus

```python
--> 507     for sym in symbols:
    508         sl1 = sym.symbolLayer(1)

ipdb> import os                                                                                                                                                                               
ipdb> os.getenv('QGIS_TEST_VERSION')                                                                                                                                                          
'latest'
ipdb> n                                                                                                                                                                                       
> /usr/src/qgis2web/utils.py(508)is25d()
    507     for sym in symbols:
--> 508         sl1 = sym.symbolLayer(1)
    509         sl2 = sym.symbolLayer(2)

ipdb> n                                                                                                                                                                                       
IndexError: 1
```

**Comment by volcan01010** [comment]
It was reaching that line, then sl1 was set to `None` so the is25d method returns `False` because `None` is not an instance of `QgsGeometryGeneratorSymbolLayer`.

**Comment by tfh-galbraith** [comment]
we could potentially either do something like:

```
    for sym in symbols:
        try:
            sl1 = sym.symbolLayer(1)
            sl2 = sym.symbolLayer(2)
        except IndexError:
            continue
        if (isinstance(sl1, QgsGeometryGeneratorSymbolLayer) and
            isinstance(sl2, QgsGeometryGeneratorSymbolLayer)):
            return True
```

or 

```     
for sym in symbols:
        if sym.symbolLayerCount() < 2:
            continue
        # ...
```

which should both avoid the problem by not trying to access layers that aren't there.

**Comment by tomchadwin** [comment]
I owe you both an apology. Thanks for figuring this out - I made the wrong assumption. Agree that a `try` might be best, though the except probably wants to be `return False` not continue.

Also, checking the number of symbolLayers earlier on, and returning False if it's not 3 would still probably fix this.

But the other weird question is: why don't I get this error locally? I'm on 3.8

**Comment by tfh-galbraith** [comment]
> I owe you both an apology. Thanks for figuring this out - I made the wrong assumption. Agree that a `try` might be best, though the except probably wants to be `return False` not continue.
I wasn't sure if it needs to by an if any (at least 1 has multiple symbol layers) or an 'if all' condition, so the continue assumes any.

have changed it in the PR to be early return (if not all ...)

> But the other weird question is: why don't I get this error locally? I'm on 3.8.

Possibly stupid thought: are you definitely using 3.8? (`docker-compose run qgis qgis --version`), otherwise just updating the QGIS_TEST_VERSION var externally might not be actually using the right container/image? We needed to `export QGIS_TEST_VERSION=... TRAVIS_BUILD_DIR=$PWD; docker-compose -f .docker/docker-compose.travis.yml build` to update the container tags before running the `docker-compose run qgis run-tests....` command to force that to happen.

Otherwise, I have no idea.

**Comment by tomchadwin** [comment]
I should have clarified: I meant it works for me manually in my local install of QGIS 3.8 - no test, no Docker, just me manually exporting a single layer. That's what the failing test is replicating.

**Comment by tomchadwin** [comment]
And I have the "old" behaviour:

```
iface.activeLayer().renderer().symbol().symbolLayer(1) is None
True
```

**Comment by tfh-galbraith** [comment]
> And I have the "old" behaviour:
> 
> ```
> iface.activeLayer().renderer().symbol().symbolLayer(1) is None
> True
> ```

Interesting, I'm seeing the same (manually) here on 3.8.3 on Ubuntu, with the occasional hard segfault when trying to access `symbol()` or `symbolLayer()` of various styled layers.

I have no idea how the build process for qgis works; is there any way the IndexError stuff could have made it into the docker but not packaged releases? Seems unlikely but maybe?

**Comment by tomchadwin** [comment]
I don't know enough about Docker, but I've not come across anything else similar. Really odd. Might have to ask on the dev list.

**Comment by tfh-galbraith** [comment]
I think the answer is actually that the version installed by docker `qgis/qgis:latest` tag is actually reporting itself as `3.9.0-Master`, which contains a decent amount of changes since the last official packaged release which for me is 3.8.3.

The commit I linked to above, that introduces the IndexError and other changes to the symbol API, is dated after that release, and if my git-fu isn't failing me, doesn't appear in any of the tagged repo versions (and hence docker containers), so it'll only appear in `:latest`.

If I run the latest container interactively I do get the IndexError with the `iface.activeLayer()....` test directly in the qgis console, which further supports it being something along these lines.

I wonder if it might be worth adding a 3rd entry to the travis version matrix, so it tests LTS (3.4), stable (3.8) and dev (latest)?

**Comment by volcan01010** [comment]
Test, stable and dev sounds like a good idea.  Then you get a longer warning if things are broken.

**Comment by tomchadwin** [comment]
Apologies - forgot to reply to this. Yes, LTR, latest, and master would be wise. @riccardoklinger recently got the Travis setup working with the versions it does, so hopefully it won't be too much to add another, if the Docker image exists and is maintained.

**Comment by tomchadwin** [comment]
Tests are now passing.
