### ISSUE TITLE
Basemap Layer doesn't visible

### ISSUE THREAD

**Issue by febriansusanta** [tomchadwin/qgis2web#816]
Hello..
Now, I am using QGIS 3.8.3, qgis2web 3.9.0, Windows 10

I want to present basemap for my map. However, when I wanted export to web map using qgis2web, the basemap layer didn't appear to my web map. 

Attached screencapture of my project.

Is it a bug? Thank you.

![Basemap does not visible](https://user-images.githubusercontent.com/17267550/67139521-6a4f6c80-f27b-11e9-96e2-fcdbc5aeb63e.png)

**Comment by jukos** [comment]
Hello,
no problems with 3.4.12 with openlayers and leaflet.
But with mapbox I saw no basemap (openstreetmap).
Basemap layer active and visible?
Greetings

**Comment by tomchadwin** [comment]
@febriansusanta You might want to check the option "Match project CRS", and see whether that brings your basemap into the webmap. If that doesn't solve it, we need to know how you added the basemap to QGIS.

@jukos No, XYZ tiled layers are not yet supported in the Mapbox GL JS exporter.

**Comment by febriansusanta** [comment]
@tomchadwin Thank you for your responses, problem solved. But I have a problem again when I want to present point with style. The style couldn't be displayed correctly. Attached a screen capture of my problem. 

![image](https://user-images.githubusercontent.com/17267550/67629327-87e98b00-f8a6-11e9-8d41-c1b7d281e5f9.png)

**Comment by jukos** [comment]
Hello,
you can create own svg symbols.
I have one created for you. You can it use, it works. 
You can change the svg with inkscape.
You must insert the svg to the right folder:
C:\Program Files\QGIS 3.4\apps\qgis-ltr\svg\
You can use there an available folder or you can create an own folder with your own svg.
Sure, for one svg symbol you must have a little bit time to do this, but for the future it is a good investment.

Greetings

[kreis.zip](https://github.com/tomchadwin/qgis2web/files/3775609/kreis.zip)

**Comment by riccardoklinger** [comment]
hey @febriansusanta is your issue still valid and not resolved? If so, please reopen this ticket. I will close this for the moment.

Best, Riccardo

**Comment by viktorjracz** [comment]
Hello,

I am using QGIS 3.10.4, qgis2web 3.12.1 on a Mac. 
I have experienced the same issue: basemap layer is not visible in the layer and groups list.
Furthermore, when I run qgis2web I get a "Broken Pipe (Errno 32)" error message. I have tried with and without Match project CRS and both Openlayers and Leaflet.

Could you please help me what can be the issue and how could I solve it?
Thank you very much in advance!

Best, Viktor

**Comment by viktorjracz** [comment]
Hello again, 

I have found the answer for the "missing" basemap layer issue (I am sorry, I just started using Github as well..), so I added a XYZ layer and it just works fine, thank you.

However, the problem with the "broken pipe" still exists. Could you please help me with that? Thank you.

Best, Viktor
