### ISSUE TITLE
geolocation symbol not show on android mobile

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#817]
Hello,
the fontawesome marker of the geolocation plugin is not shown on my android tablet (chrome). But only with maps from qgis2web / leaflet. Demo from leafletjs is ok (https://www.domoritz.de/leaflet-locatecontrol/demo/)
On PC all OK.
Function is also for mobile OK.
Here the "screenshot":
![geolocation](https://user-images.githubusercontent.com/31866672/67275131-3c0f9e00-f4c2-11e9-9ce6-4d3555fcc67e.jpg)
What could be the reason?
Greetings

QGIS 2.18.28
qgis2web 2.34

edit:
QGIS 3: all OK - but I NEED it for QGIS 2 !!

**Comment by jukos** [comment]
Hello Tom,
I have found the solution.
**Could you please change this code:**

http://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
to
http**s**://maxcdn.bootstrapcdn.com/font-awesome/**4.7.0**/css/font-awesome.min.css"

Important here is the missing "s" in https.

I know it is for qgis2web. Please change it. It is possible to change the code after export, but it is better to have a new qgis2web version for qgis2.

Thank you and greetings

**Comment by tomchadwin** [comment]
I didn't realize this was for qgis2web 2. This is now unsupported- the fix has already been made for qgis2web 3. I am aware that you need to use v2 until images in popups are fixed. However, I'm afraid this won't be fixed.

**Comment by jukos** [comment]
OK. Thank you for response.
I am looking forward to the new improved qgis2web for qgis3.
Greetings
