### ISSUE TITLE
Unavailable templates

### ISSUE THREAD

**Issue by danielchoperena** [tomchadwin/qgis2web#818]
Hi!, I was doing a web map using this amazing tool, unfortunately, I couldn't add a template layer (OSM). I the previous version we can do it just clicking on the option. :C

Please help me. This is for a high school homework. :C 

In the "help" option, It says that I can Add in "qgis2/template", but I do not know what kind of file, or where to find this folder :( 

Please help me. :( 

![Sin título](https://user-images.githubusercontent.com/56658143/67497338-718fc500-f643-11e9-8c57-abfc1282dabe.png)
![Sin título22](https://user-images.githubusercontent.com/56658143/67497340-72285b80-f643-11e9-85b4-cc01e73325a7.png)

**Comment by tomchadwin** [comment]
Do you mean basemaps? If so, add an XYZ layer to QGIS, and it will export.

**Comment by tomchadwin** [comment]
Closing without further feedback.
