### ISSUE TITLE
Scale-dependent visibility in Leaflet

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#82]
To achieve this, I need to convert QGIS scales to Leaflet zoom levels. Anyone know how to do this?

**Comment by tomchadwin** [comment]
Done in master, released as 0.16.0 and pushed to QGIS plugin repo

**Comment by Polperobis** [comment]
As a new user, I'm not sure to well understand this closed issue. Does it means that it's impossible to use the scale-dependent visibility with the leaflet layer ?

**Comment by tomchadwin** [comment]
@Polperobis No no - it works. Set your scale-dependent visibility levels in QGIS, and the exported webmap will automatically use them.

**Comment by Polperobis** [comment]
So I think I have a bug. When I set the scale-dependent visibility for the leaflet layer the scale-dependent is disabled for all layer when I export with Q2W.

**Comment by tomchadwin** [comment]
Can you zip together all the files of your exported webmap, and drag-and-drop them into a comment on this thread?

**Comment by tomchadwin** [comment]
I think you're right - looks like a bug with scale-dependent visibility for *raster* layers specifically. I'll investigate when I can. Thanks!

**Comment by Polperobis** [comment]
Thank you for investigating ! Do you think it's possible to manually modify the index.html file to get around the issue ?

**Comment by Polperobis** [comment]
It works ! Thanks
