### ISSUE TITLE
leaving out records in category symbolization gives blue maps

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#822]
Hi Tom,

I am still having some issues with Categorization symbology.
See also #533 and maybe #524, #746 and #766 
See attached zip for testing.
[testpaw.zip](https://github.com/tomchadwin/qgis2web/files/3784083/testpaw.zip)

Choosing symbolisation using field paw18_status and click classification, you will get three categories. Then create the webmap (Leaflet), everything is fine. 
When you delete the third line within the classification (the 'empty' or ELSE lline) Q2W is showing those 'left-out' records in blue.

The thing that throws me off is QGIS working differently from Q2W:
The left-out records are not rendered in QGIS, I can't click on them, I can't get info on them, QGIS seems to ignore these records. If they don't fit within a category, the don't exist in my map.

Q2W doesn't ignore those records.
And this is not a NULL issue. The same thing applies to a layer consisting of only records with values.
QGIS always creates an 'ELSE' category, even when there are no records that match ELSE. Removing one of the categories those records will then be part of ELSE and Q2W works perfectly. Removing also the ELSE category will result in the blue records.
Removing just the ELSE category, Q2W works perfecrtly, because all records fit within a category.

So, for Q2W every record needs to fit within a category. For QGIS, it doesn't.

To circumvent this, if I want to just show the records with certain values I have to create a different layer, for example using sql to select just those records that have the correct values. That has its benefits and its drawbacks.

Is there any other solution?

**Comment by tomchadwin** [comment]
This is because Leaflet's default style is the blue. In other words, if you provide no style yourself in a Leaflet map, it uses blue. If you delete a category, no styling info for that category will be exported, and the blue will replace it. Does that make sense? I don't think a change in qgis2web is required, and one which covered all possible missing categories could be tricky to code.

**Comment by Jeroen-GroeneBij** [comment]
Ah, that clarifies it. I didn't know this about Leaflet. 
This means I will have to build my maps in a different way. That is build it with this Leaflet behaviour in mind, in stead of relying on the visual result I see in QGIS.
