### ISSUE TITLE
QGIS stalls when calling qgis2web

### ISSUE THREAD

**Issue by tammojan** [tomchadwin/qgis2web#825]
I installed qgis2web and tried to export my rather large project (many features). The first time the qgis2web interface opened fine, but stalled on exporting. I killed qgis and started anew. Now when I press qgis2web in the qgis menu, qgis stalls immediately, I get the spinning beachball and cannot interact with QGIS anymore.

I already tried uninstalling and reinstalling the plugin, but that did not solve the issue.

Is there a hidden cache somewhere that I need to clear before properly reinstalling?

I'm using QGIS 3.8, with the latest version of qgis2web (as installed through the plugins manager).

**Comment by tomchadwin** [comment]
I suspect that the preview window is trying to display your map, and stalling for the same reasons as your initial export. You possibly need to reset a saved QGIS setting (set by QGIS).

In QGIS, go to Settings > Options > Advanced (click the warning button to enable access, but heed the warning, and change nothing else). Expand the qgis2web folder, and look for the option `previewOnStartup`. Double-click the value, and change it to 0.

Let us know if that works.

**Comment by tammojan** [comment]
Thanks for the quick reply! I cannot find a qgis2web folder in the advanced settings list, while the plugin is installed (according to the plugin manager).

**Comment by tammojan** [comment]
I opened a much simpler project, in which the preview did appear. In that GUI I could disable the preview. So problem fixed, thanks for your pointers.
