### ISSUE TITLE
basemaps change design

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#830]
Hello,
it is possible to change the design (for example brightness) of basemaps, for example openstreetmap or others?
I can only change the opacity, but not more.
Is the only way to use the plugin Leaflet.TileLayer.ColorFilter?
(my first try: no success....)
Greetings, Jürgen

**Comment by jukos** [comment]
Have found a solution.
For others:
With the plugin Leaflet.TileLayer.ColorFilter:

1. insert the js file
2. change the index.html file:
a) insert the link to the js file
`<script src="js/leaflet-tilelayer-colorfilter.min.js"></script>`
b) insert, what do change with the design,
for example
```
let defaultToDarkFilter = [
        'grayscale:80%',
        'invert:0%',
    ]
```
c) **change** the basmap layer, here a openstreetmap layer to:
```
var layer_openstreetmap_0 = L.tileLayer**.colorFilter**('http://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png', {
            opacity: 1.0,
            attribution: '',
            minZoom: 1,
            maxZoom: 28,
            minNativeZoom: 0,
            maxNativeZoom: 18**,
        filter: defaultToDarkFilter
    }).addTo(map)**;	
```

**Comment by tomchadwin** [comment]
Nice solution. Other than creating your own amended tiles, I know of no other way, so I'll close this. Thanks!
