### ISSUE TITLE
Hyperlink of PDF files in QGIS2WEB

### ISSUE THREAD

**Issue by EsmH** [tomchadwin/qgis2web#831]
I have attached some pdf files in some features by using QGIS 3.8. 
![1](https://user-images.githubusercontent.com/32569479/68207908-4eb0c980-ffd0-11e9-80c4-be7a739d2efc.png)

The hyperlink works in QGIS :
![2](https://user-images.githubusercontent.com/32569479/68208260-1958ab80-ffd1-11e9-89dc-3e7cf89e5dc8.png)

When I export it with qgis2web (as Leaflet) the hyperlink does not appear.
![3](https://user-images.githubusercontent.com/32569479/68208622-dcd97f80-ffd1-11e9-895f-745599a75211.png)

![4](https://user-images.githubusercontent.com/32569479/68208632-e19e3380-ffd1-11e9-9f3f-fef0757d7ea1.png)

I have copied the folder "Hyperdokumente" in the same folder as index.html file. but nothing was done. 

![5](https://user-images.githubusercontent.com/32569479/68208690-02668900-ffd2-11e9-9731-8f42a0699374.png)

Can anyone help me, please?

**Comment by tomchadwin** [comment]
Edit widget type "Attachment" won't work here - qgis2web is not coded to handle it in this way. Can you use a Text Edit widget instead? Handling this properly, including copying over the files, would be a nice new feature, but it's not there yet.

**Comment by EsmH** [comment]
Thank you. I didn't know it. I found your answer for something similar here: https://tutel.me/c/gis/questions/221893/register.html#
How can I edit the index.html code to access pdf files, please?

**Comment by tomchadwin** [comment]
You don't need to edit the index.html file if you change the edit widget type as I described above.

**Comment by EsmH** [comment]
Thank you. It worked, buy adding this : <a target="_blank" href="./Hyperdokumente/Bayern/Kolbermoor/Grundbuchauszug/Grundbuch_Nr_10786.pdf">Open pdf</a> in an attribute table field.

**Comment by tomchadwin** [comment]
Great - glad you got it sorted, and thanks for reporting back.

**Comment by lemfor** [comment]
how did you  attached some pdf files in some features by using QGIS ?

**Comment by toledoassessorsoffice** [comment]
hello please help me. my pdf attachment wont show. what should i do?
![image](https://user-images.githubusercontent.com/116332885/215394131-9910462d-2768-4be9-8935-4b81d49ce51d.png)

**Comment by toledoassessorsoffice** [comment]
what setting should i use?
![image](https://user-images.githubusercontent.com/116332885/215394259-a0500743-c78a-4199-8ae8-881f73c074b2.png)
