### ISSUE TITLE
rgba (alpha) problem in preview and export

### ISSUE THREAD

**Issue by jipexu** [tomchadwin/qgis2web#835]
Hi
(in 3.10 version for openlayer export)
If i use a layer with a simple fill with for example opacity 6%
this x value become 1.0 (for alpha value) in preview and in the layer_style.js file
so in the preview and style file is always the good color but with 100% opacity ....

```
    var style = [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(0,0,0,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 1}),fill: new ol.style.Fill({color: 'rgba(0,0,0,1.0)'}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })];
```

of course if i change again this alpha in the layer style file value its ok  ...

Thanks

**Comment by tomchadwin** [comment]
One of the complications is the number of different places in which opacity can be set. In your case, are you setting 6% opacity:

- for the layer
- for the symbol
- only as part of the fill colour (and/or stroke colour, etc)

Not all of these are handled by qgis2web, so if you can let us know which you want/need, we can look at either fixing it (if it is implemented but broken), or adding in support for it.

**Comment by jipexu** [comment]
@tomchadwin thanks

It is not very important it just for notified this behavior .... because i use often a lower opacity instead of transparency to have a better contexte to use popup ...

is it is this dialog box ..

<img width="835" alt="Capture d’écran 2019-11-11 à 13 14 36" src="https://user-images.githubusercontent.com/328101/68586665-721ebd00-0485-11ea-9b58-cd1baf12eb65.png">

**Comment by tomchadwin** [comment]
I'll look at this when I can. Thanks for your patience.

**Comment by jipexu** [comment]
👍 no worry it's a "detail"

**Comment by riccardoklinger** [comment]
Use the "Rendu de couche"  option in the symbology tab and set the value to 6%. 
<img width="828" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79387809-9b7bd180-7f6c-11ea-8058-0c148495fbac.png">
works like a charm in leaflet:
<img width="1438" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79387885-b3535580-7f6c-11ea-84b0-a19861bb9536.png">
and openlayers:
<img width="1443" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79387917-c1a17180-7f6c-11ea-934b-3bea01830c58.png">

**Comment by riccardoklinger** [comment]
will close this. if you want to discuss switching to another approach on where and how to read opacity settings, please open another issue.

**Comment by jipexu** [comment]
@riccardoklinger thank for the tip...i probably miss something but if i apply this way i lost the borders ... as you see on this screenshot

with 6% on the symbol (my borders stay visible)
<img width="687" alt="Capture d’écran 2020-04-16 à 13 16 17" src="https://user-images.githubusercontent.com/328101/79450478-3a441480-7fe5-11ea-8567-60568b7105a1.png">
with 6% on the rendu (no more borders visible)
<img width="687" alt="Capture d’écran 2020-04-16 à 13 17 31" src="https://user-images.githubusercontent.com/328101/79450385-2698ae00-7fe5-11ea-87ce-187e098b4359.png">
