### ISSUE TITLE
Leaflet.OpacityControls working/how to use?

### ISSUE THREAD

**Issue by KoalaGeo** [tomchadwin/qgis2web#837]
Hi, 

I'd like to have an opacity slider for one of the layers in my map, is this functionality in QGIS2Web or do I need to code manually after export? 

Thanks

**Comment by tomchadwin** [comment]
I'm afraid there's no built-in qgis2web functionality for this. You will therefore have to add it in to the code yourself after export.

**Comment by KoalaGeo** [comment]
Ok, thanks for getting back to me.
