### ISSUE TITLE
Failure to export multisurface layer or layer with no CRS assigned from PostGIS

### ISSUE THREAD

**Issue by NyakudyaA** [tomchadwin/qgis2web#838]
# Problem

I have a multi surface layer loaded in QGIS a when I try to export it to a web map using leaflet it just fails with the following message.
 
Multi Surface
![multi](https://user-images.githubusercontent.com/2510900/69225748-a0885080-0b87-11ea-9b27-1c7da6fc6e7f.png)

![export-fails](https://user-images.githubusercontent.com/2510900/69225702-851d4580-0b87-11ea-9fd0-945c41d23fc0.png)

This error also occurs when I have a layer with no SRID assigned from the Postgres.

**Comment by boesiii** [comment]
Can you send a screen shot of the error message?  I am not sure what type of layer is multisurface but I don't think the plugin can handle that type of layer.  Can you send a sample of the multisurface data?  Try to export that layer to a shapefile and then try and use it with the plugin.

**Comment by riccardoklinger** [comment]
@NyakudyaA unfortunately we haven't heard back from you. I'll close this now. If you want to share the screenshot, please reopen the ticket.
