### ISSUE TITLE
Error occuring while executing Python Code

### ISSUE THREAD

**Issue by catlaidlaw** [tomchadwin/qgis2web#839]
When exporting a map (either as OpenLayers or Leaflet) I receive ' Python KeyError: 12' quite a lot. It seems to relate to any layers I've originally got the data from a WMS/WFS and then exported the features to a Geopackage or Shapefile. I'm not a programmer unfortunately, and so would someone be able to explain what the error means, why it occurs when exporting via QGIS2web but not in pdfs, svgs etc, and if there's anyway I can resolve it?

Many thanks in advance.
![KeyError 12](https://user-images.githubusercontent.com/49450732/69711889-bfdc2c00-10f9-11ea-85f1-0abf28bb992f.jpg)

**Comment by boesiii** [comment]
It does not like one of your layers.  Are you able to upload a sample of your date and a Qgis project file?

**Comment by riccardoklinger** [comment]
as you've mentioned some WFS/WMS services, please share the links as @boesiii suggested. also add the qgis2web version your are using in qgis 3.10.0 
The Wkbtype is a category for the type of layer we are exporting. you can see a list here:
TYPE_MAP = {
    QgsWkbTypes.Point: 'Point',
    QgsWkbTypes.Point25D: 'Point',
    QgsWkbTypes.PointZ: 'Point',
    QgsWkbTypes.PointM: 'Point',
    QgsWkbTypes.PointZM: 'Point',
    QgsWkbTypes.LineString: 'LineString',
    QgsWkbTypes.LineStringM: 'LineString',
    QgsWkbTypes.LineStringZ: 'LineString',
    QgsWkbTypes.LineStringZM: 'LineString',
    QgsWkbTypes.LineString25D: 'LineString',
    QgsWkbTypes.CircularString: 'LineString',
    QgsWkbTypes.CircularStringZ: 'LineString',
    QgsWkbTypes.CircularStringM: 'LineString',
    QgsWkbTypes.CircularStringZM: 'LineString',
    QgsWkbTypes.CompoundCurveZ: 'LineString',
    QgsWkbTypes.CompoundCurveM: 'LineString',
    QgsWkbTypes.CompoundCurveZM: 'LineString',
    QgsWkbTypes.MultiLineStringZ: 'LineString',
    QgsWkbTypes.MultiLineStringM: 'LineString',
    QgsWkbTypes.MultiCurve: 'LineString',
    QgsWkbTypes.MultiCurveM: 'LineString',
    QgsWkbTypes.MultiCurveZ: 'LineString',
    QgsWkbTypes.MultiCurveZM: 'LineString',
    QgsWkbTypes.Polygon: 'Polygon',
    QgsWkbTypes.PolygonZ: 'Polygon',
    QgsWkbTypes.PolygonM: 'Polygon',
    QgsWkbTypes.PolygonZM: 'Polygon',
    QgsWkbTypes.Polygon25D: 'Polygon',
    QgsWkbTypes.CurvePolygon: 'Polygon',
    QgsWkbTypes.CurvePolygonZ: 'Polygon',
    QgsWkbTypes.CurvePolygonM: 'Polygon',
    QgsWkbTypes.CurvePolygonZM: 'Polygon',
    QgsWkbTypes.MultiPolygonZ: 'Polygon',
    QgsWkbTypes.Triangle: 'Polygon',
    QgsWkbTypes.TriangleZ: 'Polygon',
    QgsWkbTypes.TriangleM: 'Polygon',
    QgsWkbTypes.TriangleZM: 'Polygon',
    QgsWkbTypes.MultiPoint: 'MultiPoint',
    QgsWkbTypes.MultiPoint25D: 'MultiPoint',
    QgsWkbTypes.MultiPointZ: 'MultiPoint',
    QgsWkbTypes.MultiPointM: 'MultiPoint',
    QgsWkbTypes.MultiPointZM: 'MultiPoint',
    QgsWkbTypes.MultiLineString: 'MultiLineString',
    QgsWkbTypes.MultiLineStringM: 'MultiLineString',
    QgsWkbTypes.MultiLineStringZ: 'MultiLineString',
    QgsWkbTypes.MultiLineStringZM: 'MultiLineString',
    QgsWkbTypes.MultiLineString25D: 'MultiLineString',
    QgsWkbTypes.MultiPolygon: 'MultiPolygon',
    QgsWkbTypes.MultiPolygon25D: 'MultiPolygon',
    QgsWkbTypes.MultiPolygonZM: 'MultiPolygon',
    QgsWkbTypes.MultiPolygonM: 'MultiPolygon'}
As you're receiving a "keyError" 12 means, we cannot find a suitable entry in this list for the specific layer.
Though as I looked up this "12" it showed me, that this was listed as a RGBType layer. So we need to find out, how your project looks like and which layer is creating the problems. Otherwise we can't move on with providing a fix.

**Comment by riccardoklinger** [comment]
seems like OC has no further interest in solving this issue. WOuld close this now. If someone disagree, please reopen.

**Comment by denmur** [comment]
Hello! I have the same issue.
Could you help me please?

```
An error has occurred while executing Python code: 

KeyError: 12 
Traceback (most recent call last):
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 131, in writeOL
    popup, json, restrictToExtent, extent, feedback, matchCRS)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 232, in exportLayers
    iface, extent, precision, crs, optimize)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 245, in exportVector
    cleanLayer = writeTmpLayer(layer, restrictToExtent, iface, extent)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 172, in writeTmpLayer
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 12


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.10-Hannover Hannover, e5b665e952 

Python Path:
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HTML_Generator-main
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\...\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\...\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
U:...
```
