### ISSUE TITLE
QGIS crashes when qgis2web plugin is opened

### ISSUE THREAD

**Issue by bmou464** [tomchadwin/qgis2web#840]
I have just recently installed the plugin on qgis 3.4.4. Every time I want to open the plugin I get a crash report:
-------------------------------------------------------------------------------------------------
Crash ID: a59a1ac8af962d593a5aa733b651ccd9dd52721c

Stack Trace

ShCompile :

QGIS Info
QGIS Version: 3.4.4-Madeira
QGIS code revision: af723c4942
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: i386
Kernel Type: winnt
Kernel Version: 6.1.7601
--------------------------------------------------------------------------------------------
I don't get any other error messages. 
My project only contains one layer as a GeoPackage. It is a vector layer (polygon). In the project properties I have enabled WFS properties.

the error:
![afbeelding](https://user-images.githubusercontent.com/12115380/69922894-6a5ca200-14a0-11ea-9d0c-e212001a2f33.png)

My settings:
![afbeelding](https://user-images.githubusercontent.com/12115380/69922924-9e37c780-14a0-11ea-8673-a2174cc30ccd.png)

My project and data:
[qgis_server.zip](https://github.com/tomchadwin/qgis2web/files/3908926/qgis_server.zip)

Can anyone help me to fix this?

Thanks,
Bart

**Comment by tomchadwin** [comment]
I can't recreate the problem, I'm afraid. The plugin opens and previews without a crash. I am on 3.10, not 3.4, so all I can suggest in the first instance is to upgrade QGIS if you can. Does the crash occur with different data/project loaded?

Can anyone else recreate this issue?

**Comment by bmou464** [comment]
I have upgraded to 3.8.3-Zanzibar (somehow 3.10 wouldn't install), and I have the same problem. This time the plugin opens for about 1 second and then I get the same crash report.

**Comment by boesiii** [comment]
Are you using Qgis Desktop or Qgis Server?  Try using the plugin with some of the Qgis sample data from a shapefile.  You can downoad some sample data from this repo.
https://github.com/tomchadwin/qgis2web/tree/master/qgis2web/test/data/layer

**Comment by bmou464** [comment]
I have downloaded the data and tried it with that data, but with the same result:
![afbeelding](https://user-images.githubusercontent.com/12115380/70064288-946dab80-15e9-11ea-82d5-5421b3ceb6f6.png)

**Comment by boesiii** [comment]
Are you using Qgis Desktop or Qgis Server?

**Comment by bmou464** [comment]
I am using Qgis Desktop.

**Comment by boesiii** [comment]
I am using Qgis 3.4.12 and I am able to load your data and export without an issue.  What version of Windows?  What version of the plugin are you using, the latest is 3.11.0?

Try installing Qgis 3.4.12 and also upgrade your plugin version to the latest.

**Comment by bmou464** [comment]
I am using the latest version of the plugin (3.11.0). I have installed Qgis 3.14.12. I still get the same crash report. I am using Windows 7 on a 32 bit computer. These are the specs:
![afbeelding](https://user-images.githubusercontent.com/12115380/70110116-332bf380-164e-11ea-89df-94904e1f9077.png)

I'm a bit flabbergasted by this, I haven't got a clue why this keeps happening ?!!

**Comment by boesiii** [comment]
Do other plugins work on your system?

**Comment by riccardoklinger** [comment]
I can't recreate the issue as well. sample project from OP works well in 3.4.10 and latest master.
would close this now as it can't be recreated. I would assume, it is an issue with the 32bit system, but that is just a thought.

**Comment by bmou464** [comment]
ok to close the issue, it doesnt seem this can be solved.

Op za 7 dec. 2019 10:56 schreef Riccardo Klinger <notifications@github.com>:

**Comment by boesiii** [comment]
I installed a Windows 7 32 bit virtual machine and installed Qgis 3.4.13 32 bit.  I could not recreate this issue either.

**Comment by NikosGavriilatos** [comment]
Am on Windows 11, and I have the same problem. I will try again on virtual machine, because I have reasons to believe that this a Windows configuration issue.

**Comment by andreaordonselli** [comment]
have you updated qgis and qgis2web to the latest versions?
have you installed qgis2web from the qgis plugin repository?
