### ISSUE TITLE
Feature Request: Mapbox JS Dynamic Legend

### ISSUE THREAD

**Issue by Kapanther** [tomchadwin/qgis2web#841]
Mapbox JS implementation is so nice.. Would love to have a legend that allows layers to be turned on and off though. Is this possible already or not implemeneted?

**Comment by tomchadwin** [comment]
No layer control/legend implemented at the moment, I'm afraid. Agree that this should probably be a priority.

**Comment by tomchadwin** [comment]
@Kapanther Can you test master branch? I've added initial support for a layers list in Mapbox GL JS exports. Not ready for release yet, as some cosmetic issues to fix:

- zoom controls overlapping layers list
- list uses unfriendly layer names, not human-readable ones

Let me know how it works for you.

**Comment by tomchadwin** [comment]
Layout glitches fixed - please test and report back. Thanks.

**Comment by tomchadwin** [comment]
Initial click fixed, width limitation removed, and text alignment improved.

**Comment by Kapanther** [comment]
@tomchadwin will check it out.. Nice work..
