### ISSUE TITLE
Probably broken hash function in new version of qgis2web

### ISSUE THREAD

**Issue by kelv-cz** [tomchadwin/qgis2web#842]
Exported maps have broken hash function (leaflet). Zoom or position change in URL is default after page reload or in link. 
Example: http://worldofdrupal.drobnepamatky.cz/ after position change on: #8/49.273/7.806 and page reload is it back on default #2/-9.4/4.1.

**Comment by tomchadwin** [comment]
Probably an incompatibility with an old version of Leaflet.Hash. Needs investigation.

**Comment by riccardoklinger** [comment]
works fine 3.11.0 in QGIS 3.4.10
will check with latest master

**Comment by riccardoklinger** [comment]
works well with master on a local host. @kelv-cz please check, whether url-rewrite is possible on your server.
Works well on my server... http://h2857527.stratoserver.net/canadaexample/index.html#6/64.741/-153.259 
will close this now as it cannot be re-created. reopen with valuable information if you like.
