### ISSUE TITLE
qgis2web base maps option not showing using qgis3

### ISSUE THREAD

**Issue by JonHall1965** [tomchadwin/qgis2web#847]
I'm using qgis2web on qgis 3.0 - the option to display the base raster map under the preview screen at the bottom right of the tab is not showing.

**Comment by riccardoklinger** [comment]
yes, you need to add a basemap in your project itself. this basemap will be used in qgis2web as well. easiest option to add a basemap: quickmapservices plugin
does this help?

**Comment by boesiii** [comment]
OpenStreetMap can also be easily added by using the Browser Panel - > XYZ Tiles -> OpenStreetmap
Right click -> add selected layer to canvas
![background maps](https://user-images.githubusercontent.com/2079638/71680040-0a834080-2d57-11ea-863f-5e35c94b8843.PNG)

**Comment by tomchadwin** [comment]
To clarify, there used to be a list of preselected basemaps available in the qgis2web GUI. When QGIS started to support XYZ tle layers, we removed the preconfigured basemaps. As @riccardoklinger and @boesiii describe, you can now add any  basemap to your QGIS project and it will be exported.

**Comment by driansmith** [comment]
![desktop-map](https://user-images.githubusercontent.com/38726678/99409831-b3904680-28e9-11eb-855f-01e2c605b099.GIF)

Generating a webpage from a map always elevates the basemap from the bottom (within the QGIS Project) to the top (on the webpage map). This means the additional layers can never be overlaid to fully appreciate the map. Can anyone help please? 

![webpage-map](https://user-images.githubusercontent.com/38726678/99409905-c9057080-28e9-11eb-9161-6b274a3e3ca6.GIF)
No matter what i do, I cannot get the basemap to sit at the bottom of the webpage layers.

**Comment by joooeey** [comment]
Are there any technical differences between XYZ tiles and QuickMapServices? Is one of them faster?

**Comment by wstaelens** [comment]
> 

i have the same problem!
