### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'settings' 

### ISSUE THREAD

**Issue by jipexu** [tomchadwin/qgis2web#848]
Hi
with the last versions QGIS 3.10.1 and qgis2web 3.12.0  i now get for several layers this type of error
the preview in qgis doesn't work and the exported map is broken too ...

```
getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
```
`
Exception in layer bassin_091562d6_962c_4f85_b52a_ee5a67c916df with renderer SINGLE: FILL SYMBOL (1 layers) color 53,121,177,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 

it's seems that happens with layers who have no-labels (none) ... 
so the exported style files for the concerned layers are corrupted
...sorry  i am absolute beginner with PY  so i can not help more....

**Comment by tomchadwin** [comment]
Thanks for reporting this: you are completely right, and it's a really bad regression. I've made a change to master here to fix the issue. Could you test, and report back? And can others? Thanks!

**Comment by jipexu** [comment]
let me understand how i can test without a new version ... must i change some files in the qgis2web folder

**Comment by tomchadwin** [comment]
Apologies, yes. Download master branch from this repo (the green `Clone or download` button on the repo home page), and extract the files in the zip. Copy all the contents of the extracted folder `qgis2web-master` into your folder `~/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/`. Restart QGIS, and then try your qgis2web export again, to see whether the fix has worked.

**Comment by jipexu** [comment]
great !! thanks yes seems to work as previous now !!  i go ahead to see more ...

**Comment by tomchadwin** [comment]
Great! Thanks for testing and reporting back. I'll make a patch release with the fix as soon as I can.

**Comment by jipexu** [comment]
still have this probleme with the layers opacity but this is an other story ...
