### ISSUE TITLE
FIX TRAVIS

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#849]
Travis has not been working for a good while now. While other issues might be present, the one top of the list is this: `pycodestyle` is flagging the `bridgestyle` code as not PEP8-compliant.

This is now an urgent issue. It seems that the latest release contained a serious regression (#848). This would have been flagged by Travis, and the issue fixed before release.

So, can anyone help with the following:

- stop `pycodestyle` from checking `bridgestyle`

If we can't do that, then we'll just have to ditch PEP8 and `pycodestyle` completely. I really don't want to do that, as code legibility and quality is an absolute necessity to encourage contributions from other devs.

**Comment by tomchadwin** [comment]
I think it's up and running now. A bit baffled as to why I couldn't sort this before, but it seems to be working with `bridgestyle` added to the `exclude` switch for `pycodestyle`.

**Comment by tomchadwin** [comment]
Any ideas what is causing this `bridgestyle` import error in qgis2web Travis tests, @volaya:

https://travis-ci.org/tomchadwin/qgis2web/jobs/636357195#L663

I think it's the last problem I've got before Travis is fully working again.

**Comment by jipexu** [comment]
Hi
i dont known if my test is good (i have just change this file  ~/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/__init__.py) ?

i havnt no more the error for no labelled layer  but still  have some errors :



Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting World heritage South China Karst to JSON... done
Exporting World heritage South China karst to JSON... done
Exporting Karsts to JSON... done
Exporting Rivières to JSON... done
Exporting Bassins versants to JSON... done
Exporting Bassin versants to JSON... done
Exporting districts to JSON... done
Exporting prefectures to JSON... done
Exporting provinces to JSON... done
Exporting grottes to JSON... done done
Exception in layer WDPA_Nov2019_protected_area_903131_shapefile_polygons_9772c136_c237_456e_9f8a_61c39c3228ef with renderer SINGLE: FILL SYMBOL (1 layers) color 227,26,28,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Exception in layer world_heri_china_karst20120713222908499 with renderer SINGLE: MARKER SYMBOL (1 layers) color 219,30,42,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Exception in layer karsts20120712092951081 with renderer SINGLE: FILL SYMBOL (1 layers) color 145,35,145,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Exception in layer riviere20120711155355403 with renderer SINGLE: LINE SYMBOL (1 layers) color 49,136,255,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Exception in layer bassins_versants20120711155355927 with renderer CATEGORIZED: idx ENAME Alxa River::Alxa River::FILL SYMBOL (1 layers) color 0,0,255,255:1 Baicheng River::Baicheng River::FILL SYMBOL (1 layers) color 5,5,255,255:1 Dulong River - Irrawaddy River::Dulong River - Irrawaddy River::FILL SYMBOL (1 layers) color 11,11,255,255:1 Dzungarian::Dzungarian::FILL SYMBOL (1 layers) color 17,17,255,255:1 Erdos River::Erdos River::FILL SYMBOL (1 layers) color 23,23,255,255:1 Hai River::Hai River::FILL SYMBOL (1 layers) color 29,29,255,255:1 Heilong River::Heilong River::FILL SYMBOL (1 layers) color 35,35,255,255:1 Huai River::Huai River::FILL SYMBOL (1 layers) color 41,41,255,255:1 Ili River::Ili River::FILL SYMBOL (1 layers) color 47,46,255,255:1 Inner Mongolia River::Inner Mongolia River::FILL SYMBOL (1 layers) color 53,52,255,255:1 Irtysh River::Irtysh River::FILL SYMBOL (1 layers) color 59,58,255,255:1 Lancang River - Mekong River::Lancang River - Mekong River::FILL SYMBOL (1 layers) color 65,64,255,255:1 Liao River::Liao River::FILL SYMBOL (1 layers) color 70,70,255,255:1 Liaodong Peninsula::Liaodong Peninsula::FILL SYMBOL (1 layers) color 76,76,255,255:1 Liaoxi and Hebei Coastal::Liaoxi and Hebei Coastal::FILL SYMBOL (1 layers) color 82,82,255,255:1 Luan River::Luan River::FILL SYMBOL (1 layers) color 88,87,255,255:1 Nu River - Salween River::Nu River - Salween River::FILL SYMBOL (1 layers) color 94,93,255,255:1 Pearl River::Pearl River::FILL SYMBOL (1 layers) color 100,99,255,255:1 Qaidam::Qaidam::FILL SYMBOL (1 layers) color 106,105,255,255:1 Qangtang::Qangtang::FILL SYMBOL (1 layers) color 112,111,255,255:1 Sen Ge Zang Bu River - Indus River::Sen Ge Zang Bu River - Indus River::FILL SYMBOL (1 layers) color 118,117,255,255:1 Shandong Peninsular::Shandong Peninsular::FILL SYMBOL (1 layers) color 124,123,255,255:1 South Tibet::South Tibet::FILL SYMBOL (1 layers) color 130,128,255,255:1 Southeast China Coastal::Southeast China Coastal::FILL SYMBOL (1 layers) color 136,134,255,255:1 Southeast Qiong, Lei and Gui Coastal::Southeast Qiong, Lei and Gui Coastal::FILL SYMBOL (1 layers) color 141,140,255,255:1 Suifen River::Suifen River::FILL SYMBOL (1 layers) color 147,146,255,255:1 Tarim::Tarim::FILL SYMBOL (1 layers) color 153,152,255,255:1 Tumen River::Tumen River::FILL SYMBOL (1 layers) color 159,158,255,255:1 Upper Yangtze River::Upper Yangtze River::FILL SYMBOL (1 layers) color 165,164,255,255:1 Wuyuer River::Wuyuer River::FILL SYMBOL (1 layers) color 171,169,255,255:1 Yalu River::Yalu River::FILL SYMBOL (1 layers) color 177,175,255,255:1 Yangtze River::Yangtze River::FILL SYMBOL (1 layers) color 183,181,255,255:1 Yarlung Zangbo River - Ganga River::Yarlung Zangbo River - Ganga River::FILL SYMBOL (1 layers) color 189,187,255,255:1 Yellow River::Yellow River::FILL SYMBOL (1 layers) color 195,193,255,255:1 Yuan River - Red River::Yuan River - Red River::FILL SYMBOL (1 layers) color 201,199,255,255:1 : Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Exception in layer bassin_091562d6_962c_4f85_b52a_ee5a67c916df with renderer SINGLE: FILL SYMBOL (1 layers) color 53,121,177,255: Traceback (most recent call last): File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 173, in getLabelFormat color = layer.labeling().settings().format().color().name() AttributeError: 'NoneType' object has no attribute 'settings' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to /Users/jpb/Documents/Chine

**Comment by tomchadwin** [comment]
Fixed at last via https://github.com/tomchadwin/qgis2web/commit/0cf98018fab9298cd723d2af7b2f14bda3e36cee, thanks to suggestion from @metazool at FOSS4GUK 2019. I added the path where Travis installs qgis2web to PYTHONPATH.
