### ISSUE TITLE
Basemap not loading when export to Mapbox GL JS, sort of...

### ISSUE THREAD

**Issue by jmg0** [tomchadwin/qgis2web#850]
Hi, I am using QGIS 3.4.14-Madeira and qgis2web 3.12.1.

I have exported my map (only two layers-features and the basemap) separately as OpenLayers, Leaflet, and Mapbox GL JS. For all three cases, when I open the local index.html in my browser, everything appears as it did in QGIS (all the features are visible and the basemap is there). I then loaded the files to Github (as in, I uploaded all of the files from the folder created by the qgis2web export), and turned on Github pages to access the maps as webpages. Everything appears for the OpenLayers and Leaflet versions, but the basemap is missing in the Mapbox GL JS version. All of the features are present, but no basemap. I have tried with Carto Dark Matter and Esri Gray (dark) basemaps, and neither work. I got these basemaps from the QuickMapServices plugin.

What am I missing here? Again, the basemaps are present in the Mapbox version when I load the local index.html file on my machine, but the basemap won't appear when I have the exact same files posted to Github pages. The basemaps work in the OpenLayers and Leaflet versions, just not with Mapbox.

I've attached screenshots of the map in QGIS, the local index.html file loaded in my browser, and then the same export files as rendered through Github pages.

Thanks for any help!

QGIS:
<img width="762" alt="ss1" src="https://user-images.githubusercontent.com/48111471/72863587-24051180-3c9f-11ea-9f57-5928fa765891.png">

Local index.html file loaded in browser:
<img width="1672" alt="ss2" src="https://user-images.githubusercontent.com/48111471/72863588-24051180-3c9f-11ea-9e98-cf916f1a12db.png">

Same files as loaded in Github pages:
<img width="1673" alt="ss3" src="https://user-images.githubusercontent.com/48111471/72863589-24051180-3c9f-11ea-9a38-cb0bf69b7e6a.png">

**Comment by tomchadwin** [comment]
Can you check your basemap URL in QGIS? Make sure it is https:// not http://.

Other than that, you'd have to let us know the Github Pages address for us to take a look.

**Comment by jmg0** [comment]
That did it. Thank you!
