### ISSUE TITLE
Version 3.12.1 slow for many points

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#852]
Hello,
I had installad the version 3.12.1 and now I have installed the version 3.11 again.
Reason: The preview and the export of point layers (cluster) with more than 50-100 points are very slowly. Please check this. 
Many points as cluster are normally no problem for qgis2web. For example I have a clusterlayer with more the 10000 (ten thousands) points with svg icon - but also fast.

Greetings, Jürgen

QGIS 3.4.15 Windows 10

**Comment by tomchadwin** [comment]
Which export format?

**Comment by jukos** [comment]
upps....leaflet

**Comment by tomchadwin** [comment]
The only Leaflet changes between those two versions are this commit:

https://github.com/tomchadwin/qgis2web/commit/c3d643da4eb5a3e8df02a11654be4e236ff3ad3e

This did the autotruncation of popup values (and updated Autolinker.js to achieve this). Can you try doing one of the slow exports in 3.12.1, but then editing `index.html` to get rid of the truncation code?

**Comment by jukos** [comment]
Thank you for response.
In a few hours, I'm gonna try that.

**Comment by jukos** [comment]
I have deleted all 
`, {truncate: {length: 30, location: 'smart'}}`
within  the index.html 
Result: no changes

The leaflet export with 3.11 project load with 1-2 seconds within the browser (firefox/chrome).
Export with 3.12.x loads more than 30 seconds, with or without the additional truncate code.
And:
There are a message from the firefox browser: "A web page slows down your browser."
This message I get only with the 3.12 export file.
Within the chrome browser I saw a short time "ogs.google". I do not know what this is.

**Comment by tomchadwin** [comment]
The only other change you could try to revert would be a little more complex:

- export both 3.11 and 3.12.1
- copy Autolinker.js from the 3.11 export to overwrite the 3.12.1

See if that gets rid of the delay.

**Comment by tomchadwin** [comment]
And the final thing to test is to do a 3.12.1 export *without* clustering, and see whether that speeds things back up. We just need to find out specifically what is causing the issue.

**Comment by jukos** [comment]
Result:
3.12.1 with autolinker 3.11, and with cluster: fast !! perfect (1-2 seconds for 11.000 points)
3.12.1 with autolinker 3.11, without cluster: same as with 3.11 (7 seconds with 11.000 points)

Summary:
**3.12.1 plus autolinker from 3.11: all ok (with or without cluster)**

Greetings

**Comment by tomchadwin** [comment]
Sorry: I meant that you should try a 3.12.1 export without cluster, without using 3.11 Autolinker.

**Comment by jukos** [comment]
Export 3.12.1 without cluster (without 3.11 autolinker): 3 min.
Firefox searched long for url "collector.githubapp.com"
Greetings

**Comment by cesarcorreo** [comment]
Maybe, not sure (and probably not) but 3.12.1 is very slow when you double click in a layer to open layer properties. I see that change updating from 3.10 to 3.12. We are talking about it in the spanish user group.

**Comment by tomchadwin** [comment]
It definitely sounds like there is a performance issue with the updated version of Autolinker.js. If anyone can confirm or deny this by doing both a 3.12 export and a 3.11 export, and then replacing the 3.12 copy of Autolinker with the 3.11 one, and then reporting whether that improves the speed back to 3.11 rates, then that would be great.

Minor note: you only need to single-click, not double-click. Double-clicking might trigger duplicate events, and slow things down even more. However, I'm sure this is not a major factor (if at all).

**Comment by tomchadwin** [comment]
Issues opened on Autolinker repo: https://github.com/gregjacobs/Autolinker.js/issues/314

**Comment by jukos** [comment]
> If anyone can confirm or deny this by doing both a 3.12 export and a 3.11 export, and then replacing the 3.12 copy of Autolinker with the 3.11 one, and then reporting whether that improves the speed back to 3.11 rates, then that would be great.

Leaflet test (in repeat):
3.11 autolinker for 3.12 export: all OK, same speed as export with 3.11
Greetings

**Comment by tomchadwin** [comment]
OK, thanks to help from @gregjacobs, author of Autolinker.js, I hope this issue is now solved for all three map export formats. Can you try your exports which had the huge slowdown, and report back?

**Comment by jukos** [comment]
Perfect!
Tested for leaflet with different big maps.
Seems to be ok for ol and mapbox too.

 @gregjacobs and @tomchadwin 
Thanks for your work!

**Comment by tomchadwin** [comment]
Released as 3.13.0 and pushed to QGIS plugins repo.
