### ISSUE TITLE
Apostrophe in alias with inline label causes failure

### ISSUE THREAD

**Issue by jb-cloud** [tomchadwin/qgis2web#854]
After plenty of head scratching, I noticed what was causing my maps to not preview and not work after exporting was apostrophes in the aliases. Should/can they be commented in the widget > field> alias?

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by jb-cloud** [comment]
Thanks for looking. Confirmed this is still an issue.

**Comment by tomchadwin** [comment]
Released as 3.13.0 and pushed to QGIS plugins repo.
