### ISSUE TITLE
Azure Maps option

### ISSUE THREAD

**Issue by rbrundritt** [tomchadwin/qgis2web#856]
This is a proposed feature request. 

I'm on the Azure Maps team, and we use QGIS regularly. We are interested in having a plugin to publish to the Azure Maps web control. Before building something from scratch I wanted to see if adding this as a feature of this plugin would be an option. I'd find some devs on my side to work on this and make a PR, but wanted to see if this is something that would be of interest/accepted if we made a PR before we make the investment.

**Comment by tomchadwin** [comment]
Hello, and thanks for your interest. Can you point me towards some docs for the Azure Maps web control? We've always steered away from support for any provider-specific format (hence why we decided against implementing an 'export to Github Pages' option). I've had a brief look at https://docs.microsoft.com/en-us/azure/azure-maps/how-to-use-map-control, and the requirement of a licence key suggests it's not an open platform.

So, on too little knowledge, I'd say it's probably not something we would want to support. qgis2web doesn't support plugins, but if that could be implemented, then of course anyone could write a plugin for it.

At a code level, as things stand, you would want to reimplement the various export format Python files you can see in the repo, but for Azure Maps (eg `leafletWriter.py`, `leafletFileScripts.py`, `leafletLayerScripts.py`, `leafletStyleScripts.py`, and `leafletScriptStrings.py`, and then add another export button to the GUI (or change the GUI to select export format via drop-down). You would be able to use some functions from `utils.py` for eg vector export to GeoJSON and raster export to PNG.

So, let me know what you think, and apologies if this is not a completely positive reply.

**Comment by rbrundritt** [comment]
Thanks for getting back to me. I had noticed that Mapbox appears integrated somehow, which is also requires a key/is a paid service. But wasn't sure if this plugin was using the Mapbox services, or simply using the map control without any Mapbox data.

I'll circle back with my team and see what approach we want to take. Thanks for the pointers.

**Comment by rbrundritt** [comment]
Also worth noting that the Azure Maps web SDK only needs a key to render our base maps. There is a blank base map option which doesn't require a key and any other tile layers (raster or vector) can be used as a base map.

**Comment by tomchadwin** [comment]
To answer both your replies at once, the Mapbox GL JS export doesn't use any Mapbox services, and hence requires no key. It just uses their open-source software. In other words, it sounds like the business model is very similar to Azure Maps, and hence this could work. Is the actual control (the JS/CSS, etc) open-source?

**Comment by rbrundritt** [comment]
Its not open source yet, there are plans to eventually. At the core its using Mapbox gl for the rendering. We've added a bunch of additional functionality, like accessibility support, a cleaner API interface, a lot more validation of layer options, and a spatial data import library. I'll circle back when this is open source.

**Comment by tomchadwin** [comment]
Sounds really interesting - I look forward to hearing back from you.
