### ISSUE TITLE
Unexpected popup behavior

### ISSUE THREAD

**Issue by Llaves** [tomchadwin/qgis2web#859]
My map contains two layers, one of which is a duplicate of the other (as in Layer->Duplicate Layer), but styled differently. 
I create aliases for the field names for the top-most layer. I then created a web map. When I hover over a feature, I get two copies of the fields, one with the aliased names, one without. When I turn off the top layer I get just one copy. 
Well, you know what's happening. The popup is coded to show the fields of all visible layers (where visible means not turned off). In my case the layers are identical, so one completely overlays the other and makes it visually invisible even though it's not turned off  (unchecked). 
On the qgis canvas the Identify Features cursor applies to the active layer, which of course has no equivalent concept in the web map. When multiple layers are selected, it appears that the fields and values for the last selected layer are displayed. 

While for my case I'd love to have the ability to specify that the pop-up display the fields and values of the top-most visible layer, I'll admit this is a special-enough case that it's not clear that there is much use for this in general.  <delete I don't see an easy workaround. I though I could just hide all the fields of the lower layer, which would work for the top layer. However when the top layer is hidden, the popup would be empty. \delete> In my special case a workaround is to hide all the fields for the top layer and just display those for the bottom layer, which has the same fields. This assumes the user only hides/unhides the top layer and never the bottom layer. 

To fix this in the code means changing the inline function implementing the layer filter starting line 93 of qgis2web.js implementing the layer filter so that it only returns the topmost non-hidden layer when the a new top-most mode is active. Unfortunately this also requires editing the interface code to add this new box. I don't understand enough of the overall structure of the code to make these changes. 

So at this point I'm mainly writing this to record the issue should someone else wonder what's going on. On the other hand, if you'd be willing to kibitz (eg, answer some questions about where to find things in the code), I'd be game to try to implement this feature.

**Comment by tomchadwin** [comment]
I believe this is a fundamental difference in behavioue of Leaflet and OpenLayers. OpenLayers displays data from all features in all visible layers at the point clicked. Leaflet only shows data from features on the topmost layer at the point clicked. So, a way to solve your problem is to use Leaflet export format.
