### ISSUE TITLE
Enhancement request: Header/title & footer 

### ISSUE THREAD

**Issue by Llaves** [tomchadwin/qgis2web#861]
This issue appeared before in [665](https://github.com/tomchadwin/qgis2web/issues/665). A workaround for a header and footer are to edit the index.html file, as noted in that previous request. This has the previously noted shortcoming that each time you run qgis2web  you overwrite the index.html file. An elegant solution would involve modifying the GUI to include inputs for the header and footer and writing these values to a div before and after the div containing the map. 

A compromise solution would be to modify the template for the index.html and use [w3.js](https://www.w3schools.com/w3js/w3js_html_include.asp) to include  user provided header.html and footer.html files, presumably from the same directory as the qgis project file. (Using the w3.js include eliminates reliance on server side includes which may or may not be supported by the hosting service.)  

This approach suffers from two shortcomings.  First, we're adding yet another library to be downloaded by the user viewing the map. Second, and more challenging, when previewing the map on your local machine, the include resolves to file://..., which is treated as a cross-origin request (CORS), which is blocked by default in modern browsers. Curiously (at least to me), the include request does NOT indicate an error if the requested file doesn't exist, so this approach does not create a problem if the file doesn't exist. 

In [665](https://github.com/tomchadwin/qgis2web/issues/665) objections were noted about cluttering the GUI, an issue I am sympathetic to. In addition, I am not familiar with QT, so this approach would be difficult for me to imlement. If the include approach would be acceptable to the maintainers, I would be interested in prototyping it and figuring out how to get around the CORS issue for local viewing of the files. Let me know if I should proceed.

**Comment by Llaves** [comment]
Ignore all that cruft about includes and W3.js. Just have header. html and footer.html files in the project directory and copy their contents into index.html when it's created. No includes, no CORS issues. About the same amount of work.

**Comment by tomchadwin** [comment]
Find the `qgis2web` subfolder in your QGIS profile folder (for example, mine is `C:\Users\tchadwin\AppData\Roaming\QGIS\QGIS3\profiles\default\qgis2web`). **Note**: do *not* go to the *plugin* qgis2web folder. In there, you will find the qgis2web templates. Duplicate whichever is closest to what you want, and then edit the HTML tenmplate to add in your extra text (ie header and footer, pus whatever else you need)

**Comment by Llaves** [comment]
This approach works if you want the same content for every project, but does not support per-project changes. Even editing the template to use an include doesn't work because the included file is not copied to the directory created during the export.

**Comment by tomchadwin** [comment]
Can't you create a different template for each project?

**Comment by Llaves** [comment]
Just to make sure I understand how this all works. I'm assuming the template in the QGIS profile folder is created when qgis2web is installed and is used in every project. If I were to edit it, those edits would appear in every project. Editing per project would work as long as I don't have more than one active project at a time.  Or am I misunderstanding how this template is invoked?

**Comment by tomchadwin** [comment]
No. You can place as many templates in the template folder as you want, and then select which one to use for your project in the qgis2web dialog, where there is a "Template" drop-down.

**Comment by Llaves** [comment]
That's the critical piece of info that I was missing. Thank you. I see now this is documented in the help window - I just looked at the dropdown and saw the two entries and figured that was it.

**Comment by tomchadwin** [comment]
No problem - hope this works for you!
