### ISSUE TITLE
Only line visible in export

### ISSUE THREAD

**Issue by Isnogood1** [tomchadwin/qgis2web#867]
Hi,
I am new to QGis. When I try to export a map with polygons, there are only some horizontal lines visible but nothing else. And I can't zoom further out. Only in. See below a screenshot of the export settings and how it looks like in QGis.

![grafik](https://user-images.githubusercontent.com/63760236/79403481-24cdeb00-7fe3-11ea-8696-3b2ac27890c9.png)

![grafik](https://user-images.githubusercontent.com/63760236/79403506-37e0bb00-7fe3-11ea-8181-6a57f8bc0865.png)

![grafik](https://user-images.githubusercontent.com/63760236/79403539-4d55e500-7fe3-11ea-85af-3b950fc5f1c4.png)

![grafik](https://user-images.githubusercontent.com/63760236/79403428-08ca4980-7fe3-11ea-9c15-551680a1f68f.png)

Thanks!

[SitemapTestArea.zip](https://github.com/tomchadwin/qgis2web/files/4484370/SitemapTestArea.zip)

**Comment by riccardoklinger** [comment]
We cannot help you out here with the dataset you provided. the zip contains only the shp file. A valid shp file comes along with multiple other files that are needed to have the shape file "work properly"
a proper set of files for a shapefile might look like this:
<img width="607" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79419684-93954f00-7fb7-11ea-8866-b95fe857e9a8.png">
can you provide also a screenshot from the whole qgis application so we can see your crs settings. 
as a hint: always have the quickmapservice plugin open to "validate" your edits by simply putting it on a basemap. qgis and quickmapservice do a pretty good job there.

**Comment by tomchadwin** [comment]
This sounds like it could well be a projection issue?

**Comment by riccardoklinger** [comment]
@Isnogood1 can you please provide more input, otherwise we will need to close this ticket.

**Comment by Isnogood1** [comment]
Sorry, had a few days off. I think I found the reason. It was in the CRS. In the project CRS, I have clicked "no projection", which is kind of silly. I have set everything now to the Pseudo-Mercator CRS and it works just fine.  Thanks for the tip with the quickmapservice plugin. You guys are doing a great job!
