### ISSUE TITLE
Layer search crashes the page

### ISSUE THREAD

**Issue by saharshleo** [tomchadwin/qgis2web#868]
QGIS v3.10.3
Plotted a csv file containing lat and long, 
categorized the plot on the basis of attribute 'name'
whenever I used Layer Search, on typing first letter page becomes unresponsive

**Comment by tomchadwin** [comment]
As the issue template here says, we need your layer and project files to be able to debug this. Please upload them to this thread.

Thanks

Tom

```
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible
```

**Comment by saharshleo** [comment]
[https://github.com/saharshleo/WildlifeTracking/tree/web_issue](url)
Github doesn't support the respective file types
you can view it on the above link

**Comment by saharshleo** [comment]
https://github.com/saharshleo/WildlifeTracking/tree/web_issue

Github comments doesn't support the respective file types
you can view them on above link

**Comment by tomchadwin** [comment]
Thanks - if you zip them together, you should be able to upload them, but that repo is great.

**Comment by tomchadwin** [comment]
Your exported map is "working" for me in Firefox, including the layer search. However, it is far too slow to be usable.  I'm afraid I'd look to see whether you can serve your data via WFS - the browser is simply struggling. Worth trying Leaflet export as well, to see whether that is any quicker. Not sure what else to suggest - @riccardoklinger?

**Comment by riccardoklinger** [comment]
That are way to much data points. We are talking about 35.000 items. It was eating memory like hell: after some zooms it was consuming 5GB in the task manager... 
I would assume, using leaflet will be a bit better, also, I know it's not good for this type of data, try using the cluster function. OL is already clustering (not this obvious, but it does) so it should be a way to go. 
But as Tom suggested: GO, GO, GO with a WFS.

**Comment by riccardoklinger** [comment]
coordinate precision is already good.

**Comment by saharshleo** [comment]
Okay, will try WFS
Is there any limit to the number of data points for OL
Leaflet too is slow for this data

**Comment by riccardoklinger** [comment]
no, there is no hard limit. if your data structure is "small" and the precision of coordinates is "small" it can handle some points. maybe start with a small region when exporting. but again: your file is 12mb of pure JSON. this is quite a number! you can also create an account for free on arcgis.com/ here.xyz / cartodb or any other webmapping service and use their wfs functionality if they have one.

**Comment by riccardoklinger** [comment]
But I think we can close this one here?! @saharshleo  It does not seem like an issue, moree like a question. maybe have this discussion over at gis.stackexchange.com ?

**Comment by saharshleo** [comment]
yes, sure
Thank you
