### ISSUE TITLE
Popup appears on boundaries only, not within polygons

### ISSUE THREAD

**Issue by DrJimC** [tomchadwin/qgis2web#869]
qgis2web 3.13, qgis 3.12.1

Hi -
   I have a qGis map with a name and description code associated with each area. These are displayed if I use the 'Identify Features' pointer. When exported with qgis2web, I see no popup within any polygon, but a popup for two polygons if I click on a boundary.  Chrome & Firefox behave in the same way, if I upload the map, but the export preview shows no popup. I dont see any errors on the browser consol. The map is here -

http://www.myurl.me.uk/qGIS/Parishes/qgis2web_2020_04_19-21_19_51_977935/index.html 

& screenshots of the process here -
http://www.myurl.me.uk/qGIS/Parishes/qgis2web_2020_04_19-21_19_51_977935/Info/AboutQGIS.jpg, also Appearance.jpg, Exporting.jpg, Layers.jpg

Maybe I didn't read the manual with sufficient attention, but I cant see any options in qgis2web which might cause this behaviour. The polygons in this layer were created using Vector/Geoprocessing/Dissolve on a precursor layer - could this cause problems ?

Thanks,
           Jim Conboy

**Comment by riccardoklinger** [comment]
Hi Jim,

Would you mind to share your QGIS project with us?

Best, Riccardo

Von meinem iPhone gesendet

**Comment by DrJimC** [comment]
Hi –

                Here are the project files, I hope not too large. I requested a delivery receipt, if this bounces Ill use dropbox. 

 

                ChilternAreas is a merge of sets of parishes in ChilternParishes, which is a subset of bdline_essh_gb, a shape file with all UK admin boundaries from Ordnance Survey.  Ill try a similar exercise on the Parishes data set before merging to areas, in case that has had some unanticipated  effect on the data representation.

 

                Thanks for the swift response –

 

 

Jim Conboy

07730 230405

**Comment by tomchadwin** [comment]
From memory, in Leaflet maps, if a polygon has no fill, it is truly empty, so it can only be clicked on its border. If that might apply here, you could try giving it a fill set to 0% transparency, and see if that solves the issue.

**Comment by DrJimC** [comment]
Yes, that’s it …

                                http://www.myurl.me.uk/qGIS/Parishes/qgis2web_2004_5/index.html 

I had to put the areas layer under the parishes layer, even at 1% opacity, else the parish borders disappeared – although the legend remained. Still needs tidying up, but it now does what I want.

 

                Thanks for your help –

 

                                Jim

**Comment by tomchadwin** [comment]
Try setting the transparency on the fill colour itself, not the whole layer. That means you can have 100% opacity for the border, but 0% for the fill. Not that I can remember how well this is supported in qgis2web, of course...
