### ISSUE TITLE
plugin crashes exporting heatmap

### ISSUE THREAD

**Issue by alfieeisenberg** [tomchadwin/qgis2web#871]
Latest plugin version as of today 3.13.0, QGIS 3.12.2 'București' .
MacOS 10.15.3

I had a csv file with a bunch of columns, about 700 or so records.  
Address, Town, State were used to geocode and add appropriate columns to make the .shp file.
I can make a point map just fine and export it to a web page.
If  I make a heatmap from the same data, it works fine in the desktop app, but when I click to export it or just click on preview map, I get The stack trace below:

Note, when I click on preview, the progress dialog hangs here:
Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting francestown_full_sorted_geocoded_heat_map to JSON... done done

TypeError: %d format: a number is required, not str 
Traceback (most recent call last):
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 91, in write
    folder=dest_folder)
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 138, in writeOL
    mapSettings.destinationCrs().authid())
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 50, in writeLayersAndGroups
    vtLayers)
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 137, in layerToJavascript
    hmWeightMax, renderer, layer), vtLayers
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 409, in getJSON
    layerCode += writeHeatmap(hmRadius, hmRamp, hmWeight, hmWeightMax)
  File "/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 518, in writeHeatmap
    },''' % {"hmWeight": hmWeight, "hmWeightMax": hmWeightMax}
TypeError: %d format: a number is required, not str

Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.12.app/Contents/Resources/python
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/alfred_eisenberg/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/Users/alfred_eisenberg/Desktop/QGIS Training

Next step I tried to simplify by just including one record, but when I click on preview or export QGIS crashes instantly.

I'll attach the single line csv I started with before gecoding, and the .shp file in a zip.

I can provide more data if that helps.  

Any ideas/suggestions?

[Archive.zip](https://github.com/tomchadwin/qgis2web/files/4506999/Archive.zip)

**Comment by tomchadwin** [comment]
We need all the rest of the Shapefile files for this to work. Can you upload them?

**Comment by tomchadwin** [comment]
Is it possible that in the QGIS heatmap settings for your layer. you have specified a non-numeric field for "Weight points by"? That would cause this error.

**Comment by alfieeisenberg** [comment]
This is the only shapefile/layer I have turned on in my project, and it's layered on openstreatmaps for francestown NH.

I do see that the type is abc....so maybe it has to do with the way I imported the data initially. 

The only way I see to change the data type is in the expression dialog, so this time I tried adding to_int( "Download" ) in the expression dialog.  See attched, is this correct?  I still got the same error when previewing or exporting map.
![Screen Shot 2020-05-04 at 10 37 16 AM](https://user-images.githubusercontent.com/7181303/80977828-47d60880-8df3-11ea-9096-2b2515e72751.png)

**Comment by tomchadwin** [comment]
I don't think expressions are supported in that field in qgis2web. You can create a virtual field of numeric type, and give it the value of "Download", then weight on that column.

**Comment by alfieeisenberg** [comment]
I was able to get it to work by going to label properties and adding another column of type int derived from my original column.

Would still like to know if what I was attempting should have worked or not, one less step to produce my page that way.

**Comment by tomchadwin** [comment]
I don't have any direct experience with this, but believe the wrong field type was introduced because it was originally a CSV, which carries no type information. Are you able explicitly to set data types when you open the CSV? If not, create a CSVT file to specify column data types, as described here:

https://gdal.org/drivers/vector/csv.html

**Comment by alfieeisenberg** [comment]
Thanks for suggestion.  In any case I can at least get my heatmap to work if I modify via Layer properties, will try the CSVT at some point to optimize.
