### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by diegrootinduna** [tomchadwin/qgis2web#872]
Thanks for an awesome plugin Tom.  I have one issue that simply cannot overcome, and I apologise if I missed something in the previous issues raised.  I am not a GIS expert, quite the contrary. 
 But I am working on a COVID-19 response map that I would like to export to a webpage.  

Creating webmaps works perfectly, except when I want to include geotiff layers that were obtained from Facebook's Data for Good (https://data.humdata.org/dataset/highresolutionpopulationdensitymaps-zaf).  I'm using version 3.13 of qgis2web, downloaded via plugins.

The error message:
An error has occurred while executing Python code: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\digiMars\\AppData\\Local\\Temp\\ZAF_elderly_60_plus11587565949_piped.tif' 
Traceback (most recent call last):
  File "C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 419, in exportRaster
    processing.run("gdal:warpreproject", warpArgs)
  File "D:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\tools\general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "D:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 137, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Could not load source layer for INPUT: C:\Users\digiMars\AppData\Local\Temp\ZAF_elderly_60_plus11587565949_piped.tif not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 101, in write
    folder=dest_folder)
  File "C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 203, in writeLeaflet
    feedback, iface, matchCRS)
  File "C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 421, in exportRaster
    shutil.copyfile(piped_file, piped_3857)
  File "D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\digiMars\\AppData\\Local\\Temp\\ZAF_elderly_60_plus11587565949_piped.tif'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.5-A Coruña A Coruña, 984615fe1e 

Python Path:
D:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
D:\PROGRA~1\QGIS3~1.10\apps\Python37
D:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
D:\Program Files\QGIS 3.10\bin\python37.zip
D:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
D:\Program Files\QGIS 3.10\bin
D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
D:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\digiMars\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
.
C:\Users\digiMars\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
D:/COVID-19/Hospitale
C:\Users\digiMars\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/digiMars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\digiMars\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

Other geotiffs work perfectly.

Would appreciate some guidance.

**Comment by tomchadwin** [comment]
I don't even get that far - it hangs while trying to convert the raster to a PNG. I'm afraid a 100MB raster is probably something webmaps will struggle with. Is the data available as a WM(T)S/XYZ source anywhere?

**Comment by tomchadwin** [comment]
In fact, it did export a long time later - I had gone on to do something else, so I've no idea how long it took. I think we'll close this on the assumption that it is the size of the TIFF which is the problem. Comment if you want me to reopen.
