### ISSUE TITLE
How to call qgis2web in stand alone pyqgis?

### ISSUE THREAD

**Issue by vanthao1109** [tomchadwin/qgis2web#874]
I have a qgis project which was created by stand-alone pyqgis and now I want to produce a webmap by qgis2web but I don't know how to do it by stand-alone pyqgis. So could anyone tell me how to call qgis2web in stand-alone pyqgis? Thank you very much?

**Comment by tomchadwin** [comment]
I don't have an answer to this, though the Travis tests might help, since I think they take this approach. If the answer you were pointed to on Stack Exchange works for you, can you link it from here, too, and close this issue? Otherwise, leave this issue open, and see whether anyone else can help.
