### ISSUE TITLE
XYZ-tiles basemap not displayed 

### ISSUE THREAD

**Issue by JefCox** [tomchadwin/qgis2web#875]
the qgis2web version = 3.13.0
the QGIS version = 3.10.4-A Coruña

Problem: The google maps terrain basemaps imported as a XYZ-tile is not displayed in the preview nor in the exported webmap. 

- "match project CRS" is checked 
- CRS = 3857
- same problem in "open layers" or "mapbox"
- same problem in other OSM basemaps 

screenshot: 
![Knipselqgis2web](https://user-images.githubusercontent.com/63581307/81069311-fbb5c180-8ee1-11ea-9610-e0fd67999b02.PNG)

**Comment by tomchadwin** [comment]
Can you try unchecking Match project CRS, as 3857 is the default projection?

**Comment by JefCox** [comment]
Thanks for your quick reply! I tried but it's not solving the problem.

**Comment by JefCox** [comment]
Thanks a lot! It is working! :)
