### ISSUE TITLE
Popup Check box doesn't switch off popup for a layer ?

### ISSUE THREAD

**Issue by DrJimC** [tomchadwin/qgis2web#877]
Thanks for your previous help (#869) – I have achieved what I set out to do – see http://www.myurl.me.uk/qGIS/Parishes/qgis2web_2004-07/index.html 
The map displays the parish names, while the popup shows the area (group of parishes), & a double click generates a mailto: to the area rep. (Only for Chartridge, Great & Little Missenden with this version).  I have one specific problem & one general –

1. Deselecting the Popup check box for the parishes layer made no difference; I still got a popup at the parish boundaries, & I couldn’t see how it should have been implemented. I added an extra pair to fieldimages (in layers.js) :
`lyr_ChilternParishes_1.set('fieldImages', {'NAME': 'TextEdit', 'AREA_CODE': 'Hidden', …  'POPUP': 'NoPopup' });` 
which I test for in qgis2web.js 
(NB I need NAME:TextEdit, else the static parish names are not shown)
(Looks a bit like issue 760 ??)

**Comment by tomchadwin** [comment]
@riccardoklinger Any ideas on why "Disable popups" might fail under some conditions?

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by tomchadwin** [comment]
Closing without feedback. Comment here and we can reopen.

**Comment by DrJimC** [comment]
Hi –

                My mistake. I cleared the Popups flag in Layers and Groups, but not the ‘Show popups on hover’ flag on the Appearance tab. Now I know.

 

                Im currently waiting a decision from the customer on whether they are OK with qGIS (in which case I should commit the changes for double click processing), or if they want the web page generated by ArcGIS ( as they have ArcGIS licenses, but zero programming expertise). I should maybe check out a copy of qgis2web & see what might be involved.

 

                Sorry for raising a spurious issue –

 

                                Jim
