### ISSUE TITLE
Stability of qgis2web.js modifications against changes to the map

### ISSUE THREAD

**Issue by DrJimC** [tomchadwin/qgis2web#878]
(See #877, #869)
2)	Having added the double-click code to qgis2web.js, I wonder how much of this routine is generated & would change if the map changes ? I noticed that the map.getView call parameters change according to the export size, but is that all ? It makes quite a difference, for future maintenance; if I change the map contents - but not the number of layers - could I reuse qgis2web.js from a previous export ?
The new code is a block of 3 routines, but with a Kludge to turn off doHover (so the user can interact with the popup) & later restore it)
onDblClick contains code specific to my application, which is not so good – probably need a routine doDblPopup which includes the loop over currentFeatureKeys, and which could more easily be replaced to implement a different function ?

Is there a guide/overview of  how the qGIS map export works ? That would help in integrating a new feature.
Thanks,
             Jim Conboy

**Comment by tomchadwin** [comment]
This differs according to the map output format - please always state whether you are exporting to Leaflet, OpenLayers, or Mapbox. For OpenLayers, take a look at https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/resources/qgis2web.js. All the @CAPITALLETTERS@ placeholders are replaced with code, or removed during export. That should give you an idea as to how stable qgis2web.js is.
