### ISSUE TITLE
Leaflet 1.0

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#88]
As betas appear, test with them

**Comment by tomchadwin** [comment]
Seems to work with 1.0.0-b1. Will check against subsequent betas and the release as they appear.

**Comment by tomchadwin** [comment]
Closing until next beta

**Comment by tomchadwin** [comment]
Leaflet is now at RC1 - I'd be grateful for some help testing. Things to look at:

- check that the Leaflet plugins we use work
- see how layer stacking order can be improved and simplified with panes

**Comment by boesiii** [comment]
What do you mean by "with panes"?

**Comment by tomchadwin** [comment]
http://leafletjs.com/reference.html#map-panes

**Comment by tomchadwin** [comment]
OK, time to start working on this. Might have a go at creating one of these new rinky-dink GH projects for this, and see how much of a colossal waste of time it is.

**Comment by tomchadwin** [comment]
https://github.com/tomchadwin/qgis2web/projects/2

**Comment by tomchadwin** [comment]
Branch created:

https://github.com/tomchadwin/qgis2web/tree/leaflet1.0.0

**Comment by tomchadwin** [comment]
OK, I think things are looking pretty good. If anyone can test the leaflet1.0.0 branch, I'd be grateful. Think I'll do an experimental QGIS plugin release with it, and see how it goes.

**Comment by tomchadwin** [comment]
Released as an experimental version (1.19.0) and pushed to the QGIS plugins repo.

**Comment by tomchadwin** [comment]
I can probably merge the leaflet1.0.0 branch back into master now. Agreed?
