### ISSUE TITLE
Rule-based layers not displayed

### ISSUE THREAD

**Issue by MonikaBarget** [tomchadwin/qgis2web#883]
This relates to the (closed) issue #620 and a related discussion on [gis.stackexchange](https://gis.stackexchange.com/questions/338749/how-to-export-layers-with-rule-based-symbology-with-qgis2web/361490?noredirect=1#comment591475_361490):

Rule-based layers created from a single GeoJSON file are exported to .js by QGIS2web if the main layer is duplicated first and individual rule-based layers are selected. They are correctly stored in the "layers" folder, and at least one of them is also correctly referred to in the corresponding HTML file. However, none of the layers are displayed on the OSM base map when the HTML file is opened in the browser (FIREFOX).

[QGIS2web_for-review.zip](https://github.com/tomchadwin/qgis2web/files/4621580/QGIS2web_for-review.zip)

In the **attached ZIP folder**, you will find the following files:

1. GeoJSON file with all features used for the different layers.
2. QGIS project file.
3. Folder created by QGIS2web with 2 sample layers selected from my project.

**Comment by tomchadwin** [comment]
The layer uses the point cluster renderer which is unsupported by qgis2web, I'm afraid. While there may or may not be issues with the rule-based renderer used within the cluster renderer, it's the basic lack of support for the cluster renderer which is causing the issue. Clustering can be enabled within the qgis2web dialog instead.

**Comment by MonikaBarget** [comment]
Thanks for looking into it so soon. I copied my main layer and turned off clustering but still selected points for each sub-layer based-on rules. The map in QGIS no longer shows clustered points now, but the export problem in QGIS2web persists.

My updated QGIS project file is attached. 

![grafik](https://user-images.githubusercontent.com/38257338/81811301-b36f5280-9524-11ea-8673-8d2a07e296ae.png)

[QGIS2web_no-clustering.zip](https://github.com/tomchadwin/qgis2web/files/4621862/QGIS2web_no-clustering.zip)

**Comment by tomchadwin** [comment]
OK, not sure exactly where all issues lie, but a couple of things:

- rule-based labelling is not supported, I'm afraid
- can you combine all your layers into one, with multiple rules?

I think the second point would work better, but I'm not sure precisely which issues you are trying to solve.

**Comment by MonikaBarget** [comment]
The easiest solution for me was to export all the layers I will need as separate GeoJSON files from my original data and label them without rules. That outsources the entire selection process and works just fine. So thanks for letting me know that rule-based labelling is definitely not supported.

**Comment by tomchadwin** [comment]
Glad you found a workaround, and sorry that feature is not implemented.
