### ISSUE TITLE
OL layer search breaks page

### ISSUE THREAD

**Issue by foundationkitty** [tomchadwin/qgis2web#884]
Turning on layer search with OL results in a blank white screen (with the exception of zoom controls) under any circumstances in the latest release (3.13). Previous versions of the plugin (I tested 3.12.1) do not have this issue. I believe this is an incompatibility with OL 6.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by foundationkitty** [comment]
With the latest master, layer search for OL is working again.

**Comment by tomchadwin** [comment]
Brilliant - thanks for testing.
