### ISSUE TITLE
Measure tool visibility problem

### ISSUE THREAD

**Issue by sebastian1967** [tomchadwin/qgis2web#885]
Hi Tom,
I'm using qgis2web (ver. 3.13) with QGIS 3.10.5 LTS on Windows 10 (Chrome browser). I created with your plugin a map (Leaflet webmap) with 3 layers: 1) a vector layer with trekking paths, 2) a raster tiled map and 3) Topmap (here the link to the map: [https://www.armadilling.com/QGIS/Completa/index.html]. The problem is with the measure tool: when I take some measures the lines and polygons drawn by the tool are visible only when only the vector layer is visible. If I turn on also the raster tiled layer or Topomap the lines and polygons are hidden by those layers. Is that normal?
Many thanks.
Sebastian

**Comment by edbusana** [comment]
We have the same problem

[https://github.com/ljagis/leaflet-measure/issues/141](url)
[https://github.com/ljagis/leaflet-measure/issues/103](url)

**Comment by tomchadwin** [comment]
I've commented on one of the threads on the measure repo. This is because qgis2web uses panes, and the measure tool doesn't. No solution at this point, I'm afraid.

**Comment by edbusana** [comment]
The solution I found was to change the transparency of the layers by 50%. It is not ideal but if the measure plugin is important for your work, it was the alternative.

**Comment by edbusana** [comment]
Is it possible to change the opacity / transparency of one or more layers when executing the measure?

**Comment by sebastian1967** [comment]
Thank youTom!
