### ISSUE TITLE
Drawing moving with geographic coordinates

### ISSUE THREAD

**Issue by edbusana** [tomchadwin/qgis2web#886]
Drawing moving by rounding the geographic coordinates. Solution by editing the coordinates directly in the html file. Can this be fixed with an update later?

Problem demonstration link. [www.edbusana.eu5.org@edbusana.eu5.org/qgis2web_2020_05_15-19_34_28_447031/index.html](url)

Settings in qgis2web (image)
![config](https://user-images.githubusercontent.com/65259403/82102300-87e79600-96e5-11ea-8466-e40aabb6a029.png)

HTML
![html](https://user-images.githubusercontent.com/65259403/82102330-a0f04700-96e5-11ea-821c-d08915e98cea.png)

**Comment by tomchadwin** [comment]
I can't think of a fix for this, so your solution is the best one.
