### ISSUE TITLE
Categorized Output Not Keeping Color

### ISSUE THREAD

**Issue by coreyhoggard** [tomchadwin/qgis2web#887]
I am having an issue with the output in Leaflet with it keeping the categorized colors. See below screenshots.

QGIS version | 3.10.5-A Coruña
QGIS2WEB Version: Installed version | 3.14.0

![Screen Shot 2020-05-16 at 9 01 28 AM](https://user-images.githubusercontent.com/7786558/82120427-f19e8900-9753-11ea-8ccc-cd5b7dfdafbe.png)
![Screen Shot 2020-05-16 at 9 01 52 AM](https://user-images.githubusercontent.com/7786558/82120428-f2371f80-9753-11ea-820d-a0238c33527a.png)

**Comment by edbusana** [comment]
Checked if your layer is the same as the SRC of the project and other layers.

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by tomchadwin** [comment]
Closing without feedback. Comment here and we can reopen.
