### ISSUE TITLE
MBGLJS geocoder

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#890]
Trying to use https://github.com/lemmingapex/mapbox-gl-generic-geocoder. The problem is that I have no experience of node/browserify/webpack. I'm trying to bundle it so I can use the compiled JS in MBGLJS exports, to geocode via Nominatim. I haven't got it to work.

Can anyone who knows node/browserify/webpack create a distributable version for me?

**Comment by ThomasG77** [comment]
The recipe to get the 2 files without caring/understanding about browserify/webpack

```
cd yourdirectory
git clone https://github.com/lemmingapex/mapbox-gl-generic-geocoder.git
cd mapbox-gl-generic-geocoder
npm i # I  suppose you have node installed
npm run prepublish
```

Look in `dist` directory to get what you want

**Comment by tomchadwin** [comment]
```
C:\Users\tchadwin\Desktop\tmp\mapbox-gl-generic-geocoder>npm run prepublish

> mapbox-gl-generic-geocoder@1.0.3 prepublish C:\Users\tchadwin\Desktop\tmp\mapb
ox-gl-generic-geocoder
> NODE_ENV=production && mkdir -p dist && browserify --standalone MapboxGenericG
eocoder lib/index.js | uglifyjs -c -m > dist/mapbox-gl-generic-geocoder.min.js &
& cp lib/mapbox-gl-generic-geocoder.css dist/

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapbox-gl-generic-geocoder@1.0.3 prepublish: `NODE_ENV=production && mk
dir -p dist && browserify --standalone MapboxGenericGeocoder lib/index.js | ugli
fyjs -c -m > dist/mapbox-gl-generic-geocoder.min.js && cp lib/mapbox-gl-generic-
geocoder.css dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapbox-gl-generic-geocoder@1.0.3 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tchadwin\AppData\Roaming\npm-cache\_logs\2020-05-22T14_10_
39_285Z-debug.log
```

**Comment by tomchadwin** [comment]
Running on Windows, by the way.

**Comment by ThomasG77** [comment]
So, type in your command line `SET NODE_ENV=production`, remove in `package.json` file the part `NODE_ENV=production && ` and run again `npm run prepublish` (both command should be done in the same command window due to https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt)

**Comment by tomchadwin** [comment]
I figured out the `SET` command myself, and then started trying to run the rest of the commands from that line. It doesn't like uglifyjs, and I went down a bit of a rabbit hole on that. However, I got rid of the uglify step, and I think it has worked! Thank you!

**Comment by ThomasG77** [comment]
You should use uglify: it reduces the JS bundle size

```
44K	dist/mapbox-gl-generic-geocoder.js # Without uglify
16K	dist/mapbox-gl-generic-geocoder.min.js # With uglify
```

**Comment by ThomasG77** [comment]
Try

```
SET NODE_ENV=production
mkdir -p dist && ./node_modules/.bin/browserify --standalone MapboxGenericGeocoder lib/index.js | ./node_modules/.bin/uglifyjs -c -m > dist/mapbox-gl-generic-geocoder.min.js && cp lib/mapbox-gl-generic-geocoder.css dist/
```

**Comment by tomchadwin** [comment]
Works (if I reverse the slashes)! I have a minified lib. Thanks so much again!
