### ISSUE TITLE
Leaflet labels disappear after applying attribute filter

### ISSUE THREAD

**Issue by sophieclark4747** [tomchadwin/qgis2web#891]
After exporting a map using qgis2web (Leaflet) and applying an attribute filter, all labels disappear from the map and are not rendered again even after clearing all filters.

**Comment by tomchadwin** [comment]
@riccardoklinger

**Comment by tomchadwin** [comment]
I thought this would be fixed by calling `resetLabels()` at the end of the filter function, but it doesn't do it, so I'm baffled at the moment.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by tomchadwin** [comment]
Scratch that. Wow, did I get that fix wrong...

**Comment by tomchadwin** [comment]
OK, second attempt at a fix committed to master. Please test and report back.
