### ISSUE TITLE
OSM Standard tile layer wrong properties (= instead of :)

### ISSUE THREAD

**Issue by foksonx** [tomchadwin/qgis2web#893]
Release 3.15.0

When exported using leaflet, index.html stopped due to the error on the line (around 97) next to minNativeZoom and maxNativeZoom.

There are "=" equal sign, instead of ":"

** generated by plugin:
    var layer_OSMStandard_0 = L.tileLayer('http://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            pane: 'pane_OSMStandard_0',
            opacity: 0.5,
            attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
            minZoom: 1,
            maxZoom: 28,
            minNativeZoom=0,
            maxNativeZoom=19

** fixed:
    var layer_OSMStandard_0 = L.tileLayer('http://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            pane: 'pane_OSMStandard_0',
            opacity: 0.5,
            attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
            minZoom: 1,
            maxZoom: 28,
            minNativeZoom:0,
            maxNativeZoom:19

**Comment by tomchadwin** [comment]
Stupid mistake by me. Many apologies. Should be fixed now in master. Can you test and confirm? I'll release a patch version once I know it's working.

**Comment by tomchadwin** [comment]
Upgrade to 3.15.1 to fix this issue. Thanks for spotting and reporting it.

**Comment by foksonx** [comment]
Sorry for replying late, it works OK now
