### ISSUE TITLE
Как мне исправить эти ошибки

### ISSUE THREAD

**Issue by Pavel-Aktobe** [tomchadwin/qgis2web#895]
Ошибка при выполнении сценария Python: 

TypeError: 'float' object is not subscriptable 
Traceback (most recent call last):
  File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 104, in write
    folder=dest_folder)
  File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 294, in writeMapbox
    useOSMB, vtSources, layers)
  File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxLayerScripts.py", line 145, in writeVectorLayer
    mblayers = getLayerStyle(layer)
  File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxStyleScripts.py", line 43, in getLayerStyle
    mapboxStyle = bridgestyle.qgis.layerStyleAsMapbox(layer)
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\qgis\__init__.py", line 41, in layerStyleAsMapbox
    mbox, mbWarnings = mapboxgl.fromgeostyler.convert(geostyler)
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 10, in convert
    layers = processLayer(geostyler)
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 31, in processLayer
    layers = processRule(rule, layer["name"])
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 47, in processRule
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 47, in 
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 126, in processSymbolizer
    symbolizer = _textSymbolizer(sl)
  File "C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs\bridgestyle\mapboxgl\fromgeostyler.py", line 151, in _textSymbolizer
    offsetx = convertExpression(offset[0])
TypeError: 'float' object is not subscriptable

Версия Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Версия: 3.6.3-Noosa Noosa, 0c5774c068 

Расположение Python:
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\indoor_schematic
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider
C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider\extlibs
C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Dorogokuplya\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Gis

**Comment by tomchadwin** [comment]
This is an error in bridge-style. Can you upload a layer and style or project file which trigger the problem? I can then raise it upstream at https://github.com/GeoCat/bridge-style/issues.

**Comment by Pavel-Aktobe** [comment]
Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting Подключение to JSON... done done
Exception in layer akt_connection_point_920170922022640951 with renderer Rule-based renderer: RULE - scale [0,0] - filter - symbol [] RULE - scale [0,0] - filter - symbol MARKER SYMBOL (1 layers) color 228,7,191,255 RULE - scale [50,2000] - filter "id_block_heat_meters" = 'true' - symbol MARKER SYMBOL (1 layers) color 218,58,77,255 : Traceback (most recent call last): File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 62, in exportStyles layer_alpha, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 316, in ruleBased renderer, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 481, in getSymbolAsStyle svg = xml.etree.ElementTree.parse(sl.path()).getroot() File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse tree.parse(source, parser) File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 587, in parse source = open(source, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4wLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLVNWRy0yMDAxMDkwNC9EVEQvc3ZnMTAuZHRkIj4NCjwhLS0gQ3JlYXRvcjogQ29yZWxEUkFXIFg4IC0tPg0KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIHdpZHRoPSIyMTBtbSIgaGVpZ2h0PSIyOTdtbSIgdmVyc2lvbj0iMS4wIiBzaGFwZS1yZW5kZXJpbmc9Imdlb21ldHJpY1ByZWNpc2lvbiIgdGV4dC1yZW5kZXJpbmc9Imdlb21ldHJpY1ByZWNpc2lvbiIgaW1hZ2UtcmVuZGVyaW5nPSJvcHRpbWl6ZVF1YWxpdHkiIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIg0Kdmlld0JveD0iMCAwIDIxMCAyOTciDQogeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPg0KIDxnIGlkPSLQodC70L7QuV94MDAyMF8xIj4NCiAgPG1ldGFkYXRhIGlkPSJDb3JlbENvcnBJRF8wQ29yZWwtTGF5ZXIiLz4NCiAgPGVsbGlwc2UgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRTYzQzI0IiBzdHJva2Utd2lkdGg9IjMiIGN4PSIxMDUiIGN5PSIxNDkiIHJ4PSIzNSIgcnk9IjMyIi8+DQogIDxnIGlkPSJfMjAxMDU4MjQ2ODc1MiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMC4yIiB4MT0iMTA1IiB5MT0iMTE3IiB4Mj0iMTA1IiB5Mj0gIjExNyIgLz4NCiAgPC9nPg0KICA8ZyBpZD0iXzIwMTA1ODI0NjcwMjQiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuNSIgeDE9IjExOSIgeTE9IjEyNCIgeDI9IjkwIiB5Mj0gIjEyNCIgLz4NCiAgPC9nPg0KICA8ZyBpZD0iXzIwMTA1ODI0Njc4ODgiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiB4MT0iMTE5IiB5MT0iMTI2IiB4Mj0iOTAiIHkyPSAiMTI2IiAvPg0KICA8L2c+DQogIDxnIGlkPSJfMjAxMDU4MjQ2NzMxMiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMS41IiB4MT0iMTE5IiB5MT0iMTI4IiB4Mj0iOTAiIHkyPSAiMTI4IiAvPg0KICA8L2c+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9Ijc5IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9Ijg2IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjkzIiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjEwMSIgeT0iMTM0IiB3aWR0aD0iNS41MDMzIiBoZWlnaHQ9IjguNjc4MyIvPg0KICA8cmVjdCBmaWxsPSIjRDJEMkQyIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSIxMDgiIHk9IjEzNCIgd2lkdGg9IjUuNTAzMyIgaGVpZ2h0PSI4LjY3ODMiLz4NCiAgPHJlY3QgZmlsbD0iI0QyRDJEMiIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuMiIgeD0iMTE0IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNFQjVFNUQiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjEyMiIgeT0iMTM0IiB3aWR0aD0iNS41MDMzIiBoZWlnaHQ9IjguNjc4MyIvPg0KICA8Y2lyY2xlIGZpbGw9IiNBM0EzQTQiIGN4PSI4NiIgY3k9IjE1OCIgcj0iNiIvPg0KICA8Y2lyY2xlIGZpbGw9IiNGRUZFRkUiIHN0cm9rZT0iI0ZFRkVGRSIgc3Ryb2tlLXdpZHRoPSIwLjIiIGN4PSI4NiIgY3k9IjE1OCIgcj0iMSIvPg0KICA8cmVjdCBmaWxsPSIjRkVGRUZFIiBzdHJva2U9IiNGRUZFRkUiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSI4NiIgeT0iMTU1IiB3aWR0aD0iMC4zNzA1IiBoZWlnaHQ9IjMuNjkwOSIvPg0KICA8cmVjdCBmaWxsPSJub25lIiBzdHJva2U9IiNFNjNDMjQiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSI4NSIgeT0iMTU1IiB3aWR0aD0iMC42MjE3IiBoZWlnaHQ9IjAuMjI0OSIvPg0KICA8ZyBpZD0iXzIwMTA1ODI0NTYxNDQiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuNSIgeDE9IjkyIiB5MT0iMTY1IiB4Mj0iODAiIHkyPSAiMTY1IiAvPg0KICA8L2c+DQogIDxjaXJjbGUgZmlsbD0iI0EzQTNBNCIgY3g9IjEyMiIgY3k9IjE1NSIgcj0iOCIvPg0KICA8Y2lyY2xlIGZpbGw9IiNFNjNDMjQiIHN0cm9rZT0iI0U2M0MyNCIgc3Ryb2tlLXdpZHRoPSIwLjIiIGN4PSIxMjIiIGN5PSIxNTUiIHI9IjEiLz4NCiAgPHJlY3QgZmlsbD0iI0U2M0MyNCIgc3Ryb2tlPSIjRTYzQzI0IiBzdHJva2Utd2lkdGg9IjAuMiIgeD0iMTIyIiB5PSIxNTEiIHdpZHRoPSIwLjM3MDUiIGhlaWdodD0iMy42OTA5Ii8+DQogIDxnIGlkPSJfMjAxMDU4MjQ1MDg5NiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHgxPSIxMzEiIHkxPSIxNjQiIHgyPSIxMTQiIHkyPSAiMTY0IiAvPg0KICA8L2c+DQogIDxyZWN0IGZpbGw9IiNFMUUwREUiIHg9Ijk0IiB5PSIxNzAiIHdpZHRoPSIyNC4yMzU4IiBoZWlnaHQ9IjMuNDkyNSIvPg0KIDwvZz4NCjwvc3ZnPg0K' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:/Users/Dorogokuplya/AppData/Local/Temp/qgis2web/2/12 @tomchadwin 

- 

> `[](url)`
