### ISSUE TITLE
Legend Background color

### ISSUE THREAD

**Issue by redders47** [tomchadwin/qgis2web#898]
To be honest I am not even sure I am in the right place to ask a question like this.

My web map is here:
https://www.victoriasforestryheritage.org.au/maps/ericatyerstramlines/ericatyers2/index.html#11/-37.9954/146.2689

I simply wish to change the background color of the legend at the right.

I can change text size, color etc, but cannot see how to change background color.

Obviously my understanding of code is very limited, so any help would be appreciated.

Richard

**Comment by redders47** [comment]
Found it finally ty.

**Comment by tomchadwin** [comment]
If you have the time, please do post your solution here, in case other need to do the same thing. Thanks!

**Comment by redders47** [comment]
Tom

I finally found this section of code in leaflet.css which allowed me to alter the background colour of the layers legend.
.leaflet-control-layers-expanded {
	padding: 6px 10px 6px 6px;
	color: #333;
	background: rgb(209, 231, 12);
	}
Thank you for the plug in by the way. It allows me to do something with my historical map info I could never have imagined when starting out. Brilliant.

Richard
