### ISSUE TITLE
ol layer search - center on points not working

### ISSUE THREAD

**Issue by dtvkoe** [tomchadwin/qgis2web#899]
Hello,

when using the layer search on a layer with single point geometries the zoom to the search result is not working. 

The search finds the requestd entry but after pressing enter in the search textbox a blank page appears.

I'm using qgis2web 3.15.1. 

The problem can be fixed by manual editing "ol3-search-layer.js" in the resources folder of the qgis2web output.  In this file there is a line (arround line number 105) where the variable "typesToZoomToCenterAndZoom" is intialized with ['point'].  The entry should be ['Point'] cause the text comparison is case sensitive and the geometry type "Point" starts with an upper case letter like the other geometries.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.
