### ISSUE TITLE
Leaflet popup content shows all fields regardless of setting

### ISSUE THREAD

**Issue by mixedbredie** [tomchadwin/qgis2web#9]
In the Layers section I set the pop up content to show just one field of information but in the final output Leaflet map the popups show all fields.

It works as expected for the OL3 map output.

**Comment by tomchadwin** [comment]
Another stance of the OL3 UI not being tied to the Leaflet export.

**Comment by tomchadwin** [comment]
Fixed in master - please test.

**Comment by boesiii** [comment]
I am having problems related to popups.  When exporting to Leaflet and "Delete Unused Fields" is check "On", no layers display in browser and in the brower's developer tools there is an error in the console saying "pop_mylayer is not defined"

**Comment by tomchadwin** [comment]
Reimplemented in master. Please test.
