### ISSUE TITLE
ol layer search - zoom in not working properly

### ISSUE THREAD

**Issue by dtvkoe** [tomchadwin/qgis2web#900]
Hello,

when using the layer search and clicking on a result, the map view gets zoomed out instead of zoomed in.

In the resource file "ol3-search-layer.js" is in line 129 the following statement:
` map.getView().setZoom(options.zoom || 12);`

The attribute "options.zoom" has somehow always the value 10 which causes a big zoom out when searching for an adress. I don't know where the value 10 comes from. One possibility is that it is automatically calculated by the layer extend. Before using the qgis2web result I then to overwrite this line with a more approbiate value for my purposes.

I would wish there sould be a more suitable zoom value be set by default or there would be an option in the qgis2web dialog when creating the map in QGIS.

I'm using qgis2web version 3.15.1 with QGIS 3.12-3 on an Ubuntu based linux distribution.

**Comment by tomchadwin** [comment]
I'm not sure that there can be a "suitable" value, as we have no way of knowing what will work for any given map - for example, of there is a basemap, one can possibly zoom in quite far, but if there is not, the ideal zoom is probably as far in as possible while still displaying the nearest neighbouring feature(s). Unless someone can think of a better behaviour than what we have now, I'm not sure what change to make to improve things.

**Comment by tomchadwin** [comment]
Closing for now - comment with any other thoughts as to how we could improve this, and I can reopen.

**Comment by andreaordonselli** [comment]
In my case a medium zoom is appropriate so I changed line 129 as follows:
map.getView().setZoom(15);
