### ISSUE TITLE
Need Development in Filter in Leaflet Library

### ISSUE THREAD

**Issue by jeevanganesh** [tomchadwin/qgis2web#901]
Hi Tom
Thanks to Commit #891 and Fixed and Released the Latest Version
Based on  Latest Version it Working  Well 
 We Got a Development Query from the Respective Department
1 Requirement Filtered Feature as a Reports in a CSV file or a Spreadsheet file format  from the Geojson Data with a download link
New Website with Latest Version link
http://www.aedeedgl.epizy.com/#14/10.4787/77.9638
Best Regards,
M.Ganesan M.sc., Mphil.,Phd.,
Director 
GeoPacific Solutions Chennai

**Comment by tomchadwin** [comment]
I'm afraid this probably falls outside the scope of the plugin, so it is something you will have to investigate yourself. Many apologies.
