### ISSUE TITLE
high accuracy in var labelFont calculation

### ISSUE THREAD

**Issue by jipexu** [tomchadwin/qgis2web#906]
Hi
Do we really need to have a so high precision
in the generated _style.js files ?
example of generated code
`    var labelFont = "15.600000000000001px \'Lucida Grande\', sans-serif";
`
what is the utility and the use of a so hight accuracy ?

Thanks for your advice

**Comment by tomchadwin** [comment]
This looks like an artefact of JS float precision - I don't think it does much harm, but if someone would like to remove it, they should feel welcome.
