### ISSUE TITLE
UnboundLocal Error upon loading plugin

### ISSUE THREAD

**Issue by mps9506** [tomchadwin/qgis2web#91]
With version 0.18.0 using QGIS 2.8.2 on Win64 I get the following error immediately upon loading the plugin:

>  Traceback (most recent call last):
>  File "C:/Users/emw/.qgis2/python/plugins\qgis2web\qgis2web.py", line 51, in run
>    dlg = MainDialog(self.iface)
>  File "C:/Users/emw/.qgis2/python/plugins\qgis2web\maindialog.py", line 55, in __init__
>    self.previewMap()
>  File "C:/Users/emw/.qgis2/python/plugins\qgis2web\maindialog.py", line 99, in previewMap
>    MainDialog.previewLeaflet(self)
>  File "C:/Users/emw/.qgis2/python/plugins\qgis2web\maindialog.py", line 223, in previewLeaflet
>    previewFile = writeLeaflet(self.iface, utils.tempFolder(), 500, 700, 1, layers, visible, "", cluster, "", >"", "", "", labels, 0, 0, json, params, popup)
>  File "C:/Users/emw/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 143, in writeLeaflet
>    middle += featureGroupsScript()
>UnboundLocalError: local variable 'middle' referenced before assignment

It seems to persist despite changing layers and CRS.

**Comment by tomchadwin** [comment]
I can't figure out how your options allow that to happen, but I think I have a fix for it. Committing now.

**Comment by tomchadwin** [comment]
Committed a possible fix to master. Are you able to test and report back?

**Comment by mps9506** [comment]
Agreed, for what it is worth I was able to load the plugin after appending:
```python
middle = ''
```
at the top of the function.

**Comment by mps9506** [comment]
Thanks, looks like it is working.

**Comment by tomchadwin** [comment]
Great. I'll release 0.19.0 with that fix tomorrow. Thanks for spotting and reporting.
