### ISSUE TITLE
Cannot publish Web Map without "not secure" warning in Chrome

### ISSUE THREAD

**Issue by janspeksnijder** [tomchadwin/qgis2web#916]
How To Fix The "Not Secure Website" Warning In Google Chrome on a secure webserver?
I use OpenStreetmap as basemap.

**Comment by tomchadwin** [comment]
Make sure, when you add the basemap into QGIS, that you use an https:// tileserver, not an http:// one. If that does solve this issue, can you comment here to confirm?

**Comment by janspeksnijder** [comment]
OpenStreetmap is added in QGIS. Could there be http references that cause the warning?
