### ISSUE TITLE
Add videos, PDF´s and other files to WebGIS

### ISSUE THREAD

**Issue by Alex1234-bit** [tomchadwin/qgis2web#921]
Hi all,

i´m trying to export a WebGIS vie QGIS2Web.
The Shapefiles contain paths to different files.

I can open the files with the run action function without problems and also as hyperlinks within QGIS.
When i export the project with QGIS2web, I can´t open the files directly. Is ther a possibility to do so?

I can play videos by setting the widget type type to attachments and open play the video-file by right-click and ...open grafik in the webgis. But is there a possibility to open the viedeo/pdf-files direktly in the Internet-Browser?

**Comment by jukos** [comment]
Hello,
Yes, it is possible to open a video within the map in the browser.
For example a youtube-video:
- type: text editor
- for example for this video:
https://www.youtube-nocookie.com/embed/_riGdN3bHhk

code from youtube to copy, you can change for example width and height:
<iframe width="300" height="169" src="https://www.youtube-nocookie.com/embed/_riGdN3bHhk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

![video within the browser](https://user-images.githubusercontent.com/31866672/94716312-efc61280-034e-11eb-824c-fea599f53b3d.jpg)


Try it! 
Greetings

**Comment by Alex1234-bit** [comment]
Hi!

I (kind of) mean something exactly like this. Thank you! The only difference is, I want to implement locally stored video-files instead of youtube-videos.

I tried to substitude the youtube-link with the relative path to the file, but it didn´t work. 

<iframe width="300" height="169" src=".\data\video\video01.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  

Any idea how to correct it?

Best regards

**Comment by Alex1234-bit** [comment]
...typing error... It works just fine! Thanks again!

**Comment by jukos** [comment]
What was wrong?

**Comment by Alex1234-bit** [comment]
I just had an typo in the actual filename. It works with the relative path!

**Comment by tomchadwin** [comment]
Thanks for finding the solution for this, @jukos! Gad you are sorted, @Alex1234-bit.
