### ISSUE TITLE
Announcement - uncertain times

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#923]
Hello everyone

Some of you might be aware that my work future is currently uncertain. Since my ability to work on qgis2web in my free time depends on my having a job to pay the bills, this means that I'm currently unsure how things will work going forward. Hopefully I can keep things ticking over, but nothing is clear to me at this stage.

Thanks for your patience, everyone

Tom

Ref: https://twitter.com/tomchadwin/status/1310636305009737728

**Comment by jukos** [comment]
Good luck!

**Comment by jipexu** [comment]
more and more people on the planet, less and less jobs ... so when a universal income for each with or without job... good luck to find !

**Comment by jukos** [comment]
https://www.pilotprojekt-grundeinkommen.de/  (unconditional basic income)

A project in Germany for the next 3 years. But I think it is a looooong way.

Greetings

**Comment by boesiii** [comment]
If you don't have a paying job then technically you can spend more time on Qgis2web! Obviously I am being sarcastic.

Best wishes on finding a new job that can make you happy and some money.

**Comment by riccardoklinger** [comment]
Okay: Guys, we need a support plan:
- getting it into qgiscore?
- add sponsoring with little amounts to support the work
- I can spend some more time now
- Maybe another fellow can follow?
- reducing supported frameworks to leaflet and openlayers
- having some sort of campaign to find new supporters/maintainers/followers/users?

**Comment by andreaordonselli** [comment]
Hi Riccardo, I am very fond of qgis2web and I would be very sad to see it stop.
I have been trying to respond to the issues raised by users both here on github and on gis.stackexchange for about 2 years and **I offer to continue doing so**.

For the update plan, I believe it is best to start by updating openlayers and leaflets to the latest versions, maintaining the current functionality.

**Comment by tomchadwin** [comment]
I'll ask again at work if they are interested in contributing some dev time - no joy last time I asked.

**Comment by tomchadwin** [comment]
Iam extremely grateful for all your work in supporting the plugin, @andreaordonselli. I did notice your work!

Perhaps even before updating Leaflet and OpenLayers, we need to fix the test framework (or abandon it) - last time I merged a PR, it failed the tests. I did not have time to look into it.

After that, I agree, upgrade Leaflet and OpenLayers, and take a decision whether we should remove Mapbox GL JS, as it never reached maturity, and probably doesn't work at all now. The core work might be usable for a switch to MapLibre, especially if we could make use of the style conversion code which I think is now part of QGIS core from the MBVT work contributed by Lutra.

**Comment by nameloCmaS** [comment]
I would be happy to make some small contributions.

I have a few fixes and improvements on my laptop which I need to package up separately and merge.

**Comment by softwareengineerprogrammer** [comment]
@tomchadwin re:

> take a decision whether we should remove Mapbox GL JS, as it never reached maturity, and probably doesn't work at all now.

It appears the decision was subsequently made to disable per https://github.com/qgis2web/qgis2web/blob/9a1aa251fecfa301f23b93d78620fcb25ecceea8/metadata.txt#L40.

Assuming this is accurate, I figured it might be helpful to leave this comment for other new users who, like myself, may be wondering why the option to export to Mapbox is disabled.

PS thank you for your work and contribution!

**Comment by andreaordonselli** [comment]
Yes, your interpretation is correct.  Thanks for summarizing it.  You can still use version 3.17.1, or earlier, where you could export to Mapbox GL JS.
