### ISSUE TITLE
Mapbox GL JS layer nnot working

### ISSUE THREAD

**Issue by Krukarius** [tomchadwin/qgis2web#925]
There is no option to preview and export in the Mapbox GL JS layer.

I am getting the following error:

maindialog.py line 350 in saveMap
mapbooxWriter.py, line 104 in write
mapboxWriter.py, line 294 in writeMapbox
mapboxLayerScripts.py line 148 in writeVectorLayer
mapboxLayerScripts.py, line 392 in getLegend

the QGIS is frozen and I have to close it with the task manager.

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by tomchadwin** [comment]
Closing without feedback. Comment here and we can reopen.
