### ISSUE TITLE
QGIS2web OpenLayers map keeps coming with nothing (layer group) or not populate all the layers selected

### ISSUE THREAD

**Issue by Krukarius** [tomchadwin/qgis2web#926]
Openlayers plugin keeps coming with nothing.

After fixing the error here:

https://gis.stackexchange.com/questions/376718/is-there-an-alternative-to-qgis2web

The plugin theoretically works, as the comment says that everything is successful.

Unfortunately, it comes with nothing.

The graphic situation is here:

https://imgur.com/a/5zjrW8w

Is there any way to render all these layers included in the group?

I've extracted all these layers from the group and tried to attach them separately.
Unfortunately, some of them come and some don't

See the situation in the image below:

https://imgur.com/a/5zjrW8w

where I marked all the layers being not populated in preview mode. It means, that they don't come in the final map.

Are you able to clarify this situation?
What part of the code is "responsible" for it?

I also tried to fix it manually, by the Javascript code edition.
https://imgur.com/a/5zjrW8w

but without any results.

The layers are saved(populated) in a specific order.  Can I edit this order manually in JavaScript?

Could you help me with it?

Thank you in advance

**Comment by boesiii** [comment]
Any chance you upload your layers and Qgis project file?

Its most likely something in one of your layers that is causing the issue.  To figure out which layer you need to load a single layer into a single Qgis project and try using the plugin.  If it works try one more layer.  Keep continuing until you find the layer giving you a problem.

**Comment by Krukarius** [comment]
Do you know how can I combine these separately extracted layers into one map in Javascript?

**Comment by boesiii** [comment]
Yes but first we need to narrow done the problem.  Are you able to upload your data?

**Comment by Krukarius** [comment]
hi,

I can send you the geopackage on email tomorrow if you want

W dniu środa, 21 października 2020 boesiii <notifications@github.com>
napisał(a):

**Comment by boesiii** [comment]
Ok

**Comment by Krukarius** [comment]
Could you give me an email address please?

**Comment by Krukarius** [comment]
Hi sir,

Thank you for your contribution.

It looks like I found an error.

1. One of the columns in the data attribute table had spaces (Rod & Rope), which in turn wasn't transferred properly to the GeoJSON code, where appeared as a "rod" only.
2. I've changed the coloration of 2 layers (looks like geoJSON doesn't accept any patterns. It comes just as an opaque layer.


Best regards,
