### ISSUE TITLE
I can't remove manually unwanted values

### ISSUE THREAD

**Issue by Krukarius** [tomchadwin/qgis2web#929]
I have one unwanted value, which belongs to my "fid" column. 

I don't want the "fid" column to be visible. I cannot remove it from the data attribute table, because it crashes my QGIS.

I've made the fid column as "no label" category. In this case the label title isn't visible in my popup, but the value is still here:

<blockquote class="imgur-embed-pub" lang="en" data-id="a/ZIbcv6d" data-context="false" ><a href="//imgur.com/a/ZIbcv6d"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

https://imgur.com/a/ZIbcv6d

In my geojson file I see:

"features": [
{ "type": "Feature", "properties": { "fid": "1", "Pole No.": "P0", "X": "523696", "Y": "244232", "Address": "Opp 7a, High St", "Pole Type": "BT", "Wayleave": "N", "No. of exi": "7"

Next I removed the label from my layers.js file

lyr_Arae5LLD3A_Pole_2.set('fieldAliases', {'Pole No.': 'Pole No.', 'X': 'X', 'Y': 'Y', 'Address': 'Address', 'Pole Type': 'Pole Type', 'Wayleave': 'Wayleave', 'No. of exi': 'No. of exi', 'No. of dro': 'No. of dro', 'Type of cr': 'Type of cr', 'Hedge Cutt': 'Hedge Cutt', 'Sufficent ': 'Sufficent ', 'Enclosure': 'Enclosure', 'Comments': 'Comments', });

fid label has been completely erased here.

The last part is the qgis2web.js file, where we have:

if (doPopup) {
                    popupText += '<li><table>';
                    for (var i=0; i<currentFeatureKeys.length; i++) {
                        if (currentFeatureKeys[i] != 'geometry') {
                            popupField = '';
                            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "inline label") {
                                popupField += '<th>' + layer.get('fieldAliases')[currentFeatureKeys[i]] + ':</th><td>';
                            } else {
                                popupField += '<td colspan="5">';
                            }
							if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "header label") {
                                popupField += '<strong>' + layer.get('fieldAliases')[currentFeatureKeys[i]] + ':</strong><br />';
                            }
                            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "no label") {
                               popupField += '<strong>' + layer.get('fieldAliases')[currentFeatureKeys[i]] + ':</strong><br />';
                            }
							  if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "red label") {
                                popupField += '<strong><font color="red">' + layer.get('fieldAliases')[currentFeatureKeys[i]] + ':</font> &nbsp&nbsp&nbsp</strong>';
                            }
                            if (layer.get('fieldImages')[currentFeatureKeys[i]] != "ExternalResource") {
                                popupField += (currentFeature.get(currentFeatureKeys[i]) != null ? autolinker.link(currentFeature.get(currentFeatureKeys[i]).toLocaleString()) + '</td>' : '');
                            } else {
                                popupField += (currentFeature.get(currentFeatureKeys[i]) != null ? '<img src="images/' + currentFeature.get(currentFeatureKeys[i]).replace(/[\\\/:]/g, '_').trim()  + '" /></td>' : '');
                            }
                            popupText += '<tr>' + popupField + '</tr>';
                        }
                    }
                    popupText += '</table>';
                }

I tried sth like this
if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "no label") {}

but the fid value is still visible!

Is there any way to get rid of the unwanted value?

Can I remove them somewhere in the code?

Thank you in advance for your help.

Best regards,

**Comment by tomchadwin** [comment]
In QGIS, set the Edit widget type to "Hidden". That prevents the field appearing in the popups.

**Comment by Krukarius** [comment]
Yes, but it will apply to all of the fields. I want just one field to be invisible. How can I do that?
