### ISSUE TITLE
try to running plugin

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#93]
Hi, trying to running plugin i get:

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/qgis2web.py", line 51, in run
    dlg = MainDialog(self.iface)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 55, in __init__
    self.previewMap()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 97, in previewMap
    MainDialog.previewOL3(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 222, in previewOL3
    previewFile = writeOL(self.iface, layers, groups, popup, visible, json, cluster, labels, params, utils.tempFolder())
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/olwriter.py", line 53, in writeOL
    exportLayers(layers, folder, precision, optimize, usedFields)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/utils.py", line 65, in exportLayers
    uri = TYPE_MAP[layer.wkbType()]
KeyError: -2147483645

**Comment by tomchadwin** [comment]
Can you narrow it down to a single layer which causes this? It is failing to identify the geometry type of what it thinks is a vector layer. So we need to know if it is a vector layer, and what geometry type it is.

**Comment by marcobra** [comment]
There are some dbf but also some others Openstreetmap downloaded files with qgis plugin quickosm files, tey are shapes files....  i just sent via PM testing project

**Comment by tomchadwin** [comment]
Catching layers without geometry shouldn't be too hard, but I know it's not currently implemented. Not sure about the other issue - will investigate @marcobra's test data.

**Comment by tomchadwin** [comment]
Bug confirmed.

**Comment by tomchadwin** [comment]
I've committed a possible fix to master to handle layers without geometry in Leaflet (to ignore them without error). Can you test and report back?

I can't get an error with the Aree_ layers - they preview fine in both Leaflet and OL3.

**Comment by tomchadwin** [comment]
That last commit might also have fixed the OSM layer problem - can you test?

**Comment by marcobra** [comment]
Hi, after fetching with git clone your commit i get still same error

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 97, in previewMap
    MainDialog.previewOL3(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 226, in previewOL3
    previewFile = writeOL(self.iface, layers, groups, popup, visible, json, cluster, labels, params, utils.tempFolder())
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/olwriter.py", line 53, in writeOL
    exportLayers(layers, folder, precision, optimize, usedFields)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/utils.py", line 65, in exportLayers
    uri = TYPE_MAP[layer.wkbType()]
KeyError: -2147483645


Versione Python:
2.7.6 (default, Jun 22 2015, 18:01:27) 
[GCC 4.8.2]

Versione di QGIS:
2.10.1-Pisa Pisa, exported

**Comment by tomchadwin** [comment]
The fixes I committed were for Leaflet output. You've used OL£ - I'll look at that. Which layers from that project are you selecting to get that error?

**Comment by tomchadwin** [comment]
Ah, the housenumber layer in that project layer use an expression for its label. Either remove the expression, or turn off labelling for that layer, and see if that now works.

**Comment by tomchadwin** [comment]
However, this only manifested itself as JS errors in the OL3 output. I'm not getting Python errors at all. So I still can't recreate your issue.

**Comment by tomchadwin** [comment]
Label expressions not supported is #51

**Comment by tomchadwin** [comment]
Fixed (we think) in master. OL3 export was not handling 2.5-dimensional layer geometry.

**Comment by tomchadwin** [comment]
I think this is all fixed now. Reopen if not.

**Comment by tomchadwin** [comment]
Released as 0.21.2 and pushed to QGIS plugin repo
