### ISSUE TITLE
XYZ basemap not loading, but will load locally

### ISSUE THREAD

**Issue by kaputkin** [tomchadwin/qgis2web#933]
Using QGIS 3.10, qgis2web 3.16.0. I added a Stamen basemap to my project as XYZ tiles, and it works fine within QGIS, and after exporting via qgis2web using Leaflet, the HTML works fine locally, but when I upload to Github and make a page, the basemap does not load. Everything works fine though. 

I made sure each layer is the same CRS as the basemap, but that doesn't seem to be the issue.

**Comment by kaputkin** [comment]
The issue is that the Stamen XYZ url is HTTP, not HTTPS. Looks like github pages will only load HTTPS links. I switched to another basemap with an HTTPS xyz url and it works.

**Comment by tomchadwin** [comment]
It's not that Github will only load HTTPS. It's that browsers will not allow HTTP content to be loaded in an HTTPS page. Github pages (and pretty much all websites these days) are HTTPS, so finding HTTPS sources for your basemaps is the solution.
