### ISSUE TITLE
qgis2web basemaps sit on top of all other layers in Leaflet and OpenLayers on webpages

### ISSUE THREAD

**Issue by driansmith** [tomchadwin/qgis2web#935]
![desktop-map](https://user-images.githubusercontent.com/38726678/99409831-b3904680-28e9-11eb-855f-01e2c605b099.GIF)

Generating a webpage from a map always elevates the basemap from the bottom (within the QGIS Project) to the top (on the webpage map). This means the additional layers can never be overlaid to fully appreciate the map. Can anyone help please? 

![webpage-map](https://user-images.githubusercontent.com/38726678/99409905-c9057080-28e9-11eb-9161-6b274a3e3ca6.GIF)
No matter what i do, I cannot get the basemap to sit at the bottom of the webpage layers.

**Comment by jukos** [comment]
Hello,
layers of a group are within the legend under the basemaps - openlayers and leaflet.
Solution: No groups, only layers.
Greetings

**Comment by driansmith** [comment]
Thanks jukos, but I'm afraid I don't understand your point.
I want the basmaps relegated to the bottom of the legend in the webpage as well as in the QGIS project.
That way all other layers can be visualized on top.

**Comment by jukos** [comment]
Yes, I understand.
"Megalakes" is a group for the layers
- Arabian lakes...
- Makga....
- an so on......

An now you must drag the layers (Arabien lakes..., Makga, etc.)  out of the group. No group!

Than you have only individual layers, no groups.

Excuse me, sometimes I have problem to explan in english. I hope it is no clear. If not, I can create some screenshots.

Greetings

**Comment by driansmith** [comment]
I understand what you are saying, but I'm not sure you understand me.
The layer Stamen Terrain (a basemap) is at the bottom of the legend in the QGIS Desktop image, but it always appears in the top of the legend in the Webpage image. I want it to be at the bottom of the legend in the webpage image.

**Comment by jukos** [comment]
![groups ](https://user-images.githubusercontent.com/31866672/99718781-b2a71280-2aab-11eb-9550-d59f745f4b5a.jpg)

**Comment by driansmith** [comment]
Excellent !!!
Thank you very much jukos, that does indeed solve my problem.

**Comment by tomchadwin** [comment]
Many thanks, @jukos. Apologies that QGIS layer groups are not well supported. Kt's a longstanding issue, for which I don't have any solution, I'm afraid. See: https://github.com/tomchadwin/qgis2web/issues/175

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
