### ISSUE TITLE
Question about Precision in data export. 

### ISSUE THREAD

**Issue by freewheelCarto** [tomchadwin/qgis2web#94]
Your precision default is '15'.  From what I can tell, this translates to 15 decimal places for Long/Lat coordinates in decimal degrees.  This is an excessive number of decimal places.  

Maybe the reason 15 is default is to take in to account other CRSs?  Or am I misunderstanding the Precision parameter?

**Comment by tomchadwin** [comment]
I copied 15 from qgis2leaf. I'm afraid I have no idea how exactly the values are interpreted. They are used in writeAsVectorFormat(). Can anyone else explain? Remember that the dialog remembers whatever you change the value to.

**Comment by freewheelCarto** [comment]
The reason I bring it up is that 15 decimal places is such a fine precision as to be impossible.  8 decimal places is ~1mm.  This also has an impact on file size. 

Thanks!

**Comment by boesiii** [comment]
Yes, I agree 15 is excessive.  After reading http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude I think the default value should be set to 6 or 7.

**Comment by tomchadwin** [comment]
I agree only if:

- precision = decimal places
- unit = metre

Otherwise these figures are incorrect.

**Comment by freewheelCarto** [comment]
Yes, finding out what precision actually is and how it works with different coordinate system inputs in this code is key.  thanks.

**Comment by tomchadwin** [comment]
Do we need a default value for the precision drop-down: "Preserve"? Or some other clearer term which means don't change the data at all?

**Comment by freewheelCarto** [comment]
Makes sense to me, and "Preserve" is a good term I think. Especially since the docs' definition of the Precision parameter is "Simplify geometry to reduce file size", preserve implies 'don't simplify geometry'.

**Comment by boesiii** [comment]
Yes it would be good to add that as an option

**Comment by tomchadwin** [comment]
Not simple to add "Preserve". Therefore closing this for the moment. Reopen if still relevant.

**Comment by tomchadwin** [comment]
"Precision: maintain" committed to master. Please test.

**Comment by tomchadwin** [comment]
Released as 1.7.0 and pushed to QGIS plugins repo.
