### ISSUE TITLE
Use the exported files in a vue project

### ISSUE THREAD

**Issue by JiahangOK** [tomchadwin/qgis2web#944]
I am using the [vue-element-admin](https://panjiachen.gitee.io/vue-element-admin-site/zh/) framework to develop a website. One of the pages needs to contain a map. Now  I have successfully exported my QGIS map into OpenLayers format. However, it used the <script> to import js, which is not easy to apply to the vue-element-admin project. Is there any solution? Looking forward to your reply.Thanks.

**Comment by jukos** [comment]
Hello,
it is easy to embed your map with with the iframe command.
You need only a website and set for example this code:
<p><iframe src="https://www.yoursite.de/qgis2web/index.html" name="mymap" width="80%" height="400px" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

And within the folder "qgis2web" are located your qgis2web export folder/files.

Greetings

**Comment by JiahangOK** [comment]
Got it. Thank you.@jukos
