### ISSUE TITLE
KeyError: 'color' by single symbol with extra marker

### ISSUE THREAD

**Issue by EisbaerLolo** [tomchadwin/qgis2web#946]
when i create deeper structures in the display i get the following error message:

Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting rindenmulch to JSON... done done
Exception in layer rindenmulch_9d61c07b_8b0b_4de0_a163_9bce4def7fc9 with renderer SINGLE: FILL SYMBOL (1 layers) color 43,26,26,255: Traceback (most recent call last): File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 49, in exportStyles layer, feedback) File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 214, in singleSymbol feedback) File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 565, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:\Users\Administrator\AppData\Local\Temp\qgis2web
<img width="376" alt="1" src="https://user-images.githubusercontent.com/80031351/109932584-b06b6b80-7cca-11eb-94ae-7c80f45a219c.png">
<img width="414" alt="2" src="https://user-images.githubusercontent.com/80031351/109932599-b5301f80-7cca-11eb-9952-aebebb000c34.png">

**Comment by tomchadwin** [comment]
I'm afraid point pattern fills are not supported in qgis2web. Sorry.
