### ISSUE TITLE
Certain Data Does Not Show up on Exported Map

### ISSUE THREAD

**Issue by Perosu1** [tomchadwin/qgis2web#951]
Hello,
Creating a qgis2web map from this file does not seem to work.
When clicking preview or export, absolutely nothing shows up. If I'm using OpenStreetMap as an additional layer, OSM will show up, but again, not this layer. If I tried making a qgis2web map from a different source (UK government) using the same steps, it worked and returned lines, shapes etc.
I have also tried importing both files into QGIS and making a qgis2web map from both - the UK data showed up, but the Slovenian data was blank.

Nothing was rule-based. The only style used was simple fill.

Slovenian file (has to be imported as unzipped folder, otherwise QGIS returns error during importing)
[SR.zip](https://github.com/tomchadwin/qgis2web/files/6246447/SR.zip)

Sadly, the UK file is too large to upload.

Thank you!

**Comment by jukos** [comment]
Hello,
try coordinate system
ETRS_1989_Slovenia_TM
Greetings

**Comment by Perosu1** [comment]
That worked! Thank you so much!
Regards

**Comment by Perosu1** [comment]
That worked! Thank you so much!
Regards
