### ISSUE TITLE
Changing leaflet icons

### ISSUE THREAD

**Issue by myfta** [tomchadwin/qgis2web#969]
I am using qgis2web with QGIS 3.16.3 and have been using qgis2web for some time. Now I have created a relatively simple map with an OSM base layer and a set of points on another layer. All my place markers appear as round dots. I can create them all in one color and with rule-base symbology two different colors.

The issue is the png files are located in the export folder \legend. I thought I should be able to simply replace those pngs with an alternative file of approximately the same size but of a design that is more informative. When I change the icons (and changing the file names to the original ones) and refresh the browsers the icons remain unchanged. So what is actually defining the icons being used as I cannot locate any other pngs in the exported folders? (I'm not trying to use svg files.)

Looking in the index.html code there is no mention of the \images folder.

Thanks.

Graham

**Comment by tomchadwin** [comment]
It's not using images at all. It's drawing the features directly onto the canvas, in the same way that lines and polygons are drawn. If you want to do what you're attempting, change the layer style to use SVGs, and replce the SVGs.

**Comment by myfta** [comment]
Thank you. Perfect.
