### ISSUE TITLE
add area measurement openlayers export

### ISSUE THREAD

**Issue by ordisabeba** [tomchadwin/qgis2web#971]
openlayers export don't have measurement area. there is a solution to add a form when click in ruler icon that allows a lenght or area choice like this? 
https://openlayers.org/en/latest/examples/measure.html
thanks

**Comment by ordisabeba** [comment]
I tried to integrate the original qgis2web code with this example: giserdqy.com/wp-content/guids/ol-v4.6.5/examples/measure.html - Obviously, given my lack of experience, it doesn't work, but maybe anyone can unlock me. The first click is ok, even for the type length or area variable, but the second click moves the map rather than measuring. Where am I wrong? Result here:
https://pianifterrprovpu.altervista.org/_test/test_area_measurement_ol-v4.6.5/index.html
Code here: pianifterrprovpu.altervista.org/_test/test_area_ol-v4.6.5/resources/qgis2web.js

**Comment by ordisabeba** [comment]
Given the many variables present in qgis2web when activating/deactivating the measurement, I decided to eliminate the length measurement while keeping only the area measurement inserting in qgis2web.js:
`var continuePolygonMsg = 'Click to continue drawing the polygon';`
and modify:
```
var draw; // global so we can remove it later
function addInteraction() {
  var type = 'Polygon';
 etc....
```
```
var listener;
  etc....
          var geom = evt.target;
          var output;
            output = formatArea(geom);
                  tooltipCoord = geom.getInteriorPoint().getCoordinates();
          etc...
```
```
      var formatArea = function(polygon) {
        var area = polygon.getArea();		
        var output;
        if (area > 10000) {
          output = (Math.round(area / 1000000 * 100) / 100) +
              ' ' + 'km<sup>2</sup>';
        } else {
          output = (Math.round(area * 100) / 100) +
              ' ' + 'm<sup>2</sup>';
        }
        return output;
      };
```
I ask for help showing half segment length label like [this example](https://stackoverflow.com/questions/67782484/labeling-the-length-of-each-side-of-polygon-openlayers-3): 

```
<!DOCTYPE html>
<html>
  <head>
    <title>Measure</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v3.20.1/css/ol.css" type="text/css">
    <style>
      html, body, .map {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
      }
      #map {
        position: relative;
      }
      #form {
        z-index: 1;
        position: absolute;
        bottom: 0;
        left: 0;
      }
    </style>
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v3.20.1/build/ol.js"></script>
  </head>
  <body>
    <div id="map" class="map">
      <form id ="form" class="form-inline">
        <label>Measurement type &nbsp;</label>
          <select id="type">
            <option value="LineString">Segments (LineString)</option>
            <option value="Polygon">Sides (Polygon)</option>
          </select>
      </form>
    </div>
    <script>

      var style = new ol.style.Style({
        fill: new ol.style.Fill({
          color: 'rgba(255, 255, 255, 0.2)'
        }),
        stroke: new ol.style.Stroke({
          color: 'rgba(0, 0, 0, 0.5)',
          lineDash: [10, 10],
          width: 2
        }),
        image: new ol.style.Circle({
          radius: 5,
          stroke: new ol.style.Stroke({
            color: 'rgba(0, 0, 0, 0.7)'
          }),
          fill: new ol.style.Fill({
            color: 'rgba(255, 255, 255, 0.2)'
          })
        })
      });

      var labelStyle = new ol.style.Style({
        text: new ol.style.Text({
          font: '14px Calibri,sans-serif',
          fill: new ol.style.Fill({
            color: 'rgba(0, 0, 0, 1)'
          }),
          stroke: new ol.style.Stroke({
            color: 'rgba(255, 255, 255, 1)',
            width: 3
          })
        })
      });

      var labelStyleCache = [];

      var wgs84Sphere = new ol.Sphere(6378137);

      var formatLength = function(line) {
        var length;
        var coordinates = line.getCoordinates();
        length = 0;
        var sourceProj = map.getView().getProjection();
        for (var i = 0, ii = coordinates.length - 1; i < ii; ++i) {
          var c1 = ol.proj.transform(coordinates[i], sourceProj, 'EPSG:4326');
          var c2 = ol.proj.transform(coordinates[i + 1], sourceProj, 'EPSG:4326');
          length += wgs84Sphere.haversineDistance(c1, c2);
        }
        var output;
        if (length > 100) {
          output = (Math.round(length / 1000 * 100) / 100) +
              ' ' + 'km';
        } else {
          output = (Math.round(length * 100) / 100) +
              ' ' + 'm';
        }
        return output;
      };

      var styleFunction = function (feature, drawType) {
        var styles = [style];
        var geometry = feature.getGeometry();
        var type = geometry.getType();
        var lineString;
        if (!drawType || drawType === type) {
          if (type === 'Polygon') {
            lineString = new ol.geom.LineString(geometry.getCoordinates()[0]);
          } else if (type === 'LineString') {
            lineString = geometry;
          }
        }
        if (lineString) {
          var count = 0;
          lineString.forEachSegment(function(a, b) {
            var segment = new ol.geom.LineString([a, b]);
            var label = formatLength(segment);
            if (labelStyleCache.length - 1 < count) {
              labelStyleCache.push(labelStyle.clone());
            }
            labelStyleCache[count].setGeometry(segment);
            labelStyleCache[count].getText().setText(label);
            styles.push(labelStyleCache[count]);
            count++;
          });
        }
        return styles;
      };

      var raster = new ol.layer.Tile({
        source: new ol.source.OSM()
      });

      var source = new ol.source.Vector();

      var vector = new ol.layer.Vector({
        source: source,
        style: function(feature) {
          return styleFunction(feature);
        }
      });

      var map = new ol.Map({
        layers: [raster, vector],
        target: 'map',
        view: new ol.View({
          center: [-11000000, 4600000],
          zoom: 15
        })
      });

      var typeSelect = document.getElementById('type');

      var draw; // global so we can remove it later

      function addInteraction() {
        var drawType = typeSelect.value;
        draw = new ol.interaction.Draw({
          source: source,
          type: drawType,
          style: function (feature) {
            return styleFunction(feature, drawType)
          }
        });
        map.addInteraction(draw);
      }

      typeSelect.onchange = function () {
        map.removeInteraction(draw);
        addInteraction();
      };

      addInteraction();

    </script>
  </body>
</html>
```

I don't know how to fit the final "var styleFunction" without "if" for length and area, because I have only area. With this solution you would have area and length in a single command. Ideally, the second click on the ruler icon deletes the measurements made.
Thanks to all

**Comment by ordisabeba** [comment]
I managed to reach the goal despite having had so much difficulty given my little experience with programming (it took me 3 months). This is the result:

1) clicking on the button opens a form with a request for geometry, length or area
![image](https://user-images.githubusercontent.com/89784373/150791730-9a2269ff-62e8-406b-a117-98ad7e65a1b7.png)
2) the drawing is a broken line with the measurement of the segments in addition to the measurement of the total
![image](https://user-images.githubusercontent.com/89784373/150791776-218a14fb-f8f2-410b-94cf-35fb9bc2a386.png)
3) with the double click the geometry is closed, the balloon of the total is yellow and further measurements can be carried out
![image](https://user-images.githubusercontent.com/89784373/150791818-372b2e11-d445-44b4-a414-c7b08eaa3325.png)
4) the area presents the balloon with the total in the center, maintaining the measurement of the segments
![image](https://user-images.githubusercontent.com/89784373/150791901-28281898-eb38-4951-b31d-5246a911c635.png)
5) when you change the type of geometry from length to area the measurements on the screen are reset. To completely deactivate the measurement, click again on the measurement button and all the elements on the screen will be deleted.

I describe the modified code of qgis2web:
**index.html**

    <style>
    ...etc... 

    .ol-touch .measure-control {
      top: 80px;
    }	
    #form_measure {
      background-color: rgba(255, 255, 255, 0.75);
      border: 3px solid #f8f8f8 !important;
      z-index: 1;
      opacity: 1;
      position: absolute;
      top: 65px;
      left: 2.7em;
      margin: 0;
      width: 147px;
      height: 19px;
          }
    </style>

    <body>
            <div id="map">
                <div id="popup" class="ol-popup">
                    <a href="#" id="popup-closer" class="ol-popup-closer"></a>
                    <div id="popup-content"></div>
                </div>
            </div>
    		<form id="form_measure" style="display: none">
    			<label>&nbsp;Misura:&nbsp;</label>
    				<select id="type">
    					<option value="length">Lunghezza</option>	
    					<option value="area">Area</option>
    				</select>
    		</form>
    ...etc...
    </body>

**qgis2web.js**

    ...etc...

    var handleMeasure = function(e) {
            if (!measuring) {
    			typeSelectForm.style.display = '';
    			this_.getMap().addInteraction(draw);
                createHelpTooltip();
                createMeasureTooltip();
                measuring = true;
            } else {
    			typeSelectForm.style.display = 'none';
                this_.getMap().removeInteraction(draw);
                measuring = false;
                this_.getMap().removeOverlay(helpTooltip);
                this_.getMap().removeOverlay(measureTooltip);

    			var staticTooltip = document.getElementsByClassName('tooltip-static');
			while(staticTooltip.length > 0){
				staticTooltip[0].parentNode.removeChild(staticTooltip[0]);
			}
			measureLayer.getSource().clear();
            }
          };

    ...etc...

    /**
     * Message to show when the user is drawing a polygon.
     * @type {string}
     */
    var continuePolygonMsg = '1click continua, 2click chiudi';
    
    	var typeSelect = document.getElementById('type');
    	var typeSelectForm = document.getElementById('form_measure');
    
    	/**
    	 * Let user change the geometry type.
    	 * @param {Event} e Change event.
    	 */
    	typeSelect.onchange = function(e) {
    		
    	  typeSelectForm.style.display = 'none';
	     map.removeInteraction(draw);
	     measuring = false;
	     map.removeOverlay(helpTooltip);
	     map.removeOverlay(measureTooltip);
	     var staticTooltip = document.getElementsByClassName('tooltip-static');
			while(staticTooltip.length > 0){
				staticTooltip[0].parentNode.removeChild(staticTooltip[0]);
			}
			measureLayer.getSource().clear();
		
	     addInteraction();
	  
	     typeSelectForm.style.display = '';
	     map.addInteraction(draw);
	     createHelpTooltip();
	     createMeasureTooltip();
	     measuring = true;
       	};
    
    	var style = new ol.style.Style({
    	fill: new ol.style.Fill({
    	color: 'rgba(255, 255, 255, 0.2)'
    	}),
    	stroke: new ol.style.Stroke({
    	color: 'rgba(255, 204, 51)',
    	lineDash: [10, 10],
    	width: 3
    	}),
  		image: new ol.style.Circle({
   	    radius: 5,
  		stroke: new ol.style.Stroke({
    	color: 'rgba(0, 0, 0, 0.7)'
        }),
        fill: new ol.style.Fill({
       color: 'rgba(255, 255, 255, 0.2)'
        })
        })
        });
    
    	var labelStyle = new ol.style.Style({
    	text: new ol.style.Text({
    	font: '14px Calibri,sans-serif',
    	fill: new ol.style.Fill({
    	color: 'rgba(0, 0, 0, 1)'
    	 }),
    	stroke: new ol.style.Stroke({
    	color: 'rgba(255, 255, 255, 1)',
    	width: 3
    	 })
    	})
    	 });
    
    	var labelStyleCache = [];
    
			  
    	var styleFunction = function (feature, type) {
    	var styles = [style];
    	var geometry = feature.getGeometry();
    	var type = geometry.getType();
    	var lineString;
    	if (!type || type === type) {
    	if (type === 'Polygon') {
    	lineString = new ol.geom.LineString(geometry.getCoordinates()[0]);
    	} else if (type === 'LineString') {
    	lineString = geometry;
    	}
    	}
    	if (lineString) {
    	 var count = 0;
    	 lineString.forEachSegment(function(a, b) {
    	var segment = new ol.geom.LineString([a, b]);
    	var label = formatLength(segment);
    	if (labelStyleCache.length - 1 < count) {
    						  labelStyleCache.push(labelStyle.clone());
    						}
    						labelStyleCache[count].setGeometry(segment);
    						labelStyleCache[count].getText().setText(label);
    						styles.push(labelStyleCache[count]);
    						count++;
    					  });
    					}
    					return styles;
    					
    				  };
    				  
    var source = new ol.source.Vector();
    
    var measureLayer = new ol.layer.Vector({
        source: source,
        style: function(feature) {
              return styleFunction(feature);
            }
    });
    
    map.addLayer(measureLayer);
    
    var draw; // global so we can remove it later
    function addInteraction() {
    	

      var type = (typeSelect.value == 'area' ? 'Polygon' : 'LineString');		
      draw = new ol.interaction.Draw({
        source: source,
        type: /** @type {ol.geom.GeometryType} */ (type),
        style: function (feature) {
                return styleFunction(feature, type)
              }
      });
    
      var listener;
      draw.on('drawstart',
          function(evt) {
            // set sketch
            sketch = evt.feature;
    
            /** @type {ol.Coordinate|undefined} */
            var tooltipCoord = evt.coordinate;
    
            listener = sketch.getGeometry().on('change', function(evt) {
              var geom = evt.target;
              var output;
                if (geom instanceof ol.geom.Polygon) {
                output = formatArea(/** @type {ol.geom.Polygon} */ (geom));
                tooltipCoord = geom.getInteriorPoint().getCoordinates();
              } else if (geom instanceof ol.geom.LineString) {
                output = formatLength( /** @type {ol.geom.LineString} */ (geom));
                tooltipCoord = geom.getLastCoordinate();
              }
              measureTooltipElement.innerHTML = output;
              measureTooltip.setPosition(tooltipCoord);
            });
          }, this);
    
      draw.on('drawend',
          function(evt) {
            measureTooltipElement.className = 'tooltip tooltip-static';
            measureTooltip.setOffset([0, -7]);
            // unset sketch
            sketch = null;
            // unset tooltip so that a new one can be created
            measureTooltipElement = null;
            createMeasureTooltip();
            ol.Observable.unByKey(listener);
          }, this);
    }

    ...etc...

    /**
     * Format area output.
     * @param {ol.geom.Polygon} polygon The polygon.
     * @return {string} Formatted area.
     */
          var formatArea = function(polygon) {
            var area = polygon.getArea();		
            var output;
            if (area > 10000) {
              output = (Math.round(area / 1000000 * 100) / 100) +
                  ' ' + 'km<sup>2</sup>';
            } else {
              output = (Math.round(area * 100) / 100) +
                  ' ' + 'm<sup>2</sup>';
            }
            return output;
          };
    
    addInteraction();

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/80defd3c5753ca2bee0ebb72a0e0c4e65a7c207d) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.0)
