### ISSUE TITLE
Leaflet layer list does not reflect layer z-order

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#98]
Might be insoluble in Leaflet 0.7.x

**Comment by tomchadwin** [comment]
See https://github.com/Leaflet/Leaflet/issues/2086

**Comment by tomchadwin** [comment]
Closing for now - let's wait for Leaflet 1.0

**Comment by cbeddow** [comment]
Checking in with same issue, plus additional... not sure if related:

My layers are reverse ordered in the rendered HTML file (as in previous issue). However, the layer set to display initially (only one layer) is also swapped. First layer was supposed to display initially, but now it's last layer displaying.

Tips on manually editing this in the code?

**Comment by tomchadwin** [comment]
@cbeddow I need to understand this better:

"My layers are reverse ordered" - z-order on the map, order in the legend, or both?

"The layer set to display initially is also swapped" - swapped with what?

"First layer was supposed to display initially, but now it's last layer displaying" - define 'first' and 'last'

**Comment by cbeddow** [comment]
@tomchadwin here's a screenshot showing the problem. I selected "Federally Recognized Native Lands" to be the only visible layer on initial load. Instead, "Copper Wireline Coverage" is selected in the preview. When I export, the order of layers in the legend is reversed--Copper at the top, Native Lands at the bottom--and Copper is still the only one that is initially visible. Not sure about z-order, as I've set everything to be partially transparent and z-order on map wasn't a concern for me. (could test that though, just for error checking)

![image](https://cloud.githubusercontent.com/assets/10554922/10164999/354e747c-6693-11e5-96dc-0e98158828dc.png)

**Comment by tomchadwin** [comment]
OK, so possibly three parts to this:

1. There is a difference between preview and export, which very seldom happens, as they use the same function

2. Order of layers in the legend is reversed

3. The wrong layer is visible

3 is obviously the most critical. Can you confirm that this is related to the order of layers by unchecking the visible box for native lands and checking the one for Radio affiliate stations? If Cable wireline coverage ends up checked in the legend, that's is confirmed as the pattern.

Don't worry about z-order on the map if it hasn't struck you as a problem. This is plainly a legend issue, so let's stick to that for the moment.

**Comment by tomchadwin** [comment]
Would you be able to edit the output index.html and swap in Leaflet 1.0 beta? I wonder if that might make a difference.

**Comment by tomchadwin** [comment]
Closing for now with no recent feedback.
