### ISSUE TITLE
Why are a number of qgis2web's options non-selectable for me?

### ISSUE THREAD

**Issue by BahramGitt** [tomchadwin/qgis2web#99]
Hi Mr Tom Chadwin. Thank you to you for your really useful plugins such as qgis2web.
I'm very interested in this plugin but also I've some problems!
I am unable to select(check) a few number of qgis2web's options as following
 Add address search;
Add measure tool;
Geolocate user;
Match project CRS.
I need to your guidance. Can you help me please?
Windows 8.1, QGIS 2.10.1-Pisa
Regards.
![image](https://cloud.githubusercontent.com/assets/10850519/9294871/44bdb24c-446f-11e5-97ba-0e204d1863f6.png)

**Comment by boesiii** [comment]
The other settings are greyed out because they are only available for Leaflet and not OL3.  Each setting may only work for either Leaflet or OL3.

**Comment by tomchadwin** [comment]
Thanks @boesiii for answering - he is right. As more options are coded for each export format, fewer controls will be greyed out.

**Comment by tomchadwin** [comment]
Since v1.0.0-beta1 all features are available in both Leaflet and OL3 export, so you should not experience this issue any more.
