### ISSUE TITLE
qgis2web - openlayers - popup not working if measure not concluded

### ISSUE THREAD

**Issue by andreaordonselli** [tomchadwin/qgis2web#998]
The popup that queries the layers in the map no longer works if I start a measurement but do not finish it with a double click.
Is there a solution for this?

**Comment by tomchadwin** [comment]
How could it work? You open a popup with a click, but you set a measurement point with a click. That's why it's disabled.

**Comment by andreaordonselli** [comment]
after months of testing, given my little knowledge of code, I was able to understand that I had to add
**sketch = null;**
when the measurement is deactivated, both concluded with the double click and not completed

```
.... etc ......
      var handleMeasure = function(e) {
        if (!measuring) {
            this_.getMap().addInteraction(draw);
            createHelpTooltip();
            createMeasureTooltip();
            measuring = true;
        } else {
            this_.getMap().removeInteraction(draw);
            measuring = false;
            this_.getMap().removeOverlay(helpTooltip);
            this_.getMap().removeOverlay(measureTooltip);
            sketch = null;			
        }
      };
```

**Comment by andreaordonselli** [comment]
Fixed with this [commit](https://github.com/tomchadwin/qgis2web/commit/80defd3c5753ca2bee0ebb72a0e0c4e65a7c207d) and this [release](https://github.com/tomchadwin/qgis2web/releases/tag/v3.17.0)
